### ISSUE TITLE
Using rehydrated state causes error when accessing `currentState.nextEvents`

### ISSUE THREAD

**Issue by 0xR** [statelyai/xstate#1020]
**Description**
I'm trying to persist the current state to disk, but when using this to rehydrated state I get the error  `Cannot read property 'map' of undefined` when accessing `currentState.nextEvents`. After some debugging I discovered then when I use `JSON.stringify(currentState)`, `currentState.configuration` is not part of the resulting JSON. It seems there are circular references or something.

I also tried [flatted](http://npm.im/flatted) since it should be able to serialize circular objects, but that doesn't solve the issue.

**Expected Result**
`currentState.configuration` should be possible to serialize to JSON

**Actual Result**
`currentState.configuration` is missing and accessing `currentState.nextEvents` gives `Cannot read property 'map' of undefined`.

**Reproduction**
- [CodeSandbox template (React)](https://codesandbox.io/s/xstate-serialization-issue-764qb) Clicking the first button shows `nextEvents`, clicking the second button gives the error.

**Additional context**
I put in some effort in the CodeSandbox repro. I hope this makes this issue easier to fix.

**Comment by davidkpiano** [comment]
Serializing `currentState.configuration` could get pretty large, so it is intentionally ignored from the state configuration for now.

But this brings up an important point: a `State` is data representing the current state of a machine - a "snapshot in time" basically. If you want to figure out what can happen next, you need the actual machine to determine that.

The `machine.resolveState(state)` method is for this purpose:

```js
const stateJSON = JSON.parse(stateString);
const state = State.create(stateJSON);
const resolvedState = machine.resolveState(state);

// Now you have .nextEvents
resolvedState.nextEvents; // [ ... ]
```

**Comment by senser1** [comment]
@davidkpiano, thanks for the follow-up. I'm using the react hooks (useMachine, useService) to get access to my xstate machine. 

I would like to initialize my machine/state like this:

`    const [myState, send, service] = useMachine(myMachine, { state: serializedState });
`

In my React component I'm reading from `myState.nextEvents`. How does your call to `machine.resolveState` relate to using the React hooks?

**Comment by sbussard** [comment]
Any updates? Especially regarding the question above about useMachine?

**Comment by davidkpiano** [comment]
The way to resolve the state is this:

```js
      renderAppWithHydratedState(
        meetingMachine.resolveState(
          State.create(JSON.parse(JSON.stringify(currentState)))
        )
      );
```

https://codesandbox.io/s/xstate-serialization-issue-forked-zoyd8?file=/src/index.tsx
