### ISSUE TITLE
xstate/graph "unable to transition" error swallows stacktrace

### ISSUE THREAD

**Issue by JackCA** [statelyai/xstate#1051]
**Description**
The [thrown error here ](https://github.com/davidkpiano/xstate/blob/master/packages/xstate-graph/src/graph.ts#L115-L119)swallows the stack trace of the original error, making it difficult to debug.

**Expected Result**
The stack trace (or perhaps the log) should reflect where the original error actually occurred.

**Actual Result**
The only stack trace shown is from the catch block

**Reproduction**
https://codesandbox.io/s/x-state-swallowed-stack-ytvig

**Additional context**
I'm not sure if this is an actual issue, but I had to enter a node inspector session when using xstate/test in order to find out what was actually causing this issue.

Perhaps the original stack could be logged, or a library like [chained-error](https://www.npmjs.com/package/chained-error) could be used?

**Comment by Andarist** [comment]
We are going to rethink how thrown errors are handled in the upcoming v5. In SCXML those would be converted to `error.execution` events, but I'm not sure if we want to follow that. @davidkpiano have your thought about this recently by any chance?

**Comment by davidkpiano** [comment]
Yes, so error traces should be preserved and carried through to the ultimate `error.execution` event. I'll look into this.

**Comment by davidkpiano** [comment]
Errors no longer get swallowed in `@xstate/graph@beta`: https://codesandbox
![CleanShot 2023-09-07 at 00 05 02](https://github.com/statelyai/xstate/assets/1093738/8aea8253-c99e-4ad2-b885-794bd83c17a6)
.io/s/x-state-swallowed-stack-forked-5tj274?file=/src/index.tsx
