### ISSUE TITLE
createMachine fails to infer typestate for particular state

### ISSUE THREAD

**Issue by ColCh** [statelyai/xstate#1138]
**Description**

given this code

```typescript

type YesNoContext = { value?: number };

type YesNoEvent = { type: 'YES' };

type NoLiteralContext = { value: 'no'; context: { value: undefined } };
type YesLiteralContext = { value: 'yes'; context: { value: number } };

type YesNoTypestate =
  | NoLiteralContext
  | YesLiteralContext;

const expectYesLiteralContext = (ctx: YesLiteralContext) => ctx;
const expectNoLiteralContext = (ctx: NoLiteralContext) => ctx;

const yesNoMachine = createMachine<
  YesNoContext,
  YesNoEvent,
  YesNoTypestate
>({
  context: {
    value: undefined
  },
  initial: 'no',
  states: {
    no: {
      on: {
        YES: 'yes'
      },
      entry: expectNoLiteralContext,
    },
    yes: {
      type: 'final',
      entry: expectYesLiteralContext,
    }
  }
});
```

**Expected Result**

assertion is not satisfied since `context` within `entry` is inferred as `YesNoContext`

![image](https://user-images.githubusercontent.com/599439/79606802-d6137480-80fa-11ea-9e2a-1c2859742915.png)

**Actual Result**

Within state, it should be inferred as one of literal contexts, see assertion functions

**Reproduction**

- [CodeSandbox template (JavaScript)](https://codesandbox.io/s/xstate-example-template-m4ckv)
- [CodeSandbox template (TypeScript)](https://codesandbox.io/s/xstate-typescript-template-s9kz8)
- ⚛︎ [CodeSandbox template (React)](https://codesandbox.io/s/xstate-react-template-3t2tg)
- ⚛︎ [CodeSandbox template (React + TypeScript)](https://codesandbox.io/s/xstate-react-typescript-template-wjdvn)
- 💚 [CodeSandbox template (Vue + Composition API)](https://codesandbox.io/s/xstate-vue-template-composition-api-1n23l)
- [XState Visualizer](https://xstate.js.org/viz/)

please take a look on this snippet in CodeSandbox: https://codesandbox.io/s/beautiful-cartwright-02oiw?file=/src/index.ts

**Additional context**

Latest XState version by the moment

XState version: `4.8.0`

TypeScript version: `3.8.3`

**Comment by ColCh** [comment]
May be, there is some way to get this working?

I'd like to utilize `TypeSchema` as well

may be, there is some generic with 4 parameters? e.g. `MachineDefinition<TContext, TSchema, TEvent, TTypestate>`? That would be enough for me, to use it in somewhat like following snippet:

```
type YesNoContext = { value?: number };

type YesNoEvent = { type: 'YES' };

type NoLiteralContext = { value: 'no'; context: { value: undefined } };
type YesLiteralContext = { value: 'yes'; context: { value: number } };

type YesNoTypestate =
  | NoLiteralContext
  | YesLiteralContext;

const expectYesLiteralContext = (ctx: YesLiteralContext) => ctx;
const expectNoLiteralContext = (ctx: YesLiteralContext) => ctx;

type YesNoSchema = {
    states: {
        yes: {},
        no: {},
    },
};

const states: MachineDefinition<YesNoContext, YesNoSchema, YesNoEvent, YesNoTypestate> = {
    no: {
      on: {
        YES: 'yes'
      },
      entry: expectYesLiteralContext,
    },
    yes: {
      type: 'final',
      entry: expectNoLiteralContext,
    }
  };

const yesNoMachine = createMachine<
  YesNoContext,
  YesNoEvent,
  YesNoTypestate
>({
  context: {
    value: undefined
  },
  initial: 'no',
  states,
});
```

**Comment by ColCh** [comment]
may be related but I'm not sure https://github.com/davidkpiano/xstate/issues/1120

**Comment by davidkpiano** [comment]
The `Typestate` feature is for `state.matches(...)`, and not yet for within the state machine. That's something we're going to work on for V5.

**Comment by ColCh** [comment]
Thank you for your answer!

So, there is no temporary workaround for this?

**Comment by ColCh** [comment]
Ah yes, it seems that main point is here:

```typescript
export declare type StatesConfig<TContext, TStateSchema extends StateSchema, TEvent extends EventObject> = {
    [K in keyof TStateSchema['states']]: StateNodeConfig<TContext /* <--- here! */, TStateSchema['states'][K], TEvent>;
};
```

**Comment by davidkpiano** [comment]
I would accept a PR if you really want this feature.

**Comment by ColCh** [comment]
Sure but please advise me on some steps to get started, because I'm not familiar with codebase. It's `StatesConfig` right?

**Comment by huan** [comment]
This use case should be supported by the `Typestate` because it is an intuition.

I feel very strange why the `context` is not following the `Typestate` under a specific `state` and trying to figure out why until I find this thread and read the answer from @davidkpiano.

Really looking forward to upgrading with the v5 alpha/RC/beta/next because there are lots of exciting improvements.

**Comment by Andarist** [comment]
Typestates were removed in v5. We know that this is a highly requested feature but to introduce it back we need to do it in a type-safe way and that's very challenging
