### ISSUE TITLE
Partial support for observables subscribe method

### ISSUE THREAD

**Issue by danielkcz** [statelyai/xstate#1172]
**Description**
Looking at the [proposal for observables](https://github.com/tc39/proposal-observable#observable) the `subscribe` method either accepts an object with `next/error/complete` properties or 3 callbacks.

However, looking at XState source it seems that only the latter form is accepted. 

https://github.com/davidkpiano/xstate/blob/7f5f7adc8c2a1ccb369cb795bdc4a962a9ea175b/packages/core/src/interpreter.ts#L1150

Even the `subscribe` of interpreted machine conforms to a standard.

https://github.com/davidkpiano/xstate/blob/7f5f7adc8c2a1ccb369cb795bdc4a962a9ea175b/packages/core/src/interpreter.ts#L329

**Expected Result**
The XState should support full observables according to spec.

**Actual Result**
I am using `wonka` library which is underlying stream lib for use in `urql` (GraphQL client). Unfortunately, it suffers the same problem and [implements only the other half of the spec](https://github.com/kitten/wonka/issues/84).

**Reproduction**
https://stackblitz.com/edit/react-ts-nbzjan?file=index.tsx

_I had to use Stackblitz here because CodeSandbox have some weird issue with `wonka`_

**Comment by FredyC** [comment]
The current workaround is to invoke a callback instead.

https://stackblitz.com/edit/react-ts-9w4fpr?file=index.tsx

**Comment by davidkpiano** [comment]
Can you make a PR for this? Would love to support the other subscribe signature.

**Comment by FredyC** [comment]
I think I will wait for V5 with it. It's not immediate pain since there is a viable workaround.

**Comment by davidkpiano** [comment]
XState v4 currently supports both observer objects and functions.
