### ISSUE TITLE
Typed xState Guards

### ISSUE THREAD

**Issue by PetrBrabec** [statelyai/xstate#1223]
## Feature request
Typed xState Guards

## Description:
I want to be able to provide `Guard` type (like `PropertyEqualsGuard` here in the example) to the Machine function and xState types covering guards. So the `conds` in action in the machine config is typed.

## Expected usage:
```
interface PropertyEqualsGuard<TProps, TContext, TEvent> extends Guard<TContext, TEvent]> {
    type: 'PropertyEquals'
    props?: {
        [TPropertyName in keyof TProps]?: TProps[TPropertyName]
    }
}
```
This way I will be able to define types for my Guards like this, so I can make a guard that like in this example checks if property defined in the guard is equal to provided value. 
Those properties we are comparing with can be for example in the state context.

**Comment by davidkpiano** [comment]
Hey, not sure what you're asking, can you give me a realistic usage example?

**Comment by PetrBrabec** [comment]
I'm sorry, I've changed the description. Is it clear now?

**Comment by davidkpiano** [comment]
This is for parameterized guards, right?

**Comment by PetrBrabec** [comment]
Yes.

**Comment by PetrBrabec** [comment]
custom guards exactly: https://xstate.js.org/docs/guides/guards.html#custom-guards

**Comment by Andarist** [comment]
Could you prepare a "full" pseudo-code of how would you like to use the proposed feature in the code assuming it would be implemented? It's very hard for me to assess what you are actually asking for from the given description.

**Comment by CodingDive** [comment]
Can't speak for OP and from the question I'm not sure if we are on the same page here, but I was hoping I could type my custom guards like this:

```typescript
cond: (context: IContext, event: IEvent, stateGuard: StateGuard<{ maxNumberOfItems: number }>) => context.items.length <= stateGuard.cond.maxNumberOfItems
```

The second and third generic TypeScript argument of StateGuard could be used to pass in the context and event again with which it could type the `state: State<Context, Event>` of the `stateGuard`.

Arguably it should only allow a second type argument which can be `State | undefined` as this would allow to explicitly define a guard that can be invoked by initial transitions of a machine where the state is not yet available.

```TypeScript
stateGuard: StateGuard<{ maxNumberOfItems: number }, State<IContext, IEvent> | undefined>
```

**Comment by PetrBrabec** [comment]
@CodingDive That's it, I have a react component which properties are reflected to the state context. 
What you can see in the _expected usage_ section is an abstract type for a guard that can for example check if the `disabled` property equals `true`.

**Comment by FloValence** [comment]
Hello,
Any news on the Guard typing? It seems that I'm still forced to cast `cond` as `any` using the `Condition` type for the guards.

**Comment by Andarist** [comment]
@FloValence  I'm not sure if your issue is exactly the same as the one outlined in this issue. We are working on improving TS experience in https://github.com/statelyai/xstate/pull/2674

**Comment by davidkpiano** [comment]
Closing as this is now improved in #2674
