### ISSUE TITLE
Not supplying a config level context and using assign should be an error

### ISSUE THREAD

**Issue by UberMouse** [statelyai/xstate#1228]
I just got bit by this, probably spent approx 7h debugging everything under the sun I could think of. Just didn't think to check I had set an initial context for the machine in the config (because my initial context was an empty object).

I guess I had assumed that xstate would create an empty context object if I tried to use assign to set something on the context. I was lead in the wrong direction when I couldn't see the assign action in the actions property of the state object I was logging in onTransition. Thought somehow the assign was getting removed from the entry actions.

It feels like this should be an error instead of xstate just silently failing to assign new values to the context object.

**Comment by Andarist** [comment]
Could you prepare a quick repro case? Would allow us to check out how things behave quicker.

**Comment by UberMouse** [comment]
I'll create one tomorrow when I'm back at work. But it seems to be as simple as a machine that has an context of `undefined` causes `assign` to no-op silently.

**Comment by Andarist** [comment]
Right, I understand the simplicity of the issue but providing a repro case helps nevertheless. We try to handle as many questions/issues we can and any help given to us is highly appreciated because setting things up takes time (even if probably not that much time in this case).

**Comment by davidkpiano** [comment]
In `xstate@beta`, the machine `context` is always defined, and initialized to an empty object `{}` if not specified. This issue is mitigated in that version:

```ts
  const machine = createMachine({
    entry: assign({
      foo: 'bar'
    })
  });

  machine.initialState.context; // { foo: 'bar' }
```
