### ISSUE TITLE
[TypeScript] Using sendParent requires exposing child events in parents machine Events Type

### ISSUE THREAD

**Issue by UberMouse** [statelyai/xstate#1229]
I'm having a go at using Actors for the first time and there seem to be problems with it in TypeScript.

<del>1. Because the type definition for `sendParent` has the first argument typed as `event: Event<any> | SendExpr<TContext, TEvent>` it ends up collapsed to just `event: any` when the type is resolved (which also means passing a function to access `ctx` and `event` is a type error)
2. `sendParent` inherits the events generic of the machine it's in, so even if the above is changed to `event: TEvent["type"] | SendExpr<TContext, TEvent>` or similar the only events you can send are the events the machine can handle. Not the parent machine. 
3. If you create another type to represent the events that can be sent to the parent, `sendParent`s generics don't support different input/output generics so you have to merge the machines event type and the parent events it sends together. Not the worst but can easily lead to valid typed code that is invalid at runtime.</del> (fixed in 4.10)
4. If you include the above type in the parent machines event union it exposes the event external users of the machine. Which is not ideal, I only want it sent by the child machine

<del>A potential fix for 1 is changing the definition of `sendParent` from 
`export declare function sendParent<TContext, TEvent extends EventObject>(event: Event<any> | SendExpr<TContext, TEvent>, options?: SendActionOptions<TContext, TEvent>): SendAction<TContext, TEvent>;
`
to
`export declare function sendParent<TContext, TEvent extends EventObject>(event: TEvent | TEvent["type"] | SendExpr<TContext, TEvent>, options?: SendActionOptions<TContext, TEvent>): SendAction<TContext, TEvent>;
`.

<del>I doubt 2 can be improved much, you just need to type the generics yourself.</del>

<del>3 is a bit trickier, I had a go at adding a 3rd generic argument to specify the type of the output events but then the return value doesn't line up with what the rest of the type definitions expect (since it's now returning a `SendAction<TContext, TOutputEvent>` instead of `SendAction<TContext, TEvent>` like is expected.</del>

4 is similar to 3 but more complicated because it's a heavily used type (`StateMachine`). Seems like it could be changed in a similar way to #711?

With my above potential fix for 1 I can get it to work correctly with the following pattern (pulled straight out of the code so the specific details are missing context, the pattern it represents doesn't depend on those details).

Declare a type for the parent events
```
type ParentEvents<T> = { type: "DATA_LOADED"; data: T };
export type { ParentEvents as DataLoaderEvents }
```

Manually specify the generics for the machines events and the parent events in the `sendParent` call
```
[Actions.submitData]: sendParent<Context, Events, ParentEvents<TData>>((_ctx, event) => {
  assert(event.type === "done.invoke.promise");

  return { type: "DATA_LOADED", data: event.data };
})
```

Add the exported `DataLoaderEvents` to the event type union for the parent machine that spawns the child machine

```
type Events =
  | { type: "SWITCH_TO_REPO"; repoId: string }
  | { type: "SWITCH_ACTIVE_BRANCH"; switchTo: string }
  | { type: "ERROR_FETCHING" }
  | DataLoaderEvents<Repository[]>;
```

Now you can ensure that the types of the events the child machine is sending to the parent are typed correctly in both the child and parent machine, with the above problems described in <del>3 and</del> 4 still applying.

I'm not sure how much/what can be improved here (apart from the issue in 1) so I would be curious to hear some other opinions. Or maybe I've just miss understood how I should be using actors and there are better ways to accomplish this.

**Comment by Andarist** [comment]
> sendParent inherits the events generic of the machine it's in, so even if the above is changed to event: TEvent["type"] | SendExpr<TContext, TEvent> or similar the only events you can send are the events the machine can handle. Not the parent machine.

This has been fixed in v4.10: https://github.com/davidkpiano/xstate/blob/4282c1ef1b0817fa4572b008e63078089d6a918d/packages/core/CHANGELOG.md#minor-changes

**Comment by UberMouse** [comment]
Ah great. That gives me some impetus to fix our open XState 4.10 PR that has some problems.

**Comment by davidkpiano** [comment]
@UberMouse Can you create a CodeSandbox demonstrating the 4th issue?

**Comment by UberMouse** [comment]
Here you go @davidkpiano https://codesandbox.io/s/affectionate-dream-2uvsb?file=/src/index.ts

I've added comments on line 40 & 80 with the problem. Basically need a way to separate the events sent by child machines to their parents out of the events that can be sent to the machine. Unless that's already possible some other way than I have set it up in that code sandbox 🤷

**Comment by Andarist** [comment]
I believe that this issue is somewhat fixed in v5 but the parent<->child communication is still not fully type-safe. We are aware of the issue and we'll be thinking about remedies to that. This issue alone though can be closed now.
