### ISSUE TITLE
[TypeScript] Inlined `send` & `sendParent` not type checked correctly.

### ISSUE THREAD

**Issue by danielkcz** [statelyai/xstate#1250]
**Description**
Possible regression from #1178 where inlined `send` and `sendParent` isn't correctly type-checked.

**Expected Result**
Events should be type-checked correctly.

**Actual Result**
Typos in event names are ignored.

**Reproduction**
https://codesandbox.io/s/inspiring-snow-c3ich?file=/src/index.ts

**Comment by davidkpiano** [comment]
This correctly throws an error, and keep in mind that you can `send(...)` _any event_ to any target, so it's infeasible to limit the events sent to just those defined on the machine.

We can probably improve the typings for this in V5, but see this PR (and related issues) for now: https://github.com/davidkpiano/xstate/pull/1178 #711

**Comment by Andarist** [comment]
> This correctly throws an error, and keep in mind that you can send(...) any event to any target,

It's true for `send`s to **other** machines but a simple `send('FOO')` is being sent to the same machine so limiting to own events would be preferable. If only we could write proper overloads.

**Comment by davidkpiano** [comment]
I'll take a stab at seeing if we can overload `actions.send` to do the right thing.

**Comment by FredyC** [comment]
Yea, I should have probably elaborated more. It's coming from [discussion about strict mode](https://github.com/davidkpiano/xstate/discussions/1248#discussioncomment-28247). Obviously, if TS doesn't work for such a simple case, the strict mode is a very useful "crutch". Can you reopen, please?

**Comment by hedgepigdaniel** [comment]
I've worked around this issue by narrowing the types for `send` and `sendParent`, in a way specific to each machine: https://github.com/statelyai/xstate/issues/2994#issuecomment-1028529632

**Comment by davidkpiano** [comment]
@Andarist Would this be fixed by the recent type changes?

**Comment by Andarist** [comment]
Unfortunately, not entirely - some flavors of `sendTo` will be improved (when you send to an actor ref from context or something, but not when you send to it by its string id). `sendParent` stays loosely typed as we don't know the parent's type. 

That being said, we are aiming to improve this situation in v5. We take types into consideration when thinking about all the available APIs there

**Comment by davidkpiano** [comment]
Now typed correctly in XState v5 beta: https://codesandbox.io/s/mutable-frog-4g5j66?file=/src/index.ts

**Comment by andrecrimb** [comment]
@davidkpiano is the link provided above is still valid for the `sendParent` case?

**Comment by davidkpiano** [comment]
> @davidkpiano is the link provided above is still valid for the `sendParent` case?

Here is the updated link: https://codesandbox.io/p/devbox/mmvn4k?file=%2Fsrc%2Findex.ts%3A18%2C16
