### ISSUE TITLE
Context displayed incorrectly when using JS 'Map' object in context

### ISSUE THREAD

**Issue by nickzylstra** [statelyai/xstate#1264]
https://github.com/davidkpiano/xstate/blob/05477103bfb42a8bd0a9ef9291a13f178ec2bc4f/packages/xstate-test/src/index.ts#L200

`JSON.stringify` shows `{}` when called on a JS Map, regardless of Map content.  This leads to confusing failed test messages when the current context has a Map value in it.

Possible solution using `replacer` and `reviver`:
[stackoverflow](https://stackoverflow.com/a/56150320/11478758)

**Comment by Andarist** [comment]
I believe that nowadays there is a `stateSerializer` option available that can be used to serialize things in a custom way.
