### ISSUE TITLE
Wildcard Descriptors Do Not Transition When Child State Invokes Error

### ISSUE THREAD

**Issue by x-aaron-moore** [statelyai/xstate#1340]
**Description**
Create a machine with a parent state that has a wildcard descriptor transition, and child states with service invocations that do not have `onError` transitions hooked up. Then, cause an error to be thrown on of the children's service invocations.

**Expected Result**
The wildcard transition should be taken.

**Actual Result**
An error was raised of this shape: `Missing onError handler for invocation '{serviceId}', error was '{error message}'. Stacktrace was '{error stack trace}'`

**Reproduction**
 - https://codesandbox.io/s/still-sky-z5do6?file=/src/index.js
 - Visualizer: https://xstate.js.org/viz/?gist=https://gist.github.com/x-aaron-moore/03f141b657dbdbef5983d54c894c2a36

**Additional context**
Xstate Version: 4.11.0

**Comment by davidkpiano** [comment]
The interpreter for this is expecting that `error.platform.[id]` event to be present in `nextEvents`; otherwise, it just throws it as an error.

The workaround is to handle that error. You can either manually type `"error.platform.process1"` or use `error()` from `xstate/lib/actions`:

```js
import { Machine, interpret } from "xstate";
import { error } from "xstate/lib/actions";

export const ProcessingMachine = Machine(
  {
    id: "machine",
    initial: "processing",
    states: {
      processing: {
        initial: "processing1",
        states: {
          processing1: {
            invoke: { src: "process1", onDone: "processing2" }
          },
          // ...
        }
      },
      // ...
    },
    on: {
      [error("process1")]: ".failed" 
    }
  }
});
```

**Comment by davidkpiano** [comment]
- Partial wildcard event descriptors are now supported in `xstate@beta`
- The linked reproduction seems to be working as expected (let me know if something else is expected)
