### ISSUE TITLE
Warning: Attempted to spawn an Actor (ID: "undefined") outside of a service. This will have no effect. 

### ISSUE THREAD

**Issue by jramstedt** [statelyai/xstate#1429]
**Description**
This might be regression with xstate@4.13.0, since I didn't get this error with previous versions.
Code works as expected altough I get a warning when machine is started.

I have entry actor:
export const machine = Machine<Context, MachineEvent>({
  id: 'machineId',
  initial: State.Enter,
  entry: assign({
    listenerRef: context => spawn(context.view.pick$.pipe(map(data => ({ type: Events.MyEvent, data}) )))
  }),
  states: {
    [State.Enter]: {
....

That machine is used as child machine.

**Expected Result**
No warnings

**Actual Result**
Warning: Attempted to spawn an Actor (ID: "undefined") outside of a service. This will have no effect.

**Reproduction**
https://codesandbox.io/s/gracious-noether-k16o0

**Additional context**
4.13.0

**Comment by davidkpiano** [comment]
This warning can be safely ignored.

**Comment by Andarist** [comment]
@jramstedt you can make that actor "lazy" and this should get rid of the warning, see here: https://codesandbox.io/s/serene-euler-mhid9?file=/src/index.ts:766-858

**Comment by davidkpiano** [comment]
The new way to do this in `xstate@beta` is by using lazy context and grabbing `{ spawn }` from there:

```ts
  context: ({ spawn }) => ({
    count: 0,
    pick$,
    listenerRef: spawn(
      fromEventObservable(() =>
        pick$.pipe(map((data) => ({ type: "testEvent", data })))
      )
    )
  }),
```
