### ISSUE TITLE
xstate/test bug: `context` not available in `exec` function when using puppeteer

### ISSUE THREAD

**Issue by jamesholbert** [statelyai/xstate#1538]
## Bug 
`exec` function, when using puppeteer, replaces `context` with `page` when it should add/reorder it

## Description:
From the docs:
```
exec (function): Function that executes the events. It is given two arguments:
- testContext (any): any contextual testing data
- event (EventObject): the event sent by the testing model
```
then right below that:
```
const toggleModel = createModel(toggleMachine).withEvents({
  TOGGLE: {
    exec: async (page) => {
      await page.click('input');
    }
  }
});
```
## (Bug) Potential fix:
the `exec` api should probably be something like 
```
`exec: async (page, context, event) => {
...
```
but in order to not make it a breaking change it should probable be
```
`exec: async (page, event, context) => {
...
```

- @davidkpiano requested the issue
- This is potentially a breaking change if the `context, event` conventional order is maintained
- Doesn't seem to be part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

**Comment by davidkpiano** [comment]
Likely, the fixed API would look like:

```js
exec: async (page, event, { state }) => { ... }
```

Where the 3rd argument provides a bunch of metadata, including `state` (so you can grab `state.context`).

**Comment by davidkpiano** [comment]
The tentative API for this in `@xstate/test` is:

```js
execute: async (step, testContext) => {
  // A step consists of both the state before taking the event, and the event to be sent
  console.log(step.state, step.event);
}
```

**Comment by davidkpiano** [comment]
State assertion functions in `@xstate/test@alpha` now have the `state` as the first argument:

```js
const model = createTestModel(machine);

for (const path of model.getPaths()) {
  const page = await browser.newPage();

  await path.test({
    states: {
      loading: (state) => {
        // assert page is in correct state
      }
    }
  });
}
```
