### ISSUE TITLE
Using `spawn()` in `onEntry` vs in a transition doesn't return the same result for the same configuration

### ISSUE THREAD

**Issue by Shiroy** [statelyai/xstate#1567]
**Description**
When a machine is spawned in action triggered in the `onEntry` event, the resulting interpreter can't be used with `useService`. The `machine` property is missing.

When I run the same code during a transition, the resulting interpreter can be used with `useService`.

**Expected Result**
The resulting interpreter should be usable with `useService` in both scenarios.

**Actual Result**
Exception:
```
Attempted to use an actor-like object instead of a service in the useService() hook. Please use the useActor() hook instead.
```

**Reproduction**
https://codesandbox.io/s/bullet-journal-8v5rg

**Additional context**
The machine property is missing on the returned interpreter. On `src/machines/todoList.ts:60`, if you uncomment `ref.machine = ...`, `useService` accept the reference and everything works as expected.

It's still un-clear whether I should use `useService` or `useActor`. However the typing clearly indicates that I have to use `useService` as the returned typed of `spawn` is expected to be an `Interpreter` when passing a `StateNode` or a `StateMachine` as an argument.

On `src/machines/todoList.ts:104`, I perform **the exact same operation** and it works as expected without any workaround.

**Comment by davidkpiano** [comment]
Briefly investigating this, it's a bit tricky because when an actor is spawned as the initial state (in a not-yet-started service), that actor needs to be a "deferred actor" instead of a live service, so it will be an `Actor` type.

Making the interpreter an `Actor` instead to simplify the types would work, but would be a breaking change.

Here's one workaround you can do (see the `Actor<any>` typings; you can use `Actor<SomeEvent>` as well):

```ts
export function TodoItem({ item }: { item: Actor<any> }) {
  console.log(item);
  const [machine, send] = useActor(item);

  // ...
}

// ...

export default function TodoList(props: TodoListProps) {
  const [machine, send] = useMachine(todoListMachine, { devTools: true });

  const items = machine.context.items.map(i => {
    return <TodoItem item={i.ref as Actor<any>} key={i.uuid} />
  });
```

**Comment by Andarist** [comment]
In the recent versions of `@xstate/react` we've removed `useService` altogether and from what I've checked the `useActor` works for your use case here.
