### ISSUE TITLE
XState deps require both React 16 & 17

### ISSUE THREAD

**Issue by tomByrer** [statelyai/xstate#1584]
**Description**
```bash
$ yarn add xstate
yarn add v1.22.1
warning "@xstate/react > use-subscription@1.5.0" has incorrect peer dependency "react@^17.0.0".
success Saved 1 new dependency.
Done in 8.57s.

## (updated "react": "~17.0.1" in package.json)

tomby@MSI MINGW64 /d/doc/prog/tb/react/reactnative/expo-radio (master)
$ yarn
yarn install v1.22.1
warning " > @xstate/react@1.0.1" has incorrect peer dependency "react@^16.8.0".
warning "@xstate/react > use-isomorphic-layout-effect@1.0.0" has incorrect peer dependency "react@^16.8.0".
warning " > react-native@0.63.2" has incorrect peer dependency "react@16.13.1".
```

**Expected Result**
all deps have same requirements

cheers

**Comment by Andarist** [comment]
I've rechecked and all the involved packages have now the same peer dependency range on React, this includes `@xstate/react`, `use-isomorphic-layout-effect`, and `use-subscription`. So I think this has been fixed along the way and this issue can be closed. If you still find any problems with this - just ping me here and I will reopen this ticker or open a new issue about this.
