### ISSUE TITLE
Unhelpful error message with failing guard after invoked promise is rejected

### ISSUE THREAD

**Issue by njdancer** [statelyai/xstate#1605]
**Description**
When an invoked promise is rejected, and one of the following guards(actions etc possibly cause this as well) throws an exception the machine fails to transition(pretty much as expected) however the error message presented is particularly unhelpful as ```reportUnhandledExceptionOnInvocation``` assumes that promise was rejected with an error which afaik should not be required with a promise. This results in ```UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined``` being logged to console.

**Expected Result**
I think the outcome is fine but it would be preferable to know that the failure has been caused by the guard and not the promise itself. It would also be nice to have received a stack trace of the error thrown from the guard itself.

**Actual Result**
```UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined``` logged to console

**Reproduction**
https://codesandbox.io/s/xstate-example-template-vanilla-forked-gdfil

**Additional context**
```xstate: 4.13.0```

**Comment by DasdWaller** [comment]
I remove the second invoke and works fine. 
https://codesandbox.io/s/xstate-example-template-vanilla-forked-ddpsy?file=/src/index.js

**Comment by njdancer** [comment]
@DasdWaller The top level invoke is just the state node name(a bit confusing in hindsight) and completely arbitrary. The second level invoke is required in order for the state node to be interpreted correctly by xstate. With your modification the state node effectively has no config. The state machine upon entering the "invoke" state does nothing. If you check console in your code sandbox you will see the machine starts in the "invoke" state and never transitions away as the promise is no longer being invoked. You are no longer seeing the error because you're failing to reach the condition that causes it😉.

To try and make this clearer I've made a new sandbox with this state node renamed and the issue persists.
https://codesandbox.io/s/xstate-example-template-vanilla-forked-o3jul

To be clear, what I'm doing **should** cause an error, but a more descriptive error will be more helpful to a consumer of xstate in the future should they make the same mistake I did. If you take a look at 7e03fee9cfea163f60637763069cd03c0d372c16 you will see what changes @davidkpiano has made to improve this.

**Comment by davidkpiano** [comment]
In XState v5, this now gives a better error: https://codesandbox.io/p/sandbox/xstate-example-template-vanilla-forked-k4656y?file=%2Fsrc%2Findex.js%3A27%2C43

```
Unable to evaluate guard in transition for event 'xstate.error.actor.machine.invoke[0]' in state node 'machine.invoke':
some error
```
