### ISSUE TITLE
Inspector throws TypeError on AudioContext events with integer names

### ISSUE THREAD

**Issue by jebeck** [statelyai/xstate#1648]
**Description**

A machine that includes an [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) in its `context` throws a couple of `TypeError: _event.name.indexOf is not a function` on creation (via `createMachine` or `Machine`). From digging into my node_modules and adding some logging of `_event` around the transpiled version of [this line](https://github.com/davidkpiano/xstate/blob/xstate%404.14.0/packages/core/src/interpreter.ts#L703), it seems like this is because some events that the inspector is picking up from the initialization of the AudioContext have integer `name`s rather than strings:

<img width="641" alt="Screen Shot 2020-11-22 at 03 24 51" src="https://user-images.githubusercontent.com/1588547/99902397-6659ff00-2c72-11eb-8933-47c8062a712a.png">

(While the second problematic event here has the telltale `AudioDestinationNode` to make clear the source of the event, it's less obvious the first event (with `name` of 2) is, except that the AudioContext always shows up with id of 2 in my WebAudio inspector dev tools extension, so I think that's pretty telling.)

**Expected Result**

No annoying red console warnings when running @xstate/inspect :)

**Actual Result**

Annoying red console warnings (that, to be fair, do not appear to affect functionality, and I realize the WebAudio API is not exactly in common use 🙃)

**Reproduction**

[Code Sandbox](https://codesandbox.io/s/funny-flower-crb76) which works just fine if you comment out the `inspect()` call

**Additional context**

I updated the Code Sandbox template to match my current versions of everything as I was trying to figure this one out...

Just to get things running I updated the code in my node_modules from this:

```js

    if (_event.name.indexOf(errorPlatform) === 0 && !this.state.nextEvents.some(function (nextEvent) {`
```

to

```js

    if (typeof _event.name === 'string' && _event.name.indexOf(errorPlatform) === 0 && !this.state.nextEvents.some(function (nextEvent) {
```

...but I'm guessing that's not exactly what you would want for a long-term fix. On the off chance it is, happy to open a PR, just LMK!

**Comment by Andarist** [comment]
I can't reproduce it using the provided CodeSandbox - I've both tried clicking the button and sending events using the inspect.

I'm not sure what exactly is being put into those events that cause a failure for you but guarding against `_event.name` being of a different type than a string is not desirable. At the moment we expect all events to have a string type (where `event.type === _event.name`) - we maybe could loosen this up but that's a more profound change and I'm not sure if it's really worth it. Strings are perfect for what we use them for at variety of places.

**Comment by jebeck** [comment]
So it fails for me immediately on opening the Code Sandbox tab:

<img width="1904" alt="Screen Shot 2020-11-22 at 11 43 14" src="https://user-images.githubusercontent.com/1588547/99915371-23bb1580-2cb8-11eb-9f0f-1ff16eea86c2.png">

Just did a bit more thinking & testing, and the issue here is environmental. The Code Sandbox doesn't fail for me if I disable the WebAudio dev tools extension. (You can't replicate this without a lot of effort, unfortunately. For some reason [the published version](https://chrome.google.com/webstore/detail/web-audio-inspector/cmhomipkklckpomafalojobppmmidlgl?hl=en) hasn't been updated since 2017 and doesn't even work IME. One needs to build the extension one's self from [source](https://github.com/google/audion#web-audio-inspector) to use it, and that unfortunately involves installing Java IIRC 🙃.)

One thing I don't understand here that could perhaps be an easy and more principled fix is why @xstate/inspect is picking up the events that it now looks like are coming from the WebAudio dev tools browser extension?

I get that this is a pretty edgy edge case, and so far it appears to only cause noisy error logging that doesn't affect functionality. So if you need to close, close. It just seemed like a potentially very easy fix. (And also the whole reason I was obsessively tracking down the error is that this is only my third project with XState, so I'm still learning my way around it, and it just wasn't clear that the problem wasn't a problem with my machine config, especially since the error is actually thrown from the core XState interpreter.)

**Comment by Andarist** [comment]
> One thing I don't understand here that could perhaps be an easy and more principled fix is why @xstate/inspect is picking up the events that it now looks like are coming from the WebAudio dev tools browser extension?

It's probably using `postMessage` for some reason and the inspector picks up those unrelated events. You can see our listener [here](https://github.com/davidkpiano/xstate/blob/326b28d25535c8ce1520258b80a119f26847951b/packages/xstate-inspect/src/index.ts#L160). We should either discard events from sources that we don't trust or switch to using a MessageChannel that would allow for using a more direct channel of communication between the inspector and the host page.

**Comment by jebeck** [comment]
Yeah I browsed the code a bit yesterday and I think I saw `postMessage`. The MessageChannel approach sounds look a good idea (if obviously not a priority). Thanks for the responsiveness on this, I'm glad to have an understanding of what's happening now.

**Comment by davidkpiano** [comment]
This no longer seems to be an issue with the latest versions of the `xstate` packages: https://codesandbox.io/s/damp-sun-wxhfys?file=/src/index.js:0-749
