### ISSUE TITLE
getShortestPathPlansTo and getSimplePathPlansTo missing from docs

### ISSUE THREAD

**Issue by jamesholbert** [statelyai/xstate#1682]
Feature request

`getShortestPathPlansTo` and `getSimplePathPlansTo` missing from docs

Suggested API:

`testModel.getShortestPathPlansTo(filterFunction)`
Returns an array of testing plans based on the shortest paths from the test model's initial state to a given state specified by the filterFunction.

Argument	Type	Description
`filterFunction` Function	Takes in the state but only returns paths that result in the filtering evaluating to `true`

```
const ticTacModel = createModel(ticTacToeMachine).withEvents({
  /* ... */
});

const plans = ticTacModel.getShortestPathPlansTo(
  (state) => state.matches("winner") && state.context.winner === "X"
);
```

**Comment by jamestharpe** [comment]
https://github.com/davidkpiano/xstate/pull/1941

**Comment by davidkpiano** [comment]
As the next version of `@xstate/test` is being worked on, the docs will be rewritten, but these methods are removed.

**Comment by davidkpiano** [comment]
> @davidkpiano Will there be something comparable to these functions in the new version?

Yes there will
