### ISSUE TITLE
Warning: No implementation found for action type 'xstate.assign'

### ISSUE THREAD

**Issue by davydof** [statelyai/xstate#1792]
**Description**
Hello, after I've updated on `4.14.1` I get warning:
```
Warning: No implementation found for action type 'xstate.assign'
```
from place:
https://github.com/davidkpiano/xstate/blob/b64c8719b043a8f283ab12e6f4984e39e56c7b4c/packages/core/src/interpreter.ts#L906-L913

```js
import { assign, Machine } from 'xstate';

const createMachine = () => Machine({
  initial: 'pending',
  context: {
    foo: undefined,
  },
  states: {
    pending: {
      // with event instead of invoking actor warning appears as well
      /*on: {
        DO: 'done',
      },*/
      invoke: {
        src: () => Promise.resolve(),
        onDone: 'done',
      },
    },
    done: {
      exit: assign({
        foo: () => undefined,
      }),
    },
  },
});
```

Test:
```js
import { interpret } from 'xstate';

interpret(createMachine()).start();
```

No warning: `4.14.0`
Warning appears: `4.14.1`

**Expected Result**
No warnings

**Actual Result**
```
console.warn node_modules/xstate/lib/utils.js:451
Warning: No implementation found for action type 'xstate.assign'
```

**Reproduction**
https://codesandbox.io/s/xstate-warning-no-implementation-found-for-action-type-xstateassign-1699k?file=/index.test.js

**Comment by davidkpiano** [comment]
The reproduction is not showing that warning.

**Comment by davydof** [comment]
@davidkpiano 
Yes, it's true, but why I can get it in tests locally?

**Comment by davidkpiano** [comment]
Not sure, but a reproduction is necessary. A repo is fine.

**Comment by davydof** [comment]
Looks strange
I get it in tests.
And in production but not every time.

What I can do?

**Comment by Andarist** [comment]
Debug.

**Comment by davydof** [comment]
Reproduced, please check [codesandbox](https://codesandbox.io/s/xstate-warning-no-implementation-found-for-action-type-xstateassign-1699k?file=/index.test.js).

After test added:
```
interpreted.stop()
```

**Comment by Andarist** [comment]
I can confirm the issue and got a basic understanding of it in our codebase - gonna comment more about this sometime later.

**Comment by davidkpiano** [comment]
For now, you can safely ignore that warning (for `xstate.assign` specifically).

**Comment by Andarist** [comment]
The problem comes from this call `exec` call:
https://github.com/davidkpiano/xstate/blob/ab520711c967537b02a522f33bca5d4c57f5d1f2/packages/core/src/interpreter.ts#L506-L510

This executes actions from a state definition and this contains `assign` actions - whereas when transitioning actions are taken from the `state` and this doesn't contain `assign` actions:
https://github.com/davidkpiano/xstate/blob/ab520711c967537b02a522f33bca5d4c57f5d1f2/packages/core/src/interpreter.ts#L241-L243

As a stopgap, we could just ignore `assign` actions there as well but if we want to adhere to SCXML-defined semantics then we should update the context value based on those `assign` actions - so a latter action sees the changed context value. As we resolve `assign` actions within the Machine and not the Interpreter - we might want to move part of the stopping logic to the Machine (?).

**Comment by davidkpiano** [comment]
> As a stopgap, we could just ignore `assign` actions there as well but if we want to adhere to SCXML-defined semantics then we should update the context value based on those `assign` actions - so a latter action sees the changed context value. As we resolve `assign` actions within the Machine and not the Interpreter - we might want to move part of the stopping logic to the Machine (?).

Yeah, the quick fix here is to quell the warning for `assign` actions.

The bigger fix involves what we've done in v5, which moving the `assign` action to be sequential, which is not the case in v4, so there wouldn't be much benefit (and probably some unexpected behavior? Not sure) to doing it here.

**Comment by huan** [comment]
> Warning: No implementation found for action type 'xstate.choose'

I ran into the above warning today, does it can be safely ignored as well?

**Comment by davidkpiano** [comment]
> > Warning: No implementation found for action type 'xstate.choose'
> 
> I ran into the above warning today, does it can be safely ignored as well?

Yes, you can safely ignore this.

**Comment by Andarist** [comment]
Just note that when we release https://github.com/statelyai/xstate/pull/3126 then this `choose` action **won't** be ignored. So the final behavior will be slightly different than what it is for you today.

**Comment by huan** [comment]
Thanks for the confirmation!

I think we should publish the `next` git branch to the `next` npm tag now, so that users like me can test the v5 behavior as soon as possible with convenience? (With the necessary adaption)
