### ISSUE TITLE
@xstate/inspect - ActorRef links don't always work on refresh. Require browser restart most of the time. 

### ISSUE THREAD

**Issue by a-y-u-s-h** [statelyai/xstate#1803]
**Description**
When you first run your application development server, inspector shows you a link for `actorRef`, takes you to the internal state machine of that actor and it's nice. But when you refresh the page to reflect changes in the machine during development, that link disappears (becomes normal text). That said, in the dropdown on the right side of inspector which allows us to select different actors - works fine in both cases. Also, when you stop the development server and run it again, it shows the normal text instead of link (because of some caching maybe) but when you close the browser and go to the application, it works fine. Shows the expected result.

Update:

May not always work after restarting browser either. Maybe I did something different the other time. But it seems the drop-down on the right, when it displays the other machine visualized, it's not able to recognize the fact that the machine there is invoked by a parent machine.

**Expected Result**
![2020-12-31_01-29-11_screenshot](https://user-images.githubusercontent.com/19586719/103435740-5225fc00-4c39-11eb-97dd-6228754ca340.png)

**Actual Result**
![2020-12-31_01-29-40_screenshot](https://user-images.githubusercontent.com/19586719/103435748-5c47fa80-4c39-11eb-950c-ad6c77b90268.png)

**Reproduction**
 [Codesandbox](https://codesandbox.io/s/xstate-bug-1803-s9lzo?file=/src/index.js)

**Additional context**

 ```json
 {
   "xstate": "^4.15.3",
   "@xstate/inspect": "^0.4.1",
   "@xstate/react": "^1.2.2",
  }
```

**Comment by Andarist** [comment]
> Reproduction
> Not relevant, will happen with any code that invokes a machine.

The reproduction is **always** relevant - it cuts the time for maintainers to look into the issue so they don't have to waste time on setting up the repro case.

**Comment by a-y-u-s-h** [comment]
> > Reproduction
> > Not relevant, will happen with any code that invokes a machine.
> 
> The reproduction is **always** relevant - it cuts the time for maintainers to look into the issue so they don't have to waste time on setting up the repro case.

Just a second, will create a codesandbox.

**Comment by a-y-u-s-h** [comment]
Updated reproduction: [Codesandbox](https://codesandbox.io/s/xstate-bug-1803-s9lzo?file=/src/index.js)

**Comment by davidkpiano** [comment]
Closing as it is recommended to use the current inspector at https://stately.ai/viz instead.
