### ISSUE TITLE
@xstate/inspect is not showing any events

### ISSUE THREAD

**Issue by danielkcz** [statelyai/xstate#1843]
**Description**
@xstate/inspect is not showing any events.

**Expected Result**
To see events in the Events tab.

**Actual Result**
No events are shown unless manually send from within the inspector. In the State, it's clearly visible the latest event that happened.

**Reproduction**
https://codesandbox.io/s/persistence-with-actors-and-side-effects-forked-5njnx?file=/src/index.js

**Additional context**
I tried running this locally in case it's CodeSandbox issue, but it behaves the same way. I also tried version 0.3.0 which I remember was working in the past, but no difference either. I assume it's the problem in the online version of https://statecharts.io/inspect.

**Comment by anthonychung14** [comment]
I still see this as of @xstate/inspect 0.7

Any pointers on where the issue could be?

**Comment by anthonychung14** [comment]
uhhhh. okay events show up now. o___O idk what happened but hooray?

**Comment by davidkpiano** [comment]
> uhhhh. okay events show up now. o___O idk what happened but hooray?

Very strange, glad it's working now! I'm going to close this and reopen if it happens again.
