### ISSUE TITLE
Project fails to compile when TEvent is a union and actions/guards expect only a subset of that union.

### ISSUE THREAD

**Issue by universalhandle** [statelyai/xstate#1858]
**Description**
Project fails to compile when a `Machine`'s `TEvent` is a union and actions/guards expect only a subset of that union.

**Expected Result**
Project should compile.

The reproduction code is riff on the [example in the docs](https://xstate.js.org/docs/guides/context.html#context) modeling a glass of water. Changes of note:
- I added the `GlassContext`, `GlassStateSchema`, `GlassFillEvent`, and (unused) `GlassEmptyEvent` interfaces.
- I added the `GlassEvent` type, which is a union of `GlassFillEvent` and `GlassEmptyEvent`.

Because `GlassFillEvent` is a subset of `GlassEvent`, I would expect that the `actions` member of the config object would be happy with the `addWater` event.

**Actual Result**
For the reproduction linked below, VS Code displays this complaint when hovering over `actions: { addWater }`:

```
(property) addWater: AssignAction<GlassContext, GlassFillEvent>
Type 'AssignAction<GlassContext, GlassFillEvent>' is not assignable to type 'ActionObject<GlassContext, GlassEvent> | ActionFunction<GlassContext, GlassEvent>'.
  Type 'AssignAction<GlassContext, GlassFillEvent>' is not assignable to type 'ActionObject<GlassContext, GlassEvent>'.
    Types of property 'exec' are incompatible.
      Type 'ActionFunction<GlassContext, GlassFillEvent> | undefined' is not assignable to type 'ActionFunction<GlassContext, GlassEvent> | undefined'.
        Type 'ActionFunction<GlassContext, GlassFillEvent>' is not assignable to type 'ActionFunction<GlassContext, GlassEvent>'.
          Types of parameters 'event' and 'event' are incompatible.
            Type 'GlassEvent' is not assignable to type 'GlassFillEvent'.
              Type 'GlassEmptyEvent' is not assignable to type 'GlassFillEvent'.ts(2322)
```

For `guards: { glassIsFull }`, the complaint is:

```
(property) glassIsFull: (context: GlassContext, event: GlassFillEvent) => boolean
Type '(context: GlassContext, event: GlassFillEvent) => boolean' is not assignable to type 'ConditionPredicate<GlassContext, GlassEvent>'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'GlassEvent' is not assignable to type 'GlassFillEvent'.
      Type 'GlassEmptyEvent' is not assignable to type 'GlassFillEvent'.ts(2322)
```

(Note: the latter complaint does not appear in CodeSandbox for reasons I haven't explored.)

**Reproduction**
[CodeSandbox reproduction](https://codesandbox.io/s/dawn-cache-2rjm9).

**Workarounds**
First idea: define your actions/guards inline, without type variables, e.g.:

```typescript
  {
    actions: {
        addWater: assign({
            amount: (context, event) => context.amount + 1
          })
     },
    guards: {
        glassIsFull: (context, event) => context.amount >= 10
    }
  }
```

Second idea: if your actions require it, use the union for your type var and do type checks inside the function. For example, if `GlassFillEvent` has a property `increase` and `GlassEmptyEvent` has a property `decrease`, you could do:

```typescript
// Action to increment the context amount
const addWater = assign<GlassContext, GlassEvent>({
  amount: (context, event) => {
      const increase = event.type === 'FILL' ? event.increase : 0;
      return context.amount + increase;
  }
});
```

However, TypeScript is supposed to obviate the need to write such defensive code.

**Comment by Andarist** [comment]
This is, unfortunately, quite hard to compute using TS types alone (even given their crazy expressiveness). We are working on a solution for that problem - you can check out this project for now: https://github.com/mattpocock/xstate-codegen

**Comment by davidkpiano** [comment]
The `createModel` helper was recently released that helps with this (docs coming soon)!

```js
import { createModel } from 'xstate/lib/model';

// ...
const glassModel = createModel<GlassContext, GlassEvent>({ amount: 0 });

// Action to increment the context amount
const addWater = glassModel.assign({
  amount: (context, event) => context.amount + 1
});

// the rest of the code stays the same
```

Check it out: https://codesandbox.io/s/musing-smoke-62o2o?file=/src/index.ts

**Comment by Andarist** [comment]
@davidkpiano this doesn't quite help with this problem: https://codesandbox.io/s/jovial-dhawan-p716t?file=/src/index.ts . The problem is that we are currently not able to narrow down `TEvent` for `implementations.actions.*` so they would only accept specific events that are actually processed by specific actions.

**Comment by Andarist** [comment]
This is currently impossible for us to validate at the type level. We can't process the state machine transitions at the type level to learn about the possible event types for given actions. You can use our typegen to get better types in those kinds of situations: https://xstate.js.org/docs/guides/typescript.html#typegen
