### ISSUE TITLE
Inconsistent handling of `StateMachine.withContext` and `useMachine` options.context

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#1882]
**Description**
When the custom initial context is configured with `StateMachine.withContext` API, the machine's context is **completely replaced** with the custom context, as explained [in the docs](https://xstate.js.org/docs/guides/machines.html#extending-machines). In contrast, when using the React hook useMachine, context passed in the options object is **merged** with the machine's context.
Consider:
```javascript
machine.withContext({ data: 42 })  // overwrites machine's context
// vs.
// (in a React component)
useMachine(machine, { context: { data: 42 } }) // merges data into machine's initial context
```
Unless I missed some deeper reasoning, this inconsistency is suboptimal.

**Expected Result**
A consistent behavior when extending state machines with context using both APIs is perhaps expected.

**Actual Result**
Two different methods of extending machine with a custom context have different behavior.

**Reproduction**
https://codesandbox.io/s/condescending-kowalevski-z48m2

**Comment by davidkpiano** [comment]
Yeah, this is currently an inconsistency. In v5, the default behavior will be to _merge_ context, so the behavior will become consistent.

**Comment by davidkpiano** [comment]
In `xstate@beta`, you are encouraged to use `input` instead of directly providing `context`:

```js
const machine = createMachine({
  context: ({ input }) => {
    return { count: input.data }
  }
});

interpret(machine, {
  input: { data: 42 }
}).start();
```
