### ISSUE TITLE
False positive when testing transitions

### ISSUE THREAD

**Issue by TheDutchCoder** [statelyai/xstate#1924]
**Description**
Consider the following state machine:
```ts
export const machine = Machine<{}, MachineState, MachineEvents>({
  id: 'buttonMachine',
  type: 'parallel',
  states: {
    loading: {
      initial: 'idle',
      states: {
        idle: {
          on: {
            TOGGLE_LOADING: 'loading',
          },
        },
        loading: {
          on: {
            TOGGLE_LOADING: 'idle',
          },
        },
      },
    },
  },
})
```

And the following test:
```ts
  it('transitions from `idle` to `loading` when the TOGGLE_LOADING event occurs', () => {
    const expected = 'loading'
    const actualState = machine.transition('idle', 'TOGGLE_LOADING')

    expect(actualState.matches(expected)).toBe(true)
  })
```

Because there is no `idle` state (only `loading.idle`), the test should fail. However the test passes successfully creating a false positive.

**Expected Result**
The test to fail.

**Actual Result**
The test passes

**Reproduction**
https://codesandbox.io/s/wild-thunder-oe915?file=/src/__tests__/index.spec.js

**Additional context**

**Comment by davidkpiano** [comment]
This is now invalid in XState v5 beta, since a valid `State` object is now the only thing allowed to be passed to `machine.transition(...)`. It is recommended to actually create an actor and test it by sending it events in v5:

```ts
const actor = createActor(machine).start();

actor.send({ type: 'TOGGLE_LOADING' });

expect(actor.getSnapshot().matches('loading')).toBe(true);
```
