### ISSUE TITLE
statecharts.io breaks when sending batched events

### ISSUE THREAD

**Issue by pedro-l9** [statelyai/xstate#1929]
**Description**
Whenever I'm sending batched events the inspector website crashes

**Expected Result**
I should be able to inspect batched events the same way it works with single events

**Actual Result**
The website prompts the message "An unexpected error has occurred." and in the console the following error stack is shown
![image](https://user-images.githubusercontent.com/17520099/107696470-c15b2b00-6c90-11eb-8849-ea392b66d875.png)

**Reproduction**
In the following [codesandbox](https://codesandbox.io/s/nifty-moser-ik0uu?file=/src/index.js) whenever you press the "Click me button" more than once the inspector website crashes

**Additional context**
"@xstate/inspect": "^0.4.1",
"@xstate/react": "^1.2.2",

**Comment by Andarist** [comment]
Hi, thank you for the report and sorry for getting to this so late. In the next branch, we have already removed support for batching (you can always just use a regular for loop to achieve very similar behavior). In addition to that, your codesandbox doesn't crash with the new visualizer that you can use like this:
```js
inspect({
  url: "https://stately.ai/viz/?inspect",
  iframe: false
});
```

You can see this in action [here](https://codesandbox.io/s/stupefied-wildflower-3pnfjv).

Given those two things, I don't see this having a high priority for us at this moment so we are probably not going to fix this in the old visualizer. Sorry for the inconvenience
