### ISSUE TITLE
TestModel<>.getShortestPathPlans() getSimplePathPlans() can recurse indefinitely 

### ISSUE THREAD

**Issue by jamestharpe** [statelyai/xstate#1935]
**Description**
Given a circular state machine path through a transient state node in a test model, when getShortestPathPlans() or getSimplePathPlans() is called, a `Maximum call stack size exceeded` exception is thrown.

Example state machine:

```typescript
interface ToggleContext {
  count: number;
}

type ToggleEvent = {
  type: "TOGGLE";
};

const machine = createMachine<ToggleContext, ToggleEvent>({
  id: "machine",
  initial: "inactive",
  context: {
    count: 0
  },
  states: {
    inactive: {
      on: { TOGGLE: "toggling" }
    },
    toggling: {
      onEntry: assign((context) => {
        return { count: context.count + 1 };
      }),
      always: [
        {
          target: "inactive",
          cond: (context) => context.count % 2 === 0
        },
        {
          target: "active",
          cond: (context) => context.count % 2 === 1
        }
      ]
    },
    active: {
      on: { TOGGLE: "toggling" }
    }
  }
});
```

Example test setup:

```typescript
// Edit your service(s) here
const service = interpret(machine).onTransition((state) => {
  console.log(state.value);
});

const model = createModel(machine).withEvents({
  TOGGLE: {
    exec: async (page) => {
      service.send("TOGGLE");
    }
  }
});
```

**Expected Result**

Infinitely recursive paths are not traversed more than once, or the number of recursions is limited by some specified maximum with a sensible default, or there is a specifiable maximum depth with a sensible default.

**Actual Result**

`Maximum call stack size exceeded` exception is thrown

**Reproduction**

https://codesandbox.io/s/trusting-framework-1irmc?file=/src/index.ts

To reproduce the issue, **you must un-comment the last two lines**. I've commented them out because they trigger infinite recursion which can cause your browser tab to freeze/crash.

**Additional context**

None.

**Comment by davidkpiano** [comment]
I'm working on the next version of `@xstate/test`, and this would look like:

```ts
// FUTURE API
const plans = model.getShortestPlans({ traversalLimit: 100 });
// throws "Traversal limit exceeded" if traversal in excess of 100 iterations
```
