### ISSUE TITLE
Sending (self) transition from transition to final state doesn't work

### ISSUE THREAD

**Issue by FokkeZB** [statelyai/xstate#1953]
**Description**

(Actions of) self-transitions send by actions of transitions to final states (read that twice) don't get executed.

**Expected Result**

Anything as part of transitions to a final state to be executed before the machine stops.

**Actual Result**

They don't get executed.

**Reproduction**

https://codesandbox.io/s/festive-napier-ps5yp?file=/src/index.js

<details>
```
const machine = createMachine({
  id: "machine",
  initial: "start",
  states: {
    start: {
      on: {
        END: {
          actions: [
            () => {
              // Always logs
              console.info("END.actions[0]");
            },
            send({ type: "SELF_TRANSITION", data: "END.actions[1]" })
          ],
          target: "end"
        }
      }
    },
    end: {
      // type: "final"
    }
  },
  on: {
    SELF_TRANSITION: {
      actions: (_, { data }) => {
        // Won't log when end.type === 'final'
        console.info("SELF_TRANSITION.actions", data);
      }
    }
  }
});
```
</details>

**Additional context**

I first brought this up as a question at https://github.com/davidkpiano/xstate/discussions/1951

@davidkpiano initially saw this as intentonal:

> When you reach a final state on the root of the machine, the machine is "done" - no other transitions can follow, so no other actions can be executed.

But @Andarist suggested to report it as bug:

> This should actually be executed as it's part of the [`executeTransitionContent`](https://www.w3.org/TR/scxml/#executeTransitionContent) procedure that is called by the [`microstep`](https://www.w3.org/TR/scxml/#microstepProcedure) and at that point, the target state's type and the resulting configuration is not taken into account - this only happens at a latter step of `microstep`, it's [`enterStates`](https://www.w3.org/TR/scxml/#enterStates) that sets `running = false`.

**Comment by davidkpiano** [comment]
@Andarist Re-examining this, the behavior is still as expected.

- Yes, the action should be executed, but it is the _raise_ action ("send" in this case, but really should be raise) that is executed.
- However, after all actions are executed, the machine is in its final state, and it can no longer transition, which means it can no longer execute subsequent transition actions. The transition action belongs to a _new_ transition, not the actions in the original transition content (which are successfully executed).
