### ISSUE TITLE
Typescript can't type the typestate event object of invoked services

### ISSUE THREAD

**Issue by critocrito** [statelyai/xstate#1993]
**Description**
Typescript fails to compile if using TypeStates and `TEvent` is an union for invoked services.

**Expected Result**
The project should compile and the invoked service should recognize the type of the event object. 

**Actual Result**
Typescript shows an error that the property doesn't exist on the event object. 

```
Property 'count' does not exist on type 'ToggleEvent'.
```

The properties of the event object on the invoked service are typed as `any`.

**Reproduction**
This code sandbox uses typescript, xstate and xstate-react. The invoked service is implemented in the react view as the second argument to `useMachine`.

[Code Sandbox](https://codesandbox.io/s/weathered-firefly-v2s30?file=/src/index.tsx)

**Additional context**
typescript: 4.2.3
xstate: 4.16.2
xstate-react: 1.3.1

I think this is related to #1858 but every mention of this problem that I could find, relates to actions, not invoked services. That's why I think it's not a duplicate. I know that I used this kind of code with xstate and xstate-react 3/4-1 year ago and it used to compile. Unfortunately I don't have specifics about the stack I used back then anymore and can't reproduce it.

I can use the following workaround for now where I name the specific event and cast the event object explicitly. But this isn't pretty necessarily. 

```
setCounter2: (ctx, ev) => {
  const {count} = ev as ToggleEventNamed;
  return Promise.resolve(count);
}
```

I understand that [xstate-codegen](https://github.com/mattpocock/xstate-codegen) might solve this problem. But I don't know how to apply it in my project. Will xstate-codegen become part of xstate? Or is it just an experiment right now?

Thanks a lot in advance and thanks a lot for Xstate, I really enjoy using it.

**Comment by davidkpiano** [comment]
> I understand that xstate-codegen might solve this problem. But I don't know how to apply it in my project. Will xstate-codegen become part of xstate? Or is it just an experiment right now?

I believe the goal is to eventually make it part of the XState tools.

I'll look into this (the work around `createModel()` might be relevant/helpful here), but for now, it's safer to do what you're doing - assert that the `event` is the correct type. You might know that it will always be, but TypeScript (currently) does not.

**Comment by Andarist** [comment]
The current answer to the problem is using the typegen through our VS Code extension or through the `@xstate/cli`
