### ISSUE TITLE
TS Type inference when converting interpreter to an Observable

### ISSUE THREAD

**Issue by jzarzeckis** [statelyai/xstate#1997]
Just as noticeable in this test - it seems to be impossible to use `rxjs.from()` with xstate interpreter without casting it to `any`.
Are there plans to support proper types for this? Is it even feasible?

https://github.com/davidkpiano/xstate/blob/07586ccbe165e5b88ff9149cd13022d9cbdb331b/packages/core/test/interpreter.test.ts#L1698

**Comment by Andarist** [comment]
I've just checked this exact place in our code and it seems to work properly:
<img width="392" alt="Screenshot 2021-03-15 at 15 57 08" src="https://user-images.githubusercontent.com/9800850/111173935-4f377800-85a7-11eb-89e8-a559858b5d29.png">

If you are experiencing a problem in your codebase then please share a runnable repro case for this so I could take a look.

**Comment by jzarzeckis** [comment]
> I've just checked this exact place in our code and it seems to work properly:

Cool. Let me check it too. In that case at least the "as any" can now be removed from the test :)

I'm on version 4.16.0, and in my codebase, if I have:
```typescript
const service: Interpreter<{}> = {} as any;
const x$ = from(service)
```

I get error:
```
Argument of type 'Interpreter<{}, any, EventObject, { value: any; context: {}; }>' is not assignable to parameter of type 'ObservableInput<any>'.
  Type 'Interpreter<{}, any, EventObject, { value: any; context: {}; }>' is not assignable to type 'Subscribable<any>'.
    Types of property 'subscribe' are incompatible.
      Type '{ (observer: Observer<State<{}, EventObject, any, { value: any; context: {}; }>>): Subscription; (nextListener?: ((state: State<{}, EventObject, any, { ...; }>) => void) | undefined, errorListener?: ((error: any) => void) | undefined, completeListener?: (() => void) | undefined): Subscription; }' is not assignable to type '{ (observer?: PartialObserver<any> | undefined): Unsubscribable; (next: null | undefined, error: null | undefined, complete: () => void): Unsubscribable; (next: null | undefined, error: (error: any) => void, complete?: (() => void) | undefined): Unsubscribable; (next: (value: any) => void, error: null | undefined, c...'.
        Types of parameters 'observer' and 'next' are incompatible.
          Type 'null | undefined' is not assignable to type 'Observer<State<{}, EventObject, any, { value: any; context: {}; }>>'.
            Type 'undefined' is not assignable to type 'Observer<State<{}, EventObject, any, { value: any; context: {}; }>>'.ts(2345)
```

**Comment by Andarist** [comment]
> If only we could get access to the interpreter in the invoke callback, it would be possible to get behaviour similar to epics in redux-observable:

It's an interesting use case - this one makes sense (IMHO) but usually, we discourage people from relying on the service instance beyond for simple reads, attaching callbacks etc. The preferred way of interacting with it is through events. So having that in mind - exposing the whole `service` there might be a little bit problematic - we wouldn't like people to abuse it. That being said - we already had a version on the `next` branch that did expose a similar thing there (a simplified actor `ref` to the service) and that could be exposed. I doubt this will happen in v4 though - the use case can be covered with callback actors (even if they are less ergonomic for this). Actually... could you open a separate issue about this so it can be properly tracked there?

--- 

As to the error - please prepare a runnable repro case and I will try to take a look at it some time later.

**Comment by jzarzeckis** [comment]
Ok. Here's the proposal: #1998

**Comment by jzarzeckis** [comment]
Ok. Looks like I can't reproduce on a clean environment :D
https://stackblitz.com/edit/typescript-dspqzq?file=index.ts

Looks like it does behave as expected.

Must be an issue on my end.

**Comment by jzarzeckis** [comment]
Sorry for the hassle. Reopening - in codesandbox the TS error is reproducable:
https://codesandbox.io/s/romantic-cookies-8est0?file=/src/index.ts

**Comment by Andarist** [comment]
I'm not exactly sure how exactly are we supposed to satisfy TS here - as RxJS has a callable signature with multiple overloads in the `Subscribable` interface (which we need to match for this to work). Does that mean that our `Subscribable`~ should account for all those overloads as well? I would need to do more tests to assess that.

Just writing down some things that I've found during my investigation. TS expect us to match this deprecated overload:
https://github.com/ReactiveX/rxjs/blob/02219cc7b87b0942004f957985c18fac71ef0824/src/internal/types.ts#L44
which we doesn't. 

The last overload actually handles our types correctly:
https://github.com/ReactiveX/rxjs/blob/02219cc7b87b0942004f957985c18fac71ef0824/src/internal/types.ts#L49

I wonder what's the reaso

**Comment by monotykamary** [comment]
The easiest workaround I use is to just augment and overload the `from` function:

```ts
// index.d.ts

import { Observable } from 'rxjs';
import { EventObject, Interpreter, State, StateSchema, Typestate } from 'xstate';

declare module 'rxjs' {
  function from<
    TContext,
    TStateSchema extends StateSchema = any,
    TEvent extends EventObject = EventObject,
    TTypestate extends Typestate<TContext> = { value: any, context: TContext }>
  (input: Interpreter<TContext, TStateSchema, TEvent, TTypestate>): Observable<State<TContext, TEvent, any, TTypestate>>
}
```

**Comment by woutermont** [comment]
RxJS v7 no longer has the depracated methods, but XState's `Interpreter` still does not to work with `Observable.from()`.

Compilation now fails with `Argument of type 'Interpreter<Context, Schema, Event, State>' is not assignable to parameter of type 'ObservableInput<any>'.`

This makes sense, since v7 also removed `Subscribable<any>`, on which the `Interpreter` was modeled, from the union type of `ObservableInput<any>`

One way to solve this, also for RxJS v6, I think, would be to include the interop `Symbol.observable` to the `Subscribable` interface.

**Comment by davidkpiano** [comment]
> One way to solve this, also for RxJS v6, I think, would be to include the interop `Symbol.observable` to the `Subscribable` interface.

Is there a way to do this without depending on `rxjs`?

Also, I'd appreciate a PR for this if you have an idea of how to make this work 🙏

**Comment by woutermont** [comment]
Actually, I just noticed that symbol is already added in the `Interpreter` class ... so I have no idea why that would not work.

**Comment by woutermont** [comment]
Btw: using `Symbol.observable` would exactly be NOT depending on RxJS, since that is a package-independent interop symbol.

**Comment by woutermont** [comment]
Okay, so I got this to work in a project where we're using XState, and it was solved by adding the following line to the typing of the `Interpreter`: 

```
[Symbol.observable](): Subscribable<State<TContext, TEvent, TStateSchema, TTypestate>>
```

However, I can't see why this would not already appear based on the current TS code, or how I would add it (but maybe I'm missing something obvious).

**Comment by davidkpiano** [comment]
> [Symbol.observable](): Subscribable<State<TContext, TEvent, TStateSchema, TTypestate>>

It's currently typed as `any` (for some reason) and seems like more of a runtime thing.

Made a PR for this, though: #2358

**Comment by woutermont** [comment]
Indeed, wrote the same code locally, but it behaves differently than expected (which also makes the test fail).
