### ISSUE TITLE
@xstate/fsm: No console errors for invalid transitions (Cannot read property 'entry' of undefined)

### ISSUE THREAD

**Issue by f-elix** [statelyai/xstate#2054]
**Description**
The core XState package outputs an error in the console when a targeted state in a transition does not exist on the machine. I noticed the @xstate/fsm package does not, which leads to runtime errors when the invalid transition is reached.

**Expected Result**
The @xstate/fsm package should output the same warning as in the core XState package regarding invalid transition configurations.

**Actual Result**
The @xstate/fsm package does not output the same warning as in the core XState package regarding invalid transition configurations, which leads to runtime errors

**Reproduction**
Here in the codesandbox, you can toggle between XState and @xstate/fsm to see the difference in behavior with an invalid transition on the machine. XState tells us as expected that the transition is invalid, while @xtate/fsm doesn't and once the invalid transition is reached we get the following error: `Cannot read property 'entry' of undefined`.

https://codesandbox.io/s/sweet-hopper-olxww?file=/src/index.js

Thank you so much for your great work on XState! This library is invaluable.

**Comment by davidkpiano** [comment]
Thanks! I'd welcome a PR for this.

**Comment by f-elix** [comment]
I submitted a PR! Here it is: https://github.com/davidkpiano/xstate/pull/2055

**Comment by Narretz** [comment]
This issue is fixed and can be closed
