### ISSUE TITLE
createMachine signature support for Model seems to change type inference from 4.16.0 to 4.17.1

### ISSUE THREAD

**Issue by avaragado** [statelyai/xstate#2067]
**Description**

I just upgraded xstate from 4.16.0 to 4.17.1. Types that were correctly inferred now give type errors.

**Expected Result**
No type errors.

**Actual Result**

In my code:

```ts
  const [current, send] = useMachine<
    SessionMachineContext,
    SessionMachineEvent,
    SessionMachineTState
  >(sessionMachine, { ... })
```

I get red squiggles under `sessionMachine`, and here's the error:

```
src/library/session/context.tsx:117:38 - error TS2345: Argument of type 'StateMachine<SessionMachineEvent, any, SessionMachineTState, Typestate<TContext>>' is not assignable to parameter of type 'MaybeLazy<StateMachine<SessionMachineContext, any, EventObject, Typestate<SessionMachineContext>>>'.
  Type 'StateMachine<SessionMachineEvent, any, SessionMachineTState, Typestate<TContext>>' is not assignable to type 'StateMachine<SessionMachineContext, any, EventObject, Typestate<SessionMachineContext>>'.
    The types of 'config.context' are incompatible between these types.
      Type 'SessionMachineEvent | (() => SessionMachineEvent) | undefined' is not assignable to type 'SessionMachineContext | (() => SessionMachineContext) | undefined'.
        Type 'AuthzRequestedEvent' is not assignable to type 'SessionMachineContext | (() => SessionMachineContext) | undefined'.
          Type 'AuthzRequestedEvent' is not assignable to type '() => SessionMachineContext'.
            Type 'AuthzRequestedEvent' provides no match for the signature '(): SessionMachineContext'.
```

This didn't happen with 4.16.0.

I believe it's because there's a different inference in play, possibly due to Model.

My code for creating the machine:

```ts
export const sessionMachine = createMachine<
  SessionMachineContext,
  SessionMachineEvent,
  SessionMachineTState
>({ ... })
```

Looking at xstate's `Machine.d.ts`:

```ts
export declare function createMachine<TModel extends Model<any, any, any>, TContext = ModelContextFrom<TModel>, TEvent extends EventObject = ModelEventsFrom<TModel>, TTypestate extends Typestate<TContext> = {
    value: any;
    context: TContext;
}>(config: MachineConfig<TContext, any, TEvent>, options?: Partial<MachineOptions<TContext, TEvent>>): StateMachine<TContext, any, TEvent, TTypestate>;

export declare function createMachine<TContext, TEvent extends EventObject = AnyEventObject, TTypestate extends Typestate<TContext> = {
    value: any;
    context: TContext;
}>(config: MachineConfig<TContext, any, TEvent>, options?: Partial<MachineOptions<TContext, TEvent>>): StateMachine<TContext, any, TEvent, TTypestate>;
```

I think TypeScript may be inferring the first `createMachine` signature. That would put my `SessionMachineEvent` into the `TContext` position, which might explain why, in the reported error, it's trying to assign `AuthzRequestedEvent` to `SessionMachineContext` etc.

I may of course be entirely wrong. But commenting out the first signature in `Machine.d.ts` removes the squiggles.

Any ideas how I can force the correct inference path? Or workaround another way?

**Comment by Andarist** [comment]
Please share a runnable repro case - without it it's really hard for us to investigate this.

**Comment by avaragado** [comment]
I appreciate that. It's not a public repo so I'll see what I can do.

**Comment by avaragado** [comment]
https://codesandbox.io/s/yeu96 contains a minimal repro.

There's an additional error (line 39 in the sandbox) that seems significant. In the real code I was unable to make everything typecheck successfully, and added a ts-expect-error directive here.

**Comment by davidkpiano** [comment]
For the second part, you can workaround the issue by providing the generic context type:

```ts
        actions: {
            assignRestart: assign<SessionMachineContext>({
                authzResult: null,
            }),
        },
```

**Comment by avaragado** [comment]
Ah, that doesn't work in the real code, but 

```
assignRestart: assign<SessionMachineContext, SessionMachineEvent>({ ... }),
```

does work. I'm sure I tried that before, as I spent a good while trying to get all this to typecheck before I resorted to the escape hatch. Perhaps there were changes to types between versions.

And that change also fixes the original error too, somewhat miraculously.

I can only assume it's tickled something deep in the types to make the stars align, but I have no idea what.

I don't know whether there's anything you need to look at now. I'll leave the issue open in case there is, but feel free to close it.

My one suggestion is to revisit the TypeScript doc, as there's nothing on the "Using TypeScript" page about using generics with assign here.

Thanks!

**Comment by Andarist** [comment]
@avaragado the provided repro errors on 4.16 as well: https://codesandbox.io/s/distracted-architecture-tcd1s?file=/src/index.tsx:839-852 . So if your code has stopped typechecking successfully with 4.17 then I would say that this repro is not really demonstrating your issue - it demonstrates a one (a one we are aware of).

> My one suggestion is to revisit the TypeScript doc, as there's nothing on the "Using TypeScript" page about using generics with assign here.

I already know how to fix this so hopefully, no changes to the docs related to this issue will be needed. However, I have some higher priority stuff to handle right now so I can't promise when the fix will get into XState.

**Comment by RomainLanz** [comment]
I have multiple issue related to this one.

The mistyping happen "randomly" when calling `useMachine()` with the following TypeScript error.

```text
TS2345: Argument of type 'StateMachine<Events, any, StateSchema, Typestate<TContext>>' is not assignable to parameter of type 'MaybeLazy<StateMachine<Events, any, EventObject, Typestate<Events>>>'.
  Type 'StateMachine<Events, any, StateSchema, Typestate<TContext>>' is not assignable to type 'StateMachine<Events, any, EventObject, Typestate<Events>>'.
    Types of property 'withConfig' are incompatible.
      Type '(options: Partial<MachineOptions<Events, StateSchema>>, context?: Events | undefined) => StateMachine<Events, any, StateSchema, Typestate<...>>' is not assignable to type '(options: Partial<MachineOptions<Events, EventObject>>, context?: Events | undefined) => StateMachine<Events, any, EventObject, Typestate<...>>'.
        Types of parameters 'options' and 'options' are incompatible.
          Type 'Partial<MachineOptions<Events, EventObject>>' is not assignable to type 'Partial<MachineOptions<Events, StateSchema>>'.
            Types of property 'guards' are incompatible.
              Type 'Record<string, ConditionPredicate<Events, EventObject>> | undefined' is not assignable to type 'Record<string, ConditionPredicate<Events, StateSchema>> | undefined'.
                Type 'Record<string, ConditionPredicate<Events, EventObject>>' is not assignable to type 'Record<string, ConditionPredicate<Events, StateSchema>>'.
                  Index signatures are incompatible.
                    Type 'ConditionPredicate<Events, EventObject>' is not assignable to type 'ConditionPredicate<Events, StateSchema>'.
```

It is also happening when using the `assign()` function.

```ts
removeActiveFilter: assign({
  searchTerm: () => '',
  value: () => '',
  activeFilter: () => null,
}),
```

```text
TS2322: Type 'AssignAction<{ searchTerm: string; value: string; activeFilter: null; }, Events>' is not assignable to type 'ActionObject<Context, Events> | ActionFunction<Context, Events>'.
  Type 'AssignAction<{ searchTerm: string; value: string; activeFilter: null; }, Events>' is not assignable to type 'ActionObject<Context, Events>'.
    Types of property 'exec' are incompatible.
      Type 'ActionFunction<{ searchTerm: string; value: string; activeFilter: null; }, Events> | undefined' is not assignable to type 'ActionFunction<Context, Events> | undefined'.
        Type 'ActionFunction<{ searchTerm: string; value: string; activeFilter: null; }, Events>' is not assignable to type 'ActionFunction<Context, Events>'.
          Types of parameters 'context' and 'context' are incompatible.
            Type 'Context' is not assignable to type '{ searchTerm: string; value: string; activeFilter: null; }'.
              Types of property 'activeFilter' are incompatible.
                Type 'FilterContract | null' is not assignable to type 'null'.
                  Type 'FilterContract' is not assignable to type 'null'.
```

If needed, I can provide my entire machine (270 LOC).

**Comment by Andarist** [comment]
@RomainLanz could you open a new issue about this that would contain the full reproduction of the problem?

**Comment by RomainLanz** [comment]
Yes, I will create a new issue with the minimum amount of code to reproduce the problem.

However, this has to wait a little bit. I do not believe I will have time before mid-august if that is ok for you.

**Comment by lianghx-319** [comment]
Any updates about this issue?

**Comment by Andarist** [comment]
I've rechecked with `xstate@4.30.1` and the reported problem seems to be gone. If you experience any typing problems with the current version - please open new issues with the appropriate repro cases.
