### ISSUE TITLE
Inconsistent options of spawn vs invoke for specifying ID

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#2070]
**Description**
There is a discrepancy between how we set ID for an invoked service vs a spawned actor.

**Expected Result**
Consistent way to configure an ID for an interpreter.

**Actual Result**
For invoked services, one has to specify an `id` option.
```javascript
invoke: {
  src: someMachine,
  id: 'machine1',
}
```

For spawned actors, one has to specify a `name` option.
```javascript
entry: assign({
  actorRef: () => spawn(someMachine, { name: 'machine2' })
})
```

**Additional context**
Both spawned actors, and invoked services are listed in the `service.children` map side by side, keyed by their id/name.

**Comment by davidkpiano** [comment]
In `xstate@beta`, these are now both `id`:

```ts
invoke: {
  // ...
  id: 'machine1'
}
```

```ts
entry: assign({
  actorRef: ({ spawn }) => spawn(someMachine, { id: 'machine2' })
})
```
