### ISSUE TITLE
Inconsistent behavior for initial state using `interpret` vs. `useInterpret`

### ISSUE THREAD

**Issue by bemayr** [statelyai/xstate#2084]
**Description**
Using `interpret` and `useInterpret` results in different runtime behavior.
If a machine **without initial context** is started using `interpret` the `context` resolves to `undefined`, if it is started with `useInterpret` the context resolves to `{}`, this in turn affects the behavior of `assign(...)`.
Because of the huge advantage of xstate being framework independent, I think that's unwanted or even potential risky behavior.
This inconsistency can easily be solved by simply providing an initial context, but **it currently fails silently if one switches from `useInterpret` to `interpret`**.

The reason for this is: (@VanTanev 🙏)
https://github.com/davidkpiano/xstate/blob/14cdef612df29b9e067a34ca96b0750e729c9aff/packages/xstate-react/src/useInterpret.ts#L90-L93

> [@VanTanev on discord](https://discord.com/channels/795785288994652170/799416943324823592/831444212322533418): `useInterpret()` calls `machine.withConfig()`. The second argument to `withConfig()` is a new `context` object, that overwrites `context: undefined` in the original machine definition. Here it's kind of accidental, and possibly **a more consistent way to write this would be something like**:

```ts
const machineWithConfig = machine.withConfig(machineConfig, (machine.context || context ? {
  ...machine.context,
  ...context
} : undefined) as TContext);
```

**Expected Result**
Consistent runtime behavior using either `interpret` or `useInterpret`. Preferably the behavior of `interpret`, because it is the underlying framework-agnostic version of `useInterpret`. _The power of writing framework-agnostic logic code is just too valuable to be given up 😍._

**Actual Result**
Different runtime behavior (see **Reproduction**).

**Reproduction**
_xstate 4.17.1; @xstate/inspect 0.4.1; @xstate/react 1.3.1_
`interpret`-Example: https://codesandbox.io/s/xstateinitial-context-interpret-24bbz ⮕ this results in `context: undefined`
`useInterpret`-Example: https://codesandbox.io/s/xstateinitial-context-useinterpret-33950 ⮕ this results in `context: {}`

**Additional context**
- _There already was a little bit of discussion on discord about this:_
  - https://discord.com/channels/795785288994652170/799416943324823592/831217793479082024
  - https://discord.com/channels/795785288994652170/799416943324823592/831264646274482210
  - https://discord.com/channels/795785288994652170/799416943324823592/831444212322533418
  - https://discord.com/channels/795785288994652170/799416943324823592/831444929062240266
- Changing this behavior might be a breaking change ⚡.

**Comment by bemayr** [comment]
One more note initially provided by @VanTanev:
> It's an interesting edge case. Machines without a context are perfectly valid, but assigning to an undefined context is not, so, uh... yeah. I almost feel like assigning to an undefined context should throw instead of printing a warning.

I completely agree to your point of throwing an error instead of printing a warning 💯, but on top of that I see a problem with the different runtime behavior as explained above.
This concern was raised by copying machines out of [xstate-catalogue](https://xstate-catalogue.com/) that work using `useInterpret` but not with plain xstate `interpret`.

**Comment by davidkpiano** [comment]
It makes sense to fix the inconsistency. Would you like to make a PR for this?

**Comment by bemayr** [comment]
Yes for sure! 👌

**Comment by davidkpiano** [comment]
Can you check the behavior with `xstate@beta` and `@xstate/react@beta` and see if it works as expected? 🙏

**Comment by davidkpiano** [comment]
Closing as stale/no longer valid in `@xstate/react@beta`
