### ISSUE TITLE
Passing DOM event crashes when inspector is enabled

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#2138]
**Description**
It seems that any usage of `onFocus={() => send({ type: 'ANY', data: event });}` will cause the inspector to crash.
It seems from my local problems that this is some sort of circular reference.

**Expected Result**
No crash to happen. Like we handle 'circular data' we could also just make the inspector do `event is Event ? '[DOM Event]' : event`.

**Actual Result**
The app and inspector crashes!

**Reproduction**
https://codesandbox.io/s/xstateinspect-bug-with-events-mr0wd

**Comment by ronaldborman** [comment]
@davidkpiano I just have experienced this bug when trying to send a DOM event directly. Initially I was looking in other directions before seeing this issue. A warning in the inspect documentation would be useful imho.

**Comment by Andarist** [comment]
I've been discussing this briefly last week with David. One of the options to solve this would be to accept an option like `serialize` that would allow us to serialize complex data types before sending them through serialization boundaries like 2 different windows. We'd probably have to ship some built-in, simple, serializer but allow this to be configured.

**Comment by davidkpiano** [comment]
This addition has been made here: https://github.com/statelyai/xstate/pull/2640

So you will be able to do something like this:

```js
inspect({
  // ...
  serialize: (key, value) => {
    if (value instanceof UIEvent) {
      return { type: value.type }
    }
    return value;
  }
});
```
