### ISSUE TITLE
useInterpret logs warning about uninitialized service when service is passed to child component

### ISSUE THREAD

**Issue by alirezavlz** [statelyai/xstate#2157]
**Description**
Trying to use a machine using `useInterpret` but cannot access to machine in children and it throws error + a warning `Attempted to read state from uninitialized service`.
 
**Expected Result**

**Actual Result**

**Reproduction**
I think this is fixed in useMachine https://github.com/davidkpiano/xstate/issues/1132#issue-601539469

**Additional context**
```js
 "xstate": "^4.18.0",
  "@xstate/react": "^1.3.2",
```

**Comment by alirezavlz** [comment]
Example: 
```js
  const selectService = useInterpret(
    selectMachine(props.data, false)
  );

 return (
    <>
      <Header
        selectService={selectService}
      />
      <TrackList
        itemProps={{ selectService }}
        {...props}
      />
    </>
  );
```

**Comment by alirezavlz** [comment]
The weird thing about this issue is, Only Header has issue with it, TrackList component is working fine but at the end they use same component so what I guess is, it's has something todo with scheduling or something since I tried something stupid I rendered the Header with a setTimout(0) `(with wrapping it with <Delay/> component)` delay and then it worked correctly.

**Comment by stevenmusumeche** [comment]
I'm having the same issue.

**Comment by davidkpiano** [comment]
This should no longer be an issue in the latest `@xstate/react` version, but please re-open if it is.
