### ISSUE TITLE
@xstate/fsm + Preact + Next.js - Shallow routing causing machine service to stop and not starting again

### ISSUE THREAD

**Issue by berndartmueller** [statelyai/xstate#2210]
**Description**

Using @xstate/fsm + Preact + Next.js and shallow routing leads to re-rendering of the component and causing the xstate service to stop. Unfortunately, it seems the service is not restarted again.

The main issue here seems to be Preact. I tried the same setup with React.js without any issues.

**Expected Result**

Machine service should be stopped and restarted accordingly.

**Actual Result**

Machine service keeps being stopped.

**Reproduction**

https://codesandbox.io/s/strange-stallman-lbzf0

1. Click on "Go to wizard" (watch the url change to `/wizard#first`)
2. Click on "Next Step" -> Broken. Expected result would be to go to next step.

BUT, it works in following case:

1. Click on "Go to wizard" (watch the url change to `/wizard#first`)
2. Reload the page (Important! This is to have a clean render of the page and a working xstate machine)
3. Click on "Next Step" -> Now it works!

As I mentioned before that it works with React.js, here's a fork of my previous example but with React.js. Everything else is the same. 

https://codesandbox.io/s/xstatefsm-react-nextjs-6iq7r

**Additional context**

@xstate/fsm 1.6.1
@xstate/react 1.3.3

https://github.com/davidkpiano/xstate/blob/main/packages/xstate-react/src/fsm.ts#L71

I found a potential issue why this problem exists. In useEffect() in Line 71 in file `packages/xstate-react/src/fsm.ts` the service is getting stopped in the cleanup function. If I change the useEffect() function to following code, it works:

```
  useEffect(() => {
    service.start().subscribe(state => {
      setState(state);
    });
    return () => {
      service.stop();
    };
  }, []);
```

But I'm not sure if that's the correct fix.

Thanks a lot!!

**Comment by berndartmueller** [comment]
Bump

**Comment by davidkpiano** [comment]
Can you please PR the fix? Would be greatly appreciated 🙏

**Comment by Andarist** [comment]
Since on the `next` branch, we discontinued `@xstate/fsm` package (see [here](https://github.com/statelyai/xstate/pull/4265)) - I think that this issue can be closed now as it's no longer applicable. 

`@xstate/fsm` continues to work so you don't need to refactor your code if you care about its lightweight bundlesize.
