### ISSUE TITLE
Typescript documentation example is not type-correct

### ISSUE THREAD

**Issue by niallpaterson** [statelyai/xstate#2232]
**Description**
The documentation provides an example of how to use typescript with xstate. But the documented example is not type-correct.

**Expected Result**
I expected the typescript documentation example to be type-correct.

**Actual Result**
The provided example throws type errors, in particular with the second and third generic parameters of createMachine.

**Additional context**
If I switch out createMachine for the older syntax (i.e.., Machine) the type errors go away. I'm assuming the docs got updated without updating the types.

From what I can tell there are at least two problems:

1. The order of generic parameters has changed. The example puts `LightStateSchema` as the second argument, but the newer factory accepts a schema type in its third argument place.

2. The schema generic parameter expects value and context properties, but this is missing from the documented type definition.

I did have a go at fixing this locally but there's a lot going on with the types. Happy to spend some time trying to fix it but woud ideally like some guidance. Does the documentation just need updating? Are there problems with the types of createMachine? If so, what is the expected behaviour?

Also, im a little unsure how to type the createMacine factory as it stands. We're using xstate at work but are just passing in anys to the generics which is super icky. 

Oh: awesome pkg btw 😍

EDIT: Ok so I also noticed the second example in the typescript docs is typed properly. Just need to update the documentation for the first example. Ill do this later and put in a PR if that's OK.

**Comment by davidkpiano** [comment]
> EDIT: Ok so I also noticed the second example in the typescript docs is typed properly. Just need to update the documentation for the first example. Ill do this later and put in a PR if that's OK.

Yes please!

**Comment by VanTanev** [comment]
Back a while ago I wrote this small script that validated typescript examples in documentation:
https://github.com/VanTanev/angular-styleguide/blob/typescript-examples/a1/scripts/verifyTypescript.js

Maybe we could adopt something like it 🤔

**Comment by niallpaterson** [comment]
@VanTanev yeah that's a great idea! What an awesome little script 😊

**Comment by j-funk** [comment]
Since this is related to TypeScript docs / examples I noticed that `MachineOptions` is not mentioned at all in the documentation.  I found out about it via the following blog:

https://dev.to/giantmachines/an-introduction-to-xstate-in-typescript-1pdn

**Comment by davidkpiano** [comment]
> Since this is related to TypeScript docs / examples I noticed that `MachineOptions` is not mentioned at all in the documentation. I found out about it via the following blog:
> 
> https://dev.to/giantmachines/an-introduction-to-xstate-in-typescript-1pdn

Ideally you shouldn't have to manually reach for types like that.

**Comment by j-funk** [comment]
Thank you for replying @davidkpiano, love XState.  

I am defining / implementing my guards and actions in a separate options object and eslint was complaining: 
![Screen Shot 2021-06-28 at 3 09 58 PM](https://user-images.githubusercontent.com/4483540/123690859-e953c100-d822-11eb-80af-ed50f2fe5752.png)

I'm new to TypeScript, maybe I'm missing some part of the rationale or perhaps I should structure my machines differently.

**Comment by davidkpiano** [comment]
@j-funk Try to type your guards as:

```ts
function someGuard(context: TheContext, event: TheEvents): boolean {/* ... */}
```

And your actions as:
```ts
function someAction(context: TheContext, event: TheEvents): void {/* ... */}
```

**Comment by j-funk** [comment]
Thank you David, but isn't that quite redundant?  Using `MachineOptions<Context, Event>` resolves it nicely without needing to type every parameter, which can be a lot if you have a significant number of actions/guards etc.  I do appreciate your time commenting on this, thank you.

**Comment by davidkpiano** [comment]
> Thank you David, but isn't that quite redundant? Using `MachineOptions<Context, Event>` resolves it nicely without needing to specify types on every parameter, which can be a lot if you have a significant number of actions/guards etc. I do appreciate your time commenting on this, thank you.

Yes, it is redundant; I was moreso addressing [this comment](https://github.com/davidkpiano/xstate/issues/2232#issuecomment-869923341); the typical use-case would be defining actions, etc. inline or as the 2nd argument to `createMachine(config, options)`. You can use the `MachineOptions` type to externally define machine options, but the documentation cannot cover every possible use-case. We can improve the text in the API docs, but the discoverability of types such as `MachineOptions` would be the same.

The majority of types used in XState are meant to be internal; `MachineOptions` is one of those gray-area types that might be useful, but is mostly meant to be internal.

**Comment by davidkpiano** [comment]
Closing as the new docs should be up-to-date with the correct types: https://stately.ai/docs
