### ISSUE TITLE
Children machines get stopped/dereferenced when targeting sibling parallel machine

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#2238]
**Description**
If a machine sends an event to a parallel state, the child machines of the sending machine are stopped.

```js
type: 'parallel',
states: {
  machineA: {
    id: 'machineA',
    init: 'one'
    states: { one: {}, two: {} }
  },
  machineB: {
    id: 'machineB',
    init: 'start',
    states: {
      start: {
        on: { SOMETHING: '#machineA.two' },
        invoke: { src: 'someMachine', onDone: '.finished' }
      },
      finished: {}
    }
  }
}
```

The workaround for this is to change `on: { SOMETHING: 'machineA.two' }` to `on: { SOMETHING: ['#machineA.two', '#machineB.start'] }

**Expected Result**
On sending `SOMETHING`;
* machineA should be in state `two`
* machineB should be still in state `start'
* `someMachine` should still be running

**Actual Result**
* machineA is in state `two`
* machineB is in state `start'
* `someMachine` is no longer running

**Reproduction**
https://codesandbox.io/s/xstate-children-machines-bug-kex29

**Comment by davidkpiano** [comment]
One workaround that you can do is to `raise(...)` an event internally:

```js
const machine = createMachine({
  id: "file",
  type: "parallel",
  states: {
    upload: {
      initial: "idle",
      states: {
        idle: {
          on: {
            INIT_UPLOAD_FROM_DOWNLOAD: "pending"
          }
        },
        pending: {
          on: {
            UPLOAD_COMPLETE: { target: "success" }
          }
        },
        success: {}
      }
    },
    download: {
      initial: "idle",
      on: {
        INIT_UPLOAD: { actions: actions.raise("INIT_UPLOAD_FROM_DOWNLOAD") }
      },
      states: {
        idle: {
          on: {
            INIT_DOWNLOAD: { target: "pending" }
          }
        },
        pending: {
          invoke: {
            src: minuteMachine,
            onDone: { target: "success" }
          }
        },
        success: {}
      }
    }
  }
});
```

**Comment by davidkpiano** [comment]
This no longer occurs in the latest version of XState: https://codesandbox.io/s/xstate-children-machines-bug-forked-b70n64
