### ISSUE TITLE
Adding a second event to a model seems to cause type errors

### ISSUE THREAD

**Issue by joneshf** [statelyai/xstate#2276]
**Description**

It seems like using a model can cause a type error if there's more than one event.
I've made a reproduction of the issue at https://github.com/joneshf/xstate-model-type-error.
E.g. going from:

```TypeScript
type Event =
  | { type: "ADD_NUMBER"; number: number };
```
to

```TypeScript
type Event =
  | { type: "REMOVE_NUMBER" }
  | { type: "ADD_NUMBER"; number: number };
```
Seems to trigger the issue.

I could totally be doing something incorrect here.

For posterity, this is the code from the linked repo:

<details>
<summary>index.ts</summary>

```TypeScript
import * as xstate from "xstate";
import * as xstateModel from "xstate/lib/model";

interface Context {
  values: number[];
}

type Event =
  // Uncomment line 24 (the `| { type: "REMOVE_NUMBER" }` line),
  // and `tsc` fails to compile with an error like:
  // index.ts:47:7 - error TS2322: Type 'AssignAction<Context, { type: "REMOVE_NUMBER"; }>' is not assignable to type 'ActionObject<Context, Event>'.
  //   Types of property 'exec' are incompatible.
  //     Type 'ActionFunction<Context, { type: "REMOVE_NUMBER"; }> | undefined' is not assignable to type 'ActionFunction<Context, Event> | undefined'.
  //       Type 'ActionFunction<Context, { type: "REMOVE_NUMBER"; }>' is not assignable to type 'ActionFunction<Context, Event>'.
  //         Type 'Event' is not assignable to type '{ type: "REMOVE_NUMBER"; }'.
  //           Type '{ type: "ADD_NUMBER"; number: number; }' is not assignable to type '{ type: "REMOVE_NUMBER"; }'.
  //             Types of property 'type' are incompatible.
  //               Type '"ADD_NUMBER"' is not assignable to type '"REMOVE_NUMBER"'.

  // 47 const addNumber: xstate.ActionObject<Context, Event> = model.assign({
  //          ~~~~~~~~~

  // Found 1 error.
  // | { type: "REMOVE_NUMBER" }
  | { type: "ADD_NUMBER"; number: number };

export type Model = xstateModel.Model<Context, Event, any>;

interface Schema {
  states: States;
}

type States = {
  normal: {};
};

const context: Context = {
  values: [],
};

export const model: Model = xstateModel.createModel(context, {
  events: {
    ADD_NUMBER: (number: Number) => ({ number }),
  },
});

const addNumber: xstate.ActionObject<Context, Event> = model.assign({
  values: (context: Context, event: Event): number[] => {
    if (event.type !== "ADD_NUMBER") {
      return context.values;
    }

    return context.values.concat([event.number]);
  },
});

const config: xstate.MachineConfig<Context, Schema, Event> = {
  id: "values",
  initial: "normal",
  context: model.initialContext,
  states: {
    normal: {
      on: {
        ADD_NUMBER: [
          {
            actions: ["addNumber"],
          },
        ],
      },
    },
  },
};

const options: Partial<xstate.MachineOptions<Context, Event>> = {
  actions: {
    addNumber,
  },
};

export const machine: xstate.StateMachine<Context, Schema, Event, any> =
  xstate.createMachine<Model>(config, options);

```

</details>

**Expected Result**

Adding a second event shouldn't require removing the model in order to type check.

**Actual Result**

There are type errors that don't seem to be able to be resolved until the model is removed.

**Reproduction**

I tried to use the codesandbox link and I cannot seem to get the error to reproduce.
Here's the link anyway: https://codesandbox.io/s/adoring-haze-jntkx?file=/src/index.ts

As mentioned, I've reproduced this in a full git repo: https://github.com/joneshf/xstate-model-type-error

It might be because codesandbox is running TypeScript 4.1.2 and the repo is using 4.3.2, but I tried downgrading to 4.1.2 in the repo and it still had the type error.

**Additional context**

TypeScript version - 4.3.2
XState version - 4.20.0

Talked about briefly in discord: https://discord.com/channels/795785288994652170/809564589880639548/849675000071585812

**Comment by joneshf** [comment]
Hey so, somehow it started erroring on the code sandbox. Nothing's changed since this issue was opened, but it at least reproduces the issue now. The error is on like 46 now (due to reformatting).

**Comment by davidkpiano** [comment]
If you remove the type annotations, it works fine:

```ts
const addNumber = model.assign({
  values: (context, event) => {
    if (event.type !== "ADD_NUMBER") {
      return context.values;
    }

    return context.values.concat([event.number]);
  }
});
```

**Comment by Andarist** [comment]
This is because the `ActionObject` type has a contravariant property (`exec`). We plan to remove this in the future (or rather - remove that from the type) - so this should become assignable.

**Comment by paulrberg** [comment]
I just encountered this type error in my project as well, and it took me a while to stumble upon this issue.

I think that this limitation of `assign`, that is, that it cannot be used in certain situations with union types, should be explicitly mentioned in the [guide](https://xstate.js.org/docs/guides/typescript.html).

**Comment by davidkpiano** [comment]
Closing as using `createModel` is deprecated, and typegen helps fill in the gaps here. We'll be further improving the types in v5.
