### ISSUE TITLE
Bug with @xstate/immer and delete

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#2300]
**Description**
According to the immer.js docs we should be able to use `delete context.value` or `delete context['value']` but neither of these seem to work. The workaround is to set the value to `undefined` directly.

https://immerjs.github.io/immer/update-patterns#object-mutations

**Expected Result**
Triggering `deleteAction: assign(context => { delete context.value; })` should delete the value key and contents from the context object.

**Actual Result**
The value is unchanged.

**Reproduction**
@xstate/immer: https://codesandbox.io/s/xstate-immer-counter-forked-s9gyi?file=/src/index.js
Pure ImmerJS version: https://codesandbox.io/s/immerjs-forked-d0kkg

**Comment by davidkpiano** [comment]
I believe this was mentioned (without Immer) in a previous issue, but you can assign `undefined` to it instead.

**Comment by SimeonC** [comment]
Thanks, yea that workaround works fine for me. I think the previous issue was https://github.com/davidkpiano/xstate/issues/989 from my searching. I was searching specifically for immer issues so didn't find that last time.
