### ISSUE TITLE
Eventless transition actions are passed different events

### ISSUE THREAD

**Issue by Silverwolf90** [statelyai/xstate#2306]
**Description**
Eventless transition actions are getting passed different events depending on if they are a built in (assign, pure) or just a normal function.

**Expected Result**
They would all receive the same event (preferably the one logged in the function, as that is more useful than a null event).

**Actual Result**
- `assign`, `pure` (didn't test other built in actions) receive a null event (ie: `{ type: '' }`)
- a normal function is passed the event that transitioned into the current state

**Reproduction**
https://codesandbox.io/s/brave-wildflower-7t649

**Comment by Andarist** [comment]
This is something that we are aware of and something that is going to be fixed in the next major version.

**Comment by Silverwolf90** [comment]
Ah thanks, good to know! Is there a workaround? For `assign` actions it looks like I can grab the event from the `meta.state.event`, but the `meta` is not available for `send`/`pure`.

**Comment by Silverwolf90** [comment]
As a workaround I've simply replaced `always` in favor of `entry` + `send`

```js
'transient-state': {
  entry: [
    ....
    send('finished'),
  ],
  on: {
    'finished': '#next-state',
  },
},
```

**Comment by rlaffers** [comment]
A partial workaround for the `assign` action - use the meta object passed as the 3rd argument to some actions.
```javascript
assign((ctx, event, meta) => {
  console.log("assign", event.type, meta.state.event); // meta.state.event will be the correct event
  return ctx;
}),
```
Alas, this does not work for the `pure` and `send` action creators (I haven't checked others).

**Comment by davidkpiano** [comment]
This is a breaking change in v4, but is fixed for v5: https://github.com/statelyai/xstate/pull/2824
