### ISSUE TITLE
Errors should respect source maps & unhandled rejections

### ISSUE THREAD

**Issue by davidkpiano** [statelyai/xstate#2319]
> Logging is great! I'm just thinking that in any real production application (mobile, web) uncaught errors are usually funneled to some logging platform such as BugSnag etc. If error occurs only in production, sometimes that's the only way to notice an issue. I wonder how this should be done here.

I just found my way here because I was trying to figure out why we don't get a proper sentry.io error from a service that fails in strict mode. Turns out that the error is just logged to console and not propagated to Sentry's unhandled promise rejection handler. While logging is great for backend applications this happens in frontend code where we rely on Sentry error collection as it groups the errors based on callstack and other values.

As a side note the error logging does not respect source maps in Chrome as it's concatenating a string like `console.error("Error: " + error)`. The error should be sent to the logger as an error object to allow Chrome to handle sourcemaps, ie. `console.error("Error:", error)`.

_Originally posted by @qtiki in https://github.com/davidkpiano/xstate/issues/463#issuecomment-604947112_

**Comment by davidkpiano** [comment]
> Hello @davidkpiano, I have been using xstate on my daily work and it is an awesome tool, I would like to contribute, is this issue still available to be solved?

Yes, it is (cc. @Andarist for guidance), thank you!

**Comment by rubenmeza** [comment]
Hi @Andarist I'm getting familiar with the code, but if you can point me on where to start that would be nice, thank you

**Comment by davidkpiano** [comment]
Hey @urig-40seas!

We will be working on `onError` for XState v5 soon, which should solve these kinds of issues.

**Comment by davidkpiano** [comment]
@Andarist Can this be closed as finished?

**Comment by Andarist** [comment]
We no longer use `console.error` to report any errors so I think this isn't an issue in v5.
