### ISSUE TITLE
Passing a ref to @xstate/inspect crashes/throws

### ISSUE THREAD

**Issue by alavkx** [statelyai/xstate#2373]
**Description**

Passing an HTMLVideoElement ref to `useMachine` when `devtools: true` throws
```
Uncaught TypeError: Converting circular structure to JSON
```

In the Electron app that this code was written in the app infinite loops and freezes, with no runtime error in the console.

**Expected Result**

Can inspect machine

**Actual Result**

App crashes

**Reproduction**

https://codesandbox.io/s/agitated-knuth-g18yr?file=/src/MediaPlayer.tsx

**Additional context**

Toggle `devtools: false` to see the app working.

**Comment by fedekau** [comment]
@alavkx Did you find a way to avoid this? The exact same thing is happening to me. I tried using the `serialize: false` option but it did not help

**Comment by alavkx** [comment]
I didn't—just avoided passing refs to machine context. It seems like an anti-pattern anyways so it didn't bother me too much.

**Comment by rossng** [comment]
I see [this commit](https://github.com/statelyai/xstate/commit/65f4322efd184057490b93e4cad820ec88172739) from a few months ago which added this handler:

```ts
service.subscribe((state) => {
      inspectService.send({
        type: 'service.state',
        state: stringify(state),
        sessionId: service.sessionId
      });
    });
```

The `stringify` function here is safe, I think - if `JSON.stringify` fails it falls back to [a circular-proof method](https://www.npmjs.com/package/fast-safe-stringify).

However, at the same time, that commit leaves in place a duplicate handler a few lines later

```ts
    service.subscribe((state) => {
      inspectService.send({
        type: 'service.state',
        state: JSON.stringify(state),
        sessionId: service.sessionId
      });
    });
```

This one does not use the safe method for stringification and I'm pretty sure the crashes are happening as a result of that.

Looking at the [current code](https://github.com/statelyai/xstate/blob/4999395323025dfbe3fe44c33ed9ffd640f00e89/packages/xstate-inspect/src/server.ts#L120), I don't see any particular reason for this subscription to be duplicated. But I'm not familiar with XState internals so it's possible I'm missing something.

Paging @davidkpiano to see if there's any reason that [this `subscribe` call](https://github.com/statelyai/xstate/blob/4999395323025dfbe3fe44c33ed9ffd640f00e89/packages/xstate-inspect/src/server.ts#L135) can't be deleted.

**Comment by davidkpiano** [comment]
Closing as stale – if there are issues with the new inspector, please file them here: https://github.com/statelyai/inspect/issues/new
