### ISSUE TITLE
Machine stops due to Fast Refresh

### ISSUE THREAD

**Issue by bard** [statelyai/xstate#2383]
**Description**

When fast refresh is enabled and a component that calls `useMachine` is modified, the service run by `useMachine` stops.

**Expected Result**

Service stays active.

**Actual Result**

Service stops.

**Reproduction**

I suspect that this is a lower level issue that what can be reliably checked on CodeSandbox, so I created a reproduction which is little more than the XState/React+TypeScript sandbox inside a create-react-app. The index, App, and machine are moved each to their own file to ensure that changes to one don't cause reloads in another. A `useEffect` is added in `App` to register a callback on `service.onStop`, to notify when it stops.

```sh
$ git clone https://github.com/bard/repro-xstate-fast-refresh
$ cd  repro-xstate-fast-refresh
$ yarn && yarn start
```

1. open the browser console
2. click the "Click me" button a few times
3. change something cosmetic in `App.tsx`, e.g. the `h1` content
4. **unexpected**: the browser console reports "stopped"
5. click the "Click me" button a few times again
6. **unexpected**: the counter restarts from zero, suggesting that the previous state got lost

**Additional context**

It seems to be the same issue as https://github.com/statelyai/xstate/issues/995. In particular I believe this comment of @Andarist still applies: 

> What I'm observing is that our effect gets "remounted" - its cleanup (service.stop()) is being called even though [] is passed as inputs so it should only be cleaned up when unmounting.

Which is consistent with what mentioned in the [page](https://reactnative.dev/docs/fast-refresh#fast-refresh-and-hooks) linked to later in the thread:

> Sometimes, this can lead to unexpected results. For example, even a useEffect with an empty array of dependencies would still re-run once during Fast Refresh.

**Comment by johtso** [comment]
Would be interested in a workaround for this. Fast refresh is super useful for development.. but now that I'm using xstate I'm having to refresh the page any time I make a change.

**Comment by milanbgd011** [comment]
I do not get errors like this anymore after update to 4.27.0 in NextJS app:
https://github.com/statelyai/xstate/releases/tag/xstate%404.27.0

Please confirm that this is now working or not in CRA.

**Comment by Andarist** [comment]
I believe that the situation around this got substantially improved by https://github.com/statelyai/xstate/pull/4436 for the upcoming v5 release
