### ISSUE TITLE
using `useSpawn` in @xstate/react@>=1.5.0 requires at least xstate@v4.22

### ISSUE THREAD

**Issue by karfau** [statelyai/xstate#2410]
**Description**
`useSpawn` tries to import from `xstate/[src|lib]/behaviors` which seems to only exist since v4.22.

**Expected Result**
Not sure, ideas:
- correct version range for 1.5.2 version in 
```json5
"peerDependencies": {
  //...,
  "xstate": ""
}
```
- conditionally check if the behaviors import is required/are available?
- update changelog/release notes of 1.5.0 and 1.5.1 regarding this issue
- ???

**Actual Result**
With an earlier version of xstate there are errors when trying to resolve that "xstate/src/behaviors"(1.5.0) or `xstate/lib/behaviors`(1.5.1).

**Reproduction**

https://codesandbox.io/s/elegant-wind-08c99?file=/src/index.js

**Additional context**

**Comment by davidkpiano** [comment]
cc. @Andarist

**Comment by Andarist** [comment]
See the closing comment below the PR that was meant to fix this in the past: https://github.com/statelyai/xstate/pull/2411#issuecomment-1018362868
