### ISSUE TITLE
The third argument passed to services has no "state" prop

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#2421]
**Description**
While guards and actions receive the machine state in its third "meta object"  argument, services don't.
(Less importantly - but inconsistently too - there is no "_event" property on the meta object).

```javascript
function myService(context, event, meta) {
   console.log(Object.keys(meta)) // data, src (but no state)
}
```
Compare vs a guard or an action:
```javascript
function myGuard(context, event, meta) {
   console.log(Object.keys(meta)) // cond, state, _event
}

function myAction(context, event, meta) {
   console.log(Object.keys(meta)) // action, state, _event
}
```

**Expected Result**
```javascript
const machine = createMachine({
  id: 'root',
  initial: 'Idle',
  states: {
    Idle: {
      on: {
        EVENT: {
          cond: (ctx, e, meta) => {
            console.log(meta.state) // State
            return true
          },
          actions: (ctx, e, meta) => {
            console.log(meta.state) // State
          },
        },
      },
      invoke: {
        src: (ctx, e, meta) => {
          console.log(meta.state) // <------- expected State, got undefined
          return Promise.resolve()
        },
      },
    },
  },
})
```

**Actual Result**
There is no state property on the third argument passed to services.

**Reproduction**
https://codesandbox.io/s/cold-cache-0z7ys?file=/src/index.js

**Additional context**
The machine state is quite useful, especially with the recent `getSnapshot` method addition. Inside a service, one may wish to retrieve a value from a child actor, e.g.:
```javascript
function myService(state, event, { state }) {
  const lastValue = state.children.actor1?.getSnapshot()
}
```
```

**Comment by Andarist** [comment]
`state` is currently not given to any kind of implementation (actor, action, delay, guard) in v5. We understand that there might be some concerns related to that - they deserve a new thread to be created if needed though. 

For the time being, I'm closing this issue since it's not directly actionable on our side.
