### ISSUE TITLE
Create machine from the model typescript example doesn’t work

### ISSUE THREAD

**Issue by dqunbp** [statelyai/xstate#2424]
**Description**
When creating a state machine from a model, types are not in woks correctly

**Expected Result**
Works correctly with types as in the example from the docs
https://xstate.js.org/docs/guides/models.html#typescript

**Actual Result**
Shows `ts(2322)` error in the actions

**Reproduction**
- [CodeSandbox example (TypeScript)](https://codesandbox.io/s/xstate-model-6i98z)

**Additional context**
XState version: 4.23.0

**Comment by davidkpiano** [comment]
Resolved in #2426
