### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'getSnapshot' in undefined

### ISSUE THREAD

**Issue by paulrberg** [statelyai/xstate#2435]
**Description**

The `useActor` hook throws an error when used with the `useInterpreter` hook.

**Expected Result**

I should get the state by using the hook.

**Actual Result**

> TypeError: Cannot use 'in' operator to search for 'getSnapshot' in undefined

```
  27 |     /* ... */
  28 | };
  29 | function defaultGetSnapshot(actorRef) {
> 30 |     return 'getSnapshot' in actorRef
  31 |         ? actorRef.getSnapshot()
  32 |         : isActorWithState(actorRef)
  33 |             ? actorRef.state
  ```

**Reproduction**

See http://github.com/paulrberg/xstate-useActor-bug.

**Additional context**

- xstate@npm:4.23.0
- @xstate/react@npm:1.5.1

**Comment by Andarist** [comment]
Your `Web3StateProvider` is not used anywhere in your app - I suspect that when you fix that then the problem will go away.

You can check out this working example of the `useInterpret` and `useActor` combination: https://codesandbox.io/s/goofy-ellis-rk7hz?file=/src/App.js

**Comment by mattpocock** [comment]
Working as designed, @paulrberg feel free to re-open if you have any other issues.

**Comment by paulrberg** [comment]
Oh, right! So the issue was that I forgot to put the `Web3StateProvider` in `App.tsx`. Duh!

Thanks.
