### ISSUE TITLE
[core] Action meta objects are different

### ISSUE THREAD

**Issue by fraserdrops** [statelyai/xstate#2438]
**Description**
The meta object (third argument) for action is currently different for different actions. 

I was trying to use action payloads to parameterize a send action, but the send action doesn't seem to have access to action in the actionMeta object (third argument):
```js // works here
awardPoints: assign({
  totalPoints: (ctx, event, { action }) => ctx.totalPoints + action.points
}),
// doesn't work 
sendPointsUpdate: send((ctx, event, { action }) => ({
  type: 'UPDATE_POINTS',
  points: action.points // action is undefined
}))
```

**Expected Result**
I would expect all actions get the same meta object, or at least all have the action property in the meta object.

**Actual Result**
assign gets `{state, action, _event}`, while send and pure (haven't checked other actions) just get `{_event}` for it's third argument. 

**Related Issues**
#2421 
#2306 

**Reproduction**

- [Codesandbox](https://codesandbox.io/s/xstate-send-action-meta-sf67z?file=/src/App.js)
In the codesandbox, the assign actions work fine, but the send action breaks because it doesn't have the action property.

**Additional context**
v4.23.0

**Comment by mellanslag-de** [comment]
@davidkpiano This is the issue I was originally interested in^^ Can you confirm that it does indeed make sense to wait until v5.0 to take another look at the code for this?
Probably will make the solution much cleaner as well as the code looked more modular in the next branch at the first glance.

**Comment by davidkpiano** [comment]
This has been fixed in `xstate@beta`
