### ISSUE TITLE
xstate-inspect from a local viz?

### ISSUE THREAD

**Issue by polx** [statelyai/xstate#2439]
**Description**
[xstate-inspect](https://github.com/statelyai/xstate/tree/main/packages/xstate-inspect) has URL option but how to build the "destination"?

**Expected Result**
I'd expect to download a repository and be able to adjust it and deploy it to a static URL and direct the `inspect` function call to this URL.

**Actual Result**
Only https://statecharts.io/inspect seems to be working.

**Reproduction**
That: [XState Visualizer](https://xstate.js.org/viz/) did not work for me (or I did not find the URL to call for the inspect function to work.

**Additional context**
87e87c8610ed84d5d61975c8451be7aba21ca18a is a commit of xstate-vis which I tried to get it to work.

**Comment by polx** [comment]
From [here](https://github.com/statecharts/xstate-viz/issues/67#issuecomment-631482869) it seems that something was baking somewhere. But where?

**Comment by Andarist** [comment]
We are currently rebuilding the visualizer which is going to also work as the inspector - and the current plan is to open source it once it's get released. 

A sideways question from my side is - why do u want to self-host the inspector?

**Comment by polx** [comment]
Thanks @Andarist : three reasons to self-host the inspector:

- Save bandwidth as at least one of our major developers is behind very shaky networks (even in Europe this happens!); this is probably moot in many cases but is crucial.
- Keep information internally by ensuring no network activity goes outside. This might well be the case in xstate's visualizer but there seems to be no documentation about it nor an assertion that this is going to stay so.
- Allow, possibly, for tunings (but we have not yet met that requirement).

**Comment by Andarist** [comment]
So - once we'll release the new version it should be possible to do this. I've added an issue about this in our internal issue tracker.

**Comment by ynhhoJ** [comment]
@Andarist, any ETA?

**Comment by davidkpiano** [comment]
> @Andarist, any ETA?

All updates will be announced on [@statelyai (Twitter)](https://twitter.com/statelyai) and the [Discord community](https://discord.gg/xstate).

**Comment by davidkpiano** [comment]
This can now be done: https://github.com/statelyai/xstate-viz

**Comment by technoplato** [comment]
> We are currently rebuilding the visualizer which is going to also work as the inspector - and the current plan is to open source it once it's get released.
> 
> A sideways question from my side is - why do u want to self-host the inspector?

@Andarist @davidkpiano Are you all still planning to open source this?

And can I get some clarification as to whether or not it should be possible to inspect a react native state machine right now?
