### ISSUE TITLE
Difference between `service.machine.initialState` and `service.initialState`

### ISSUE THREAD

**Issue by ChrisShank** [statelyai/xstate#2457]
**Description**
A consumer of `xstate-vue2` noticed a bug where there is a critical difference between accessing the initial state on `service.machine.initialState` and `service.initialState` when spawning another machine. They put up a fix [here](https://github.com/ChrisShank/xstate-vue2/pull/3). 

**Expected Result**
Accessing `service.machine.initialState.context` does not cause an extra `entry` action to run.
**Actual Result**
The entry action for the spawn logs again. Also its interesting that `service.machine.initialState.context` logs an `ActorRef` while `service.initialState.context` logs an interpreter.

**Reproduction**
https://codesandbox.io/s/focused-voice-hnuni?file=/src/main.ts

**Additional context**
I am unsure of whether this is a bug in core or the component packages (`@xstate/vue`, `@xstate/react`, ect.). These packages currently access `service.machine.initialState` in `useMachine`.

**Comment by davidkpiano** [comment]
The only difference between `service.machine.initialState` and `service.initialState` is that:

- `service.initialState` will return the state with the initial context with _actors spawned on the parent_
- `service.machine.initialState` is basically `machine.initialState` which is completely unaware of the parent

The fix that they put up should be fine (most likely).

**Comment by ChrisShank** [comment]
Thanks for the quick response! I will merge it in and update this issue if any unintended side effects come up!

For book keeping `service.machine.initialState` is used [here](https://github.com/statelyai/xstate/blob/main/packages/xstate-react/src/useService.ts#L11), [here](https://github.com/statelyai/xstate/blob/main/packages/xstate-vue/src/useMachine.ts#L32), and [here](https://github.com/statelyai/xstate/blob/main/packages/xstate-react/src/useMachine.ts#L94).

**Comment by Andarist** [comment]
Note that in the React land this would not work properly (at the time). The `service.initialState` variant is not pure and might execute side-effects at the wrong time: https://codesandbox.io/s/sleepy-almeida-ql101?file=/src/App.js

**Comment by davidkpiano** [comment]
@ChrisShank Can this be considered answered/solved? Or should we add documentation for this?

**Comment by ChrisShank** [comment]
@davidkpiano Its answered, but does the vue package still have this bug?

**Comment by Andarist** [comment]
As far as I see it might have that bug - I'll assign myself to this issue, write a test and fix the bug (or just add a test if it turns out that there is no bug after all).

**Comment by davidkpiano** [comment]
I'm _pretty_ sure this problem is avoided completely in `xstate@beta` since there is no longer any `actor.initialState` (rather, `actor.getSnapshot()` only).

Feel free to reopen if this is still an `xstate@beta` issue somehow.
