### ISSUE TITLE
[xstate/svelte] bundling of @xstate/svelte/lib/fsm with sveltekit & vite is broken

### ISSUE THREAD

**Issue by benbender** [statelyai/xstate#2458]
**Description**
If I create a new sveltekit-app:

1. `npm init svelte@next xstate-sveltekit-repro`
2. install its dependencies via `npm i && npm add @xstate/svelte @xstate/fsm`
3. add the example for the usage of `@xstate/svelte/lib/fsm` from the docs @ https://xstate.js.org/docs/packages/xstate-svelte/#usemachine-machine-with-xstate-fsm
4. build the app via `npm run build`
5. start it via `npm preview`

I get the following error:

````
> svelte-kit preview

> Cannot find module '[...]/xstate-sveltekit-repro/node_modules/@xstate/svelte/lib/fsm' imported from [...]/xstate-sveltekit-repro/.svelte-kit/output/server/app.js
Did you mean to import @xstate/svelte/lib/fsm.js?
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '[...]/xstate-sveltekit-repro/node_modules/@xstate/svelte/lib/fsm' imported from [...]/xstate-sveltekit-repro/.svelte-kit/output/server/app.js
Did you mean to import @xstate/svelte/lib/fsm.js?
    at finalizeResolution (internal/modules/esm/resolve.js:271:11)
    at moduleResolve (internal/modules/esm/resolve.js:694:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36)
````

**Expected Result**
The app should run with the production build.

**Actual Result**
`@xstate/svelte/lib/fsm` can't be imported

**Reproduction**
see above.

**Additional context**
* The app works in dev-mode. The problem seems to be rooted in the vite-build.
* Reproduced with NPM & PNPM
* Strangely the `@xstate/svelte` package doesn't seem to use rollup for bundling like the rest of the packages in this repo. Any reason for that?

**Comment by floratmin** [comment]
I just made it work with the description from:
[https://xstate.js.org/docs/recipes/svelte.html](https://xstate.js.org/docs/recipes/svelte.html)

But contrary to the description the `@rollup/plugin-replace` breaks the build. Without this step everything seems to work.

**Comment by benbender** [comment]
@floratmin `svelte@next` is `sveltekit`, which uses `vite` as its bundler. Additionally I did no extra steps - as stated above. So I don't think both problems are related.

**Comment by floratmin** [comment]
No that's right I use it with SvelteKit.

**Comment by benbender** [comment]
@floratmin It works in a production-bundle with the fsm-packages? If yes, did you do anything special?

**Comment by floratmin** [comment]
No I use it with the full xstate package, I tried it also with `@sveltejs/adapter-static` where it also worked.

**Comment by benbender** [comment]
As I said. Different context. This is a problem with the bundling of the /lib/fsm-subpackage.

**Comment by floratmin** [comment]
I just replaced `xstate` with `@xstate/fsm` and it does not work. I get the error :
`'default' is not exported by node_modules/@xstate/fsm/es/index.js, imported by src/lib/state/login.ts`

**Comment by benbender** [comment]
@floratmin try the example here: https://xstate.js.org/docs/packages/xstate-svelte/#usemachine-machine-with-xstate-fsm. And let's try to stop cluttering this bug-report ;)

**Comment by floratmin** [comment]
@benbender This could related [https://github.com/sveltejs/kit/issues/928](https://github.com/sveltejs/kit/issues/928)

**Comment by benbender** [comment]
Not quite sure on what side this got resolved, but the issue is gone \o/

````
~/xstate-sveltekit-repro is 📦 v0.0.1 via  v14.17.3
❯ npm run build

> ~TODO~@0.0.1 build
> svelte-kit build

vite v2.4.4 building for production...
✓ 41 modules transformed.
.svelte-kit/output/client/_app/assets/svelte-logo.87df40b8.svg                           1.85kb
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal.1f8b3a07.woff2          10.48kb
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal.8659ae46.woff2      7.85kb
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal.b3140dd3.woff2   16.11kb
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal.b6331a25.woff2      11.84kb
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal.046b609f.woff2       9.08kb
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal.a2f9dbe8.woff2          16.44kb
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal.0d19eb5d.woff             75.54kb
.svelte-kit/output/client/_app/manifest.json                                             2.68kb
.svelte-kit/output/client/_app/error.svelte-1d6e44ca.js                                  1.56kb / brotli: 0.64kb
.svelte-kit/output/client/_app/pages/index.svelte-8e2651ef.js                            4.07kb / brotli: 1.45kb
.svelte-kit/output/client/_app/pages/xstate.svelte-d6f84ed4.js                           1.73kb / brotli: 0.76kb
.svelte-kit/output/client/_app/pages/__layout.svelte-c0b481c5.js                         4.66kb / brotli: 1.53kb
.svelte-kit/output/client/_app/pages/todos/index.svelte-e7b4e6ee.js                      5.44kb / brotli: 1.96kb
.svelte-kit/output/client/_app/pages/about.svelte-520b8026.js                            2.39kb / brotli: 0.90kb
.svelte-kit/output/client/_app/assets/start-a8cd1609.css                                 0.16kb / brotli: 0.10kb
.svelte-kit/output/client/_app/assets/pages/index.svelte-078f1a0b.css                    1.35kb / brotli: 0.36kb
.svelte-kit/output/client/_app/assets/pages/about.svelte-4db5be0d.css                    0.11kb / brotli: 0.07kb
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-ded7473c.css                 5.06kb / brotli: 1.36kb
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-05e41044.css              3.72kb / brotli: 0.86kb
.svelte-kit/output/client/_app/start-98a34a08.js                                         18.19kb / brotli: 5.71kb
.svelte-kit/output/client/_app/chunks/vendor-4ad73005.js                                 18.89kb / brotli: 7.13kb
vite v2.4.4 building SSR bundle for production...
✓ 35 modules transformed.
.svelte-kit/output/server/app.js   70.80kb

Run npm run preview to preview your production build locally.

No adapter specified
See https://kit.svelte.dev/docs#adapters to learn how to configure your app to run on the platform of your choosing
````

**Comment by annaghi** [comment]
> 4\. build the app via `npm run build`
> 5\. start it via `npm preview`
> 
> I get the following error:

@benbender What happens when you run `npm run preview`?

**Comment by benbender** [comment]
Oh sh*t. You're right... Its still broken - my memory betrayed me as I thought that it broke when building. sorry for the noise!

Btw, my old workaround:

```
    import { useMachine } from '@xstate/svelte/lib/fsm.js';
    import * as pkg from '@xstate/fsm';

    const { createMachine, assign } = pkg.default;
```

Works for now even if its not pretty...

**Comment by annaghi** [comment]
No problem :) Thanks for confirming!

With your workaround we have two possible solutions now! Good.

**Comment by benmccann** [comment]
It's best to used named imports instead of default imports for this reason. Then it will work the same with both ESM and CJS
