### ISSUE TITLE
Send action documentation appears to be incorrect for sending events to actors

### ISSUE THREAD

**Issue by mattpocock** [statelyai/xstate#2462]
**Description**
https://xstate.js.org/docs/guides/actions.html#send-action

```ts
// Send { type: 'SOME_EVENT' } to the actor ref via string target
{
  actions: send({ type: 'SOME_EVENT' }, {
    to: context => context.someActor.name
  })
}
// ...

// Send { type: 'SOME_EVENT' } to the actor ref via ref target
{
  actions: send({ type: 'SOME_EVENT' }, {
    to: context => context.someActor.ref
  })
}
```

`context.someActor.name` and `context.someActor.ref` appear not to work.

**Comment by Andarist** [comment]
Could you prepare a codesandbox representing the issue? Given how the `someActor` is created in the `entry` action it looks OK to me, would love to check what's going on in the repro case.

**Comment by davidkpiano** [comment]
It should be:
```ts
{
  actions: send({ type: 'SOME_EVENT' }, {
    to: context => context.someActor
  })
}
```

I'll fix this.
