### ISSUE TITLE
Error with spawned machine and Global State

### ISSUE THREAD

**Issue by gepd** [statelyai/xstate#2482]
**Description**

I am spawning a machine in the context to use it in a component with `Global State/React Context`. As David told me in discord, this code should work

```js
const isOpenedSelector = (state: StateFrom<typeof spawnedMachine>) =>
  state.matches("inactive");

export const ChildComponent = () => {
  const { toggle } = useContext(ToggleContext);
  const spawnedMachine = toggle.state.context.spawnedRef;
  const isOpen = useSelector(spawnedMachine, isOpenedSelector);

  return <div>{isOpen ? "is open" : "is closed"}</div>;
};
```

**Expected Result**
use the spawned machine without any error

**Actual Result**
In the code sandbox I'm getting the error: `Cannot read property 'context' of undefined`

**Reproduction**

- https://codesandbox.io/s/lazy-spawn-nkwjz?file=/src/ChildComponent.tsx

**Additional context**
`xstate: 4.23.1`
`@xstate/react: 1.5.1`

**Comment by gepd** [comment]
Using `useSelector` seems to avoid the error:

```js
const machineSelector = (state: StateFrom<typeof toggleMachine>) => state.context.posSessionMachineRef;

export const ChildComponent = () => {
  const { toggle } = useContext(ToggleContext);
  const spawnedMachine = useSelector(toggle, machineSelector);
  const isOpen =  !!spawnedMachine.getSnapshot()?.matches("opened");

  return <div>{isOpen ? "is open" : "is closed"}</div>;
};
```

But I'm wondering if there is a better way to do this, I would like something like with no spawned machines

```js
const globalServices = useContext(Context);
const inputSearch = useSelector(globalServices.ServiceName, selectorCallback);
const { send } = globalServices.ServiceName;
```

**Comment by davidkpiano** [comment]
We're exploring some sort of a receptionist pattern like you demonstrated in the second code example.

Closing this as `useSelector` is the workaround.
