### ISSUE TITLE
Error sending event to spawned machine in initial context

### ISSUE THREAD

**Issue by gepd** [statelyai/xstate#2486]
**Description**
Send an action after spawn a machine in the context result in an error: `Unable to send event to child 'spawnedMachine' from service 'toggle'.`

**Expected Result**
Send an action to the spawned machine

**Actual Result**
Error telling that isn't possible to send the event

**Reproduction**
https://codesandbox.io/s/lazy-spawn-forked-uxeux?file=/src/toggleMachine.ts

Press the `Update Spawned Machine` button

**Comment by davidkpiano** [comment]
Verified to be working with the latest XState (4.25.0)
