### ISSUE TITLE
After "state" deprecation in ActorRefFrom, there is no easy way to get the type of an ActorRef

### ISSUE THREAD

**Issue by VanTanev** [statelyai/xstate#2493]
**Description**
Previously, when I needed a way to extract the context from an ActorRef of a generic machine, I could do something like this:
```ts
interface MyMachineActor<T> extends ActorRefFrom<MyMachine<T>> {}

// but now I get
// 'state' is depricated
const myMachineSelector<T, R>(selector: (state MyMachineActor<T>['state']) => R) { ... }
```

**Expected Result**
We probably can provide a utility type like:
```ts
type EmittedFrom<T> = T extends ActorRef<any, infer TEmitted> 
  ? TEmitted 
  : T extends Behavior<any, infer TEmitted>
  ? TEmitted
  : never 
```

Used like this:
```ts
const myMachineSelector<T, R>(selector: (state EmittedFrom<MyMachineActor<T>>) => R) { ... }
```

Let me know what you think and if I should open a PR.
Thanks!

**Comment by davidkpiano** [comment]
> Let me know what you think and if I should open a PR.

Yes please! This would be a good addition (cc. @Andarist)
