### ISSUE TITLE
`useMachine(machine, { state })` returns the initial state instead of the `service.state`

### ISSUE THREAD

**Issue by p-j** [statelyai/xstate#2505]
**Description**
As [discussed on discord](https://discord.com/channels/795785288994652170/809564609383890965/874567900126642197)
the following code
```ts
const intialState = State.from(stateValue, context)
const [state, send,  service] = useMachine(machine, { state: intialState, context })
```
The state returned by the hook is equal to the `initialState` (as the [code suggest it should](https://github.com/statelyai/xstate/blob/2236b9f3ca4c9c9c475d976cf375987eb11213fc/packages/xstate-react/src/useMachine.ts#L115-L124)) but in this particular case, this leads to an incomplete state being returned.

It is missing the `nextEvents` and possible parallel states that were not part of the stateValue.
Furthermore, the `state` return differs from the `service.state` which has those missing pieces.

As discussed below/shown in the repro, there are multiple workaround, it may also just be a case of improving documentation to show how it's done.

**Expected Result**
The state returned should be complete and most likely should be the `service.state` or a clone of it.

**Actual Result**
The state return is not complete and differs from the internal state of the `service`

**Reproduction**
I've made a small reproduction here and also showcasing the different behavior between `useMachine` vs `useInterpret + useActor`

there is a workaround that consist in calling `machine.resolveState` on top of `State.from` in which case it works as expected

https://codesandbox.io/s/elated-taussig-mq98r?file=/src/index.tsx

**Additional context**
This issue was discovered as part of looking for a way to work with machine that are hydrated using partial states obtained from a remote API (usually a StateValue and the context).

**Comment by p-j** [comment]
in the end this is what I'm going with for my use case:
```ts
export function useHydratedMachine<TContext, TEvent extends EventObject>(
  machine: StateMachine<TContext, any, TEvent>,
  stateOrStateValue?: State<TContext, TEvent> | StateValue,
  context?: TContext,
) {
  const initialState = machine.resolveState(State.from(stateOrStateValue ?? machine.initialState, context))
  const [state, send, service] = useMachine(machine, { state: initialState, context })
  return { state, send, service }
}
```

**Comment by manyaagarwal** [comment]
@davidkpiano I would like to take this issue if no-one else is working on it?

**Comment by davidkpiano** [comment]
> @davidkpiano I would like to take this issue if no-one else is working on it?

Yes, please!

**Comment by p-j** [comment]
If that helps, I've updated the code above to this now:
```ts
import { useMachine } from '@xstate/react'
import { UseMachineOptions } from '@xstate/react/lib/types'
import { EventObject, State, StateMachine, StateValue } from 'xstate'

export interface IUseHydratedMachineOptions<TContext, TEvent extends EventObject>
  extends Omit<UseMachineOptions<TContext, TEvent>, 'state'> {
  state?: State<TContext, TEvent> | StateValue
  context?: TContext
}
export function useHydratedMachine<TContext, TEvent extends EventObject>(
  machine: StateMachine<TContext, any, TEvent>,
  { state: _state, context: _context, ...options }: IUseHydratedMachineOptions<TContext, TEvent> = {},
) {
  // Get the context from either the options or the machine
  const context = _context ?? machine.context
  // Resolve the initial state from the given options
  const state = machine.resolveState(State.from(_state ?? machine.initialState, context))
  // Initialize the machine with the resolved state and the given options
  return useMachine(machine, {
    ...options,
    state,
    context,
    devTools: process.env.NODE_ENV === 'development',
  })
}
```

This is because as I've had issues with guards referencing a `context` that wasn't part of the machine's definition but passed afterward either using the context option of `useMachine` or the `.withContext` method.
In those case, the previous code would crash when attempting to compute the `intialState`.

**Comment by itsnoa04** [comment]
Hey, @davidkpiano is this pr still open?, if so id like to work on it.

**Comment by davidkpiano** [comment]
The workaround is correct:

```diff
function useHydratedMachine(machine, stateValue, context) {
  const [state, send, service] = useMachine(machine, {
-   state: State.from(stateValue, context),
+   state: machine.resolveState(State.from(stateValue, context)),
    context
  });
  service.start(stateValue);
  return { state, send, service };
}
```

**Comment by Andarist** [comment]
I believe that this issue is already fixed on the `next` branch.
