### ISSUE TITLE
Spawned Machines are not removed from `children` after `stop()` is called

### ISSUE THREAD

**Issue by j-funk** [statelyai/xstate#2531]
**Description**
Spawned Machines are not removed from `children` after `stop()` is called.

**Expected Result**
I would expect the machine would be deactivated and also the reference removed from the `children` object.

**Actual Result**
References to stopped machines are accumulating in the `children` object and could present significant memory leaks if spawning actors is used on a large scale. 

**Reproduction**
https://codesandbox.io/s/xstate-todomvc-forked-nbsl4?file=/todosMachine.js

I've modifies the TODOs MVC example to call `stop` when `Clear completed` is called.  I also log the length of the keys in the `children` attribute of the state which continues to grow.

**Comment by j-funk** [comment]
I've created a [new fork](https://codesandbox.io/s/xstate-todomvc-forked-vq563?file=/todosMachine.js) of the TODO MVC example which uses the `stop` action as recommended.  The length of `children` continues to grow however.  Happy to investigate any alternative implementations that would work around this issue.  Let me know.

```
    CLEAR_COMPLETED: {
      actions: assign({
        todos: (context) => {
          // Call stop on all completed
          context.todos
            .filter((todo) => todo.completed)
            .forEach((todo) => stop(todo.ref))
          return context.todos.filter((todo) => !todo.completed);
        }
      })
    }
```

**Comment by davidkpiano** [comment]
Here is how it should be done: set `preserveActionOrder: true` on the machine and stop the actors first, before removing them:

```js
    CLEAR_COMPLETED: {
      actions: [
        actions.pure((context) => {
          return context.todos
            .filter((todo) => todo.completed)
            .map((todo) => actions.stop(todo.ref));
        }),
        assign({
          todos: (context) => {
            return context.todos.filter((todo) => !todo.completed);
          }
        })
      ]
    }
```

https://codesandbox.io/s/xstate-todomvc-forked-69hct?file=/todosMachine.js:2197-2567

**Comment by gkiely** [comment]
@davidkpiano Does this still work? In the codesandbox, when I delete a todo the children.length does not go down.
I'm also seeing the same issue in the latest XState.

**Comment by j-funk** [comment]
Just wanted to mention this PR I noticed here.  Will take a look at this again once v5 is released.

https://github.com/statelyai/xstate/pull/4078

**Comment by Andarist** [comment]
We made it impossible to `.stop()` non-root actors directly:
https://github.com/statelyai/xstate/blob/ec758593320d04691b2a0732b7cd6808e36622d7/packages/core/src/interpreter.ts#L517-L522

To properly stop child actor you need to use the `stopChild` action and that cleans up `snapshot.children` properly.
