### ISSUE TITLE
documented syntax for entry actions crashes the inspector

### ISSUE THREAD

**Issue by jebeck** [statelyai/xstate#2542]
**Description**
The configuration that exists in the documentation for `entry` actions and does _not_ cause any errors in application code crashes the inspector.

**Expected Result**
Can view the working machine and spawned child machine in the inspector.

**Actual Result**
"An unexpected error has occurred." in the inspector. Dev tools shows:
<img width="685" alt="Screen Shot 2021-08-20 at 18 21 42" src="https://user-images.githubusercontent.com/1588547/130306087-8f3aa743-b728-474b-ae96-3a384090247a.png">

**Reproduction**
Reproduction here: https://codesandbox.io/s/morning-moon-qdjnp

The core issues is specifying `entry` like this (crashes inspector):
```
entry: ["createNewNode", log()],
```
vs. this, which works but which is not how entry actions are documented (as far as syntax) in [the docs on actions](https://xstate.js.org/docs/guides/actions.html?#actions):
```
entry: { type: "createNewNode" },
```
(I also don't know how to include the log action in the second type of syntax... I tried an array of objects, but it didn't work.)

**Additional context**
Maybe of interest to note: things like this happen to me all the time with the inspector, where one syntax works for a machine without errors but not for the inspector. If there was a way to view all possible syntaxes of different types of machine properties, that would be helpful to reduce my search space when things like this happen. As I said above, I had no idea that the second way of configuring `entry` was even possible until I combed through a lot of issues here in the repo and saw it referenced [here](https://github.com/statelyai/xstate/issues/1437). Thanks for the tooling tho, the inspector is beyond valuable, which is why I find it so hard to continue working when it crashes!

**Comment by Andarist** [comment]
This is using the old inspector - we've recently released a new one and the issue seems to be fixed there. You just need to change the URL to https://stately.ai/viz?inspect=1

https://codesandbox.io/s/affectionate-antonelli-0spuz

**Comment by jebeck** [comment]
> This is using the old inspector - we've recently released a new one and the issue seems to be fixed there. You just need to change the URL to https://stately.ai/viz?inspect=1

Yep, you're right, both syntaxes work in the new one. Would you like a PR on the docs and/or the @xstate/inspect package updating the URL? Happy to do those small changes to pay it forward to future people like me who might similarly get frustrated.

**Comment by davidkpiano** [comment]
> > This is using the old inspector - we've recently released a new one and the issue seems to be fixed there. You just need to change the URL to https://stately.ai/viz?inspect=1
> 
> Yep, you're right, both syntaxes work in the new one. Would you like a PR on the docs and/or the @xstate/inspect package updating the URL? Happy to do those small changes to pay it forward to future people like me who might similarly get frustrated.

That would be great!

**Comment by Andarist** [comment]
> Yep, you're right, both syntaxes work in the new one.

Since this works in the new inspector I'm going to close this issue.
