### ISSUE TITLE
Payload not passed using useActor and send second argument 

### ISSUE THREAD

**Issue by alysakowski** [statelyai/xstate#2573]
**Description**
I was trying to use a combination of `useInterpret` + `useActor` with GlobalStateContext, but seems like `send` returned by `useActor` is not working the same way as for `useMachine`. Passing the second argument to `useActor's` `send` is not passed forward 

**Expected Result**
I would expect those two functions to work exactly the same, at this abstraction level

**Actual Result**
We can do `send("LOGIN", { ... })` for `send` returned by `useMachine` but have to do `send({type: "LOGIN", payload: { ... }})` for `send` returned by `useActor`

**Reproduction**
Please see comments in code, you can uncomment some parts just to test it 

https://codesandbox.io/s/romantic-montalcini-2h0fv?file=/src/index.tsx:769-781

**Additional context**
Latest XState version combained with default xstate + typescript + react template. I faced this issue following documentation global state https://xstate.js.org/docs/recipes/react.html#global-state-react-context implementation

**Comment by davidkpiano** [comment]
Sorry, this was missing from the documentation  (https://xstate.js.org/docs/packages/xstate-react/#api), which should provide this warning:

-----

Also, keep in mind that only a single argument (the event object) can be sent to `send(eventObject)` from `useActor(...)`. When migrating to `useActor(...)`, refactor `send(...)` calls to use only a single event object:

```diff
const [state, send] = useActor(service);
-send('CLICK', { x: 0, y: 3 });
+send({ type: 'CLICK', x: 0, y: 3 });
```

**Comment by alysakowski** [comment]
@davidkpiano awesome! 🤝
