### ISSUE TITLE
No Implementation found for action type ''

### ISSUE THREAD

**Issue by maxime4000** [statelyai/xstate#2594]
**Description**
I just update xstate from 4.23.1 to 4.23.3, @xstate/react 1.5.1 to 1.6.0 and @xstate/inspect from 0.4.1 to 0.5.0. 
My app was working fully before I update and now it's barely do anything. 

I have 2 places where actions are defined. In the machine config and in the react component using useMachine
```.tsx
/** Simplify version of SpawnedActorRef definition */
interface SpawnedRef<T>
	extends SpawnedActorRef<
		AnyEventObject,
		State<T, AnyEventObject, any, { value: any; context: T }>
	> {
	state: State<T, AnyEventObject, any, { value: any; context: T }>;
}

const machineConfig = Machine<any>({
  id: "",
  initial: "",
  context: {
    machineARef: {} as SpawnedRef<MachineAContext>
  },
  states: {
    sender: {
      type: "atomic",
      on: [SETSOMETHING, SENDSOMETHING(MachineA), SENDSOMETHINGB(MachineB), ...]
    },
    receiver: {
      Idle <-> receiveData
    },
  },
  type: "parallel",
  entry: ["initSpawn"],
  actions: {
    // mostly assign, send, sendParent
    setSomething: () => assign({}),
    sendSomething: () => send("SOMETHING", { to: (ctx) =>ctx.machineARef }),
  }
});
const [state, send, service] = useMachine<any>(machineConfig, {
  actions: { 
    initSpawn: assign({
      machineARef: () => spawn(machineAConfig.withConfig({services: {}}))
      // machineB, machineC, ...
    }),
  },
  services: {...},
});
```

There is one machine that spawn 3 other machine through an initSpawn action in the react component and it seem like "initSpawn" is call when I look at the xstate inspector, but when the machine try to call actions from the config. I get : 
- `Warning: No implementation found for action type 'setSomething'` 
- `Warning: No implementation found for action type 'sendSomething'`

I think useMachine override actions added from the config with thoses added in as arguments.

Design : 
- MainMachine :
  - contains all the data needed for the app
  - contains all the "Services" machine
  - Sender who's choosing which sub-machine to send the actions
  - Receiver who's waiting to get data from sub-machine + post-processing
- MachineA/B/C
  - Wait for Transition with params
  - fetch data
  - send data back to parent

**Expected Result**
Machine are sending actions correctly

**Actual Result**
- `Warning: No implementation found for action type 'setSomething'` 
- `Warning: No implementation found for action type 'sendSomething'`

**Reproduction**
Sorry for not giving a reproduction example, but I hope I gave enough info to help you fix the issue.

**Comment by maxime4000** [comment]
Quick update. @xstate/react 1.6.0 is causing the issues and not xstate in itself.

**Comment by davidkpiano** [comment]
Can you try it with `@xstate/react` version `1.6.1`? Just released a patch: https://github.com/statelyai/xstate/pull/2591

**Comment by maxime4000** [comment]
Yeah thanks ! The issue is fix :)

**Comment by NoriSte** [comment]
Confirm, fixed, thanks @davidkpiano!! 🙏
