### ISSUE TITLE
*From utility types returning `never`

### ISSUE THREAD

**Issue by waspeer** [statelyai/xstate#2600]
**Description**
```typescript
const model = createModel(
  { editions: [] as Edition[], error: null as string | null, invalidFields: [] as string[] },
  {
    events: {
      submit: (values: Record<string, Date | null>) => ({ values }),
    },
  },
);

type Context = ContextFrom<typeof model>;
type Event = EventFrom<typeof model>;
```

The `ContextFrom` and `EventFrom` utility types were working great, but since a recent update they return `never`.

**Expected Result**
I expected them to return the inferred context and event types.

**Actual Result**
They returned `never`

**Reproduction**
Weirdly enough a reproduction in CodeSandbox does not have the same results. I also added my `tsconfig.json` to it.
https://codesandbox.io/s/thirsty-water-dyxqi?file=/src/index.ts 

**Additional context**
The types start breaking for me from version 4.23.2. The project is based on the [Vite React TS](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react-ts) template.

**Comment by davidkpiano** [comment]
cc. @mattpocock Can you take a look into this?

**Comment by theianjones** [comment]
Oddly enough, when you add an `actions` object that is non-empty, it resolves the issue.

I forked that code sandbox here:
https://codesandbox.io/s/exciting-chatterjee-yhxb2?file=/src/index.ts
