### ISSUE TITLE
CDN for @xstate/inspect

### ISSUE THREAD

**Issue by a-y-u-s-h** [statelyai/xstate#2605]
**Description**
There's confusion regarding usage of @xstate/inspect in a VanillaJS project. Docs don't say much about it right now. And though I tried multiple combinations of links and tried importing variables from files ([this](https://unpkg.com/@xstate/inspect@0.5.0/lib/index.js) and [this as well](https://unpkg.com/@xstate/inspect@0.5.0/es/index.js)), with `type="module"` specified in `script` tag, it gave me errors.

**Expected Result**
Would be nice if the documentation has a section all about it. Vanilla example of inspect makes use of npm, which is...also vanilla, but it doesn't say anything about the _true_ vanilla - which is simply HTML, CSS and JS file with CDN.

**Actual Result**

Upon importing files this way - 

```html
    <script type="module" src="https://unpkg.com/xstate@4.23.3/dist/xstate.web.js"></script>
    <script type="module" src="https://unpkg.com/@xstate/inspect@0.5.0/es/index.js"></script>
    <script type="module" src="src/scripts/index.js"></script>
```

And trying to import exported variables from those files - it doesn't work. Gives different errors like - 

```
Uncaught TypeError: Failed to resolve module specifier "xstate". Relative references must start with either "/", "./", or "../".
index.js:1 Uncaught SyntaxError: The requested module 'https://unpkg.com/@xstate/inspect@0.5.0/lib/index.js' does not provide an export named 'inspect'
```

And upon importing files this way - 

```html
    <script type="module" src="https://unpkg.com/xstate@4.23.3/dist/xstate.web.js"></script>
    <script type="module" src="https://unpkg.com/@xstate/inspect@0.5.0/lib/index.js"></script>
    <script type="module" src="src/scripts/index.js"></script>
```

I get these errors in console: 

```
Uncaught ReferenceError: exports is not defined
    at index.js:3
index.js:1 Uncaught SyntaxError: The requested module 'https://unpkg.com/@xstate/inspect@0.5.0/lib/index.js' does not provide an export named 'inspect'
```

This is how I'm importing it - 

```js
import { inspect } from "https://unpkg.com/@xstate/inspect@0.5.0/lib/index.js"


console.log(inspect)

```

**Reproduction**
This isn't really a bug (maybe a bug in documentation?), it's simply a question of how do I make xstate and xstate inspect work without npm, with CDN. @mattpocock told me to put it in issues lol :) 

**Additional context**
Xstate version: 4.23.3
Xstate inspect version: 0.5.0

**Comment by davidkpiano** [comment]
cc. @Andarist What can be improved here?

**Comment by davidkpiano** [comment]
Closing as stale – if there are issues with the new inspector, please file them here: https://github.com/statelyai/inspect/issues/new
