### ISSUE TITLE
`createModel` second param cause TS errors

### ISSUE THREAD

**Issue by RafalFilipek** [statelyai/xstate#2619]
**Description**
Second parameter in `createModel` cause type errors in machine.

For example:

```
import { createModel } from "xstate/lib/model";

export const model = createModel(
  { apiKey: "" },
  // If you remove this everything works just fine
  {
    /* ... */
  }
);

export const machine = model.createMachine(
  {
    initial: "ready",
    states: {
      ready: {
        // Type 'string' is not assignable to type 'BaseActions ...
        entry: "initWidget",
      },
    },
  },
  {
    actions: {
      // Parameter 'ctx' implicitly has an 'any' type.
      initWidget: (ctx) => {
        console.log(ctx.apiKey);
      },
    },
  }
);
```

**Reproduction**

https://codesandbox.io/s/dark-darkness-5pwig?file=/src/index.ts

**Additional context**

 - `xstate`: `4.23.4`
 - `typescript`: `4.2.3` / `4.4.2`

**Comment by Andarist** [comment]
I think the error is expected here as `createModel` encourages you to declare available events and actions upfront. If you add the `initWidget` action to your `createModel` call then it works as expected:
https://codesandbox.io/s/bold-jang-8u3z7?file=/src/index.ts

**Comment by RafalFilipek** [comment]
Hmmm, @Andarist when this was introduced? My update was from version `4.23.1`. To be clear, I love this change.

**Comment by davidkpiano** [comment]
Going to reopen this because not specifying actions should result in the same behavior as before, especially since the `actions` param in `createModel` isn't documented yet.

**Comment by davidkpiano** [comment]
This is fixed in https://github.com/statelyai/xstate/pull/2632 cc. @Andarist
