### ISSUE TITLE
[@xstate/inspect]: Overflow scroll on side panel

### ISSUE THREAD

**Issue by PaulPCIO** [statelyai/xstate#2629]
**Description**
If you have a large state, the side panel will not scroll to the bottom because the containing div has a height of 100%:
![image](https://user-images.githubusercontent.com/39598117/132456402-80532378-79d9-404b-a752-75f5454f6e76.png)

**Expected Result**
I would expect the side panel to be scrollable

**Actual Result**
You can not scroll if text overflows

**Reproduction**
1. Implement a state machine
2. Add a large context as state
3. Open the inspector (https://statecharts.io/inspect)
4. Try to scroll in the side panel to the right

**Comment by richtera** [comment]
Same issue here.

**Comment by Andarist** [comment]
Could you try using the new inspector with:
```js
inspect({
  url: 'https://stately.ai/viz?inspect=1'
})
```

**Comment by richtera** [comment]
Thanks that works great. BTW is it possible to self-host the inspector?

**Comment by Andarist** [comment]
Maybe the canvas position doesnt get reset? Could u try to use the third (iirc) icon on the bottom to reset it?

**Comment by richtera** [comment]
There is an opacity left on the canvas after switching actors.
![image](https://user-images.githubusercontent.com/708186/132944327-7dc58334-d32f-436d-86e4-607f15f504f6.png)
Also I am noticing that actors names don't seem to be displayed.

**Comment by Andarist** [comment]
Its definitely a bug then - could u file an issue in the other repo with the repro steps listed?

**Comment by davidkpiano** [comment]
Closing this as the original issue is no longer an issue with the new inspector. Please file a separate issue for the actor change visual bug.
