### ISSUE TITLE
SCXML imported machine events missing

### ISSUE THREAD

**Issue by jSalinasNuavis** [statelyai/xstate#2630]
**Description**
When importing a machine from a Scxml format events raised with the tag <send> do not appear in the machine.events property. As an example I have used the following machine:
```xml
<scxml datamodel="ecmascript" name="Scxml" version="1.0"
	xmlns="http://www.w3.org/2005/07/scxml">
    <state id="test">
        <state id="st1">
            <transition event="ev1" target="st2"/>
        </state>
        <state id="st2">
            <onentry>
                <send event="entrySt2"/>
            </onentry>
            <transition event="ev2" target="st1"/>
        </state>
    </state>
</scxml>
```

**Expected Result**
When using `console.log(machine.events)` I expected to get `["ev1", "entrySt2", "ev2"]`

**Actual Result**
`["ev1", "ev2"]`

**Reproduction**
The issue has been reproduce on the following [codesandbox](https://codesandbox.io/s/7guis-counter-forked-g6mcy?file=/src/index.tsx:557-966)

**Comment by davidkpiano** [comment]
Should `send` events be placed in the internal event queue, as well as `raise` events? The SCXML spec doesn't explicitly say this, but it make ssense.

cc. @Andarist

**Comment by davidkpiano** [comment]
Actually, this is invalid - `machine.events` only lists events for which transitions are defined. In this case, `entrySt2` is not handled in this machine.
