### ISSUE TITLE
unexpected results with `preserveActionOrder`

### ISSUE THREAD

**Issue by Enteleform** [statelyai/xstate#2643]
## Description
With `preserveActionOrder` enabled, post-`assign` consumers are not receiving the expected `context`s.

## Results
Executing an event several times, with different event data, will result in:

**Expected:**
- [x] `action`s being evaluated in sequential order
- [x] each action receiving a `context` which reflects the preceding `assign` actions and current `event` data 

**Actual:**
- [x] `action`s being evaluated in sequential order
- [ ] <strike>each action receiving a `context` which reflects the preceding `assign` actions and current `event` data</strike>
  - [x] each action receiving a `context` which reflects the preceding `assign` actions and \*\***FIRST**\*\* `event` data

### Reproduction
https://stately.ai/viz/da8f1ce9-7d90-4031-962d-2f0188c9dc4b

### Additional context
```
XState: 4.23.4
```

**Comment by Andarist** [comment]
Thank you for the report - I've recognized the issue and gonna be fixing this soon. Could you report the other problem (the one about undefined from the comment within the code of that viz playground) in the https://github.com/statelyai/xstate-viz/ ? I think I've diagnosed it as well but I would prefer to keep both discussions separate so I'll describe the issue in the dedicated issue once it gets created.

**Comment by Enteleform** [comment]
@Andarist 

I'm running `4.24.1`, and ran into what I think might be a related issue.

Should `preserveActionOrder` be affecting `sendParent` actions as well?

I have something like the following:

```ts
//###  @ Machine Definitions  ###//

parentMachine = createMachine({
  on: {
    SOME_CONTEXT_MODIFICATION: {
      actions: {
        assign({someProp:() => newValue}),
        ({someProp}) => {console.log({"@":"parent", someProp})},
      }
    }
  }
})

childMachine = createMachine({
  on: {
    INITIAL_EVENT: {
      actions: [
        sendParent("SOME_CONTEXT_MODIFICATION"),
        "SomeUserAction",
      ],
    }
  }
})


//###  @ Point Of Use  ###//

childMachine.withConfig({
  actions:{
    SomeUserAction: {
      () => {console.log({"@":"child", someProp:parentService.getSnapshot().context.someProp})}
    }
  }
})
```

-----

I'm expecting the output of `childMachine.INITIAL_EVENT` to be:
```ts
{"@":"parent", someProp:newValue}
{"@":"child",  someProp:newValue}
```

but I'm getting:
```ts
{"@":"child",  someProp:oldValue}
{"@":"parent", someProp:newValue}
```

`preserveActionOrder` is enabled for both machines.

**Comment by Enteleform** [comment]
Would have created a stately.ai repro but am currently having issues w/ getting parent/child machines working. Started a conversation about it @ https://discord.com/channels/795785288994652170/873201691032420442/886669124594434089, but it died off. Will create an issue for it soon.
