### ISSUE TITLE
(xState+Typescript) Change Typing definition of assign function to allow no context argument.

### ISSUE THREAD

**Issue by maxime4000** [statelyai/xstate#2664]
**Description**
I use Typescript with xstate. I'm using ESLint to lint my files and in some of my machine, I do assign without using the context arguments. Though, I'm force to set the context argument or the typing definition goes off. 
```ts
{
  actions: {
    setLoadingTrue: assign({ loading: (ctx) => true, }), // No error
    setLoadingTrue: assign({ loading: () => true, }), // Typing error, but why ?
    setLoadingTrue: assign({ loading: true, }), // Not sure if this is allow, but error too. Maybe I'm reading the definition wrong.
  }
}
```
I'm expect to add eslint disable rules comment for each ctx because they are unused, but why does I need to have the ctx if I'm not using it ? 
```ts
{
  actions: {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    setLoadingTrue: assign({ loading: (ctx) => true, }), // No error
  }
}
```
**Could we fix this typescript definition so having () => true does not cause compiler issues ?**
Thanks ! :)

**Comment by davidkpiano** [comment]
Can you make a CodeSandbox with this? 🙏  [CodeSandbox (XState TypeScript template)](https://codesandbox.io/s/xstate-typescript-template-6dsws)

**Comment by maxime4000** [comment]
I was able to replicate the issue with the config I made. I remove all the meaning of the machine so it won't work but the typing definition is the issue here.
https://codesandbox.io/s/xstate-typescript-template-forked-v6x6r?file=/src/index.ts

Just in case, here a screenshot and the typing error:

![image](https://user-images.githubusercontent.com/4070713/133692393-e7b186c5-5cbe-4e87-a607-d9caa4d60e88.png)

```
Type 'AssignAction<{ retries: number; }, AnyEventObject>' is not assignable to type 'ActionObject<Context, AnyEventObject> | ActionFunction<Context, AnyEventObject, ActionObject<Context, AnyEventObject>> | undefined'.
  Type 'AssignAction<{ retries: number; }, AnyEventObject>' is not assignable to type 'ActionObject<Context, AnyEventObject>'.
    Types of property 'exec' are incompatible.
      Type 'ActionFunction<{ retries: number; }, AnyEventObject, ActionObject<{ retries: number; }, AnyEventObject>> | undefined' is not assignable to type 'ActionFunction<Context, AnyEventObject, ActionObject<Context, AnyEventObject>> | undefined'.
        Type 'ActionFunction<{ retries: number; }, AnyEventObject, ActionObject<{ retries: number; }, AnyEventObject>>' is not assignable to type 'ActionFunction<Context, AnyEventObject, ActionObject<Context, AnyEventObject>>'.
          Types of parameters 'meta' and 'meta' are incompatible.
            Type 'ActionMeta<Context, AnyEventObject, ActionObject<Context, AnyEventObject>>' is not assignable to type 'ActionMeta<{ retries: number; }, AnyEventObject, ActionObject<{ retries: number; }, AnyEventObject>>'.
              The types of 'action.exec' are incompatible between these types.
                Type 'ActionFunction<Context, AnyEventObject, ActionObject<Context, AnyEventObject>> | undefined' is not assignable to type 'ActionFunction<{ retries: number; }, AnyEventObject, ActionObject<{ retries: number; }, AnyEventObject>> | undefined'.
                  Type 'ActionFunction<Context, AnyEventObject, ActionObject<Context, AnyEventObject>>' is not assignable to type 'ActionFunction<{ retries: number; }, AnyEventObject, ActionObject<{ retries: number; }, AnyEventObject>>'.
                    Types of parameters 'context' and 'context' are incompatible.
                      Type '{ retries: number; }' is not assignable to type 'Context'.ts(2322)
```

**Comment by davidkpiano** [comment]
That's super strange. Recorded the behavior here in case any TypeScript experts want to tackle this...

https://user-images.githubusercontent.com/1093738/133710544-fcebfa33-5cf6-4bca-86e1-cf9dfecb1e15.mp4

**Comment by mattpocock** [comment]
@davidkpiano We'd need to bump the repo to `strict: true` to fix this, since it only happens then. Detailed in our 'Using Typescript' docs:

https://xstate.js.org/docs/guides/typescript.html#troubleshooting

**Comment by JoshuaAmaju** [comment]
I think `createModel` was introduced to fix this. But it's a very old issue

**Comment by davidkpiano** [comment]
> I think `createModel` was introduced to fix this. But it's a very old issue

Yes, `createModel(...)` should be used for this:

```js
const model = createModel({
  some: 'context'
});

// ...
actions: model.assign({/* typed to context! */})
```

Docs: https://xstate.js.org/docs/guides/models.html#models
