### ISSUE TITLE
xstate-inspect server example fails with latest version of ws ^8.0.0

### ISSUE THREAD

**Issue by marklawlor** [statelyai/xstate#2698]
**Description**

https://github.com/statelyai/xstate/blob/main/packages/xstate-inspect/examples/server.ts

Using this example with  `ws: ^8.0.0` does not work and will silently fail.

The error appears to be these lines, as message is of type `Buffer` not string

https://github.com/statelyai/xstate/blob/d98d948a534b028f4af8b271eb431a8625ab5cb3/packages/xstate-inspect/src/server.ts#L74-L76

**Expected Result**

[https://statecharts.io/inspect?server=localhost:8888](https://statecharts.io/inspect?server=localhost:8888) should correctly visualise the example

**Actual Result**

[https://statecharts.io/inspect?server=localhost:8888](https://statecharts.io/inspect?server=localhost:8888) is stuck on "waiting for connection"

**Additional context**

Downgrading to the `ws` version used the example fixes the issue.

**Comment by tom-sherman** [comment]
@marklawlor what version of `ws` is known to work?

**Comment by Andarist** [comment]
@tom-sherman could you prepare a runnable repro case of the problem? The mentioned change is specifically documented as a breaking change included in [the `ws@8.0.0` release](https://github.com/websockets/ws/releases/tag/8.0.0). Our code was also developed against 7.x as per the declared peer dep range:
https://github.com/statelyai/xstate/blob/d98d948a534b028f4af8b271eb431a8625ab5cb3/packages/xstate-inspect/package.json#L49

So I think that 7.x versions should work with `@xstate/inspect`. But either way, I will prepare a PR in a sec to upgrade our code to `ws@8.x`
