### ISSUE TITLE
useSelector not updating state.context when used with spawned machine

### ISSUE THREAD

**Issue by epikhighs** [statelyai/xstate#2702]
**Description**

When using useSelector on a spawned machine, the state.context of the spawned machine does not update with an `assign` action.  However, directly accessing the machine's state.context does contain the updated value.  Refer to the repro.

**Expected Result**

When using a spawned machine, I expect the state.context values to be in sync whether I use `useSelector` or `useActor` to obtain a piece of the `state.context`

**Actual Result**

The state.context values remain unchanged when using `useSelector`

**Reproduction**

https://codesandbox.io/s/lazy-spawn-forked-gbhug?file=/src/index.tsx

**Additional context**

Current workaround is to use the state directly from useActor, but this causes additional renders in the component.

**Comment by davidkpiano** [comment]
> I did some more debugging and it appears for spawned machines, [the subscription callback function](https://github.com/statelyai/xstate/blob/main/packages/xstate-react/src/useSelector.ts#L42) in useSelector never gets inovked for some reason.

Would you be able to add a failing test for this? That will be very helpful in getting this fixed.

**Comment by epikhighs** [comment]
hi @davidkpiano - is this what you were looking for?  obviously, the code isn't up to whatever standards your dev team has, but I got it reproducing in the unit test on my fork (https://github.com/epikhighs/xstate/commit/7e1a3aef32db4b5dc9afa1dc30a8404cfc0626a1)

**Comment by davidkpiano** [comment]
Yes, thank you!
