### ISSUE TITLE
Spawned Behavior Does Not Fully Support Actorref's `send` Type

### ISSUE THREAD

**Issue by christoph-fricke** [statelyai/xstate#2706]
I noticed that the `send` function for actors that are spawned from behavior does not behave the same as the `send` function for interpreted machines. Generally, the `ActorRef` interface uses the `Sender<TEvent>` type for its send function, i.e. both `send("hello")` and  `send({type: "hello"})` are supported.

This works as expected if the `ActorRef` refers to an interpreted machine. However, `Behavior` that is spawned with `spawnBehavior` allows `send("hello")` since it is an `ActorRef`, but it is not correctly processed at runtime. The implementation around `spawnBehavior`, `toActorRef`, and `BaseActorRef` works with `send: (e: TEvent) => void`.

I would like to unify the functionality around `Behaviors` and `StateMachines` and this might be the first step in the right direction. Before I can contribute a pull-request, we should clarify what type definition is expected in the future, i.e. should `send("hello")` be supported? A [*TODO*](https://github.com/statelyai/xstate/blob/9fb87ab0b637dda6fb21aaedcd0b0ff62e3e230f/packages/core/src/types.ts#L1382) suggests otherwise in the source code. However, @davidkpiano [mentioned](https://discord.com/channels/795785288994652170/799416911259369472/893270046376341534) that he would like to keep the `send("hello")` shortcut on Discord.

**Comment by christoph-fricke** [comment]
@davidkpiano I would like to contribute this enhancement to the project. What is the type signature for `send` that should be used going forward? `send: (e: Event<TEvent>) => void` or `send: (e: TEvent) => void`?

**Comment by Andarist** [comment]
If anything this should be `Sender<TEvent>` because `(e: Event<TEvent>) => void`, unfortunately, isn't type-safe.

I would be in favor of unifying this (so adding the runtime support for `Sender<TEvent>`) regardless of potential changes in the future. However, as you have said: David likes the sugar for payloadless events so this probably will stay here.

**Comment by davidkpiano** [comment]
In `xstate@beta`, this is now unified so that only event objects can be sent.
