### ISSUE TITLE
using `actions.raise` with a callback results in a type error.

### ISSUE THREAD

**Issue by Enteleform** [statelyai/xstate#2710]
### Description
Using `actions.raise` with a callback results in a type error.

### Expected Result
- [x] The `raise` action is executed with the same outcome as `send`.
- [x] No type errors are present.

### Actual Result
- [x] The `raise` action is executed with the same outcome as `send`.
- [ ] No type errors are present.
```log
Argument of type '() => { type: string; }' is not assignable to parameter of type 'Event<EventObject>'.
Property 'type' is missing in type '() => { type: string; }' but required in type 'EventObject'.ts(2345)
```

### Reproduction
https://codesandbox.io/s/empty-silence-7t6c2?file=/src/index.ts:459-504

**Comment by Andarist** [comment]
`raise` doesnt accept a callback atm but I think that it should, since it will become more powerful. Even if the ine in SCXML doesnt support this

**Comment by Enteleform** [comment]
> `raise` doesnt accept a callback atm but I think that it should, since it will become more powerful. Even if the one in SCXML doesnt support this

It seems to be working with a callback. This is a code snippet of where I actually ran into the issue:

```ts
_INSERT: {
  actions: [
    assign(({entries}, {index, newEntries}) => ({
      entries:     insert_AtIndex({array:entries, items:newEntries, index}),
      activeIndex: index,
    })),
    actions.choose([{
      cond:    ((_, {context}) => Boolean(context)),
      actions: raise((_, {context, index}) => ({type:"UPDATE_ENTRY", context, index})),
    }]),
  ],
},
```

The `UPDATE_ENTRY` action is definitely executing. If I comment it out, it results in an error in my program due to the missing `context` assignment to a child actor.

**Comment by davidkpiano** [comment]
@Andarist Would this be fixed with the upcoming `raise()` changes?

**Comment by Andarist** [comment]
This was already fixed by https://github.com/statelyai/xstate/pull/3393
