### ISSUE TITLE
Type error on event properties in actions

### ISSUE THREAD

**Issue by eyezick** [statelyai/xstate#2744]
**Description**
Typescript compiler is not detecting the properties of additional event type definitions that are joined by ORs (`|`) when the properties are referenced in actions

**Expected Result**
No error when the event is properly typed

**Actual Result**
Error is thrown: `TS2339: property 'payload' does not exist on type 'MachineEvent'`
This is the error thrown by the `savePayload` action in the below linked codesandbox

**Reproduction**
https://codesandbox.io/s/priceless-sun-bogjb?file=/src/index.tsx

**Comment by leandrojo** [comment]
Use `interface`:

```tsx
interface MachineEvent {
  type: 'TOGGLE' | 'SAVE';
  payload?: string;
}
```

**Comment by davidkpiano** [comment]
TypeScript isn't smart enough to know where the action will be used, so without upcoming tools like the VS Code XState extension with typegen, you will have to ensure that this is the expected event:

```diff
    actions: {
      savePayload: assign((context, event) => {
+       if (event.type !== 'SAVE') { return context; }
        const newContext = Object.assign({}, context);
        const { payload } = event;
        newContext.payload = payload;

        return newContext;
      })
    }
```
