### ISSUE TITLE
Can't sent event to an initial child actor from within `useEffect`

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#2753]
**Expected Result**

I should be able to send an event to a child from within `useEffect`

**Actual Result**

The event is missed because the captured child is "deferred" and events sent to it are never "replayed". IMHO part of the problem is that we ditch that deferred actor (IIRC), so its identity is not preserved.

**Reproduction**
https://codesandbox.io/s/friendly-hugle-gyzm4?file=/src/App.js

**Additional context**
XState 4.25.0

**Comment by davidkpiano** [comment]
The issue in the repro is caused by a stale closure. This works:

```diff
  const [state] = useMachine(parent);
  React.useEffect(() => {
    state.children.foo.send({ type: "MY_EVENT" });
- }, []);
+ }, [state.children.foo]);
```
