### ISSUE TITLE
Viz does not update the list of removed machines

### ISSUE THREAD

**Issue by gepd** [statelyai/xstate#2788]
**Description**
When you invoke a machine, you will se the machine in the list of machines of the viz, you will see it in the `children` object as well. When the invokation ends, it's removed from the `children` object but not from the viz

**Expected Result**
The viz should not show the children machine in the list

**Actual Result**
The machine keeps in the list of machines

**Reproduction**
https://codesandbox.io/s/ancient-surf-qk5rw?file=/src/index.js

![xstate](https://user-images.githubusercontent.com/7091609/140427346-6186d6b0-426c-45fc-baf6-132f8666eccb.gif)

**Comment by davidkpiano** [comment]
Please use the new visualizer, and post viz-related issues there: github.com/statelyai/xstate-viz

Thank you!
