### ISSUE TITLE
can() will trigger assign()

### ISSUE THREAD

**Issue by qingmingsang** [statelyai/xstate#2803]
**Description**
can() will trigger assign()

**Expected Result**
do not trigger

**Actual Result**
can() will trigger assign()

**Reproduction**
```
...
       test: {
            on: {
              TEST: {
                target: 'a',
                actions: 'testAction'
              },
            },
          }
...
actions: {
    testAction: assign({
      behavior: (_context, event) => {
        console.log('xxxxxxxxxxxxxxxxxxxxxxxx');
    })
}
```

```
xState.can('TEST')
```

**Comment by Andarist** [comment]
I can confirm - this shouldn't happen, ideally we'd stay away from any transition resolving logic there. We only need to check if a particular event can be handled or not.
