### ISSUE TITLE
v5: event vs. _event

### ISSUE THREAD

**Issue by davidkpiano** [statelyai/xstate#2805]
Having both `event` and `_event` is IMHO confusing. Not a lot of people care about SCXML all that much for it to be so explicitly called out in our internal structures. Especially that our `_event` is not fully compliant with the SCXML one - in SCXML the `type` doesn't appear in the `_event.data` nor `_event.data` is bound to be an object (it can be just a string or whatever and there are SCXML tests using this, such as test179).

There might still be a value in those meta properties though and as trying to make things simple we probably don't want to wrap our `event` into this nested structure with the metadata. So what I would propose would be to either use a single object internally and unpack it accordingly when calling user-provided functions or keep both as separate objects **but** rename the `_event` and remove `data` from it. Such an object should focus solely on those "meta" properties.

This might complicate XState <-> SCXML conversion at times but I think it's worth it. It feels better to try to convert things explicitly, which allows us to have clear rules for such a conversion than to try squeezing rats into a mouse-sized hole.

_Originally posted by @Andarist in https://github.com/statelyai/xstate/pull/2484#discussion_r727913319_

**Comment by Andarist** [comment]
`_event` was removed in https://github.com/statelyai/xstate/pull/3971
