### ISSUE TITLE
state.can() returns false on NOOP transitions

### ISSUE THREAD

**Issue by VanTanev** [statelyai/xstate#2825]
**Description**
`state.can()` returns `false` for transitions that are valid, but do not change the state.

```ts
import { createMachine } from "xstate";

createMachine({
  initial: 'initial',
  states: {
    initial: {
      on: {
        NOOP: {}
      }
    },
  },
});

state.can('NOOP') // false
```

**Workaround**
Adding an empty action to the event makes this work:

```ts
import { createMachine } from "xstate";

createMachine({
  initial: 'initial',
  states: {
    initial: {
      on: {
        NOOP: {
          actions: () => {}
        }
      }
    },
  },
});

state.can('NOOP') // true
```

**Comment by Andarist** [comment]
This is kinda on purpose - only if the transition results in some kind of a change then it's considered as "allowed". This IMHO matches a pattern described somewhere in the docs:
```js
createMachine({
    initial: 'a'
    states: {
        a: {
            on: {
                NEXT: 'b'
            }
        },
        b: {
            on: {
                // forbidden transition
                FOO: undefined
            }
        },
    },
    on: {
        FOO: {
            actions: 'doSmth'
        }
    }
})
```

in this situation IMHO it's completely OK to return `false` for this "forbidden" transition. And this is basically what your snippet implements, just using a different syntax.

**Comment by VanTanev** [comment]
I think that your and my example are fundamentally different in the intent of the code.

In your example, it definitely makes some sense that FOO is forbidden as it overwrites an existing transition. I would argue the definition is very vague, an explicit definition would definitely be better, something like:

```ts
            on: {
                // forbidden transition
                FOO: {
                  allowed: false
                }
            }
```

Also notice, in your case you used `undefined` for the value of a forbidden transition, which at least kind of communicates that something special is happening. In my example, I use an empty object, so I would expect that it just means "This is an event that does nothing, but it is allowed in this state."

In my actual use case, I would argue it's even more reasonable that `state.can()` should work:

```ts
import { createMachine } from "xstate";

createMachine({
  initial: 'initial',
  states: {
    initial: {
      on: {
        NOOP: {
          cond: 'someGuard'
        }
      }
    },
  },
});
```
This is way different from an `NOOP: undefined` transition, and `state.can('NOOP')` can give a meaningful answer depending of in the guard condition is fulfilled.

**Comment by Andarist** [comment]
I see how you can see this differently but if we stick to the basic XState syntax for defining transitions:
```js
on: { NEXT: 'state' }
```
is just a sugar over
```js
on: {
  NEXT: {
    target: 'state'
  }
}
```
and because we can use targetless transitions this way:
```js
on: {
  NEXT: {
    // no target, implicitly it's undefined
    actions: 'foo'
  }
}
```
we can come to a conlusion that both:
```js
on: { NEXT: undefined }
```
and
```js
on: {
  NEXT: {}
}
```
are just sugar syntaxes for:
```js
on: {
  NEXT: {
    target: undefined
  }
}
```

The only thing that happens internally is this:
```js
const hasTarget = !!normalize(transition).target
```

But I feel that this is kinda irrelevant anyway, just showing how this can be looked at in a way that matches the implementation. I don't quite see **why** this matters to you because I don't see any use case for this - even the last snippet that you have shared here doesn't make much sense to me: a guarded transition with no actions and no target is looking invalid to me (or rather - pointless).

`state.can` is not meant as an util to query "is this event accepted by a machine" but rather "does sending this event to a machine results in a change". And there is no change in response to an event in both of your snippets.

**Comment by VanTanev** [comment]
> `state.can` is not meant as an util to query "is this event accepted by a machine" but rather "does sending this event to a machine results in a change". And there is no change in response to an event in both of your snippets.

In that case, the naming is unfortunate, because to me it reads as "Can the current state execute this event." By comparison, in xstate-helpers I named the same functionality very clunky `useIsXStateTransitionAvailable()`, but I think that is a much more accurate description of what the functionality is - "is a transition available from the current state given this event".

> I don't quite see why this matters to you because I don't see any use case for this - even the last snippet that you have shared here doesn't make much sense to me: a guarded transition with no actions and no target is looking invalid to me (or rather - pointless).

You are correct that the use case is not immediately obvious, and in real code, it's somewhat convoluted. Basically, I have a parent machine that holds extra state + a child with its own state that need to be synchronized.

However, the parent must always go A -> [EVENT] -> B [invoke] -> C, while the child can go to A' -> [EVENT] -> C', or C' -> [EVENT] -> C'.

Also, the child is an FSM, doesn't run in an interpreter, and can start from any state. It's running in the backend, and it writes out its state with each transition to the database.

With that in mind, I needed a way to sort of say: If I start the child with this state, is it valid for it to run [EVENT]? If so, it's valid for the parent as well.

Ultimately, this was done because I wanted to concentrate the logic about what is allowed to happen inside XState. I could also pull this guard on the NOOP event into its own function, but this seemed like a better way. But, then I hit this snag.

I really do think that the current behavior is not intuitive. Even if we can't change it for V4, I would argue at least the explicit way to disable transitions on events should be considered for V5. And, I do think an event that only has a guard makes some sense - it might be pointless inside a singular machine, but have use as part of a broader system.

**Comment by Andarist** [comment]
Could you showcase this use case in code? It's quite to see build a proper mental model for this, only based on the description.

**Comment by VanTanev** [comment]
Extracting the full context is super lenghty. I'll try to do a light version here, that hopefully captures the important points.

```ts
// this is a backend state machine that runs as a FSM with no interpreter
type Workflow = {
  state: string // one of the states of the machine below
}
type Event = 
 | { type: 'START_TAGGING' } 
 | { type: 'CONTINUE_TAGGING'}  
 | { type: 'COMPLETE' }

const backendWorkflowMachine = createMachine({
  context: {
    workflow: null!
  },
  states: {
    assigned: {
      on: {
        START_TAGGING: { target: 'tagging' }
      }
    },
    tagging: {
      on: {
        // !!! THE IMPORTANT PART !!!
        CONTINUE_TAGGING: {
           // noop transition
           actions: () => {}
        },
        COMPLETE: { target: 'done' }
      }
    },
    done: {}
  },
})

class WorkflowHelper {
  transition (workflow: Workflow, event) {
    const state = backendWorkflowMachine.transition(workflow.state, event, { workflow })
    
    if (state.changed) {
      // persist the state machine change to the workflow record
      db.write({ ...workflow, state: state.value })
    }
  },
  
   // !!! THE IMPORTANT PART !!!
  can (workflow: Workflow, event: Event) {
    return !!backendWorkflowMachine.transition(workflow.state, event, { workflow }).changed
  }
}
```

Then, on the frontend there is a very complext state machine. Again, I'll try to extract the important part:

```ts

type Context = {
  resource: any // some complex type that is not important
  workflow: Workflow // workflow for this resource. An optional ref to a child machine in the real implementation
  locks: Lock[] // an array of locks that lock parts of the resource. Refs to 0-many child machines in the real implementation
}

const resourceStateMachine = createMachine<Context>({
  states: {
    idle: {
      on: {
        // !!! THE IMPORTANT PART !!!
      
        // if we can execute a START_TAGGING event on the workflow in the backend, then this transition is valid
        START_TAGGING: { 
          target: 'startWorkflow', 
          cond: ctx => WorkflowHelper.can(ctx.workflow, 'START_TAGGING')
        },
      
        // if we can execute a (noop) CONTINUE_TAGGING event on the workflow in the backend, then this transition is valid
        CONTINUE_TAGGING: {
          target: 'aquireLocks',  // but we still need to aquire locks
          cond: ctx => WorkflowHelper.can(ctx.workflow, 'CONTINUE_TAGGING ')
        },
      }
    },
    startWorkflow: {
      invoke: {
        src: () => { /* Do a network request that will transition the workflow from "assigned" to "tagging" */ },
        onDone: { target: 'aquiringLocks' }
      }
    },
    aquireLocks: {
      invoke: {
        src: () => { /* do lock aquisition over the network */ },
        onDone: { target: 'editing' }
      }
    },
    editing: {}
  }
})
```
So, in the above code, we have two options:
1) When `START_TAGGING` is valid, we do 1 extra network request to change the state of the workflow in the database, and then we aquire locks
2) When `CONTINUE_TAGGING` is valid, we skip that network request and just aquire locks

The use of 2 different events makes building the UI much easier, as we can display 2 different buttons based on eg `state.can('CONTINUE_TAGGING')`.

I know that instead of doing a check on an event, I could write:
```ts
        CONTINUE_TAGGING: {
          target: 'aquireLocks',  
          cond: ctx => ctx.workflow.state === "tagging"
        },
```

This obviously works, but I find the pattern of asking the backend workflow if it can perform a particular event that matches a frontend event to be much more readible. It keeps the full definition of what a workflow can do entirely in the machine, while in the above approach I actualy need to know which states from the backend machine are valid for a given event in the frontend.

Sorry this was so long, hopefully I managed to explain the reasoning.

**Comment by davidkpiano** [comment]
@VanTanev Thanks for the context/explanations. The use of no-op transitions on the backend machine doesn't make much sense because those transitions are not being used for their intended purpose; you're using them as "indicators" that something can be done on the frontend machine.

Another (more semantic IMO) way to do this is with tags:

```js
    tagging: {
      tags: ['canContinueWork'],
      on: {
        COMPLETE: { target: 'qaAvailable' }
      }
    },
    qaAvailable: {
      on: {
        START_WORK: { target: 'qa' }
      }
    },
    qa: {
      tags: ['canContinueWork'],
      on: {
        COMPLETE: { target: 'done' }
      }
    },
```

And then the guarded transition on the front-end machine can be refactored:
```js
        CONTINUE_WORK : {
          target: 'aquireLocks',  // but we still need to aquire locks
          cond: ctx => workflow.state.hasTag('canContinueWork')
        },
```

**Comment by VanTanev** [comment]
@davidkpiano Thanks for your thoughts. In most cases, I think tags are a very good approach to solving this!

In my particular case, `workflow.state` is `(string)State.value`, so the code would be a tad more involved, but still very doable.

With that said, I think it's safe to close this issue. Thanks to all!
