### ISSUE TITLE
Docs: Add example of using selectors to get child actors state/context

### ISSUE THREAD

**Issue by overtune** [statelyai/xstate#2826]
**Description**
It would be good to add some documentation about using "global" machines, actors and `useSelector`.
E.g. we have a global machine which uses child actors (accessible through the global machines context), and wants to select the state of the child actor.

I think it should be something like this:

```javascript
// Selectors
const selectChildActor = (current) => {
  return current.context.myChildActor;
};
const selectIsLoading = (current) => {
  return current.matches('loading');
};

// Usage
const myChildActor = useSelector(globalServices.myGlobalService, selectChildActor);
const isLoading = useSelector(myChildActor, selectIsLoading);
```

**Additional context**
Link to the discussion about this on Discord:
https://discord.com/channels/795785288994652170/809564609383890965/911204956432904252

**Comment by rlaffers** [comment]
> const isLoading = useSelector(myChildActor, selectIsLoading);

The problem with that is that if the child actor is not spawned/invoked from the very beginning, this gives an error (since `myChildActor` is initially `null`).

A more robust solution is:
```js
const selectIsLoading = (current) => {
  return current.context.myChildActor?.state?.matches?.('loading');
};
const isLoading = useSelector(globalServices.myGlobalService, selectIsLoading);
```

**Comment by overtune** [comment]
@rlaffers That makes sense. These type of problems is what shows the need for a bit more documentation/examples regarding "global" machines and actors.
But I'm not sure if any of this might change in V5 of xstate?

**Comment by davidkpiano** [comment]
This is now documented: https://stately.ai/docs/xstate-react#useselectoractorref-selector-compare-getsnapshot
