### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by hrant-nurijanyan** [statelyai/xstate#2833]
`import { createMachine } from '@xstate/fsm';` fails with error `SyntaxError: Named export 'createMachine' not found. The requested module '@xstate/fsm' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:`

I copied the super quicstart code from [your npm site](https://www.npmjs.com/package/@xstate/fsm#super-quick-start) and I expected it to work.

It fails with this error `SyntaxError: Named export 'createMachine' not found. The requested module '@xstate/fsm' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:`

Cannot reproduce in other environment

**Comment by mattpocock** [comment]
@hrant-nurijanyan Could you give us more information about your setup? What are you using/building?

Node/Vite/Create React App/Next.js?

**Comment by hrant-nurijanyan** [comment]
It's node.js clean environment, just created it with `npm init -y` for testing.

**Comment by hrant-nurijanyan** [comment]
It worked when I changed the code to this
```
import Machine from "@xstate/fsm";

const toggleMachine = Machine.createMachine({
  id: "toggle",
  initial: "inactive",
  states: {
    inactive: { on: { TOGGLE: "active" } },
    active: { on: { TOGGLE: "inactive" } },
  },
});
```

Please update your quickstart doc accordingly)

**Comment by Andarist** [comment]
Support for ESM in node has been released in a way that conflicts with the existing ecosystem. Fixing compatibility with it can only be done in a major version. We'll be doing that but it's really cumbersome to do that in the current release line without breaking one environment or another in some way.
