### ISSUE TITLE
Let ActorRef be an RxJS InteropObservable

### ISSUE THREAD

**Issue by woutermont** [statelyai/xstate#2834]
A while back we fixed the `Interpreter` so that it was recognized by RxJS as an `InteropObservable` (using interop symbols). However, when retrieving children of a machine, this does not suffice, since these children are typed as `ActorRef`. Would it be possible to have `ActorRef`, or even it's parent interface `Subscribable`, to either mandate their subclasses to contain the necessary symbols, or change them into abstract classes containing the symbols themselves?

If this is not an immediate NO, and I find some time, I can try to implement a suggestion.

**Comment by davidkpiano** [comment]
I think this is a good idea. Feel free to make a PR!
