### ISSUE TITLE
TypeScript documentation

### ISSUE THREAD

**Issue by chasm** [statelyai/xstate#2843]
### Discussed in https://github.com/statelyai/xstate/discussions/2842

<div type='discussions-op-text'>

<sup>Originally posted by **chasm** November 30, 2021</sup>

There doesn't appear to be any real TypeScript documentation despite that TypeScript is highly recommended by xState. Am I missing something? Is there a repository of excellent, detailed, and _complex_ examples in TypeScript?

For example, how do I model parallel states? Where is the truly detailed and strict TS example? Is there one?

I work in enterprise and I've been trying to introduce xState at my company since two companies ago (two years now) only to be frustrated each time because the TS is just too painful to figure out and implement.

Perhaps I'm the only dev on Earth with this problem, but I really doubt it. Would it be possible to provide _all_ the examples in TypeScript as well? Shouldn't that be the default? And can we have some real world examples, too? So many of the examples are toy apps. Few state machines, I bet, are that simple.

I'm trying to build a state machine for a _single_ form field, and it has 8 parallel states and 20 events. I can find nothing out there remotely similar, but _someone_ must be doing something similar...</div>

**Comment by davidkpiano** [comment]
The documentation is currently being renovated and we will include both JavaScript and TypeScript for each of the code examples.

**Comment by davidkpiano** [comment]
TypeScript docs: https://xstate.js.org/docs/guides/typescript.html
