### ISSUE TITLE
`respond` only work when it's in the first state that receiving the EVENT

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2861]
**Description**

When using `respond` to send events to parent/actors, the `respond` action has to be put in the state that first receives the EVENT.

If I use an `always` to transition state to another one, then the `respond` will not work as my expected (the respond-ed EVENT will be lost)

Does this behavior is expected?

**Expected Result**

The `respond` can send the EVENT to the latest valid `eventOrigin`.

if the current behavior is expected, then I'd like to ask for adding a new feature to support this.

**Actual Result**

The EVENT with `respond` is lost.

**Reproduction**

https://codesandbox.io/s/optimistic-river-epqlm?file=/src/index.ts

```ts
    selecting: {
      entry: respond("TOKEN1"),
      always: [
        {
          target: "waitingForCode",
          actions: respond("TOKEN2")
        }
      ]
    }
```

In the above transition, only "TOKEN1" will be sent successfully, but the "TOKEN2" will be lost:

![image](https://user-images.githubusercontent.com/1361891/144737976-c17ebd4b-a0e9-47aa-8505-05c61d00f347.png)

**Additional context**

According to the source code of `respond`:

https://github.com/statelyai/xstate/blob/2e126cb54f8f99ba3478774b6777ab9a8d8dd6b6/packages/core/src/actions.ts#L327-L341

I think the `eventOrigin` can be reused if the user wants.

For me, I have to write a workaround helper function named `respondLastOrigin` to fulfill my requirement:

```ts
import {
  actions,
}                 from 'xstate'

interface ContextLastOrigin {
  lastOrigin?: string,
}

const respondLastOrigin = (
  event: Parameters<typeof actions.send>[0],
) => actions.send(
  event,
  {
    to: (
      ctx: ContextLastOrigin,
    ) => ctx.lastOrigin!,
  },
)

export {
  type ContextLastOrigin,
  respondLastOrigin,
}
```

It will be great if the official `respond` can support this kind of scenario: the machine can always `respond` to the latest event origin.

**Comment by Andarist** [comment]
This is something that we’ve recently fixed on the next branch - we prepare a v5 release there. Unfortunately, it’s not possible to change the behavior in v4 - unless we’d introduce an opt-in flag for that

**Comment by huan** [comment]
Awesome, it is great to know that we have fixed it in the v5 release!

Is there any plan for publishing the v5 alpha/RC/next version for the community for now? I read a lot about the coming v5 and I'd like to try it as soon as possible.

Thank you very much!

**Comment by Andarist** [comment]
We'll think about publishing a prerelease version sometime soon.

**Comment by huan** [comment]
Thank you very much for letting me know that the ?v
5 prerelease will be published soon!

 Close this issue and looking forward to it!
