### ISSUE TITLE
Can not reuse an existing `model.events` in another `createModel()`

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2862]
**Description**

I have a child model and I want the parent model to reuse the event definitions in the child so that it will be DRY:

```ts
const child = createModel({}, {
  events: {
    C: (c: string) => ({ c }),
  },
})

const parent = createModel({}, {
  events: {
    ...child.events,
  },
})
```

**Expected Result**

The typing system should be happy.

**Actual Result**

The typing system is not happy:

```ts
    Type '(c: string) => { c: string; type: "C"; }' is not assignable to type '"An event creator can't return an object with a type property"'.ts(2322)
```

**Reproduction**

https://codesandbox.io/s/floral-rgb-bz9zr

**Comment by huan** [comment]
After investigating it turns out that it's because of the additional `type` property added by the `createModel`.

I realized the `createModel({}, { events: {} })` will act as a creator and added the `type` in the payload, which caused the returned `events` does not same as the value in args.

I think we need a way to do this, I don't know if there has already solution, but for now I write this one:

```ts
type RemoveType<T extends (...args: any[]) => {}> = (...args: Parameters<T>) => Omit<ReturnType<T>, 'type'>
```

And then:

```ts
{
    events: {
      MESSAGE: events.message as RemoveType<typeof events.message>,
    },
},
```

it's ugly but workable...

**Comment by JoshuaAmaju** [comment]
That should be considered a bad practice. Under what conditions would you want to share events? That would disrupt how you think about your state machine, making it difficult to pin down where a certain event was fired.

**Comment by huan** [comment]
@JoshuaAmaju My case is that I have lots of parent and children machines that they need not only to talk from parents to children but also I want to use the actor model to send events between them.

In this case, I want to reuse the events between them, as an internal communication standard protocol.

**Comment by Andarist** [comment]
@huan have you seen [this thread](https://github.com/statelyai/xstate/discussions/3078)? I would love to hear your thoughts on it

**Comment by huan** [comment]
@Andarist Thank you very much for showing this thread to me!

I will close this issue and continue monitoring that thread.
