### ISSUE TITLE
The `context` provided to the `expr` inside a State should be exactly the **context in this state**

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2891]
**Description**

I spent lots of hours debugging my state machine with some logic like the below transition code:

```ts
      step1: {
        entry: [
          actions.assign({
            lastSetBy: (_) => {
              spy("states.step1.entry.assign");
              return "states.step1.entry.assign";
            }
          }),
          (ctx) =>
            spy("states.step1.entry.expr context.lastSetBy:" + ctx.lastSetBy)
        ],
        always: "step2",
        exit: [
          actions.assign({
            lastSetBy: (_) => {
              spy("states.step1.exit.assign");
              return "states.step1.exit.assign";
            }
          }),
          (ctx) =>
            spy("states.step1.exit.expr context.lastSetBy:" + ctx.lastSetBy)
        ]
      },
      step2: {
        entry: [
          actions.assign({
            lastSetBy: (_) => {
              spy("states.step2.entry.assign");
              return "states.step2.entry.assign";
            }
          }),
          (ctx) =>
            spy("states.step2.entry.expr context.lastSetBy:" + ctx.lastSetBy)
        ],
     ....
```

**Expected Result**

I thought that in the states `step1`, the `context` should be set by the `entry` actions of the `step1`.

**Actual Result**

In the states `step1`, the `context` is set by the `entry` actions of the `step2`.

I got the below result, which means that in the `states.step1`, the `entry` actions expr function has been passed a `context` in states `step2`:

```
    "states.step1.entry.expr context.lastSetBy:states.step2.entry.assign"
```

**Reproduction**

https://codesandbox.io/s/xenodochial-margulis-4eky0?file=/src/index.ts

**Additional context**

After spending lots of hours debugging, I decided to write the unit test above, and learned this behavior: if the `entry`/`exit` is in a state with `always` transition, then the `context` is passed to them will not be the context in their state.

I can understand this is because we treat the transitions as a whole batch, however, I think this behavior is not natural as the users' intuition, and I'd like to suggest that it should be treated as a BUG.

## Workaround

According to this great post [Automating Spaceships with XState, @stafford Williams, Mar 22, 2021](https://staffordwilliams.com/blog/2021/03/22/automating-spaceships-with-xstate/), we can split the batched transition by changing the `always` to `after: { 0: ... }`, which can be proved in my unit test code.

## My suggestion

We should always provide the `context` to an `expr` exactly the same as its current state.

If this behavior change will introduce breaking change for the v4, then we should include this breaking change in v5, to make the state change code more intuitive and controllable.

**Comment by Andarist** [comment]
This is already fixed in v5. In v4 you can get the fixed behavior if you set `preserveActionOrder: true` at the top level of your machine

**Comment by huan** [comment]
Awesome, great to know this can be fixed with the `preserveActionOrder` option! I have run my test with it again and the order is expected now.

Is there a way to use v5 for users like me? I'd like to develop with v5 to prevent future problems like this (already fixed).

Thank you very much!

**Comment by davidkpiano** [comment]
> Is there a way to use v5 for users like me? I'd like to develop with v5 to prevent future problems like this (already fixed).

Not yet! We're working on the final tasks to release an alpha, hopefully by the end of the year.

**Comment by huan** [comment]
I hope we can complete the final tasks soon and looking forward to using the v5 alpha in 2021!

Thank you very much for working on the great XState!
