### ISSUE TITLE
Machine exit actions have been called twice

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2914]
**Description**

I have a machine with two children: one is spawn-ed and the other is invoke-ed.

They all have `entry` and `exit` actions which is a spy for testing.

**Expected Result**

after the `interpreter.stop()`, the parent and two children `exit` actions will be called once.

**Actual Result**

They have been called twice instead of once.

**Reproduction**

https://github.com/wechaty/bot5-assistant/blob/ffb902ebfa2513630a92309ce9091a28c80dbdfc/src/mailbox/xstate-child-exit-order.spec.ts#L61-L68

**Additional context**

I want to do cleanup whenever the machine (actor) has been stopped.

One more thing: I noticed that the exit order is not the same as the entry order.

- Entry order: spawn, invoke, parent
- Exit order: parent, spawn, invoke

I think the exit order should be exactly the reverse order of the entry?

**Comment by Andarist** [comment]
Have you tried with 4.27.0? This should have been just fixed there: https://github.com/statelyai/xstate/releases/tag/xstate%404.27.0

**Comment by huan** [comment]
@Andarist Thank you very much for the information!

I can confirm that this issue has been fixed by the 4.27, appreciate your fix!

**Comment by huan** [comment]
And may I ask your option for the exit order is not as same as the entry order problem?

- Entry order: spawn, invoke, parent
- Exit order: parent, spawn, invoke

I think the exit order should be exactly the reverse order of the entry, or do we have any reason that make those order like this?

**Comment by Andarist** [comment]
The exit actions order is being fixed here: https://github.com/statelyai/xstate/pull/2903

**Comment by huan** [comment]
Aha, brilliant!
