### ISSUE TITLE
simplePathPlan fails but shortestPathPlan succeeds

### ISSUE THREAD

**Issue by DavidOrchard** [statelyai/xstate#2929]
**Description**

I'd like to be able run shortest and simplest path plans but simple fails, 2/5 tests pass.

**Expected Result**

Simple plan returns 5 plans which should all pass.  Shortest does return 4 plans which do succeed.

**Actual Result**

simple plan returns 5 plans but only 2/5 pass

**Reproduction**

https://github.com/DavidOrchard/xstate-model-testing-loading/tree/simple_fails_shortest_succeeds

**Additional context**

**Comment by davidkpiano** [comment]
This is unlikely to be a bug with `@xstate/test` itself. The shortest paths will necessarily choose paths that don't include some transitions that might be causing tests to fail. I'd recommend you look at the transitions to determine if any of the test assertions are faulty.
