### ISSUE TITLE
"An unexpected error has occurred" with statecharts.io/inspect

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2931]
**Description**

https://statecharts.io/inspect?server=localhost:8888

Can show the state charts when my program has just begun, but after a while when I switch the machine in the state menu at the right panel, it shows an error message:

> An unexpected error has occurred.

with the following console log:

![image](https://user-images.githubusercontent.com/1361891/148800304-03743968-171a-4a04-8f13-d5d4889a4ad7.png)

```
Object sessionId: "x:9" type: "service.select"
[[Prototype]]: Object
ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:1866 
Object sessionId: "x:8"type: "service.select"
[[Prototype]]: Object
framework.4dd1003cc9c949c7fcd3.js:1
TypeError: t.expr is not a function
    at QkgP.e.resolveLog (ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:6794)
    at ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:5221
    at l (ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:5243)
    at Gi (framework.4dd1003cc9c949c7fcd3.js:1)
    at ko (framework.4dd1003cc9c949c7fcd3.js:1)
    at xu (framework.4dd1003cc9c949c7fcd3.js:1)
    at wu (framework.4dd1003cc9c949c7fcd3.js:1)
    at du (framework.4dd1003cc9c949c7fcd3.js:1)
    at framework.4dd1003cc9c949c7fcd3.js:1
    at t.unstable_runWithPriority (framework.4dd1003cc9c949c7fcd3.js:1)
lo @ framework.4dd1003cc9c949c7fcd3.js:1
main-3416e08504db70d9b9e9.js:1 
TypeError: t.expr is not a function
    at QkgP.e.resolveLog (ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:6794)
    at ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:5221
    at l (ffe100b7dadf7d66cb287d8c1cac5c9e636a5bca.02734d24c079fd118957.js:formatted:5243)
    at Gi (framework.4dd1003cc9c949c7fcd3.js:1)
    at ko (framework.4dd1003cc9c949c7fcd3.js:1)
    at xu (framework.4dd1003cc9c949c7fcd3.js:1)
    at wu (framework.4dd1003cc9c949c7fcd3.js:1)
    at du (framework.4dd1003cc9c949c7fcd3.js:1)
    at framework.4dd1003cc9c949c7fcd3.js:1
    at t.unstable_runWithPriority (framework.4dd1003cc9c949c7fcd3.js:1)
te @ main-3416e08504db70d9b9e9.js:1
```

The related source code is:

```js
        e.resolveLog = function(t, e, n) {
            return r(r({}, t), {
                value: c.isString(t.expr) ? t.expr : t.expr(e, n.data, {
                    _event: n
                })
            })
        }
```
**Expected Result**

The statechart does not throw an error

**Actual Result**

> An unexpected error has occurred.

**Reproduction**

I can reproduce this error with my unit test file at:

- https://github.com/wechaty/bot5-assistant/blob/cf146d180714e468ac4a1a859900772b0dfa2751/src/actors/brainstorming-actor.spec.ts#L118

**Additional context**

**Comment by Andarist** [comment]
Thank you for the repro case - I should be able to take a look at this soon.

**Comment by huan** [comment]
@Andarist I can confirm that the code that trigger this problem is at https://github.com/wechaty/bot5-assistant/blob/cf146d180714e468ac4a1a859900772b0dfa2751/src/actors/brainstorming-actor.spec.ts#L198-L200

If I add two `await new Promise(resolve => setTimeout(resolve, 15000))` before it and after it, then at the first 15s, the statechart is OK, then the statechart crash when the code executed after 15s.

**Comment by Andarist** [comment]
The given repro case was quite involved so I didn't dive into that (thank you for providing it though as repro cases are very often essential for debugging issues). Based on the given stack trace though I was able to repro this with a minimal amount of code:
https://codesandbox.io/s/loving-hill-i81kb?file=/src/App.js

The problem is somewhat known to me and goes beyond this `log` action. We could patch this temporarily within the `resolveLog` but that would be just a bandaid. I'll put that on our roadmap - to go through this problem with a more top-down approach. I will also look into updating the current inspector (https://statecharts.io/inspect) and the new one with the XState version that patches this.

**Comment by huan** [comment]
Yeah I post my repo is to make sure you can see what happens, it is a complicated one and I'm always missing myself on it, that's why I need the state chart to visualize my state machine! :^)

And great to know that we have a minimum reproducible code and know how to fix it.

Looking forward to using the fixed version, please let me know when there's any workaround I can use.

Thank you very much!

**Comment by davidkpiano** [comment]
It is now recommended to use https://stately.ai/viz - will reopen if this is still a problem there (please let me know)
