### ISSUE TITLE
Low performance in spawning thousands of machines at same time/loop.

### ISSUE THREAD

**Issue by alirezavlz** [statelyai/xstate#2938]
**Description**

Low performance in spawning thousands of machines at same time/loop.

**Expected Result**

Be able to run and spawn machines in queue or improve the performance.

**Actual Result**

**Additional context**

Hi, Thanks for this great work. Really enjoying of Xstate these days :) 

However I found some poor performance results in spawning actors in a loop which makes me sad.

Basically Imagine you are building Spotify and you have a library machine which spawns all the musics which they are machines. So each item in library is an actor and you have library machine which spawns these machines in a loop. This issue happens when you have a lot of items in your library something like above of 1K. I spent some time of the debugging my app I also made it work but I'm looking for proper solution, the code is something similar to this:

NOTE: actor is an empty machine which has no logic inside it for now. 

`library-machine.js`
```js
{
  ...res...states,
  loadLibrary: {
    invoke: {
       src() { loadData from database },
       onDone: {
          actions: ['setItems']
       }
     }
  }
}
```
`actions.js`
```js
const setItems = assign({
   items(_, { data }) {
    const items = {};
     for (let i = 0; i < data.length; i++) {
        const ref = spawn(machine(params));
        items[someId] = ref;
      }
    
      return items
    }
})
```
I could solve the issue with adding `setTimout(fn, i)` when I spawn each actor in loop. I know you cannot spawn an actor outside of  `assign()` function, So my question is, Is there any better solution? anyone had this issue before?
Also one more issue is when you have couple of functions/keys in actions in onDone, you cannot access to items data because it has a delay to be fill, so it's default value in you context.
I wish there was an ability to handle this with a queue and spawn each actor one by one.

Thanks

**Comment by Andarist** [comment]
It could be interesting to investigate a performance profile of that perf problem. Note there will always be some boundary amount of machines that you can create in a single synchronous loop - but maybe there are some things that we could do to raise that amount 😉
