### ISSUE TITLE
Error propagation from entry actions execution using interpreter 

### ISSUE THREAD

**Issue by ahamid** [statelyai/xstate#2954]
**Description**

Same as #463 but specifically for automatic entry (and presumably exit) actions which are invoked automatically by the state machine / scheduler, so cannot be caught by calling code. Is the alternative to convert all actions to explicit states with internal service calls (which can fail/be rejected, and handled via state machine definition)? That seems a bit cumbersome.

**Expected Result**
Interpreter should have a mechanism for errors to be caught / propagate outside.

**Actual Result**
Error is thrown from within interpreter and cannot be handled by state machine definition.

**Reproduction**
Slight variant of @davydof's [example](https://github.com/statelyai/xstate/issues/463#issuecomment-719180736) on #463, but executing an automatic entry action:
https://xstate.js.org/viz/?gist=cb72b4656ce8f440b2f1704b4e33a99b

Error is thrown from within interpreter/scheduler:
https://github.com/statelyai/xstate/blob/2c094d33dd8d5f5644e60c6054f1987f298f3d87/packages/core/src/interpreter.ts#L250
https://github.com/statelyai/xstate/blob/2c094d33dd8d5f5644e60c6054f1987f298f3d87/packages/core/src/scheduler.ts#L72

**Comment by Andarist** [comment]
At the moment how errors are handled in the runtime is a little bit under-specified. We are aware of the issue and we plan to address it. I've created an RFC going into more details - I would appreciate it if you could take a look at it and give feedback about those proposed changes: https://github.com/statelyai/rfcs/pull/4/files

**Comment by Andarist** [comment]
I believe that https://github.com/statelyai/xstate/pull/4145 & https://github.com/statelyai/xstate/pull/4492 addressed this issue.
