### ISSUE TITLE
[TS] issue matching on parent compound state when using TypeStates

### ISSUE THREAD

**Issue by el-dav** [statelyai/xstate#2966]
**Description**
Given a machine with a compound state where states have been modelled using TypeStates e.g
```
{
  parentState: {
    states: {
      childState1: {},
      childState2: {}
  },
  otherState: {}
}
```

When using `state.matches` you get a Typescript error when using `state.matches('parentState')`. This forces running a match on each combination of parentState and childState. This isn't an issue when not using TypeStates.

**Expected Result**
You should be able to match on just `parentState` to include all childState combinations

**Actual Result**
You get a TS Error

**Reproduction**
[codesandbox reproduction](https://codesandbox.io/s/summer-sea-0g6ls?file=/src/index.ts)
(see line 66 for TS error)

**Comment by davidkpiano** [comment]
Moving forward, we do not recommend using typestates because they are unsafe – it is possible to create an impossible typesafe. With the upcoming typegen, we will eventually be able to safely infer typestates.

**Comment by el-dav** [comment]
Interesting, is there somewhere I can hear more about the typegen plans?

I'm currently working on a library where I generate a machine via a factory function. This is partly so that my consumers could pass some types via a generic to include in the machine's Context type. Would this be supported by the typegen approach or would it only work where you have a fully formed machine with a fixed Context type?

**Comment by Andarist** [comment]
Beta support for the typegen has been just released in [xstate@4.29.0](https://github.com/statelyai/xstate/releases/tag/xstate%404.29.0). It requires our [VS Code extension](https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode).

The config argument passed to the `createMachine` has to be statically analyzable for this to work. If you only want to configure parts of the context type using factories - then it should work quite OK (but we have not tested such a scenario). Configuring the shape of actual states etc is not supported though. If you need that - I would love to learn more about your use case but I wouldn't expect to add support for this any time soon (we have higher priority items to work on at the moment).

**Comment by el-dav** [comment]
That's very exciting! I'll try it out as soon as I can.

I think the shape of the states is stable in my use case so hopefully this will work. I had considered whether I could use factories to optionally add features to a machine but it's not something I'm currently working on.

An example use-case might be if I was creating a drag and drop library, I might want to optionally include a feature in the machine which waits till a certain threshold 'distance has been moved' or 'time has been elapsed' before the drag is activated. This might be desired by some users but not by others and so you might want to tweak the machine based on a config.

I'm sure this could be achieved in other ways though e.g. include all the functionality in the machine but set the threshold to zero if the user isn't using the feature.

**Comment by Andarist** [comment]
> I think the shape of the states is stable in my use case so hopefully this will work. I had considered whether I could use factories to optionally add features to a machine but it's not something I'm currently working on.

That would technically be possible at runtime but this makes stuff like visualization much harder. So my general advice is that - just don't try to do this. I don't think there is good RoI for us supporting this kind of a thing at the tooling level.

> An example use-case might be if I was creating a drag and drop library, I might want to optionally include a feature in the machine which waits till a certain threshold 'distance has been moved' or 'time has been elapsed' before the drag is activated. This might be desired by some users but not by others and so you might want to tweak the machine based on a config.

This can still be achieved with factory parameters and guards+always transitions in the machine. 

> I'm sure this could be achieved in other ways though e.g. include all the functionality in the machine but set the threshold to zero if the user isn't using the feature.

Yeah, there are ways around that 👍
