### ISSUE TITLE
Compilation issue with xstate@4.29.0 and typescript@4.5.5

### ISSUE THREAD

**Issue by mlegait** [statelyai/xstate#2979]
**Description**
Since I've upgraded xstate to 4.29.0, my project doesn't compile anymore.

**Expected Result**
TypeScript compilation ok.

**Actual Result**
Here is the error I get:
```
node_modules/xstate/lib/types.d.ts(567,18): error TS2430: Interface 'StateMachine<TContext, TStateSchema, TEvent, TTypestate, TAction, TServiceMap, TResolvedTypesMeta>' incorrectly extends interface 'StateNode<TContext, TStateSchema, TEvent, TTypestate, TServiceMap, TResolvedTypesMeta>'.
  The types of 'withConfig(...).withContext(...).withConfig' are incompatible between these types.
    Type '(options: InternalMachineOptions<TContext, TEvent, AreAllImplementationsAssumedToBeProvided<TResolvedTypesMeta, Prop<TResolvedTypesMeta, "missingImplementations">> extends false ? MarkAllImplementationsAsProvided<...> : TResolvedTypesMeta, true, Prop<...>>, context?: TContext | ... 1 more ... | undefined) => StateMa...' is not assignable to type '(options: InternalMachineOptions<TContext, TEvent, TypegenDisabled, true, never>, context?: TContext | (() => TContext) | undefined) => StateNode<...>'.
      Types of parameters 'options' and 'options' are incompatible.
        Type 'InternalMachineOptions<TContext, TEvent, TypegenDisabled, true, never>' is not assignable to type 'InternalMachineOptions<TContext, TEvent, AreAllImplementationsAssumedToBeProvided<TResolvedTypesMeta, Prop<TResolvedTypesMeta, "missingImplementations">> extends false ? MarkAllImplementationsAsProvided<...> : TResolvedTypesMeta, true, Prop<...>>'.
          Type 'InternalMachineOptions<TContext, TEvent, TypegenDisabled, true, never>' is not assignable to type 'IsNever<Prop<Prop<AreAllImplementationsAssumedToBeProvided<TResolvedTypesMeta, Prop<TResolvedTypesMeta, "missingImplementations">> extends false ? MarkAllImplementationsAsProvided<...> : TResolvedTypesMeta, "missingImplementations">, "actions">> extends true ? {} : { ...; }'.
```

Thank you for your help :)

**Comment by mattpocock** [comment]
@mlegait Could you add a repro in a codesandbox? That will help us diagnose the issue. It looks like it's something to do with `.withConfig`, `.withContext`?

**Comment by mlegait** [comment]
@mattpocock here is a repro in codesandbox: https://codesandbox.io/s/competent-darkness-2lfu5?file=/package.json

**Comment by Andarist** [comment]
@mlegait did you save your codesandbox? it looks pretty empty to me. TS compilation issues should also be pretty easy to replicate in the TS playground itself - creating those playgrounds can often simplify the experience for **type-only** repro cases.

**Comment by rjokelai** [comment]
Hi @Andarist, try modifying src/app.ts. It's a server-side codesandbox and they behave a little differently. You need to be logged in to be able to fork the sandbox and run the server containers

**Comment by Andarist** [comment]
Please use `"skiplLibCheck": true` in your `tsconfig.json` - it will be beneficial for your compilation performance anyway.

We are aware of this incompatibility between those types (`StateMachine` & `StateNode`) but fixing it didn't seem like a worthwhile thing to do:
https://github.com/statelyai/xstate/blob/e38ee00456c81513cbbd6a91ded6868f820b8eac/packages/core/src/types.ts#L997-L998

The problem is... that our useful `@ts-ignore` comment got removed during compilation. I will recheck if we can do something easy to leave it as is in the published code

**Comment by mattpocock** [comment]
@Andarist is this `skipLibCheck: true` tip worth adding to the docs?

**Comment by Andarist** [comment]
Hm, I don't think so - this accidentally caused problems twice in a row but that's super accidental. Our code should still work without this flag so this was a legitimate bug report. 

If we want to educate people about this option - we can do that, it goes outside of XState's scope but it's also not harmful in any way.

**Comment by mlegait** [comment]
Thank you so much for your reactivity 🙏
