### ISSUE TITLE
Exception in `xstate >= 4.28.0` using actorRefs `TypeError: Cannot use 'in' operator to search for 'getSnapshot' in undefined`

### ISSUE THREAD

**Issue by rtmruczek** [statelyai/xstate#2985]
**Description**
Since `xstate@4.28.0`, my colleagues and I have seen breaking behavior with `actorRef`s. It's the same error as seen in this issue report: https://github.com/statelyai/xstate/issues/2435

The above reported issue seems to suggest that this was not an issue with xstate, however it's strange that this issue just started to manifest in  `xstate@4.28.0` and later.

**Expected Result**
We should be able to call `useActor` on an `actorRef` passed in props.

**Actual Result**
We receive the error `TypeError: Cannot use 'in' operator to search for 'getSnapshot' in undefined`

**Reproduction**

###  See reproduction here: https://codesandbox.io/s/prod-currying-bvsj4 

Notice that if you change xstate to `4.27.0`, the error is resolved.

**Additional context**

N/A

**Comment by Andarist** [comment]
This is a change introduced by [this PR](https://github.com/statelyai/xstate/pull/2864). To resolve it you can add an explicit `id` to your `invoke`.

**Comment by davidkpiano** [comment]
This was a long-standing bug that was fixed in https://github.com/statelyai/xstate/pull/2864 (issue: #464)

If you are referencing an invocation, you need to specify the ID for it:

```diff
const toggleMachine = createMachine<ToggleContext>({
  id: "toggle",
  initial: "idle",
  states: {
    idle: {
      invoke: {
+       id: "childMachine",
        src: "childMachine"
      }
    }
  }
});
```

cc. @Andarist Should we add a dev-time warning when IDs aren't specified for invocations?

**Comment by Andarist** [comment]
> cc. @Andarist Should we add a dev-time warning when IDs aren't specified for invocations?

They are not required though and often can be redundant so I would not make this a hard rule - and a dev-time warning that would be printed at all times would kinda make it such.

**Comment by rtmruczek** [comment]
Makes sense, thanks for letting us know about the fix @Andarist  and @davidkpiano .

Just my two cents because I have no idea what the original bug was - perhaps it makes sense to adjust the type and make this value required if it could potentially cause an exception if the value's not present. I understand that it's not required for most typical use cases though, so maybe we could default to using a different value (`src`?) as the id, and report a dev-time exception if there's a collision.

Feel free to close this issue since it's not an issue with the package itself. Thanks!
