### ISSUE TITLE
4.29.0 specific issue with delays within spawned child

### ISSUE THREAD

**Issue by Jimmy89** [statelyai/xstate#2990]
**Description**
I'm reporting this bug knowing that I cannot fully explain the bug, in the hope that others might be able to add information.

I found out that my jest test for a complex machine was having some endless loop when initiating a child machine directly on the context of a parent machine init. Zooming in on the problem I found out: this issue started occuring on v4.29.0, on v4.28.1 this issue is not present. Jest is NOT timing out (does not matter how small I set the timeout window), so it seems to be in an endless loop. 

What I do know: 
- This issue occurs if you have a delay present on the child machine.
- This issue only occurs if you set a machine as child through the context initialization.

**Reproduction**
Jest going haywire if I do this:
```js
const machine = formMachine(saveFormModel).withConfig({
  guards: {
    tokenFetchTryoutThresholdExceeded: mockThresholdGuard,
  },
  services: {
    runTransaction: mockService,
  },
  delays: {
    TIMEOUT_TOKEN_FETCH: 10,
  },
});

const parentMachine = createMachine({
  id: "parent",
  context: () => ({
    child: spawn(machine, "form"),
  }),
  initial: "init",
  states: { init: {} },
});
<-- Jest does not go any further that this line.
```

Jest running fine if I initialize like this:
```js
const machine = formMachine(saveFormModel).withConfig({
  guards: {
    tokenFetchTryoutThresholdExceeded: mockThresholdGuard,
  },
  services: {
    runTransaction: mockService,
  },
  delays: {
    TIMEOUT_TOKEN_FETCH: 10,
  },
});
const parentMachine = createMachine({
  id: "parent",
  context: {},
  initial: "init",
  entry: assign(() => ({
     child: spawn(machine, "form"),
  })),
  states: { init: {} },
});
```

OR also fine if I do this:

```js
const machine = formMachine(saveFormModel).withConfig({
  guards: {
    tokenFetchTryoutThresholdExceeded: mockThresholdGuard,
  },
  services: {
    runTransaction: mockService,
  },
  // delays: { <-- Commenting out delays helps. Normally TIMEOUT_TOKEN_FETCH is a function deciding which timeout in ms to provide.
  //  TIMEOUT_TOKEN_FETCH: 10,
  // },
});
const parentMachine = createMachine({
  id: "parent",
  context: {},
  initial: "init",
  entry: assign(() => ({
     child: spawn(machine, "form"),
  })),
  states: { init: {} },
});
```

I hope that the developers of the XState have a possible clue where to loop for. Posting the child machine is unfortunatly not an option.

**Additional context**

**Comment by Andarist** [comment]
That is somewhat stranger because 4.29.0 doesn't come with any particular changes that would have the potential to affect the runtime like that.

It's hard to look into this further if we don't receive a repro case for the problem. Would you be able to create one?

**Comment by Andarist** [comment]
I'm going to close this as part of cleaning up issues for housekeeping purposes. However, please don't hesitate to respond back here or in another issue - I will reopen this if you feel like the issue has not been addressed in full.
