### ISSUE TITLE
[Typescript] When using schema, context is returning any

### ISSUE THREAD

**Issue by BrunoQuaresma** [statelyai/xstate#2991]
Hey folks, I'm using the new schema prop to generate better types but looks like it is typing the context with any.

Here is the Codesandbox: https://codesandbox.io/s/floral-snowflake-dqxti?file=/TakeExamForm.tsx

<img width="1680" alt="Screen Shot 2022-01-30 at 12 46 46" src="https://user-images.githubusercontent.com/3165839/151706714-c646bb38-d613-43ac-a328-aa22a24c1c30.png">

**Comment by mattpocock** [comment]
@BrunoQuaresma Great catch!

**Comment by mattpocock** [comment]
Added a failing test here:

https://github.com/statelyai/xstate/pull/2992

**Comment by Andarist** [comment]
This got fixed by https://github.com/statelyai/xstate/pull/2992 and will go out in the very next release

**Comment by BrunoQuaresma** [comment]
Thanks!
