### ISSUE TITLE
Bug: send() with specific TContext/TEvent/TSentEvent not assignable to `on.<event>.actions`

### ISSUE THREAD

**Issue by hedgepigdaniel** [statelyai/xstate#2994]
### Description

The return type of `send<TContext, TEvent, TSentEvent>()` is `SendAction<TContext, TEvent, TSentEvent>`. As I understand, the generics have the following meaning:
 * `TContext`: the type of the context of the machine where the action is sent from
 * `TEvent`: the type of the events of the machine where the action is sent from
 * `TSentEvent`: the type of the event that is sent (possibly to a different machine than where the event is send from, as added in https://github.com/statelyai/xstate/pull/1178)

However when using `send` in the `on.<state>.actions` key, the `TEvent` type is inferred as `never`. Manually narrowing the `TEvent` type to refer to the source machine's event type results in the returned `SendAction` not being assignable to the `actions` array of the machine's transitions.

The expected type of the actions in the `actions` array is:
```typescript
export declare type Action<
  TContext,
  TEvent extends EventObject
> =
  | ActionType
  | ActionObject<TContext, TEvent>
  | ActionFunction<TContext, TEvent>;
```

but this apparently isn't satisfied by the `SendEvent` returned from `send`:
```typescript
export interface SendAction<
  TContext,
  TEvent extends EventObject,
  TSentEvent extends EventObject
> extends ActionObject<TContext, TEvent> {
    to:
      | string
      | number
      | ActorRef<any>
      | ExprWithMeta<TContext, TEvent, string | number | ActorRef<any>>
      | undefined;
    event: TSentEvent | SendExpr<TContext, TEvent, TSentEvent>;
    delay?: number | string | DelayExpr<TContext, TEvent>;
    id: string | number;
}
```

### Expected result

It should be possible to specify a type for `TEvent` compatible with a machine, and in that case the return type of `send()` should be assignable to the `actions` on that machine.

### Actual result

There is a type error:
```
Type '{ target: string; actions: SendAction<ToggleContext, ToggleEvent, { type: "LOG"; }>[]; }' is not assignable to type 'TransitionConfigOrTarget<ToggleContext, { type: "TOGGLE"; }>'.
  Types of property 'actions' are incompatible.
    Type 'SendAction<ToggleContext, ToggleEvent, { type: "LOG"; }>[]' is not assignable to type 'Actions<ToggleContext, { type: "TOGGLE"; }>'.
      Type 'SendAction<ToggleContext, ToggleEvent, { type: "LOG"; }>[]' is not assignable to type 'Action<ToggleContext, { type: "TOGGLE"; }>[]'.
        Type 'SendAction<ToggleContext, ToggleEvent, { type: "LOG"; }>' is not assignable to type 'Action<ToggleContext, { type: "TOGGLE"; }>'.
          Type 'SendAction<ToggleContext, ToggleEvent, { type: "LOG"; }>' is not assignable to type 'string'.ts(2322)
```

### Reproduction

https://codesandbox.io/s/wizardly-allen-wm619?file=/src/index.tsx

### Additional context

To explain why I'm doing this, I think it's unfortunate that https://github.com/statelyai/xstate/issues/1250 prevents `send` from being correctly typechecked, and for the common case of sending and event from a machine to itself, it should be possible to create a wrapper around `send` that restricts the type to events in the specified machine.

In the process of trying to do that, I've come across this issue, which prevents the creation of such a wrapper around `send`.

**Comment by Andarist** [comment]
The problem would go away if we'd remove this pesky contravariant property from the `ActionObject` type:
https://github.com/statelyai/xstate/blob/1bc344e74d66661f81f9385d1a0b9893ffb5b2de/packages/core/src/types.ts#L69

This is a bigger refactor that we plan to do eventually - unfortunately, I don't have any quick wins for this.

**Comment by hedgepigdaniel** [comment]
Hmm, after some experimentation I did manage to write some restricted types, that actually narrow the type of `send` and `sendParent` without any casting:

``` typescript
import type {
  DoneInvokeEvent,
  Event,
  EventObject,
  MachineConfig,
  SendAction,
  SendActionOptions,
  SendExpr,
  StateMachine,
  StateSchema,
} from 'xstate';
import { createMachine, send, sendParent } from 'xstate';

/*
 * It's very difficult to refer to the type of a `function() { ... }` in Typescript,
 * such as xstate's `send` with generics. `typeof send<{}, {}>` is a syntax error.
 * See https://stackoverflow.com/questions/50321419/typescript-returntype-of-generic-function
 *
 * To work around this, the below type definitions are written from scratch, although
 * informed by xstate's definitions for `send`/`sendParent`.
 */

/**
 * Equivalent to xstate's `send`, but restricted to send events internally within
 * the same machine.
 */
export interface SendToSelf<TContext, TAllEvents extends EventObject> {
  <
    TEvent extends TAllEvents | DoneInvokeEvent<unknown>,
    TSentEvent extends TAllEvents,
  >(
    event: Event<TSentEvent> | SendExpr<TContext, TEvent, TSentEvent>,
    options?: Omit<SendActionOptions<TContext, TEvent>, 'to'>,
  ): SendAction<TContext, TEvent, TSentEvent>;
}

/**
 * Equivalent to xstate's `sendParent`, but restricted to sending events to a
 * parent machine of a given type.
 */
export interface SendToKnownParent<
  TParentEvent extends EventObject,
  TContext,
  TAllEvents extends EventObject,
> {
  <
    TEvent extends TAllEvents | DoneInvokeEvent<unknown>,
    TSentEvent extends TParentEvent,
  >(
    event: Event<TSentEvent> | SendExpr<TContext, TEvent, TSentEvent>,
    options?: Omit<SendActionOptions<TContext, TEvent>, 'to'>,
  ): SendAction<TContext, TEvent, TSentEvent>;
}

/**
 * Wrapper around xstate's `createMachine`. Instead of accepting a `MachineConfig`,
 * it accepts a function that creates a `MachineConfig`. That function receives
 * as arguments some useful utilities, including specifically typed versions of
 * xstate's `send` and `sendParent`, aka `sendToSelf` and `sendToParent`.
 * @param makeConfig
 */
export const createMachineWithExtras = <
  TContext,
  TEvent extends EventObject,
  TParentEvent extends EventObject = never,
  TStateSchema extends StateSchema = StateSchema<any>,
>(
  makeConfig: (options: {
    sendToSelf: SendToSelf<TContext, TEvent>;
    sendToParent: SendToKnownParent<TParentEvent, TContext, TEvent>;
  }) => MachineConfig<
    TContext,
    any, // < Most likely this is my own problem...
    TEvent
  >,
): StateMachine<TContext, TStateSchema, TEvent> => {
  return createMachine(
    makeConfig({ sendToSelf: send, sendToParent: sendParent }) as MachineConfig<
      any, // Needed bacause TContext is generic. See https://github.com/statelyai/xstate/issues/3006
      any,
      TEvent
    >,
  );
};
```

Reference: https://github.com/statelyai/xstate/issues/3006

So then you can use it as follows:
```typescript
const machine = createMachineWithExtras<
  TContext,
  TEvent,
  TParentEvent
>(({ sendToParent, sendToSelf }) => ({
  id: 'MACHINE_ID',
  // ... machine config
  // use `sendToParent` instead of `sendParent`
  // use `sendToSelf` instead of `send`
});
```
`sendToSelf` and `sendToParent` only accept events compatible with the current or parent state machines respectively, and where they are used, the source/sent event types are correctly inferred along with the `context`, `event`, `meta` arguments to action functions. `event` particularly is inferred as:
 * in `on.<event>.actions`: the specific event type that triggered the action
 * in `<state>.entry`: any event accepted by the machine
 * in `invoke.onDone`: `DoneInvokeEvent<unknown>`

**Comment by hedgepigdaniel** [comment]
I think what fixed it is the distinction between `TAllEvents` and `TEvent`:
* `TAllEvents`: all the events of the machine triggering the action
* `TEvent` all the events that could have triggered this particular action.

`TEvent` is often different from `TAllEvents`:
 * in `on.<event>.actions`, it is more specific, i.e. the specific `<event>` that triggered the action
 * in `states.<state>.invoke.onDone`: It is unrelated, i.e. `DoneInvokeEvent<unknown>` (there is no event in the current machine that triggered the action).

**Comment by Andarist** [comment]
Yes, I think so - the original code snippet posted here works OK with the new improvements in the types.
