### ISSUE TITLE
Bug: Could not find a declaration file for module '@xstate/react'

### ISSUE THREAD

**Issue by RoyalHunt** [statelyai/xstate#2998]
### Description

Hi there!
I've tried to update react xstate library to the latest version. 
<img width="818" alt="Screenshot 2022-02-01 at 00 57 30" src="https://user-images.githubusercontent.com/22590130/151886874-d8d3d2f9-be3f-4b45-addb-61d3e9ad88cb.png">

But start receiving the error on the build process. 
<img width="963" alt="Screenshot 2022-01-31 at 23 33 59" src="https://user-images.githubusercontent.com/22590130/151886918-428c4545-2700-4dc3-9ff7-8706195f1756.png">

I have no idea where I need to look at to resolve the issue.

My tsconfig:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "jsx": "react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "lib",
    "paths": {
      "@loanpal/*": ["packages/*/src"]
    },
    "removeComments": false,
    "rootDir": ".",
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext",
    "types": ["node", "react"]
  },
  "exclude": [
    "./.*",
    "node_modules",
    "dist",
    "__tests__",
    "**/*.test*",
    "**/*.spec*",
    "**/*.stories*"
  ],
  "include": ["./packages/**/*.ts", "./packages/**/*.tsx", "./packages/**/*.d.ts"],
  "references": [
    {
      "path": "packages/auth"
    },
    {
      "path": "packages/core"
    },
    {
      "path": "packages/email"
    },
    {
      "path": "packages/filters"
    },
    {
      "path": "packages/form-generator"
    },
    {
      "path": "packages/layout"
    },
    {
      "path": "packages/table"
    },
    {
      "path": "packages/theme"
    },
    {
      "path": "packages/yup"
    }
  ]
}

```

### Expected result

I expected a typescript build with no errors.

### Actual result

I'm getting the error I mention abovementioned

### Reproduction

https://codesandbox.io/s/xstate-example-template-m4ckv (empty)

**Comment by Andarist** [comment]
It would help us out if you could share a runnable repro case. Alternatively, I could try to read the output of running `tsc` with [`--traceResolution`](https://www.typescriptlang.org/tsconfig/#traceResolution) but you'd have to provide one to me.

**Comment by RoyalHunt** [comment]
Hi Mateusz,
Thank you for your quick response. I've made a repo with the problem. Xstate together with tsdx falling down on the building process. The issue is in the tsdx, but could be interesting for you as well.

Repo: https://github.com/RoyalHunt/xstate-tsdx

**Comment by Andarist** [comment]
Thanks, gonna take a look at this when I get some free time to do so.

**Comment by RoyalHunt** [comment]
Thank you.

**Comment by Andarist** [comment]
One big problem with TSDX is that it will use its own TS version because it's specified as a dependency:
https://github.com/jaredpalmer/tsdx/blob/9dc28f28cf6105bfa724b2e439e074a56989d48d/package.json#L99

So this will actually try to load types for `<4.0` even though you are using `4.5.5`.

The second problem is that we forgot to add the file targeting `<4.0`:
https://github.com/statelyai/xstate/blob/7e17c41f68d3805181ebaad09118caf39847872f/packages/xstate-react/index.v3.d.ts
to the allowlist of the published files:
https://github.com/statelyai/xstate/blob/7e17c41f68d3805181ebaad09118caf39847872f/packages/xstate-react/package.json#L33-L40

We could fix the second problem... but since `@xstate/react@2` has never shipped with those types we might also refrain from doing so. In a way I think this declarationn file is:
- incorrect (because it's using different generic function signatures than the one that targets `>=4`)
- redundant (we might not need to actually support `typescript@<4`)

I think that the proper action here is to... wait. I would just observe how many issues we get about this and choose a path forward later on.

**Comment by EgorOvechkin** [comment]
I have the same issue. I want to add xstate to my react project with typescript. Should I use prev version @xstate/react@1 to avoid the problem ?

**Comment by RoyalHunt** [comment]
You have couple of options:
1. Remove tsdx - switch to any other bundler
2. Downgrade the xstate. Version ^1.x works fine.

**Comment by RoyalHunt** [comment]
> One big problem with TSDX is that it will use its own TS version because it's specified as a dependency: https://github.com/jaredpalmer/tsdx/blob/9dc28f28cf6105bfa724b2e439e074a56989d48d/package.json#L99
> 
> So this will actually try to load types for `<4.0` even though you are using `4.5.5`.
> 
> The second problem is that we forgot to add the file targeting `<4.0`: https://github.com/statelyai/xstate/blob/7e17c41f68d3805181ebaad09118caf39847872f/packages/xstate-react/index.v3.d.ts to the allowlist of the published files:
> 
> https://github.com/statelyai/xstate/blob/7e17c41f68d3805181ebaad09118caf39847872f/packages/xstate-react/package.json#L33-L40
> 
> We could fix the second problem... but since `@xstate/react@2` has never shipped with those types we might also refrain from doing so. In a way I think this declarationn file is:
> 
> * incorrect (because it's using different generic function signatures than the one that targets `>=4`)
> * redundant (we might not need to actually support `typescript@<4`)
> 
> I think that the proper action here is to... wait. I would just observe how many issues we get about this and choose a path forward later on.

Thank you for your thorough response. Before I upgraded xstate, I planned to replace a bundler. As a result, there will be a reason to do it :)

**Comment by Andarist** [comment]
@EgorOvechkin which TS version are you using? Are you also using tsdx?

**Comment by EgorOvechkin** [comment]
@Andarist sorry I missunderstood the problem. I dont use tsdx, but I use typesrcipt version 3.9.3. I think if I updtae my ts version to 4 the problem will sloved, right ?

**Comment by Andarist** [comment]
Yes, upgrading your TS version in such a situation should help you to fix this. I've rechecked with DefinitelyTyped what's their level of support for older TS versions. It seems that the official support for 3.8 ends up this month but 3.9 will be supported till May. I think it makes sense to follow their support schedule (which is: versions released in the last 2 years) - so I'll try to make a PR fixing this issue in the `@xstate/react` some time later
