### ISSUE TITLE
Bug: React useMachine state type checks stopped working in latest versions

### ISSUE THREAD

**Issue by ShaneAtJag** [statelyai/xstate#3004]
### Description

xstate@4.28.1 + @xstate/react@1.6.3
https://codesandbox.io/s/fast-wave-0vkb3?file=/src/index.tsx
![Screenshot 2022-02-02 at 08-52-06 CodeSandbox](https://user-images.githubusercontent.com/95544653/152168932-aa13e0bd-a6b7-4263-b88d-7db2f9cb7aa2.png)

xstate@4.29.0 + @xstate/react@2.0.0
https://codesandbox.io/s/red-breeze-2e9ub?file=/src/index.tsx
![Screenshot 2022-02-02 at 08-52-25 XState React TypeScript Template - CodeSandbox](https://user-images.githubusercontent.com/95544653/152169020-074ea0b1-923d-4539-a079-d90696a974f5.png)

### Expected result

xstate@4.29.0 + @xstate/react@2.0.0 should red line because the state doesn't exist.

### Actual result

xstate@4.29.0 + @xstate/react@2.0.0 doesn't red line.

### Reproduction

N/A

### Additional context

I'm not sure if I'm missing something with the new type features, but couldn't find anything to suggest it shouldn't work.

Looking forward to working with `schema` and the extension BTW!

**Comment by mattpocock** [comment]
@ShaneAtJag I think this is a bug, but it's interesting. The new typegen features are an improvement on declaring typestates, because you don't need to add the typestates - state.matches will be typesafe anyway.

We're also looking to deprecate typestates in the near future.

Not saying that this is a "won't fix", but thought this was worth pointing out.

**Comment by ShaneAtJag** [comment]
@mattpocock I understand now. That helps a lot. I extracted a machine from code using the previous versions into a new repo and couldn't figure out what went wrong.

Deprecating typestates makes sense. I love the direction you're going in.

Thank you.

**Comment by Andarist** [comment]
This has been fixed [here](https://github.com/statelyai/xstate/pull/2992) and the fix was released in `xstate@4.30.0`
