### ISSUE TITLE
XState init is being called twice

### ISSUE THREAD

**Issue by BrunoQuaresma** [statelyai/xstate#3005]
### Description

Hey folks, I noticed the machine is being initialized twice even using the `useInterpret`. Here is the example:

<img width="1354" alt="Screen Shot 2022-02-02 at 18 21 24" src="https://user-images.githubusercontent.com/3165839/152239365-a1c9f5c5-7dbb-4576-897e-4cfbc0fb05f0.png">

```
import { useInterpret, useSelector } from "@xstate/react";
import { createMachine, assign, spawn } from "xstate";
import "./styles.css";
import { uniqueId } from "lodash";

const todoMachine = createMachine({
  on: {
    MARK_AS_DONE: {},
    MOVE: {}
  }
});

const todoListMachine = createMachine(
  {
    initial: "initializing",
    context: {
      todos: []
    },
    states: {
      initializing: {
        always: {
          target: "ready",
          actions: "createTodoSample"
        }
      },
      ready: {}
    }
  },
  {
    actions: {
      createTodoSample: assign({
        todos: (ctx) => {
          console.log("CREATE TODO");
          return [
            ...ctx.todos,
            spawn(todoMachine.withContext({ id: uniqueId(), text: "Get good" }))
          ];
        }
      })
    }
  }
);

const selectTodos = (state) => state.context.todos;

export default function App() {
  const todoList = useInterpret(todoListMachine, {}, (state) => {
    console.log("CHANGE: ", state);
  });
  const todos = useSelector(todoList, selectTodos);

  return (
    <ul>
      {todos.map((t) => (
        <li key={t.id}>{t.text}</li>
      ))}
    </ul>
  );
}

```

### Expected result

Not being initialized twice.

### Actual result

It is being called twice.

### Reproduction

https://codesandbox.io/s/headless-waterfall-n3rz4?file=/src/App.js

### Additional context

Maybe it is related to this issue: https://github.com/statelyai/xstate/issues/1211 but looks like it was closed as "done". 

Versions:
"xstate": "^4.29.0"
"@xstate/react": "^2.0.0"
"react": "17.0.2"
"next": "12.0.9"

**Comment by davidkpiano** [comment]
This is expected behavior; the initial state needs to be determined before interpreting (starting) the machine, so the `assign` action is evaluated. Then, when the machine is started, it is evaluated again, because it might change; and in this case it does, since `spawn` now needs to know which actor is doing the spawning (the parent).

**Comment by BrunoQuaresma** [comment]
I'm just receiving an SSR warning related to the component key on the client not be matching the one from the server since the ids are being generated twice, not a big deal tho. I appreciate your explanation, thanks.

**Comment by Andarist** [comment]
Note that we'll be working on improving the situation slightly in February. With the changes that I have in mind `assign` we won't be recomputing initial states twice within `@xstate/react` and thus `assign` won't be called twice in such a scenario.

> I'm just receiving an SSR warning related to the component key on the client not be matching the one from the server since the ids are being generated twice, not a big deal tho. 

This sounds like a slightly different problem though. IDs mismatch between the server and the client is a different issue than the initial state being recomputed multiple times **on the client**. I don't have a solution for this that would work for you at the moment but React 18 will bring us a new hook - `useId`. This hook should allow you to avoid such ID-based mismatches between the server and the client.

We'll also be thinking about "server snapshots" (it's something supported by the upcoming `useSyncExternalStore`) that maybe could help here as well but I'm not 100% sure yet how this will play out.

**Comment by BrunoQuaresma** [comment]
Thanks @Andarist @davidkpiano you are awesome!
