### ISSUE TITLE
Bug: embedded visualizer not working in docs

### ISSUE THREAD

**Issue by codingedgar** [statelyai/xstate#3032]
### Description

there are black boxes in the docs

### Expected result

see the content of the boxes

### Actual result

![image](https://user-images.githubusercontent.com/10213241/153212252-b739e16b-119d-41a2-bc0f-c9d575e50c57.png)

### Reproduction

https://xstate.js.org/docs/guides/events.html#api

### Additional context

i'm in Google Chrome Version 98.0.4758.80 (Official Build) (x86_64)
macOS Big Sur 11.6

**Comment by davidkpiano** [comment]
They take a couple seconds to load but they do appear:

![CleanShot 2022-02-09 at 08 53 37](https://user-images.githubusercontent.com/1093738/153214989-c59b700a-13a4-4d4a-b4fb-74bfee2c1120.png)

**Comment by codingedgar** [comment]
@davidkpiano I have like an hour with multiple tabs open and they do not load in any of them

**Comment by codingedgar** [comment]
today after refreshing a lot I could see the loader and it did load in one page

![image](https://user-images.githubusercontent.com/10213241/153215508-9e73170a-77b0-4ae7-8bec-6ffaa7e14828.png)

yesterday I tried a lot and couldn't load a single one

**Comment by strass** [comment]
I also can't see them

**Comment by davidkpiano** [comment]
Should be working now. We're also replacing the visualizer in the newer docs.

**Comment by codingedgar** [comment]
@davidkpiano seems like I have to load or reload the page and go to the block quickly for it to load.

Otherwise, if I load the page, wait a few seconds, and then scroll to the block, it never loads.

Seems there are some timeouts involved in the dev tools.
