### ISSUE TITLE
Bug: Custom Guards typescript

### ISSUE THREAD

**Issue by MatheusPires99** [statelyai/xstate#3045]
### Description

I'm developing a custom guard and I faced a weird typescript issue. So here's an example:

```js
const machine= createMachine<MachineContext, MachineEvent>(
  {
    id: "machine",
    initial: "init",
    states: {
      init: {
        on: {
          COMPLETE: [
            {
              cond: {
                type: "checkGuard",
                value: 2,
              },
              target: "complete",
            },
          ],
        },
      },
      complete: {
        type: "final",
      },
    },
  },
  {
    guards: {
      checkGuard: (context, event, { cond ) => {
        return cond.value > 0;
      },
  }
);
```

### Expected result

Should be able to access the typed values of the `cond` (in this case the `value` key).

### Actual result

When accessing the `value` on `checkGuard` I have the following typescript error:

```
Property 'value' does not exist on type 'Guard<MachineContext, MachineEvent>'.
Property 'value' does not exist on type 'GuardPredicate<MachineContext, MachineEvent>'
```

### Reproduction

[https://codesandbox.io/s/zen-cherry-25hl2?file=/src/machine.ts](https://codesandbox.io/s/zen-cherry-25hl2?file=/src/machine.ts)

**Comment by davidkpiano** [comment]
Unfortunately, this kind of type inference isn't possible yet. We'll explore how it can be implemented. Likely, you will have to specify the guard type in `schema`:

```ts
// FUTURE API
const machine = createMachine({
  schema: {
    guards: {
      checkGuard: createSchema({ value: number }), // or something similar
    }
  },
  // ...
});
```

Then this type will be able to be properly inferred throughout the machine.

**Comment by MatheusPires99** [comment]
@davidkpiano I didn't fully get it. I doing this implementation and this is what I'm getting:

`Property 'type' is missing in type '{ checkGuard: any; }' but required in type '{ [key: string]: any; type: string; }'`
`'number' only refers to a type, but is being used as a value here.`

**Comment by Andarist** [comment]
I believe that this was addressed by https://github.com/statelyai/xstate/pull/4181
