### ISSUE TITLE
Bug: [React] Delayed transitions cause each react component using useSelector to render one after another

### ISSUE THREAD

**Issue by el-dav** [statelyai/xstate#3047]
### Description

When I include a delayed transition in a machine e.g. the following:
```
const machine = createMachine({
  id: "machine",
  initial: "inactive",
  states: {
    inactive: {
      on: {
        TOGGLE: "pendingactive"
      }
    },
    pendingactive: {
      after: {
        0: "active"
      }
    },
    active: {
      on: {
        TOGGLE: "pendinginactive"
      }
    },
    pendinginactive: {
      after: {
        0: "inactive"
      }
    }
  }
});
```
I then consume this service via useSelector in a component:
```
const StatusItem = () => {
  const service = useService();
  const value = useSelector(service, (state) => JSON.stringify(state.value));
  return <div>{value}</div>;
};
```

I then create 1000 `<StatusItem />` components and send `TOGGLE` to the machine. I record what happens in the React DevTools profiler.

### Expected result

I would expect there to be a single render where all the components were updated, similar to where no delayed transitions are used e.g. if we change the delayed transition to 'always'

```
const machine = createMachine({
  id: "machine",
  initial: "inactive",
  states: {
    inactive: {
      on: {
        TOGGLE: "pendingactive"
      }
    },
    pendingactive: {
      always: {
        target: "active"
      }
    },
    active: {
      on: {
        TOGGLE: "pendinginactive"
      }
    },
    pendinginactive: {
      always: {
        target: "inactive"
      }
    }
  }
});
```
![Screenshot 2022-02-14 at 18 49 03](https://user-images.githubusercontent.com/7252227/153927303-dcf452d2-828d-4a7f-82e5-9e3980200cc1.png)

### Actual result

What I actually see is 1000 individual renders (one for each component)

![Screenshot 2022-02-14 at 18 42 34](https://user-images.githubusercontent.com/7252227/153926344-1aaed472-06bc-49e1-bf3d-4b12ac3696d2.png)

This can cause significant lag in an application.

### Reproduction

https://codesandbox.io/s/xstate-delayed-transition-useselector-bug-6y9re?file=/src/App.js:174-560

### Additional context

```
xstate: 4.30.0
@xstate/react: 2.0.0
react: 17.0.2
```

**Comment by Andarist** [comment]
At the moment React 17 doesn't batch external updates and from their perspective all of our internal subscriptions are external. Luckily this will get resolved automatically with React 18 (once you switch to the new `createRoot` API). You can read more about it here: https://github.com/reactwg/react-18/discussions/21

If this is a problem in your app - you could try this workaround for the time being:
```js
const usePatchedInterpret = (machine) => {
  const service = useInterpret(machine);
  const isAlreadyPatched = useRef(false);
  if (!isAlreadyPatched.current) {
    isAlreadyPatched.current = true;
    const originalSend = service.send;
    service.send = function (...args) {
      unstable_batchedUpdates(() => originalSend.apply(this, args));
    };
  }
  return service;
};
```

You can check it our running here: https://codesandbox.io/s/xstate-delayed-transition-useselector-bug-forked-xgswq?file=/src/App.js

**Comment by el-dav** [comment]
Many thanks for the reply and workaround! That explanation makes sense so hopefully it won't be an issue in the long run. I've tried the workaround in my app and it seems to to the job nicely.

Maybe it would be worth adding a note to the documentation around useInterpret or useSelector about this?

**Comment by Andarist** [comment]
> Maybe it would be worth adding a note to the documentation around useInterpret or useSelector about this?

Hopefully, this isn't that big of an issue for the majority of our users - and since there is an automatic fix on the horizon I would prefer not to mention that in the docs. I'm worried that this dirty patch will spread across codebases and will come back to bite us in the future 😅

**Comment by el-dav** [comment]
Fair point! :smiley:
