### ISSUE TITLE
Bug: @xstate/test `getPlanFromEvents` function tries unwanted transitions

### ISSUE THREAD

**Issue by Devessier** [statelyai/xstate#3064]
### Description

I use `getPlanFromEvents` to generate specific paths from a particular list of events for a `@xstate/test` model. Actually, it tries transitions for events not defined in the provided list, leading to errors in transitions where a payload is expected, as the payload has been defined nowhere.

### Expected result

I would expect `getPlanFromEvents` to only try transitions for defined events.

### Actual result

It tries transitions for events not defined by the user and leaves empty the payload they must bring, leading to errors.

### Reproduction

https://github.com/Devessier/xstate-test-unwanted-transition-repro/blob/main/index.js

### Additional context

In the meantime, the person who implemented this function has made a Pull Request that should solve the issue: https://github.com/statelyai/xstate/pull/3062. I tried it, and it works!

**Comment by davidkpiano** [comment]
This should be fixed in `@xstate/test@alpha`, and will only try transitions for specified events.
