### ISSUE TITLE
Bug: Root invocations should never be restarted

### ISSUE THREAD

**Issue by davidkpiano** [statelyai/xstate#3072]
### Description

See this thread: https://discord.com/channels/795785288994652170/799416943324823592/945378092552179753

### Expected result

Root invocations are started when a machine is started, and only stopped when a machine is stopped.

### Actual result

Root invocations can be restarted on external root transitions (which arguably should not be allowed).

### Reproduction

https://codesandbox.io/s/unable-to-send-event-to-child-o5h24d?file=/src/index.ts:528-891

### Additional context

Working example: https://codesandbox.io/s/unable-to-send-event-to-child-forked-e6bsn0?file=/src/index.ts:529-914

**Comment by Andarist** [comment]
We've decided that we want to implement this behavior. However, we've also decided that this is not a critical fix - one can always use an internal transition to workaround this today. Changing this now creates an unnecessary risk of breaking some existing machine configuration - as this behavior was with us for quite some time.

I'm keeping this ticket open - so we can still adjust the behavior in v5 and once that is done then this ticket will get closed.

**Comment by davidkpiano** [comment]
This is implemented in `xstate@beta`

**Comment by Andarist** [comment]
Just note that we actually allow restarting root invocations - it's just that now transitions are "internal" by default and thus one shouldn't end up accidentally restarting a root invocation. A root invocation can still be restarted in v5 with a transition using `reenter: true`
