### ISSUE TITLE
Bug: `interpreter.state.can()` always be `false` if the interpreter started with an initial state from DB

### ISSUE THREAD

**Issue by davidkpiano** [statelyai/xstate#3096]
### Discussed in https://github.com/statelyai/xstate/discussions/3094

<div type='discussions-op-text'>

<sup>Originally posted by **suerta-git** February 26, 2022</sup>
### Description

I am storing states in DB as JSON string following doc's recommendation. And restore them like:

```ts
const state = JSON.parse(jsonString)
const service = interpret(machine).start(state)
```

Then I want to use `state.can()` to test an event, but its result always be `false`

```ts
service.state.can(validEvent)  // false
```

If the interpreter started with a non-parsed state, the result is correct.

### Expected result

`true` for a valid event

### Actual result

`false`

### Reproduction

https://codesandbox.io/s/wizardly-perlman-01g01l?file=/src/index.ts

### Additional context

_No response_</div>

**Comment by davidkpiano** [comment]
@suerta-git Sorry for converting this into a discussion; it is indeed a valid issue.

**Comment by suerta-git** [comment]
@davidkpiano No worries. And please feel free to take a look on my question about "strict mode" in [the discussion](https://github.com/statelyai/xstate/discussions/3094), thanks.

**Comment by ptomask** [comment]
**Possible workaround:** I observed that as well, the guard does not get called at all. I found out, that it happens only if the guard is applied on an edge going right from the state you have just reloaded the interpreter into. After you make a transition, the situation gets fixed. It turns out that the healing transition is enough to be internal so I have temporarily come out with this (Maybe it could help you, @suerta-git) :

```ts
function createExampleMachine3() {
  return createMachine(
    {
      initial: "A",
      states: {
        A: { on: { T: "B" } },
        B: {
          entry: "enB",
          on: {
            U: { target: "C", cond: "isAllowed" },
          },
        },
        C: {},
      },
      // Added this transition on machine-level:
      on: {
        reinitGuards: { internal: true },
      },
    },
    {
      actions: {
        enB: (ctx, event) => {
          console.log("Entering B");
        },
      },
      guards: {
        isAllowed: (ctx, event) => {
          console.log("Calling isAllowed guard.");
          return true;
        },
      },
    }
  );
}

function usecase3() {
  const m1 = createExampleMachine3();
  const i1 = interpret(m1)
    .onTransition((state, event) => {
      console.log("TR1", state, event);
    })
    .start();

  i1.send("T");

  const persistedState = JSON.stringify(i1.state);

  const m2 = createExampleMachine3();
  const i2 = interpret(m2)
    .onTransition((state, event) => {
      console.log("TR2", state, event);
    })
    .start(State.create(JSON.parse(persistedState)));

  // This causes the state just loaded to re-enter and makes `state.can(...)` working again.
  // The transition is internal so it is not going to re-run your actions and invocations.
  i2.send("reinitGuards");

  console.log(i2.state.can("U"));
}

usecase3();
```
