### ISSUE TITLE
Bug: ContextFrom resolves to never with typegen enabled

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#3103]
### Description

Enabling typegen prevents `ContextFrom` from correctly resolving due to the extra generics passed in. (See attached Typescript playground reproduction)

### Expected result

Should resolve to the type of the machine context.

### Actual result

Resolves to never

### Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOAYQmOwA8YAxKCECgZRi13yNLgC+cAGYsQcAOR0Azl2wSA3ACglaOpFhwS2KMPxo4AFQCeYNAHM0xAAyIlcSQAFHMuWgD0MUxasSAXHAwUACuaMoOaABuVjDSlBjB0iTmAILIMMA00gEIAuFatGhQxBgANgCi0bTZdg4OUrLcAHQkwDD+iIHeAQ1uLcRtEoL5efYFkRAA1mjsUMgAchggPGA5ow4gwNJJxOYAkuClaMu0WJnENQhjDvgZWQGk0VD5DtJFkcDIaDWPRS9w5mCGCgABMflE-tc4CC0KUMMZwU8RvkIdV4olkux3p9vmsUVVYuiduYAOJA0GXdZwVGEhLEgAisPhlPyICwhG+nG4NWCxBhwhIaBB+S45kRkIEKmQWXg2FkeEIgrgAF4UOhuAq+GgABRXByxExmSlwDDSIzeSw2MhjaQctk5KHSwoMNYms1IaSsNAwPjmAIAIwgECOGGIgjGkoEAEplEovGZAiqqDR6EwxAAeeNoCDCQLfGCawUAPmU7ncDgAegB+OPeOCMYB0IXUZ1p1jpgBKRaTHepDCsYLgXOwhdI6bGJGERSMLdT1ock+nAH15wUp1A4EuVxPiOvN1vV4uN1uDzu90uAKyH3fLgBsSiLYyrM5TahgYweEOetYTMAAzEmDZNiCs5vsw7ZZjmebyrwxaluWcDVj+BgwAALEmkG5nKBawaQADaEhOqmEgALrwZWVZAA

### Additional context

xstate 4.30.3

**Comment by Andarist** [comment]
@SimeonC I'm working on a fix and the PR should be up soon. However, I can't reproduce the issue with `MachineOptionsFrom`. Could you create a separate issue with a repro case for that one?

**Comment by SimeonC** [comment]
The `MachineOptionsFrom` error I got resolves down to `Type 'undefined' is not assignable to type 'MakeKeysRequired<any>'.` which is in #

**Comment by Andarist** [comment]
@SimeonC I'm still unsure if I understand the issue in full - could you share a repro case that I could inspect?

**Comment by SimeonC** [comment]
@Andarist Managed to reduce it down to just the typegen, the rest of the machine seems to be rather irrelevant as it doesn't change the type error but the full machine spec is the same as in https://github.com/statelyai/xstate/issues/3102 if you need it.

[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOPQktAeTBmAmIGcAxKCEOAXzgDNO3AOQAPFjCxphAbgBQcgPSK4AFSIsBwADZo4AdwyaMAVxhcswZBm3aAnnADmaUlCkATAHRwAou+Awmvo62nAARnoQAG5oUPpQAdjECmiikLBwJNhQ-Ph6qnZgaM7EAAyIcnBwwgACNeKS2IowhcUuwgBccDBQJmjyVWgxxIEAwqYsJI4AgsiMzCxdCJVVcOgg0XQMTMRdwgBKPji0AGo+wnAAPtUA0j4AmgD6h8dnsitVLC7uowQYxM49i9TucrrcHs8jiCLtdhO9Vms0PwIMgTItwU9gW8BqsSAEcHiQCYQPR5qw9vDVi4WCZ0CdgLATDYAJLEMBmClg4QAIQAMgBVfYw6qjAAS0wAcgBxc44wasWloNgotFodzM9x7Ni0Ub8gDKlKqyNRLH5YD2dye-IACoaBCqWAARCD6XYYx6O2gAdQldtSAXpjJZbI51T5grtJjA7ikpJ2ezFkpldvWm0DMCZ2lZ7JgCfF0tlHzgXxg6cz2dDwkTBbtyF0GCgZeDObzScLCLrmCgypNao1nNh4aFOJ4OKysWINh8w0CSyLcKW3VanNH84aUk8eJgnUQS6Ke3X2E3xACF1XVXPmWIUQgAGs0HqoMgJRgQLgMObEJeQMAWJMAcy4C6G+IyWAsc4IvgZLosIXzED8fwAtIcrFrEURWGg6KkDEUAoY4TJQO4WFDLEKHuGg2gYHYxE4SOOIkSMLDjGiUx6mhGHoggl4MWMExTFKBFERBqyOOgUhQOo-wEieRIgECUJvFylqQq87YiWJ2SScQPgAI6ZngoigMSFIobof5adJRlydUdq-ryRgwHGzBajq+q2SwTbaE5brCNquoGihv4+OALStjWdErDxTF8QCjoUVRnHflghCYXqjSYR0RawluwhZdU6ASLlCKwugxpokVqywmVXzuBVVRVQ6aqeOhQbaHVXLVU1xDQCANjtQ1vbuPZhV5UgnXuAA-HsLUZn1XLdVAvVtbwOKSI4NGkXIPApGk0DwMgCzwBA2zMGwwAUURVBEKQcAALwrIoABUj1wPUEhSAAtJRdgQGYcASgALMyjhgI4ABSjgAKwgJ6zKjJDACKoq3tMtDTAAGtM2jOPoor3NMzLTKIqg4NMUr6NjjpgBK7gSqU3LAPs-InGEXq0MQ6NgyjjqlAjPgA9MUDTD4ABaNzTFEjhSvjADsbDMtyLD8NM3IAF7ANMvLTNM9wi2TBAq9a-DAGD6MAGwnAjdh6lEorAAAjDgADUCNsAAnLyIAwGwABWog+HqkM3I4ozIADjoIywjiOqM0yW46Nzo6M4hu2AojMta1qq6MEAELyeq3sQNw3DpBBuMA3JhHYWY6SACM+2DIDB9yOA4D7zKQ-bUD3Pcood7ebBg-sJhk2E+M4PjUBQDzxBQAD3L3PyopfGwdgAByjLperMhAvLAPX2jAHqjjo3YCOODcGC0I4Pt2LQYv8tyED3HYNxRMydi3u-vyqPcjjuDpdGPhIaW3to6MIowEbaBVsSUYMsIBuwRqMKUYBrQI2mOfaYdhrSOG5MHKi7gIAYGmIgnSMAbgSjBlYfYdhkAI0hqKMGjpmSqFUPsbkUobh6i1voSG+wChoH2DcE4Upt46Rlj4CAaMZa0D1D7UU+wwDED1DLdGtAAbWl5PoaYkDpiOBmJDaYjoNZsDYNaFgPhaASntj4RWTsh4N1GGDWgzCTijFvPoggNwEHTBFjgMh9sGCiAZm7RgxBuQnDXvgZkQ9nwnxVhESG1oTgA34O4MA-AfDMijvyHSeo9TTFVvcPU-IfBrwgPsNeIARaQNUCwKIBAABMBB6HWh9pDUY+xHA6ROH-RwAMTAnHttMJuICdI+3RreM2ZRRDEH4PwE4qs2AlOQKoWOSDeRgxuNaAgMpVbn35LnEWvJmSiDXnqBGeowZ6goaUAg-iAZOy9AjYo0wMCqDAMLUo0xrQQCdtrG4zIwj23uPsM2GAADMIszZ2B8BgUo-IPJ2FUCYVQbAwC3n0FEUoPsYA4H4AURpjSbhO2QG7fYjS3ajBgLyNgqAVZsBRtye2NxiD22hhKYJUAA60GANbG4YQ14fTNvsMGYtRaq34LyZgYQ5GNLsLQ5RjprRejNvobkBBtB6Xtvbdweq0Cq32Hqc6Eo3Y+F9rQVQjocAgB8PobBownaOFEBAIhwApTaHuGwGWJhHBenRjpCFBs3Zmzaace4vIaRhABh9WgPgWB2BlmABG+wmDv1RVKa0t59gN2zRANgOlRT6FKaMR0IBSi+yiCwdlAMvLuA0Y4fQjh4WODvmAHAJgnZRH0GEW8EA0AEFoNoKUtAhFHB8NbR0t47Ai0dCYfYzIbj8n4FKKUohC0gDdlKPuohRjywRvoXkqsogaqdjpUYoxmT6FOaKCdBAdI2pAPcSGUpbxgB9nqe4ZtR3uCgPsEAvJcVoDdtyW2BTRgKu1lKFEyB9BRigH7WOdgCY6VUKIKIxDdlQFGO+sGYARbIDsDaV8GAICOBiU0sANwcBSkafcZANwpQnChqrbQJgRZgFFJDbkj9xm3hjGvH2bsRkcC9I6BNEAkYY1GOjcJJxpilFFAjEA6M1TaA+mDQxHcpSMAwGDCANxVBcLY8yJ2btenIBwMO-kUocARLXqoEAdh2nMlvDgODOkOO7KmdUmAxBXQnHRjAEFjo7BsrQcclp2hGnYtyFaqUANdloGZDLMGvJzX3G0Na+49ttAnH2LQT+TsCDIBOPoCF1pkBSlKGEEwzIdII2o2DD69DF3MlKKnZkUpVa3kc2gZTvIpR2AhYFn4VHgA6TNjpW8ow3YJpAGDBGUQB5SjdgSMj-IIUdamWDbQvIc5RDNjnDAeoCCOBlu4fY9wkbiYRjAEWdgOCED3TpL0PtRhrzSMAYuogoCKz0abfY6MvSMsMvGr0qgwalGQMAe4JwJQ3zRVAUU-BGkmBwMQYgUz-ZuzQMgWgBB+B2GZGwXk3JRhRBAMgBb9x9AXpONoA20w4CPUUCsVAmBsBXRoAACiLMsBEVRAgFCKIlOARg1CtBKKUMgRZtpVAAJTyDkAdVgR0TrkkoPga6WxoIcC4AAHhaEUCA-A4DHTJGdC6LBuekAAHx3S-DiC3OwrfaEutrmgnhggwAIDnOZwBHA85dwsBXcggA)

**Comment by Andarist** [comment]
In this case, `withConfig` expects every implementation to be provided - but `MachineOptionsFrom` by default doesn't enforce that. You can pass a second type param (`true`) to the `MachineOptionsFrom` to make this work but, of course, then you need to assign a valid value to your variable with this declared type (which makes sense, as this matches the current reality - all implementations have to be provided)

[TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOPQktAeTBmAmIGcAxKCEOAXzgDNO3AOQAPFjCxphcAPSy4MAJ5g0LAFxwALADoAzAAYdAJgDcAKHPy4AFSIsBwADZo4AdwwOMAVxhcswMgYTk5KcADmaKRQUgAmOnAAorHAMA5uzk5wAEauEABuaFBuUKnYxJZoopCwcCTYUPz4rjYqaJHEBojmcHDCAAL94pLYssqqHcKaMFDeaBa9aIXEaQDCPiwk4QCCyIzMGt29veggBXQMTMSawgBKiTi0AGqJMgA+fQDSiQCaAPr3R4vYQLY4sKKxVYEDDESI3QHPV5wD7Cb7-BHA5F9EE9Y7ofgQZDeQ6o34Ah6InHHOrEVI4Eigbwgej7Vg3KnHKIsbzoJ7AWDeYIASWIYF87KxwgAQgAZACqt3efVWAAltgA5ADir1Bi1YPLQbEJxLQsSFsRubFoqzlAGUOb0CUSWHKwDc0X85QAFB0CY0sAAiEDc1y+ZIDtAA6urfVVUnyBcLReK+rKFb7vGBYlIWVcbqqNdrfadzgmYIKnCKxTB82qtTrcb1wTAyxWqynhAX677kC4MFBW0nq7XCw3qb3MFAjc7TeaJSi04rQTxQfUisRgollmlNAhG9jd4o2hKV-uxBIpDoGTApogj6obsNL9eZKfem+afkIABrNC2qDIOqGAgLgGBuogH4gMALCbLCQrgC4IErAEBy7vu+CsiS4LEJC0KwtIupwOCUD5IEaiaKQhRQIR4SClAsSHJRRSEbEaBOBgSiMUszG4h+3ErCw6zElstpFKRyDkRBoL8WsGxbJqdEMWh1LhOgUhQHYML0rSIBMvCFKYiiHoYmOxyqZgDSacQiQAI4VngoiMiA7KES4MFWdpTkufu0Eyp4MC5swlrWnavrQYOTiBaGwhWja9qEdBiTgMoI7dsu0nboJcmwgGbEcYcCCQVghBqLaIzkfuKIvpVfToBIwg1cI+L+g11Iok6JqxK1xztf6po6KRiZON1vS9TO8TENAIDBCNkodeCsR+fVNVIPNpoAPw3IN5YzZKk1QNNw28KCkjhFxVEWDwlTVNA8DIAc8AQJczBsMAbEMVQRCkHAAC8uKyAAVADcBDBe2AALTsUoEC+HA6paEK4RgOEABS4QAKwgBGQqrOjACKKrftstDbAAGtsTiRG4Ko-NsQrbKINg4NsmpuJTAZgOqsTqgYUrALccpPNkka0MQpMo0TAYGHjiRaNsUDbIkABanzbPk4SarTADsbBClKLD8NsUoAF7ANsMrbNsPxKyzBBG16-DACjpMAGxPHjSi2vkKrAAAjDgADUeNsAAnDKIAwGwABWoiJLa6OfOEqzIFoAZ4yw4QBqs2zuwGnyk6s4gh2AohCl6XrG6sEAEDKtrfsQnyfDZBAxMAUrZEolY2SAeNRyjICJ1KOA4FHQro77UA-D8Kpj9+bAo7c3gs9ktM4LTUBQFLxBQFoUo-HKKrgmwSgAByrLZtpChAMrAL3TjALa4Sk0oePhJ8GC0OEUdKLQKtylKEAfhKE+PkIUShvygKhDYH44RYg2VJokdG7tfYBmyKsPGTgjZMlWFrCAIc8arE1GAL0eNtiv22EoL04QpSJw4rECAGBtj4JsjAT46oUaBFuEoZAeN0YqhRgGIUNgbC3ClJqT4toLZuHRrcVoaBbifCeJqS+NktaJAgCTLWtBbRRxVLcMAxBbRa1JrQLQXoZRuG2Og7Y4Qdjo22AGM2bA2BehYIkWg6pfaJH1gHBefdVgo1oIIp4qxvy2IIJ8PB2wlY4BYb7Bgog+Yh0YMQKUTwT74CFAvQCT8ja5HRl6J4Wh+CxDAPwRIQoM5yhsraW02xjY-FtHKRIJ8IC3BPiAJW6CbAsHyAQYwBBeFeijujVYtxwg2SeDA8IWhvBPF9tsAeSCbJR1Jt+F2nRRDEH4PwJ4xs2BNOQDYbOBCZQo0+F6Ag2pjavzlNXJWMohSiBPraPGtoUa2jYQYAgsStAB0jHjdo2wMA2DAIrAw2wvQQADpbT4Qpsi+x+LcF2GA9BKxdkoRIGADByhYE8JQNhvA2DYGAb8bh8gGCjjAHA-BWjGGMJ8AOyAQ63GMCHVYMAZRsFQEbNgRMpS+0+MQX2mN1SJKgHHWgwBPafGyCfcGLtbgoxVsrY2-AZTMGyDo4wShuGGIDF6SMLs3BSgIE4OyvtfaxGtWgY2txbRvXVCHRI0daA2ADDgEAiQ3CUNWAHcIogIAMOAJqJwPw2Ba28OESMpMbJ6DtiHF2wzng-BlNybIWhwa0ESCwJQWswB41uEwUBRLNRem-LcPuFaIBsBsiqNwzTVgBhAAYaO+QWAiq0JFWIZjwhuHCNi8IP8wA4G8AHfIbhsjfggGgAgtAnCaloAoh4iRPYBm-EoJWAZvC3CFJ8OU-BNSalEHWkAIdNQz1EKsXWeM3AymNvkU1AcbKrFWEKNwTyVSroIDZT1IAfjo01N+MAUdbQ-Bdku2IUBbggBlFStAIcpTezqasXVltNSEmQG4TMUAY7ZyUHTGyNhRD5EYVcqAqwQMozAErZAShvTAQwBAcIWT+lgE+DgTUxgfjIE+JqJ4GNjZOG8ErMAKp0ZSn-is782YT5RxDosjgkYAy5ogATMmqxSapKeNsAwKo8YgFJqaJw4MUb2LHpqRgGAUYQE+DYCRwmhQBxDlM5AOAF1yk1DgNJJ8bAgCUCMoU34cDYZsqJq56zOkwGICGJ4pMYCIoDEoYVJCHmDKcMYClTR3Wai0FctAQotYoxlC6n4TgPU-F9k4J4txaDgIDgQZATw3B6C9MgTUBhsjeCFDZPGHGUbg14XuoUBhi5Ck1Mbb8fm0AGZlJqJQeg4uQnY8AGyLsbLflWCHXNIAUZ43yHPTUId6TMblIYEO6yUZOBlFXfILsq4YFtAQcIWtYi3B+ATFTeMYBKyUBwQg16bKRijqsE+1RgCN1EFAfWNjna3FJpGPljkc2RhsCjAwyBgA-CeOqL+xKoAqn4MYbwOBiDEHWbHEOaBkC0AIPwJQQo2AyilKsfIIBkC7Z+G4V9TwnB222HAAGshcSoAsqBagpAAAU+49zUl6GkVoqgCp8E8LYNoHQDBkH3FdXoABKCw5h7qsEes9NklB8BfQuJhDgXAAA84w0AQH4HAJ6rJXrvRYJ9GgFAZhzAAHy-QgnAVXMIlCgnMK7q47unAfQtzQHQGQYAECrts4A4RJeR4OLr8wQA)

**Comment by SimeonC** [comment]
Ahhh, thanks, didn't know about the `true` argument, that should solve my issue thanks! ✨
