### ISSUE TITLE
Bug: Delayed transitions stop working after state restoration.

### ISSUE THREAD

**Issue by ptomask** [statelyai/xstate#3110]
### Description

When I reload the interpreter with a state, delayed transitions are no longer working.

It turns out that the machine instance gets modified / initialized when the interpreter starts (delayed transitions are transformed to entry / exit actions), but that does not hapen when it starts with the state argument.

Workaround so far is to call `machine._init()` which initializes the entry and exit actions.

### Expected result

After the interpreter was initialized to some arbitrary state, the delayed transitions should work as they do in normal conditions (started from initial state).

### Actual result

The delayed transitions are ignored when the interpreter was started

### Reproduction

dsfds

**Comment by ptomask** [comment]
Sorry for the duplication, I obviously accidentally hit Enter on the Submit button while editing the issue. @davidkpiano Issue #3110 is just half-filled by mistake, #3111 is the fully filled in bugreport with reproduction, maybe you should close #3110 and reopen #3111 ?

**Comment by davidkpiano** [comment]
Duplicate #3111
