### ISSUE TITLE
Bug: specific event types not inferred in `assign` action with typegen

### ISSUE THREAD

**Issue by rossng** [statelyai/xstate#3120]
### Description

I am trying to write a machine that uses the `assign` action to save data from an event into the machine's context. Typegen allows imperative actions to have a correctly-typed event, but this does not seem to be the case for `assign` actions.

### Expected result

I expect the specific event type to be inferred inside the `assign` action options.

### Actual result

The event is simply inferred as an `EventObject`.

### Reproduction

https://codesandbox.io/s/xstate-typegen-assign-repro-z2dk5u?file=/src/index.ts

### Additional context

Perhaps the `assign` action needs to be defined inside the second argument to `createMachine` somehow? I don't see any documentation about how to do this, though.

**Comment by mattpocock** [comment]
> Perhaps the `assign` action needs to be defined inside the second argument to createMachine somehow? I don't see any documentation about how to do this, though.

You should use a named action for typegen to properly work.

**Comment by mattpocock** [comment]
https://codesandbox.io/s/xstate-typegen-assign-repro-forked-2fsg39?file=/src/index.ts

**Comment by rossng** [comment]
Thanks - I understand now.
