### ISSUE TITLE
Bug: Typescript issue `assign` with function and static value

### ISSUE THREAD

**Issue by bartenra** [statelyai/xstate#3151]
### Description

Say we have this context signature:

```ts
interface ToggleContext {
  count: number;
  skip: boolean;
}
```
Then this works

```ts
entry: assign({
  count: (context) => context.count + 1,
  skip: (context) => true
}),
```

but this doesn't

```ts
entry: assign({
  count: (context) => context.count + 1,
  skip: true
}),
```

### Expected result

I expect it to work like the docs: https://xstate.js.org/docs/guides/context.html#assign-action

Without Typescript issues.

### Actual result

`count` know has type `unknown`. So Typescript complains.

### Reproduction

https://codesandbox.io/s/zealous-hopper-gncn3e

**Comment by Andarist** [comment]
I plan to make some significant changes to how built-in action factories are currently typed and **maybe** this will help this case. The main goal of the planned refactor is to improve inference of the those action factories nested within `createMachine` call but I'm not yet sure if supporting "mixed" variant for `assign` will be possible.

**Comment by johtso** [comment]
I stumbled upon what I think is the same issue here: https://github.com/statelyai/xstate/issues/3267

It doesn't even seem to be an issue with mixing static and dynamic assignment values.. it seems to be an issue with assigning static values full stop.

https://stately.ai/viz/da4f046e-b98b-467b-9ff0-18aaf3a8274d

What is the workaround here?

**Comment by Andarist** [comment]
It's likely that this would get fixed if we'd wrap `TContext` occurrences on [this line](https://github.com/statelyai/xstate/blob/3bb4a00e7e4eb66a3fabfc20e811bbadfa8eb7a4/packages/core/src/actions.ts#L467) with `LowInfer` (or `NoInfer` but that would prevent inference here altogether and we don't exactly want that)
