### ISSUE TITLE
Bug: useActor on spawned actor does not sync with component  [@xstate/vue]

### ISSUE THREAD

**Issue by jamus** [statelyai/xstate#3169]
### Description

Using `useActor` in a child component does not sync with the changing state of a spawned actor as I would have expected from the doc description.

### Expected result

`useActor` subscribes to emitted changes from an existing actor as suggested from the docs - https://xstate.js.org/docs/packages/xstate-vue/#api

### Actual result

Instead it only shows the intial state of the actor.

However, if there is a change to the component that triggers a re-render (which Im assuming triggers the reactivity) syncing begins working as expected.

### Reproduction

https://codesandbox.io/s/xstate-vue-3-useactor-issue-forked-37bfl7

### Additional context

I'm new to Vue3 and spawning actors and also struggled to find a common convention / example, so it could be I'm missing something with my implimentation or expectation of `useActor`.

**A work-around seems to be** to use a `key` on the containing element that is the changing state - to activate a re-render. E.g. `:key="state.context.todos[0].ref"`

**Comment by Andarist** [comment]
As described [here](https://vuejs.org/api/composition-api-setup.html#accessing-props) you need to wrap the argument with `toRef` (or similar). Take a look at [the fixed codesandbox](https://codesandbox.io/s/xstate-vue-3-useactor-issue-forked-mrl6k4?file=/src/ChildComponent.vue:570-637) where I use this:
```js
const { state, send } = useActor(toRef(props, "someSpawnedActor"));
```

This is somewhat annoying though, so I wonder if the API of `useActor` should look differently to accommodate for this use case better. I'm not sure what are the established conventions in the Vue world though. 

cc @ChrisShank @santicros

**Comment by jamus** [comment]
Thank you @Andarist ! I Think that makes sense to rely on Vue to watch for changes I guess I was just mislead a little by the wording "subscribes to emitted changes from an existing". Perhaps "provides access to" woudl be better. With an added "Use in combination with `toRef` if subscription to changes from the actor are required"

**Comment by Andarist** [comment]
Could you propose a documentation change around this in a form of PR?

**Comment by santicros** [comment]
Hey guys,
You did a great debugging here!

Your solution is great @Andarist, tough I would recommend to better use `computed`, because `toRef` makes it a regular `ref`, which can then be mutated,... So [like this](https://codesandbox.io/s/xstate-vue-3-useactor-issue-computed-c30ykz):
```js
const { state, send } = useActor(computed(() => props.someSpawnedActor));
```

As far as I know, this is always needed in Vue when passing a reactive prop from the parent to a child component, and then passing that to a function param, so to make it not lose reactivity. So I agree this should indeed be documented on the XState docs.

**Comment by jamus** [comment]
How is this?
https://github.com/statelyai/xstate/pull/3173
