### ISSUE TITLE
Footgun: `forwardTo` causes infinite loop when you pass `undefined`

### ISSUE THREAD

**Issue by Silverwolf90** [statelyai/xstate#3177]
### Description

So I ran into this issue earlier this week, we had a bug where are servers were totally locking up and ultimately the culprit was code like the following:

```
forwardTo((context, event) => context.refs.get(event.id))
```

When the `event.id` was incorrect, then `context.refs.get(event.id)` returned `undefined` which then forwards the event to the machine's self, which forwards the event to the machine's self, which forwards the event to the machine's self, etc  😅

This feels like quite the footgun -- I'm surprised I haven't run into this issue sooner! We fixed it by passing through actor ids instead of an entire actor reference, so now we're properly getting the "Cannot send to child ...." error when the actor doesn't exist.

### Expected result

Not really sure. Maybe `forwardTo` should throw an error when it recieves `undefined`?  Is there a good usecase for it?

### Actual result

Infinite loop. Locks up the process.

### Reproduction

None

**Comment by Andarist** [comment]
Could you prepare a repro case for this? I understand that the issue should be trivial to reproduce but a proper repro case always help the maintainers to get straight to the problem.
