### ISSUE TITLE
`interpret`, `useInterpret` etc should return an Actor

### ISSUE THREAD

**Issue by mattpocock** [statelyai/xstate#3192]
### Description

Writing the v5 docs, and it's making me think that `interpret` should return an Actor-compatible API ONLY. We have a slightly strange terminology when it comes to:

1. Actors - in v4, we usually think of actors as something created by `spawn`. An actor ref is what's held in context.
2. Services - again, in v4 we think of them as something created using invoke.
3. Interpreters - something that's returned from `interpret` or `useInterpret`. To confuse things, we sometimes refer to this as a service.

Really, they're all referring to similar things - a running process that can send and receive events. We've had internal discussions to unify this language, but after an internal discussion with @Andarist he raised an interesting point:

What if we just made `interpret` return an Actor?

Andarist pointed out that the `Interpreter` type returned from `interpret` extends an Actor, and it doesn't really have that many other useful things on it. So if we return an Actor from `interpret`, we can condense the docs and teach less lingo.

### Expected result

Not applicable

### Actual result

Not applicable

### Reproduction

Not applicable

**Comment by johtso** [comment]
I agree! Just got bitten by this when I was trying to type a function that took the output of `useInterpret` as an argument and returns some ActorRef from within it. I tried to use `ActorRefFrom` but then realised that wasn't the right type. It definitely feels a little convoluted and if it could be simplified that would be awesome!

**Comment by davidkpiano** [comment]
Resolved by #3455
