### ISSUE TITLE
Bug: Timeout of `Infinity` causes `waitFor` to reject immediately

### ISSUE THREAD

**Issue by tom-sherman** [statelyai/xstate#3214]
### Description

This is caused by the use of setTimeout - `setTimeout(fn, Infinity)` invokes `fn` immediately.

### Expected result

Either:

- Throw an explicit error on infinite timeout values. It shouldn't reject instantly, this leaks implementation details of `waitFor`
- Remove the timeout

I think the second option is better as it allows for deferring the timeout to the user. I agree that a timeout is the right default but there are definitely scenarios where you want to handle that yourself.

### Actual result

Instant rejection of the promise returned by `waitFor`

### Reproduction

https://codesandbox.io/s/stoic-browser-ev9s97?file=/src/index.js

**Comment by davidkpiano** [comment]
I agree with the second option - removing the timeout. Can you make a PR for this? 🙏

**Comment by tom-sherman** [comment]
Do we want to error when passed `-Infinity`? And if so, should this be a synchronous or asynchronous error?

**Comment by tom-sherman** [comment]
Fair enough. Although I think deferring to the spec is a bit leaky, I wouldn't expect users to know that `waitFor` uses `setTimeout` under the hood.

**Comment by Andarist** [comment]
We can add a dev-only warning about negative numbers - that would handle more cases without special-casing `-Infinity`
