### ISSUE TITLE
Bug: Exit actions are not run when stop() is called on a child machine actor.

### ISSUE THREAD

**Issue by KW-M** [statelyai/xstate#3221]
### Description

When a parent machine starts a child machine using spawn(), then later the parent machine calls stop() on the spawned child machine, exit actions specified on the child machine are not run if they are xstate action creators (eg: assign(), pure(),  sendParent(), stop() etc...)

### Expected result

I would expect the exit actions to run and still be recognized without warning.

### Actual result

The browser JS console shows the following warning message:
Warning: No implementation found for action type 'whatever the name of the action was'

The action is never run.

### Reproduction

https://codesandbox.io/s/hopeful-moore-wm86bi?file=/src/index.js

### Additional context

I think there are some legitimate use cases for action creators that run on machine exit, such as:
 - Updating the parent with sendParent() or pure() based on state internal to the child actor when it is closed by the parent,
-  Actions that are re-used both as normal transition actions internal to the child machine and child machine exit actions.

**Comment by Andarist** [comment]
@KW-M I already have a PR addressing this issue - take a look [here](https://github.com/statelyai/xstate/pull/3126)
