### ISSUE TITLE
Bug: Entry assign action in state affecting action in another state

### ISSUE THREAD

**Issue by JoshuaAmaju** [statelyai/xstate#3223]
### Description

I have a setup that spawns child services and assigns them to context, then I wait for a `STOP` event in the `active` state, which then stops all child services and transitions to the inactive state. The `inactive` state has an entry action that clears all child services.

But clearing the child services in the `inactive` state happens before I get to stop the child services while in the `active` state, therefore making the array of child services empty.

I understand that the current implementation gives precedence to assign actions (which is said to be changed in the next release). But should that be the case for actions in different states when transitioning between states?

```javascript
const machine = createMachine<Context, Events, States>(
  {
    initial: 'inactive',
    id: 'task-manager',
    context: {
      tasks: new Map(),
      spawnedTasks: new Map(),
    },

    on: {
      START: 'local',
    },

    states: {
      inactive: {
       // this causes `tasks` map below in STOP event to be empty
        entry: assign({
          tasks: (_) => new Map(),
          spawnedTasks: (_) => new Map(),
        }),
      },
      idle: {
        on: {
          STOP: {
            target: 'inactive',

            // tasks map is empty here, but it shouldn't be. The entry action in the `inactive` state runs before this and clears
           // clears the map
            actions: pure(({tasks}) => {
                return [...tasks.values()].map((t) => stop(t.id));
              })
          },

          ADD_TASK: {
            target: 'spawning',
            actions: 'setTask',
          },

          TASK_DONE: {
            actions: 'setTask',
          },
        },
      },

      local: {
        invoke: {
          src: 'getSavedTasks',
          onDone: [
            {
              target: 'spawning',
              actions: 'setTasks',
              cond: (_, {data}) => Object.values(data).length > 0,
            },
            {
              target: 'idle',
            },
          ],
        },
      },

      spawning: {
        always: {
          target: 'idle',
          actions: 'spawnTasks',
        },
      },
    },
  },
  {
    actions: {
      spawnTasks: assign({
        spawnedTasks: ({tasks, spawnedTasks}) => {
          const spawned = new Map(spawnedTasks);

          tasks.forEach((task) => {
            if (!spawned.has(task.id)) {
              const ctx = {
                ...taskMachine.context,
                ...task,
                retries: 2,
                notified: false,
              };

              const actor = spawn(taskMachine.withContext(ctx), task.id);
              spawned.set(task.id, actor);
            }
          });

          return spawned;
        },
      }),
    },
  },
);
```

### Expected result

The stop event action should run before the assign action given they are called in different states.

### Actual result

The assign action clears the context value before the `pure` action gets to execute

### Reproduction

https://codesandbox.io/s/sparkling-sky-f54l7s?file=/src/machine.ts

**Comment by Andarist** [comment]
You can use `preserveActionOrder: true` to fix the problem (this will be the default behavior in the next major version):
https://codesandbox.io/s/laughing-tdd-4npbuk?file=/src/machine.ts:350-376

**Comment by JoshuaAmaju** [comment]
Thanks, that fixed it. But I don't think it's in the documentation

**Comment by Andarist** [comment]
It's mentioned here: https://xstate.js.org/docs/guides/context.html#action-order

**Comment by davidkpiano** [comment]
Closing as this has a confirmed workaround (will be fixed by default in v5)
