### ISSUE TITLE
Bug: Error: Unable to send event to child 'xxx' from service 'yyy'.

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#3253]
### Description

The following code throws an exception:

> Error: Unable to send event to child 'child-machine' from service 'parent-machine'.

```ts
const childMachine = createMachine({})

const parentMachine = createmachine({
  invoke: {
    id: "child-machine",
    src: childMachine
  },
  on: {
    EVENT_WITH_TARGET: {
      actions: actions.send((_, e) => e, { to: "child-machine" }),
      target: "test",
    },
  },
  initial: "test",
  states: {
    test: {}
  }
})

const testMachine = createMachine({
  invoke: {
    id: "parent-machine",
    src: parentMachine
  },
  on: {
    "*": {
      actions: actions.send((_, e) => e, { to: "parent-machine" })
    }
  }
})

const testInterpreter = interpret(testMachine).start();
testInterpreter.send("EVENT_WITH_TARGET");
// Error: Unable to send event to child 'child-machine' from service 'parent-machine'.
```

### Expected result

It should work without any errors / exceptions

### Actual result

```sh
Error: Unable to send event to child 'child-machine' from service 'parent-machine'.
```

### Reproduction

https://codesandbox.io/s/great-swirles-1tlh3q?file=/src/index.ts

### Additional context

If we removed the `target: "test"`, then it will not throw exceptions anymore:

```diff
  on: {
    EVENT_WITH_TARGET: {
      actions: actions.send((_, e) => e, { to: "child-machine" }),
-       target: "test",
    },
  },
```

**Comment by Andarist** [comment]
This is somewhat correct when we consider the algorithm. You have used an external transition and thus you made your source state (the one on which you have defined your `target: 'test'` transition) to be reentered (and thus it got first exited).

The order of actions is this (defined in the [`microstep` procedure](https://www.w3.org/TR/scxml/#microstepProcedure)):
```
procedure microstep(enabledTransitions):
    exitStates(enabledTransitions)
    executeTransitionContent(enabledTransitions)
    enterStates(enabledTransitions)
```

And canceling invokes is part of [`exitStates`](https://www.w3.org/TR/scxml/#exitStates). You can fix this on your side by using an internal transition, like here:
https://codesandbox.io/s/gifted-hertz-fmylil?file=/src/index.ts

**Comment by huan** [comment]
Thank you so much @Andarist for making this clear to me! I hope I have your explanation and references yesterday because it would save my whole day: I have been struggling with it for hours.

I want to say that this implementation of the algorithm is very confusing for a new user who is not familiar with SCXML specs like me. In my understanding, when I have a `actions.send(event, { to: id })`, it should be in a specific state. If so, no matter whether the transition is internal or external, the invoked machine should be always ready to use (and should not throw exception).

The current behavior, according to my code, like there has a third state: when we are executing the `actions.send()`, it's neither inside the previous state nor in the next state, because if the machine is in the state, the `invoke`-ed machine should be ready to use.

However, I have fixed my code with your help, really appreciate it!
