### ISSUE TITLE
Bug: @xstate/react v3 - getSnapshot warning when using object as a selector

### ISSUE THREAD

**Issue by xylophonehero** [statelyai/xstate#3269]
### Description

There is a warning from `use-sync-external-store` that the getSnapshot value should be cached. This happens when returning an object from the selector in the `useSelector` hook. Presumably because the objects aren't the same in memory.

```js
  const { count, active } = useSelector(service, (state) => ({
    count: state.context.count,
    active: state.matches("active")
  }));
```

Maybe we shouldn't be returning an object from the selector, but it does work fine with v2. If this were the case, would you recommend multiple selectors in the same file?

### Expected result

There was a warning when using an object returned from the selector

### Actual result

There should be no warning or maybe warn about using objects as the return value of the selector in the docs

### Reproduction

https://codesandbox.io/s/xstate-useselector-object-warning-ww5274

### Additional context

Although it only shows a warning in the reproduction, I experienced an infinite loop of renders with more complex machines

**Comment by xylophonehero** [comment]
Now that I think more about it, I shouldn't be using an object return without a compare function as the object will never be the same 🤦🏽

**Comment by Andarist** [comment]
Yeah, it's exactly that. This is a helpful warning coming out of the `use-sync-external-store`. We are not producing it on our own.
