### ISSUE TITLE
Bug: Delay on next task runs before custom actions on current task  

### ISSUE THREAD

**Issue by dementors-magnus** [statelyai/xstate#3286]
### Description

I have a state machine with two states. State A has a custom action and a target property set to state B. State B has a delay property specified. The delay property is evaluated before the state A custom action. See example below:

```
const statechart = {
  key: 'myMachine',
  initial: 'stateA',
  states: {
    stateA: {
      invoke: {
        src: () => Promise.resolve(),
        onDone: {
          actions: [
            () => console.log('Invoke action. Should run BEFORE next state.'),
          ],
          target: 'stateB',
        },
      },
    },
    stateB: {
      entry: [
        send(
          { type: 'SOME_EVENT' },
          {
            delay: (context) => {
              console.log('In delay. Should run AFTER invoke actions.');
              return 1000;
            },
          }
        ),
      ],
    },
  },
};
```

### Expected result

Custom action in state A to be evaluated before the state B delay

Output:
```
Invoke action. Should run BEFORE next state.
In delay. Should run AFTER invoke actions.
```

### Actual result

Delay in state B is evaluated before the state A custom action

Output:
```
In delay. Should run AFTER invoke actions.
Invoke action. Should run BEFORE next state.
```

### Reproduction

https://stackblitz.com/edit/xstate-reproduce-custom-action-vs-delay?file=index.js

### Additional context

xstate version: 4.32.0

**Comment by davidkpiano** [comment]
With `predictableActionArguments: true`, this works as expected: https://stackblitz.com/edit/xstate-reproduce-custom-action-vs-delay-kfetqm?file=index.js

Also, this is fixed (without that flag) in `xstate@alpha`
