### ISSUE TITLE
Bug: invoked machine event data not passed to onDone when onDone is array

### ISSUE THREAD

**Issue by Jakkc** [statelyai/xstate#3330]
### Description

Parent machine is not receiving event from invoked child machine when `onDone` is an array of state transitions.

The following works as expected. The log in the actions is called, I can access the event data from the child machine which just reached its final state:
```
 invoke: {
   src: 'fooMachine',
   data: {
     foo: (_: any, { foo }: any) => foo,
   },
   onDone: {
     actions: (ctx, e) => console.log('The event from the child machine:', { ctx, e }),
     target: 'FOO_STATE',
   },
}
```

The following does not work:

```
    invoke: {
          src: 'fooMachine',
          data: {
            foo: (_: any, { foo }: any) => foo,
          },
          onDone: [
            {
              cond: 'condition',
              actions: (ctx, e) => console.log('The event from the child machine', { ctx, e }),
              target: 'FOO_STATE',
            },
            {
              cond: 'condition2',
              target: 'BAR_STATE',
            },
          ],
        },
      },
```

### Expected result

I should be able to access the events data from the child machine irregardless on whether my onDone handler is an array of possible state transitions or a single state transition.

### Actual result

The event data is only accessible if the `onDone` handler is an object representing a single state transition.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by davidkpiano** [comment]
Closing as this should work in the latest versions and otherwise needs reproduction. Will reopen if it's still reproducible.
