### ISSUE TITLE
Bug: Invoke definition with onDone pointing to self-state enters infinite loop

### ISSUE THREAD

**Issue by canastro** [statelyai/xstate#3347]
### Description

Given an Invoke definition where `OnDone` points to the state where this `Invoke` is defined.

### Expected result

I expected this to be marked as an invalid state machine (although I couldn't find any reference in the SCXML spec)

### Actual result

The app enters an infinite loop and crashes the browser.

### Reproduction

https://stately.ai/viz/b4383ce5-49d7-472e-98ba-d6ccafaba6a9

### Additional context
I'm not really sure if this is a bug or its on the user's responsibility to take care of situations like this.

**Comment by Andarist** [comment]
Hmm, I don't think this is a bug - you are free to target just any state. This particular invokee completes immediately so it doesn't make sense but perhaps one could want to rely on such config (targeting "self-state" from `onDone`) in some legitimate scenarios.

Even though this is an infinite loop - it's an async one and I'm not sure how we could detect this at runtime to "break the loop".

**Comment by canastro** [comment]
Yeah, I wasn't sure if it could be considered a bug. It makes sense, a user might want a request to be repeated until a certain result is obtained. 

Closing this.
