### ISSUE TITLE
Bug: payload is undefined if an event is sent as a string with an object payload

### ISSUE THREAD

**Issue by henrikuper** [statelyai/xstate#3397]
### Description

I upgraded to 
"@xstate/react": "^3.0.0", from 1.2.2
"xstate": "^4.32.1" from 4.16.2

I have a file with global machine:
```
export const globalStateService = interpret(globalStateMachine, {
  devTools: true,
}).start();
```

I have a second file which imports the global machine
```
const [globalState, globalSend] = useService(globalStateService);
globalSend('START', { config: "test" });
```

This works fine before I upgraded.
After updating xstate I changed the 
useService to useActor because of the breaking change.
If I log the event on the global state, config is `undefined`.
```
const [globalState, globalSend] = useActor(globalStateService);
globalSend('START', { config: "test" });
```

This works:
```
const [globalState, globalSend] = useActor(globalStateService);
globalSend({type: 'START',  config: "test" });
```

### Expected result

Sending events as an object works.
Sending events as a string with an object payload does not work.

### Actual result

Sending events as a string with an object payload should work with a payload.

### Reproduction

https://codesandbox.io/s/jolly-rain-595uto

**Comment by davidkpiano** [comment]
The workaround, and preferred way of doing this going forward, is to use a single event object:

```diff
-send('CLICK', { some: 'payload' });
+send({ type: 'CLICK', some: 'payload' });
```

**Comment by henrikuper** [comment]
Thats correct. And fine for me. I would suggest to mark the old way as deprecated in the documentation
