### ISSUE TITLE
Bug: context not being updated in xstate/test@alpha

### ISSUE THREAD

**Issue by ErlanBazarov** [statelyai/xstate#3411]
### Description

The context of the machine when testing is not being updated when using actions
See this https://stackblitz.com/edit/node-y68tiz?file=index.test.js
The context's count is not updated when the state goes from `ready` to `incremented`

### Expected result

The context's count should become one when the state goes from `ready` to `incremented` 

### Actual result

The context's count is still zero when the state goes from `ready` to `incremented` 

### Reproduction

https://stackblitz.com/edit/node-y68tiz?file=index.test.js

### Additional context

I am using  `@xstate/test@1.0.0-alpha.0` and `xstate@4.32.1`

**Comment by Andarist** [comment]
You have accidentally put `actions` within the first argument that is the machine's config - it should be part of the second one though (same as with standard `createMachine` API):
https://stackblitz.com/edit/node-8ichjd?file=index.test.js
