### ISSUE TITLE
Bug: onDone action is getting called after exit action

### ISSUE THREAD

**Issue by balintpeak** [statelyai/xstate#3416]
### Description

```js
import { createMachine } from "xstate";

export const machine = createMachine(
  {
    id: "action-order-bug",

    initial: "initial",
    states: {
      initial: {
        exit: () => {
          console.log("exit");
        },
        invoke: {
          id: "fakeService",
          src: "fakeService",
          onDone: {
            actions: () => {
              console.log("onDone");
            },
            target: "done"
          }
        }
      },
      done: {}
    }
  },
  {
    services: {
      fakeService: () => Promise.resolve("success")
    }
  }
);
```

In the above example, the `exit` action will be called before the `onDone` action. However when `onDone` is called the state machine is still in `initial` state.

### Expected result

I expect the `onDone` action to be called before the `exit` action.

### Actual result

`exit` action getting called before `onDone` action.

### Reproduction

https://codesandbox.io/s/broken-cherry-j1n230?file=/src/machine.js

**Comment by Andarist** [comment]
I'm afraid that this is how the order of actions is defined - transition actions are called **after** exit actions, as per the procedure described [here](https://www.w3.org/TR/scxml/#microstepProcedure)
