### ISSUE TITLE
Bug: Error when using a choose action in first state/stateless machine

### ISSUE THREAD

**Issue by xylophonehero** [statelyai/xstate#3430]
### Description

When using a choose action in the entry action on the root of a machine, I get the following error

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/68996622/176196562-98fe126e-9fca-4e18-86c3-143fdefe8d4e.png">

Curiously, when I add a choose action later on in the machine in a non-initial state, the error disappears

### Expected result

Ability to use the choose action in entry action on root of machine without an error

### Actual result

There is an error

### Reproduction

https://github.com/xylophonehero/xstate-initial-choose-action

**Comment by davidkpiano** [comment]
cc. @mattpocock @Andarist
