### ISSUE TITLE
Bug: completeListener on Subscription is not triggered on stop

### ISSUE THREAD

**Issue by pixtron** [statelyai/xstate#3452]
### Description

When an interpreter is stoped, [all listeners get removed](https://github.com/statelyai/xstate/blob/6badd2ba3642391bee640aa4914003ad57f2e703/packages/core/src/interpreter.ts#L559-L562), therefore a potential subscription should `complete`. 

```
const machine = createMachine({...});
const service = interpret(machine)
const sub = service.subscribe(
  (state) => console.log('change', state),
  () => console.log('error'),
  () => console.log('complete')
);
service.start();
service.stop();
```

### Expected result

`complete` gets logged.

### Actual result

`complete` is not logged.

### Reproduction

https://codesandbox.io/s/competent-sunset-qmm9h8?file=/src/index.ts

### Additional context

As the [interpreter is stoped when entering a final state](https://github.com/statelyai/xstate/blob/6badd2ba3642391bee640aa4914003ad57f2e703/packages/core/src/interpreter.ts#L363) the [`resolvedCompleteListener`](https://github.com/statelyai/xstate/blob/6badd2ba3642391bee640aa4914003ad57f2e703/packages/core/src/interpreter.ts#L440) should probably be removed from `doneListeners` and `stopListeners` once it has been called, to avoid multiple calls to it. Eg in the repro `s2 complete` should only be logged once.

**Comment by Andarist** [comment]
The question here is... if `.stop()` is like `.complete()` or like `.cancel()`? And if `complete` callback should be called in case of a `cancel` if we'd chose the latter semantics?

I think that I'm leaning towards your expected result here... but I need to rethink this.

**Comment by pixtron** [comment]
@Andarist when i subscribe after the interpreter has been stopped, the [`resolvedCompleteListener` gets called immediately](https://github.com/statelyai/xstate/blob/6badd2ba3642391bee640aa4914003ad57f2e703/packages/core/src/interpreter.ts#L437-L439), therefore i would expect the same behavior when the interpreter enters the state `Stopped`.

**Comment by Andarist** [comment]
Would you like to work on a fix for this?
