### ISSUE TITLE
Bug: NextJS useInterpret is not initialized unless service is passed to child component and SSR is disabled

### ISSUE THREAD

**Issue by uncvrd** [statelyai/xstate#3465]
### Description

Hi! Been stumped on this one today. I've been trying to use `useInterpret` with my machine in `NextJS` however, I've run in to a problem where the service returned from `useInterpret` is not initialized on the first render. If the site hot reloads, then the initial state is defined. 

For example, the following code would display `Invalid State`:

```
const NotWork = () => {

    const service = useInterpret(myMachine);

    return (
        <NoSsr>
            {service.state?.matches("Idle") ? (
                <div>Idle State</div>
            ) : (
                <div>Invalid State</div>
            )}
        </NoSsr>
    )
}

export default NotWork;
```

I was able to resolve the problem by doing the following 2 things:

- Disabling SSR using `@mui/base`'s `NoSsr` component.
- Abstracting my use of the service to a child component, like this

```
const Child: React.FC<{
    service: InterpreterFrom<typeof myMachine>;
}> = ({ service }) => {

    return (
        <div>
            {service.state?.matches("Idle") ? (
                <div>Idle State</div>
            ) : (
                <div>Invalid State</div>
            )}
        </div>
    )
}

const Works = () => {

    const service = useInterpret(myMachine);

    return (
        <NoSsr>
            <Child service={service} />
        </NoSsr>
    )
}
```

Here's a github repo replicating this problem. Visit `/work` to view the working implementation and `/not-work` to see the broken implementation. I tried setting up codesandbox with some issues, so I apologize for the slight inconvenience but at least I have a reproduction for you to test :D 

Repo: https://github.com/uncvrd/xstate-react.git

Edit: didn't realize the template provided example codesandboxes, hope this is okay!

Video repro:

https://user-images.githubusercontent.com/25097099/180117865-b3b56e0d-0560-4edb-8c7d-9b933059de31.mov

### Expected result

I expect to be able to have the `useInterpret` initialized on first render without having to abstract away the components using this machine to a child component and not have to disable SSR.

### Actual result

The initial state of the interpreted machine is Invalid unless an additional render takes place on screen.

### Reproduction

https://github.com/uncvrd/xstate-react.git

### Additional context

Found this problem has popped up a couple times around here without resolution or with a reproduction.

Other references:

https://github.com/statelyai/xstate/issues/2157

https://discord.com/channels/795785288994652170/809564609383890965/906238361679827054 -> this discord comment soon led to this response:

```
For others that might stumble upon this in the future, I solved the problem by moving the child component to a different file.  I have no idea why that matters, but it solved the problem
```

Which eventually led me down the path of abstracting the component and also disabling `Ssr` which fixes my problem.

---
EDIT
I guess something else I'm confused about from the docs, which has to do with services updating is this line:

> Using useInterpret returns a service, which is a static reference to the running machine which can be subscribed to. This value never changes, so we don't need to worry about wasted re-renders.

But then 2 paragraphs down says:

> The useActor hook listens for whenever the service changes, and updates the state value.

So if useInterpret returns a service that never changes, how can useActor listen for updates for something that never changes?

Any guidance would really be appreciated!!

**Comment by Andarist** [comment]
Accessing `service.state` like that during render is an anti-pattern because it won't "react" to state changes. You are accessing a mutable value there and thus you make your component impure/non-deterministic.

I suggest using `useSelector` to access this state match and IIRC it should work OK during the initial render.

**Comment by uncvrd** [comment]
Got it, thanks for clarifying!
