### ISSUE TITLE
Bug:  @xstate/react bundles/duplicates react when in a package with "resolutions"

### ISSUE THREAD

**Issue by mickdelaney** [statelyai/xstate#3471]
### Description

if I add 
```
"react": "17.0.2",
"react-dom": "17.0.2"
```
to resolutions like below.  yarn will bundle react under the @xstate/react package, and we end up with duplicate versions of react. 

"resolutions": {
    "react-native": "0.68.2",
    "@types/react": "~17.0.39",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "peerDependencies": {
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "dependencies": {
    "@xstate/react": "^3.0.0",
    "expo": "^44.0.0",
    "expo-status-bar": "~1.2.0",
    "native-base": "3.4.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-safe-area-context": "3.3.2",
    "react-native-svg": "12.1.1",
    "react-native-web": "0.17.1"
  },

### Expected result

would expect it not to bundle react

### Actual result

under node_modules 

we get:

node_modules/@xstate/react/node_modules/react 

### Reproduction

https://github.com/mickdelaney/yarn-resolutions-error/tree/using-resolutions

**Comment by mickdelaney** [comment]
it seems this is due to react & react-dom being devDependencies 
even though it shouldnt cause a problem
the solution is going to be to move them to peerDependencies

**Comment by Andarist** [comment]
You should update your own direct dependencies to use the same range as the one specified in resolutions:
https://github.com/mickdelaney/yarn-resolutions-error/blob/a65c5201cec0de1788d9d4bd412fb10b53ff046b/package.json#L35-L36

It seems that Yarn only uses resolutions for what you don't necessarily control in full. So it only applied the resolutions for your transitive requirements and thus somehow installed additional React within node_modules because it was forced to put `react@17.0.1` (and not `react@17.0.2`) in your root `node_modules`.

After I've done this change everything got nicely deduplicated:
<details>
<summary>git diff</summary>

```diff
diff --git a/package.json b/package.json
index 446b5ea..7449e5a 100644
--- a/package.json
+++ b/package.json
@@ -32,8 +32,8 @@
     "expo": "^44.0.0",
     "expo-status-bar": "~1.2.0",
     "native-base": "3.4.0",
-    "react": "17.0.1",
-    "react-dom": "17.0.1",
+    "react": "17.0.2",
+    "react-dom": "17.0.2",
     "react-native": "0.64.3",
     "react-native-safe-area-context": "3.3.2",
     "react-native-svg": "12.1.1",
diff --git a/yarn.lock b/yarn.lock
index 6ba7e8b..2a94eeb 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -6009,14 +6009,14 @@ react-devtools-core@^4.23.0, react-devtools-core@^4.6.0:
     shell-quote "^1.6.1"
     ws "^7"
 
-react-dom@17.0.1:
-  version "17.0.1"
-  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-17.0.1.tgz#1de2560474ec9f0e334285662ede52dbc5426fc6"
-  integrity sha512-6eV150oJZ9U2t9svnsspTMrWNyHc6chX0KzDeAOXftRa8bNeOKTTfCJ7KorIwenkHd2xqVTBTCZd79yk/lx/Ug==
+react-dom@17.0.2:
+  version "17.0.2"
+  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-17.0.2.tgz#ecffb6845e3ad8dbfcdc498f0d0a939736502c23"
+  integrity sha512-s4h96KtLDUQlsENhMn1ar8t2bEa+q/YAtj8pPPdIjPDGBDIVNsrD9aXNWqspUe6AzKCIG0C1HZZLqLV7qpOBGA==
   dependencies:
     loose-envify "^1.1.0"
     object-assign "^4.1.1"
-    scheduler "^0.20.1"
+    scheduler "^0.20.2"
 
 "react-is@^16.12.0 || ^17.0.0", react-is@^17.0.1:
   version "17.0.2"
@@ -6190,10 +6190,10 @@ react-transition-group@^4.4.2:
     loose-envify "^1.4.0"
     prop-types "^15.6.2"
 
-react@17.0.1:
-  version "17.0.1"
-  resolved "https://registry.yarnpkg.com/react/-/react-17.0.1.tgz#6e0600416bd57574e3f86d92edba3d9008726127"
-  integrity sha512-lG9c9UuMHdcAexXtigOZLX8exLWkW0Ku29qPRU8uhF2R9BN96dLCt0psvzPLlHc5OWkgymP3qwTRgbnw5BKx3w==
+react@17.0.2:
+  version "17.0.2"
+  resolved "https://registry.yarnpkg.com/react/-/react-17.0.2.tgz#d0b5cc516d29eb3eee383f75b62864cfb6800037"
+  integrity sha512-gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==
   dependencies:
     loose-envify "^1.1.0"
     object-assign "^4.1.1"
```
</details>

**Comment by mickdelaney** [comment]
Thanks @Andarist
