### ISSUE TITLE
Bug: storage ctx into indexDb is not work

### ISSUE THREAD

**Issue by yesixuan** [statelyai/xstate#3484]
### Description

![WX20220730-194513](https://user-images.githubusercontent.com/22050621/181909495-b3f2188e-e193-4eea-849c-6f73eedd4d74.png)

1. spawn actor in context,
2. storage ctx into indexDb
3. got error

### Expected result

wish to storage whole ctx include actor into indexDb so that I can restore it

### Actual result

![WX20220730-194513](https://user-images.githubusercontent.com/22050621/181909575-2a0421f0-c68a-4a7a-9e0b-2cb7e995d77c.png)
is error

### Reproduction

ctx contains actor can not storage into indexDb

**Comment by davidkpiano** [comment]
Can you share the code that you are using to store the `ctx`?

**Comment by yesixuan** [comment]
<img width="752" alt="截屏2022-08-06 22 56 26" src="https://user-images.githubusercontent.com/22050621/183254409-5a3b9410-614b-4296-935d-a7f1ac20730a.png">
The code is I use @xstate/immer spawn some actor into context

**Comment by yesixuan** [comment]
repository address is 
https://github.com/x-vic/diligence/blob/main/projects/client/src/stateMachine/tasks.machine.ts

<img width="632" alt="截屏2022-08-06 23 01 56" src="https://user-images.githubusercontent.com/22050621/183254618-5c350ab7-e016-4d0d-bc7c-2d8bb23a3774.png">

I filter actor reference can make store context into indexDB work

**Comment by davidkpiano** [comment]
> I filter actor reference can make store context into indexDB work

Yes, this is what you should do for now, and is a good workaround. You can also call `JSON.stringify(ctx)` and use that perhaps?

**Comment by yesixuan** [comment]
> > I filter actor reference can make store context into indexDB work
> 
> Yes, this is what you should do for now, and is a good workaround. You can also call `JSON.stringify(ctx)` and use that perhaps?

Are there any plans to restore Actor into localStorage or indexDb...
That would be useful.

**Comment by yesixuan** [comment]
> > I filter actor reference can make store context into indexDB work
> 
> Yes, this is what you should do for now, and is a good workaround. You can also call `JSON.stringify(ctx)` and use that perhaps?

Are there any plans to restore Actor into localStorage or indexDb...
That would be useful.

**Comment by davidkpiano** [comment]
> > > I filter actor reference can make store context into indexDB work
> > 
> > 
> > Yes, this is what you should do for now, and is a good workaround. You can also call `JSON.stringify(ctx)` and use that perhaps?
> 
> Are there any plans to restore Actor from localStorage or indexDb... That would be useful.

It's not going to be technology-specific, but we will work on improving actor restoration in v5.

**Comment by davidkpiano** [comment]
This is in progress for v5: #3743
