### ISSUE TITLE
Bug: React runtime error in @xstate/react in machine with hierarchical state

### ISSUE THREAD

**Issue by bscheurm** [statelyai/xstate#3485]
### Description

I have a machine that includes a [hierarchical state node](https://xstate.js.org/docs/guides/hierarchical.html). The machine is imported into a React app for managing state and UI flows. Everything works great with transitions between top-level states. But when the state transitions into the hierarchical/compound nodes, the result is an error and an unusable app:

>Objects are not valid as a React child (found: object with keys {nested}). If you meant to render a collection of children, use an array instead.

I've created a [Code Sandbox repro](https://codesandbox.io/s/compound-state-error-repro-p067l6) with a simplified version of the machine.

Here is the relevant part of the sandbox code for quick reference:

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { createMachine } from "xstate";
import { useMachine } from "@xstate/react";

const compoundStateErrorReproMachine = createMachine({
  id: "nestedStateRepro",
  initial: "ready",
  states: {
    ready: {
      on: {
        TO_NEXT: {
          target: "next",
        },
      },
    },
    next: {
      on: {
        TO_NESTED: {
          target: "nested",
        },
      },
    },
    nested: {
      initial: "first",
      states: {
        first: {
          on: {
            TO_SECOND: {
              target: "second",
            },
          },
        },
        second: {},
      },
    },
  },
});

function App() {
  const [state, send] = useMachine(compoundStateErrorReproMachine);
  
  return (
    <div className="App">
      <div>
        <><b>Current state:</b> {state.value}</>
      </div>
      <div>
        <button onClick={() => send('TO_NEXT')}>TO_NEXT</button>&nbsp;
        Not a nested state: transition works<br/>
        <button onClick={() => send('TO_NESTED')}>TO_NESTED</button>&nbsp;
        Nested state, top-level: transition results in error
      </div>
    </div>
  );
}
```

### Expected result

I expected this to work without error and the current machine state to be at the first compound state.

### Actual result

The transition to the compound state results in an error:

>Objects are not valid as a React child (found: object with keys {nested}). If you meant to render a collection of children, use an array instead.

### Reproduction

https://codesandbox.io/s/compound-state-error-repro-p067l6

### Additional context

Here are the dependencies from package.json in the sandbox:

```json
{
  "dependencies": {
    "@xstate/react": "2.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "5.0.0",
    "xstate": "4.30.5"
  },
  "devDependencies": {
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.2",
    "typescript": "3.3.3"
  },
}
```

Dependencies from package.json in the custom project code (error occurs in both environments):

```json
{
  "dependencies": {
    "@xstate/react": "^3.0.0",
    "html-react-parser": "^3.0.1",
    "next": "12.2.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "xstate": "^4.32.1"
  },
  "devDependencies": {
    "@types/node": "18.0.0",
    "@types/react": "18.0.14",
    "@types/react-dom": "18.0.5",
    "eslint": "8.19.0",
    "eslint-config-next": "12.2.0",
    "typescript": "4.7.4"
  }
}
```

**Comment by kuk941025** [comment]
This is not a bug. `state.value` becomes an object when entered a nested state, which should return `nested.first` or `nested.second`.

Change `{state.value}` to `{JSON.stringify(state.value)}` to see the nested state value without error.

**Comment by bscheurm** [comment]
Thanks @kuk941025 . That makes sense. I didn't suspect that the debug printing of `state.value` was the problem. :D
