### ISSUE TITLE
[Typescript] `StateValue` is not typesafe

### ISSUE THREAD

**Issue by mrchantey** [statelyai/xstate#3504]
### Description

Working with `machine.transition()` and other implementations of `StateValue`, the type is not provided. The type safety is provided elsewhere, ie [state.matches](https://github.com/statelyai/xstate/blob/6abfc5afa7945fcb6b58cc9911bd37bec9ac573d/packages/core/src/State.ts#L318):
```typescript
TSV extends TResolvedTypesMeta extends TypegenEnabled
      ? Prop<Prop<TResolvedTypesMeta, 'resolved'>, 'matchesStates'>
      : never
```
It would be great to see this applied more broadly.

### Expected result

Here is an example implementation with a generic `StateValue`. Naturally a lot of this code is to get at the typegen that would be already available within the `StateNode` class.
```typescript
type AnyTypegen = ResolveTypegenMeta<any, any, any, any>;
type GetTypegen<T extends AnyStateMachine> = T extends StateMachine<any,any,any,any,any,any,infer T2>
  ? T2 extends AnyTypegen ? T2["resolved"] : never : never;
type StateValue<T extends AnyStateMachine> = GetTypegen<T>["matchesStates"];

const transitionSafely = <T extends AnyStateMachine>(
  machine: T,
  state: StateValue<T>,
  event: any
) => machine.transition(state, event).value as StateValue<T>;

```

### Actual result

```typescript
//'foo' should be a typescript error, and value should be 'inactive|active'
const value1 = machine.transition("foo", "TOGGLE").value;
```

### Reproduction

https://codesandbox.io/s/xstate-typescript-demo-le9xqo?file=/src/index.ts

**Comment by davidkpiano** [comment]
This is something we'll be able to do with const type generic parameters in version 5 (cc. @Andarist)

**Comment by Andarist** [comment]
That's unfortunately not necessarily true. Remember that TS still doesn't support partial inference. This particular issue mentions that it's using typegen and with that, we could revamp this PR at some point: https://github.com/statelyai/xstate-tools/pull/160

**Comment by Andarist** [comment]
We just landed this as a new feature: https://github.com/statelyai/xstate/pull/4498 . Note that it requires you to use the `setup` API (that was also recently introduced to v5)
