### ISSUE TITLE
Bug: Breaking change in nextState call in 4.33

### ISSUE THREAD

**Issue by richtera** [statelyai/xstate#3510]
### Description

The nextState call is now affecting the current state and creating transisions.

### Expected result

nextState should return the next state without affecting the current state of the machine or interp.

### Actual result

I see transitions and actions being executed due to a nextState call.

### Reproduction

https://codesandbox.io/s/musing-hill-ooejpy?file=/src/index.tsx

### Additional context

The sandbox doesn't readily display the problem, but I can't post the issue without an example.

**Comment by Andarist** [comment]
I think that you might have forgotten to save the codesandbox because it doesn't show the problem anyhow. While I have fixed the issue [here], it would be great if we could confirm that your specific use case has been fixed.

**Comment by richtera** [comment]
I see the example working correctly wrong. The first click to the button immediately counts as a full toggle. Also I don't think the problem has anything to do with predictableActionArguments since I saw the problem with and without the flag. Is the new version public so I can pull it?
