### ISSUE TITLE
Bug: Sending an empty array of events to an interpreter fails with "Cannot use 'in' operator to search for '$$type' in undefined"

### ISSUE THREAD

**Issue by Woodz** [statelyai/xstate#3519]
### Description

According to the docs of `Interpreter.send` (https://paka.dev/npm/xstate@4.33.1/api#dcfdac634e7e7494):

> An array of events (batched) can be sent as well, which will send all batched events to the running interpreter

However, this throws an error if the array is empty, forcing users to wrap all calls to `send` that use arrays of dynamic length in an array length check to avoid this bug.

### Expected result

I expected the interpreter to do nothing

### Actual result

It threw error `Cannot use 'in' operator to search for '$$type' in undefined` with stack trace:

```
    at Object.toSCXMLEvent (/var/task/dist/handlers.js:159314:41)
    at /var/task/dist/handlers.js:161157:41
    at Scheduler2.process (/var/task/dist/handlers.js:160435:11)
    at Scheduler2.schedule (/var/task/dist/handlers.js:160419:14)
    at Interpreter2.batch (/var/task/dist/handlers.js:161121:24)
    at Interpreter2.send (/var/task/dist/handlers.js:160689:19)
```

### Reproduction

https://codesandbox.io/s/keen-bell-peys02

### Additional context

XState version: 4.30.5

**Comment by Andarist** [comment]
It's an easy fix - I will prepare it soon. However, note that in the next major version we plan to remove `service.batch` (which gets called by `service.send([])`). For that reason, I recommend you to migrate towards using this:
```diff
-service.send(events)
+events.forEach(event => service.send(event))
```

**Comment by Woodz** [comment]
Makes sense! Will take note of this planned breaking change
