### ISSUE TITLE
Regression: root-level invoked services not stopped after reaching `final` state

### ISSUE THREAD

**Issue by with-heart** [statelyai/xstate#3522]
### Description

When an interpreted machine reaches a `final` state, services invoked at the root level are no longer stopped.

#3126 changed the way the interpreter is stopped when `this.state.done`, calling the new `_stop` method where previously `stop` was called. `stop` handles stopping all `children`:

https://github.com/statelyai/xstate/blob/f2bf4924c291069204baab8b2f156574c0bd085f/packages/core/src/interpreter.ts#L664-L668

### Expected result

When a service reaches a `final` state, all invoked services are stopped.

### Actual result

When a service reaches a `final` state, services invoked at the root are not stopped.

### Reproduction

https://codesandbox.io/s/kind-diffie-ewx8qk?file=/src/index.ts

### Additional context

Reproduction of previous behavior (`xstate@4.32.1`): https://codesandbox.io/s/modern-rain-4serhm

**Comment by Andarist** [comment]
Thank you for the report, It got fixed by https://github.com/statelyai/xstate/pull/3523 and the new release is already out.

**Comment by with-heart** [comment]
@Andarist You're the best! Ty 💖
