### ISSUE TITLE
Bug: "This extension violates the Chrome Web Store policy"

### ISSUE THREAD

**Issue by EightArmCode** [statelyai/xstate#3543]
### Description

![Screenshot 2022-08-24 at 13 37 32](https://user-images.githubusercontent.com/7226801/186408988-1e5b2b14-d7f5-4d2a-b994-9cf6b25009c9.png)

Not sure if this is the right place to post, but wanted to surface this issue for you all.

Thanks for all the great tooling!

### Expected result

I expect the extension to work. Chrome will not allow reinstallation when this occurs, according to my findings.

### Actual result

Extension is unavailable.

### Reproduction

Cannot provide reproduction

**Comment by Andarist** [comment]
This is not an official extension - we are working on one though

**Comment by davidkpiano** [comment]
⚠️ Please don't use the 3rd party Chrome extension ⚠️ 

It is not created nor maintained by us at Stately.

**Comment by EightArmCode** [comment]
Good to know! The good news it seems Chrome has shut it down. Thanks!
