### ISSUE TITLE
Bug: eventless transitions in parallel states not taken anymore when starting interpreter from given state

### ISSUE THREAD

**Issue by fparga** [statelyai/xstate#3544]
### Description

Eventless transitions in parallel state are not taken anymore when interpreter is started from a given state.

### Expected result

Eventless transitions should always be taken.

For example, in the linked reproduction sandbox, the expected result is:
```
state.value == {"b":{"x":"bar","y":{}}} 
```

This is the result obtained with xstate version < 4.33.0

### Actual result

The eventless transition in example is not taken anymore with xstate version >= 4.33.0.

Instead, we get:

```
state.value == {"b":{"x":"foo","y":{}}} 
```

### Reproduction

https://codesandbox.io/s/affectionate-thunder-esq8rn?file=/src/index.js

### Additional context

It looks like a regression introduced in version 4.33.0.

**Comment by Andarist** [comment]
Thanks for the repro case! We really appreciate it - I'm gonna take a look at this soon.

**Comment by Andarist** [comment]
I've found [the culprit behind this regression](https://github.com/statelyai/xstate/pull/3422/files#r905127802). It seems that this case here actually has been implicitly relying on this mutation.

I'll try to figure out an improved algorithm for this.

**Comment by fparga** [comment]
Awesome, thank you @Andarist!
