### ISSUE TITLE
Bug: Inline `assign()` is missing inferred type information

### ISSUE THREAD

**Issue by pspi** [statelyai/xstate#3590]
### Description

Inline `assign()` is missing inferred type information. Inside the assigner function, the `context` argument has incorrectly the type `unknown`.

Possibly related to statelyai/xstate-tools#299, but that issue mentions the use of Typegen.

### Expected result

The `context` argument should be typed according to the schema.

### Actual result

The `context` has `unknown` type.

### Reproduction

https://codesandbox.io/s/sad-chebyshev-cvsjsh?file=/src/index.ts

### Additional context

typescript 4.8.3
xstate  4.33.6

**Comment by pspi** [comment]
> You might have forgotten to save the codesandbox. It doesn't contain any `assign` action right now.

Oh, shoot. Now it should be saved.

**Comment by Andarist** [comment]
This is the only, hacky, solution that I know:
https://www.typescriptlang.org/play?ts=4.8.2#code/JYWwDg9gTgLgBAbwFBzgQwM4eAcwHYA0KcAxlAKZozkCyaJAFsHuUagIJa4tRtwAKUCGHKwAnp2z5RfAKIA3cnhgB5AEYArciRh92O4BDzqtOogF84AMyEg4AIgAeGGFXL2A3EiTNqUK-TkcDQSXPj6MIZ4ADwAKgDCRtSOunCxCkrw5ClKACYYcBnKJtowAHzE2dR4+XARUSU6cYnKVQRpReWIxDBiIgBcDs6u1AB0mFJ4nsQT3CCZg5Lcos1JbR2KymVwAD4CQiLiS9JQq60p7emb5V6oAPR3cDBMBcAFz0FGADZiT0x4OD+VDgDEwcDU5CU6FyuXIuXQNTgwBgAHICmgQfQANbEB5-IIUDAAVy+8AgVnxcAABrN8FSkQU8BB4CQ0F8vmg1F8gsw4BQ2cixMQABQkNYpQYJcWpcjXSWdACUg3kEGAuS85m8ViJeAMRjgIFCkzOyVSV0ycCqeQKnUa5WFMzCPEWTpWUvOZs62z2gmEol6xx4JvW5q2SCVwSN3HqRmDFw2mW2yFQFBgRKgeHQTuFtJ4CqzCLEGu8ZEo1DojGY5GFybgGEY5BAaEGtdQYo9gxrljBOqxTIA7nh82CEHB5GyieRBngiSAIVA4OY+KhZZkMJ2EN2Cr2B0OC6PegMHMxS-NlPZF3wl8R26aW8RUOOvpPBgBGK98ZjI4Bswb2NXcvYfAuG467dKgqAAVO4EQagRj3rBsEnhQZ4wAhiGwfQkRGGBhqBjWD4YRBT4vnAorSu0q7KPmAC82y3lUowkUEADUcDvoRGHmAqy6IdeXG8fxl5INxXhAA

**Comment by nomoon** [comment]
@Andarist this is an excellent workaround. Do you know why that actually works? I'm curious.

**Comment by Andarist** [comment]
This is a heuristic baked into TypeScript's inference algorithm - functions might be treated a little bit differently at times. So by adding a hacky callable signature to this we trick TS to treat this as a function and thus it starts to use a different path in its inference algorithm.

A related comment in the TypeScript's code can be found here:
https://github.dev/microsoft/TypeScript/blob/e5cd686defb1a4cbdb36bd012357ba5bed28f371/src/compiler/checker.ts#L31675-L31686
