### ISSUE TITLE
Bug: Memory leak appeared between xstate 4.32.1 and xstate 4.33.4

### ISSUE THREAD

**Issue by AlCalzone** [statelyai/xstate#3616]
### Description

We've recently had a memory leak in a Home Assistant addon which uses xstate under the hood (as a transitive dependency). It took a while to narrow this down to xstate (or using it), since there are two similar addons, using the exact same library with the exact same version, and only one of those exhibited a quite drastic memory leak (in the order of 100MB/h), while the other one is perfectly stable:
https://github.com/home-assistant/core/issues/77767

It turns out that the difference between those installations was how the dependencies got installed. The non-leaking one uses `yarn install --immutable`, resulting in an install of xstate@4.32.1 from the lockfile - while the leaking one uses `npm install`, which installed the latest version at the time. The leak appeared starting with xstate@4.33.4 and persists with 4.33.6 - unfortunately I don't know which versions between those two are also affected.
After pinning the xstate version in the leaking addon, the leak went away.

Sadly, I cannot provide a reproduction, since only a handful of users are affected and I haven't been able to reproduce myself. I haven't seen anything in the changelog that would suggest a change in behavior - like actor references not getting cleaned up or anything like that.
I would be grateful for some help with tracking this down though, since I'm afraid this is going to prevent us from upgrading xstate indefinitely.

### Expected result

No memory leak

### Actual result

Memory leak

### Reproduction

Not possible unfortunately, see description

**Comment by davidkpiano** [comment]
@AlCalzone Thanks for the report, we're looking into it. cc. @Andarist

**Comment by Andarist** [comment]
@AlCalzone are you sure that this started to happen in `4.33.4`? I'm looking at the diff between this and the version before it ([diff](https://github.com/statelyai/xstate/compare/xstate%404.33.3...xstate%404.33.4)) and I don't see any obvious culprit for a memory leak. In theory, `_outgoingQueue` could not be managed well here but in such a case I would expect a lot of runtime/logic bugs to be reported. 🤔

**Comment by AlCalzone** [comment]
No sorry, all I know is that it started after 4.32.1 and it is happening in 4.33.4.

**Comment by Andarist** [comment]
Is there anything special about those users that you can't repro this on your own?

**Comment by AlCalzone** [comment]
The [library that depends on xstate](https://github.com/zwave-js/node-zwave-js) is using it to control Z-Wave devices via radio. There are roughly 3000 different end devices on the market which, although standardized, often behave slightly differently. Users have different automations to control devices, different reporting configuration for devices, maybe even a suboptimal physical mesh that could influence this.

I'm trying to get some logs to find similarities, now that we know better what caused this. But in short, this is a needle in a haystack and I'm hoping to get at least some idea what could be triggering it. The library often creates child machines, maybe something changed in their handling, so a reference is kept around under specific circumstances now?

**Comment by davidkpiano** [comment]
> The library often creates child machines, maybe something changed in their handling, so a reference is kept around under specific circumstances now?

That's a good place for us to look. It's either that or some code introduced with the `predictableActionArguments` flag, I'd think.

**Comment by AlCalzone** [comment]
Let me know if I can test something for you

**Comment by Andarist** [comment]
How people are interacting with those machines? Or is it all hidden in your system? Are all known event types etc known upfront? Maybe we could try to do some fuzzy testing and spam the system with events to observe the memory?

**Comment by AlCalzone** [comment]
Users don't interact with the machines directly, but through the system which figures out the events to send to the machine.

There is one machine "SendThread" handling the queuing at a high level, deciding which transactions may be started and which ones have to wait.
It spawns a child machine "CommandQueue", which sends each message in the order it receives. Sending a message means invoking another short-lived machine "SerialAPI" that does the actual communication with the hardware, handling errors and repeating failed messages. Once that machine has finished, CommandQueue continues with the next.

The "SendThread" spawns a "TransactionMachine" for each transaction which may be started. Each one of those creates messages, sends them to the "SendThread", which forwards them to the "CommandQueue", which later returns the result in the opposite direction. The "TransactionMachine" can then create another message and repeat the process or transition to its final state, in which case the "SendThread" removes its reference to this machine.

The system only interacts with the "SendThread" via a fixed set of events. I guess that could be an entry point for fuzzing?
However some of those events are passed through all the way down to the "SerialAPI" machine, and only events with very specific payload are valid for certain transitions, which could make this a bit harder.

**Comment by Andarist** [comment]
While this is not a 10-minute check - it sounds possible based on the given description. I know that it's probably not exactly what you'd like to hear, but I don't have better ideas right now though. I've looked through the changed code multiple times (comparing against 4.32.1) and there are a lot of changes there and no obvious culprit in sight. I wonder - have you been using `predictableActionArguments: true` when the leaks happened? Knowing that would allow us to at least discard some set of scenarios.

**Comment by AlCalzone** [comment]
No I haven't been using that option. The dependency in package.json (and the library's `yarn.lock`) is `^4.29.0` where the option isn't available - I haven't upgraded yet due to type-related build errors. It's just that the applications using the library ended up pulling in a newer version of xstate.

Guess I'll try spamming the machine with events and see what sticks. Can't guarantee when this will happen though - might well be January or so 😅

**Comment by Andarist** [comment]
Could you link me to this library? `home-assistant/core` is a python repo and there is no XState in sight there :P

**Comment by AlCalzone** [comment]
I did above, but here you go

https://github.com/zwave-js/node-zwave-js

**Comment by AlCalzone** [comment]
The machines are defined here: https://github.com/zwave-js/node-zwave-js/tree/master/packages/zwave-js/src/lib/driver

**Comment by beejunk** [comment]
Ran into this issue this week. Deployed a Node app that uses XState, and as soon as it faced production traffic we started seeing signs of a memory leak. This deploy included an upgrade of XState from 4.31.0 to 4.35.0. Took us a while to get an idea of what was going on, and seeing this issue confirmed our theory. We downgraded XState to 4.31.0, redeployed and the issue was no longer there.

While we were investigating the issue, we analyzed a core dump from the app and discovered that a massive number of `State` and `StateNode` objects were in memory. Following this, I was able to run the app locally, hit it with bit of traffic using K6, and analyze the memory using the Chrome dev-tools heap profiler. For v. 4.35.0 of XState, this also revealed `State` and `StateNode` objects that weren't being grabage-collected. When analyzing with XState v. 4.31.0, these objects did not appear on the profile at all (so I am assuming they were effectively GC'd).

The machine in question does use parallel child machines. Additionally, the version of the app that exhibited the memory leak issue was using the `predictableActionArguments` option set to `true` for each machine.

If I have time this weekend, I'll see if I can get together a minimal reproduction.

**Comment by Andarist** [comment]
It would be lovely to get a minimal repro case for this. If you manage to create one - I would highly appreciate it. If you are able to confirm the issue locally we could also try to debug this together over a call (if that's an option on your end)

**Comment by beejunk** [comment]
@Andarist I was able to get a minimal reproduction setup for this issue: https://github.com/beejunk/xstate-memory-leak

Details are in the `README.md` file; let me know if you need any additional info. If debugging over a call is helpful, I could probably make that work but not until next weekend.

Hope this helps!

**Comment by Andarist** [comment]
@beejunk thank you! this was very helpful. Thanks to the repro I located the problem really quickly - the PR with a fix is up here: https://github.com/statelyai/xstate/pull/3801

**Comment by AlCalzone** [comment]
Amazing. I will see if I can get some of our affected users to re-test with the updated version.

**Comment by beejunk** [comment]
Just wanted to follow up and say that we finally got around to deploying the updated version of XState, and no memory leaks were detected! Thanks again for the quick work on this, @Andarist .
