### ISSUE TITLE
Entry action gets triggered on exit

### ISSUE THREAD

**Issue by thomasaull** [statelyai/xstate#3618]
### Description

Consider the following state machine:
```js
{
  initial: "update",
  id: "root",

  states: {
    update: {
      initial: "default",

      states: {
        default: {
          on: {
            START: "doSomething.pick"
          }
        },

        doSomething: {
          initial: "pick",

          states: {
            default: {},
            pick: {
              entry: () => console.log("ENTRY: doSomething.pick"),
              exit: () => console.log("EXIT: doSomething.pick"),

              on: {
                CANCEL: "#root.update"
              }
            }
          }
        }
      }
    }
  }
}
```

### Expected result

Exiting the state `doSomething.pick` should only trigger the `exit` action.

The console output should be:
```
EXIT: doSomething.pick
```

### Actual result

Exiting the state `doSomething.pick` triggers the `exit` and the `entry` action.

The console output is:
```
EXIT: doSomething.pick
ENTRY: doSomething.pick
```

### Reproduction

https://codesandbox.io/s/polished-moon-8gw0uu?file=/src/index.js

### Additional context

Apparently this is introduced with xstate `4.33.0`, downgrading to `4.32.1` does not show this behaviour

Edit: Updated the console outputs to make things a bit more clear

**Comment by Andarist** [comment]
This was specifically fixed by: https://github.com/statelyai/xstate/pull/3424

Why would you like those actions not to be called?

**Comment by thomasaull** [comment]
@Andarist When I transition from `update.doSomething.pick` to `update.default` why would I want the entry action of the state I'm transitioning away from be called?

**Comment by Andarist** [comment]
Oh, sorry - I've misread the given example. You are totally right, the entry action shouldn't happen here - I've thought that you were routed to the `pick` state through the `.initial` property on its parent.

This feels highly related to https://github.com/statelyai/xstate/issues/3617 . I'm gonna have to fix both in one sweep.

**Comment by thomasaull** [comment]
@Andarist No worries! I feel like I could have simplified the example a bit more, but it could not reproduce in every scenario, so I was happy I had one where it did :)

Thanks!

**Comment by arromeo** [comment]
Opened a PR that I believe fixes this issue. https://github.com/statelyai/xstate/pull/3623

**Comment by Andarist** [comment]
> This feels highly related to https://github.com/statelyai/xstate/issues/3617 . I'm gonna have to fix both in one sweep.

Actually, I probably have linked the wrong issue here. It should have linked to https://github.com/statelyai/xstate/issues/3613
