### ISSUE TITLE
Bug: XState React + Context fails at runtime: `actor.subscribe not a function`

### ISSUE THREAD

**Issue by ac-cb** [statelyai/xstate#3628]
### Description

When attempting to expose an XState invoked service via `useInterpret` through React.context, attempts to use `useSelector` within a child component returns a runtime error where the `actor` object **does not** have a subscribe method.

This seems to occur at the `xstate.init` stage based on interrogating the `Interpreter` object at the `useSelector` callsite when this error occurs.

<img width="884" alt="Screen Shot 2022-10-04 at 2 30 14 PM" src="https://user-images.githubusercontent.com/83252797/193933971-e971b178-2b5a-48bf-9d5e-31ae67860c61.png">

While I am PRETTY sure this is developer/user error, this pattern also seems extremely common and I am surprised this is not more well-documented.

### Expected result

I pretty much expected this to work with React Context since it's a common API.

### Actual result

Runtime error where `actor.subscribe` is not a method prevents the rest of the app from loading.

### Reproduction

https://codesandbox.io/s/mystifying-mestorf-qujj9n?file=/src/index.js

NOTE: this example works, but it DOES illustrate how we're trying to use it. we are looking for ways to debug / reason about what is going wrong

### Additional context

"@xstate/react": "1.6.3"
"xstate": "4.32.0"
"next": "12.2.5"

**Comment by de-perotti** [comment]
@ac-cb hey, I opened up the example project and it seems to be working fine
I expanded on it and add events

https://codesandbox.io/s/zen-galileo-fp2mos

**Comment by ac-cb** [comment]
@de-perotti  you are correct. the issue is specific to how our DOM is laid out. closing

**Comment by kiprasmel** [comment]
@ac-cb , do you recall what the issue was? i'm debugging old code and i'm getting the same error, but for `useActor` instead of `useSelector`

edit: nevermind, turns out that i wrapped my component in another component that included the context provider, but i used the non-wrapped component as the page, instead of the wrapped one, so of course the state machine was not initialized properly..
