### ISSUE TITLE
Bug: Action on internal self-transition only triggered once.

### ISSUE THREAD

**Issue by jsbrain** [statelyai/xstate#3636]
### Description

Consider the following machine:

```ts
export const pullMachine = createMachine(
  {
    context: {
      error: undefined,
      result: undefined,
      pulling: 'inactive',
      pullCount: 0,
    },
    predictableActionArguments: true,
    id: 'records',
    initial: 'idle',
    states: {
      idle: {
        entry: 'resetResultContext',
        on: {
          PULL_START: {
            target: '#records.pulling',
          },
        },
      },
      pulling: {
        after: {
          3000: {
            target: '#records.pulling',
            internal: true,
            actions: 'onPullProgress', // <- Gets only triggered once!
          },
        },
        on: {
          NEW_MESSAGE: {
            target: '#records.triggered',
            actions: 'resetPullContext',
          },
          PULL_STOP: {
            target: '#records.idle',
            actions: 'resetPullContext',
          },
        },
      },
      /** ... */
    },
  },
  {
    actions: {
      onPullProgress: assign({
        pulling: (context, event) => 'active',
        pullCount: (context, event) => context.pullCount + 1,
      }),
    },
  },
);
```

According to [the docs](https://xstate.js.org/docs/guides/actions.html#pure-action:~:text=as%20undefined.-,Actions%20defined%20on%20the%20transition%27s%20actions%20property%20will%20be%20executed.,-An%20external%20transition) the actions should always be executed.

But it only get's executed the first time, not every 3 seconds.

### Expected result

Execute `onPullProgress` every 3 seconds.

### Actual result

`onPullProgress` only executed once.

### Reproduction

https://codesandbox.io/s/recursing-rain-m3gncw?file=/src/index.js

**Comment by davidkpiano** [comment]
Delayed (`after`) transitions only get executed once after a specified amount of time (in this case, 3 seconds).

If you want something to occur on an interval, I recommend invoking a timer callback:

```js
invoke: {
  src: () => (sendBack) => {
    const i = setInterval(() => {
      // ...
      sendBack({ type: 'someEvent' });
    }, 3000);

    return () => { clearInterval(i); }
  }
},
on: {
  someEvent: {
    actions: 'onPullProgress' // will occur every 3000 ms
  }
}
```

**Comment by jsbrain** [comment]
Thanks for the clarification!

Can you give me a more detailed explanation why this is? It kinda feels a little counter-intuitive to me but on the other hand I wouldn't really call me an expert on state machines 😀

**Comment by davidkpiano** [comment]
The previous answer is valid, but if you change your code to:

```diff
          3000: {
            target: '#records.pulling',
-           internal: true,
            actions: 'onPullProgress', 
          },
```

Then you will see that the action does get triggered every 3000 ms, as expected.

The reason it doesn't get triggered multiple times with `internal: true` is because `after` transitions are "sugar" for adding an _entry_ action that sends a delayed event to self. If the transition is internal, the state is never re-entered.

**Comment by Andarist** [comment]
Note though that with the proposed solution (making this transition external) you will **exit** the source state with each of those `after` events. This potentially could lead to some things being called more times than you want (for example invokes would be "restarted", exit actions would be called etc). It's not that external transitions should be avoided and that the advice above is wrong - it's just that you have to be mindful when using this technique to solve this kind of problem. I think that it's safer to use the first advice - use an invoked actor with a timer in it.
