### ISSUE TITLE
Unexpected service invocation after upgrading to xstate@4.33.x

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#3651]
### Description

After upgrading from xstate@4.32.1 to the latest xstate@4.33.6 (the one with `predictableActionArguments`), my machine started behaving differently from before. A callback service gets invoked **again**, after the machine exited the state node with that service invocation.

Reproduction:

**1. With xstate 4.32.1 it works fine:**
https://codesandbox.io/s/funny-wind-gdwpyo

**2. With xstate 4.33.6 the modal dialog cannot be closed:**
https://codesandbox.io/s/nervous-tdd-mje1ws

### Expected result

1. Click Submit.
2. A modal dialog appears. Click Close.
3. The modal dialog is Closed, since the machine transitioned from Idle.Confirming to Idle.DecidingIfDirty.

### Actual result

After clicking the Close button, the modal dialog is NOT Closed.

The machine transitioned to Idle.Dirty but it invoked the `showConfirmation` service again, as can be seen in the console logs.

### Reproduction

https://codesandbox.io/s/nervous-tdd-mje1ws?file=/src/index.js

### Additional context

I found a workaround, albeit very dubious. Specifying the transition on CLOSE as internal prevents this bug.

`
CLOSE: {
  internal: true,
  target: "#form.Idle"
}
`

This prevents us from using external transitions in cases when they are required. Anyway, even when the transition is not internal, the callback service should not be invoked again, since after the `Confirming` state is exited, the machine goes to `Idle.DecidingIfDirty` (and not to `Idle.Confirming`).

**Comment by davidkpiano** [comment]
This problem is no longer present in the latest versions of `xstate` and `@xstate/react`: https://codesandbox.io/s/jolly-gould-d1ho03
