### ISSUE TITLE
Docs: Explain why assign actions must be pure

### ISSUE THREAD

**Issue by jamesbvaughan** [statelyai/xstate#3658]
### Description

The docs for assign actions state that they must be pure, but don't give any justification. As a user working with XState, it would be really useful to understand _why_ assign actions must be pure.

https://github.com/statelyai/xstate/blob/f04d0218b30e7d39a4ff05d1b8633c6b18aab604/docs/guides/context.md?plain=1#L192

Could you add a sentence or two elaborating on this? _Why_ should we keep assign actions pure, and what are the trade-offs and risks of ignoring this advice?

### Expected result

n/a

### Actual result

n/a

### Reproduction

https://xstate.js.org/docs/guides/context.html#assign-action

### Additional context

This bug report template is nice, but it doesn't feel appropriate for a documentation issue like this, and I couldn't find a better way to submit an issue related to documentation.

I know that I could create a discussion for this question, or ask it on Discord, but I'd really like to see the docs improved here, not just to have my question answered one-off.

**Comment by with-heart** [comment]
I'm not entirely sure this is true? I typically try to cause side effects in separate actions but sometimes it only makes sense to cause a side effect when assigning.

An example of this is something I've been working on that involves https://github.com/microsoft/monaco-editor. I want to store an `editor` in context but it has to be created from `context.monaco` (which mutates the stored `Monaco` instance).

```ts
createMachine(
  {
    on: {
      "monaco.initialized": { actions: "createEditor" }
    }
  },
  {
    actions: {
      createEditor: assign({
        editor: ({ monaco }) => {
          const editor = monaco.editor.create(document.getElementById("root")!);
          return editor;
        }
      })
    }
  }
);
```

Maybe that's not what's meant by side effect here

**Comment by with-heart** [comment]
I'm not entirely sure this is true? I typically try to cause side effects in separate actions but sometimes it only makes sense to cause a side effect when assigning.

An example of this is something I've been working on that involves https://github.com/microsoft/monaco-editor. I want to store an `editor` in context but it has to be created from `context.monaco` (which mutates the stored `Monaco` instance).

```ts
createMachine(
  {
    on: {
      "monaco.initialized": { actions: "createEditor" }
    }
  },
  {
    actions: {
      createEditor: assign({
        editor: ({ monaco }) => {
          const editor = monaco.editor.create(document.getElementById("root")!);
          return editor;
        }
      })
    }
  }
);
```

Maybe that's not what's meant by side effect here

**Comment by davidkpiano** [comment]
@with-heart In that case, the `monaco.editor.create(...)` action should be idempotent.
