### ISSUE TITLE
Bug: `@xstate/vue` has wrong typings for `useMachine`

### ISSUE THREAD

**Issue by TheDutchCoder** [statelyai/xstate#3662]
### Description

`useMachine` requires 2 parameters when using `@xstate/vue`, however that should just be one (options is optional).

`xstate` source: https://github.com/statelyai/xstate/blob/main/packages/core/src/interpreter.ts#L308
`@xstate/vue` source: https://github.com/statelyai/xstate/blob/main/packages/xstate-vue/src/useMachine.ts#L50

### Expected result

Not to have to pass a required options argument

### Actual result

Requires an options argument
Example: `const { state, send } = useMachine(machine, {})`

### Reproduction

N/A (Typescript issue)

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by TheDutchCoder** [comment]
I can no longer reproduce this with a simple example.
It might be a Vite caching problem (older version or something), or a typegen issue on the machine.

I will re-open if I run into it again and can isolate the case.
