### ISSUE TITLE
Bug: XState Visualizer Send event doesn't send the desired event

### ISSUE THREAD

**Issue by aaronmcadam** [statelyai/xstate#3663]
### Description

When I try to send an event, nothing happens.

### Expected result

I expect the event to send successfully.

### Actual result

When I try to send an event, nothing happens.

### Reproduction

https://codesandbox.io/s/eager-shaw-c7yxcr?file=/src/index.js

**Comment by davidkpiano** [comment]
Seems to be working (updated to latest versions): https://codesandbox.io/s/eager-shaw-c7yxcr?file=/src/index.js
