### ISSUE TITLE
Bug: Promise is invoked despite transition

### ISSUE THREAD

**Issue by bugii** [statelyai/xstate#3679]
### Description

After updating xState to 4.34.0 and adding ` predictableActionArguments: true`, the method `printDocument` in the example below executes even if the condition above evaluates to true. 

```javascript
import { createMachine, assign, interpret } from "xstate";

const printDocument = (document) => {
  console.log("printing", document);
  return new Promise((res, rej) => setTimeout(res(document), 2000));
};

const userMachine = createMachine({
  predictableActionArguments: true,
  initial: "printing",
  context: {
    documents: ["doc1", "doc2"]
  },
  states: {
    printing: {
      always: {
        target: "done",
        cond: (context) => context.documents.length === 0
      },
      invoke: {
        id: "print",
        src: (context) => printDocument(context.documents[0]),
        onDone: {
          target: "printing",
          actions: assign({
            documents: (context) => context.documents.slice(1)
          })
        }
      }
    },
    done: {
      id: "done",
      type: "final",
      entry: {
        actions: () => console.log("done")
      }
    }
  }
});

interpret(userMachine).start();

```

### Expected result

I am not sure whether this behavior is intended, but I would have expected that the invoke method does not get called if we don't enter the state. Therfore, I would expect `printDocument` to be called with 'doc1' and 'doc2'.

### Actual result

`printDocument` is called a third time with `undefined`

### Reproduction

https://codesandbox.io/s/compassionate-joji-w58mp8?file=/src/index.js

**Comment by Andarist** [comment]
This is the current limitation of `predictableActionArguments`. In v5 (where the only mode will be something close to `predictableActionArguments`) it will be possible for us to not execute actors from states that are immediately left but we were also thinking about dropping this logic altogether. How important this really is in practice and what kind of logic does it allow you to write? Deferring actors' start has some inherent complexity cost to it and we started to question if it's worth it.

**Comment by bugii** [comment]
Thank you for your answer! I am wondering what the best practice would be in the following case:
Essentially what we could do is instead of printing each document individually and then transitioning into the state itself again for the next print, we could invoke a service that takes care of printing all the documents. However, we would like to update the context after each successful print, not just when the whole promise resolves.

The way I would go about solving this is by sending an action during the invocation of the service, yet this feels hacky and requires accessing the statemachine service from the "outside", like so:

```javascript
import { assign, createMachine, interpret } from "xstate";

const printDocument = async (document) => {
  console.log("printing", document);
  return new Promise((res) =>
    setTimeout(() => {
      service.send({ type: "PRINTED", document });
      res(document);
    }, 2000)
  );
};

const printDocuments = async (documents) => {
  console.log("printing documents");
  for (const document of documents) {
    await printDocument(document);
  }
};

const machine = createMachine({
  predictableActionArguments: true,
  initial: "printing",
  context: {
    documents: ["doc1", "doc2"],
    printedDocuments: []
  },
  states: {
    printing: {
      invoke: {
        id: "print",
        src: (context) => printDocuments(context.documents),
        onDone: {
          target: "done"
        },
        onError: {
          target: "done"
        }
      },
      on: {
        PRINTED: {
          actions: assign({
            printedDocuments: (context, event) => [
              ...context.printedDocuments,
              event.document
            ]
          })
        }
      }
    },
    done: {
      type: "final",
      entry: (context) => {
        console.log("done", context);
      }
    }
  }
});

const service = interpret(machine).start();
```


What is the recommended way for such a case?

Code: https://codesandbox.io/s/mystifying-merkle-4k2ecx?file=/src/index.js

**Comment by Andarist** [comment]
This requires a little bit of manual wiring but you can communicate with the parent machine from within the invoked service if you implement it as a callback actor: https://codesandbox.io/s/optimistic-babycat-65lrmv?file=/src/index.js

**Comment by bugii** [comment]
Much appreciated, thank you for your explanation - makes perfect sense! Did not know about the doneInvoke() method 😄

**Comment by Andarist** [comment]
In v5 the actors are created immediately (the `input` is resolved and an actor object is created) but they are not *started* immediately. We only start the actors that were not stopped when we exit the internal loop through always transitions and raised events.

So I think it's fair to say that this issue is being resolved by that and that it can be closed now.
