### ISSUE TITLE
Bug: website - discover with source=landing-page invalid state

### ISSUE THREAD

**Issue by GRASBOCK** [statelyai/xstate#3728]
### Description

When going to **[Visit the Machine Registry](https://stately.ai/registry/discover?source=landing-page)** on the [landing page ](https://stately.ai/). The link is [https://stately.ai/registry/discover?source=landing-page](https://stately.ai/registry/discover?source=landing-page). When removing the `?source=landing-page` it works again --> [https://stately.ai/registry/discover](https://stately.ai/registry/discover)

### Expected result

![expected_stately](https://user-images.githubusercontent.com/31473223/209796948-31a5f6fd-2c73-47de-97e8-aff3a3f44362.png)

### Actual result

![error_stately](https://user-images.githubusercontent.com/31473223/209796858-5f0c4c5f-8996-4a07-865d-5049bd062d7f.png)

### Reproduction

Type it in the browser or press the links in the description.

**Comment by mellson** [comment]
Thank you for noticing; this is now fixed.
