### ISSUE TITLE
Bug: Recreating a state machine does not reset the state machine

### ISSUE THREAD

**Issue by tecfella** [statelyai/xstate#3741]
### Description

I have a function that recreates the state machine every invocation of the function 

```
const config = {
   context: initialContext,
   ....
}

export const someFunction = () => {
     const stateService = interpret(
    createMachine<Context, Event, State>(
      config,
      options
    )
  )
    .onTransition((state) => console.log(state.value, state.event.type))
    .start();
    
    ... do some stuff that takes ages 
    
    stateService.stop();
}
```

When unit testing - between tests I was finding the context was the same as the last test 

I could not find any docs on how to reset??

### Expected result

on recreation of the state machine the context should be reset.

### Actual result

context is the same as it was last touched

### Reproduction

https://codesandbox.io/s/dark-sea-e9n43k?file=/src/index.ts:0-1213

**Comment by tecfella** [comment]
my work around was to create an initial state that when exiting resets the context back to its initial values -- annoyingly if I add to context got to remember to reset new values in this exit function

**Comment by davidkpiano** [comment]
This is because `context` is being mutated. You can avoid this by using `assign()`:

```ts
import { createMachine, interpret, assign } from "xstate";

// ...

const config = {
  id: "machine",
  initial: "inactive",
  context: {
    count: 0
  },
  states: {
    inactive: {
      on: { TOGGLE: "active" },
      entry: assign<ToggleContext>({
        count: context => context.count + 1
      })
    },

    active: {
      on: { TOGGLE: "inactive" },
      entry: assign<ToggleContext>({
        count: context => context.count + 1
      })
    }
  }
};
```

Example: https://codesandbox.io/s/suspicious-bogdan-c5igy3?file=/src/index.ts

See here for reference: https://xstate.js.org/docs/guides/context.html

**Comment by tecfella** [comment]
Thanks worked that out - if the action passed in a copy of context then devs would find out pretty quick they need to use the assign.
