### ISSUE TITLE
Bug: No types on Deno

### ISSUE THREAD

**Issue by guy-borderless** [statelyai/xstate#3764]
### Description

Hello!
when importing xstate in deno like so: 
`import * as xstate from "https://deno.land/x/xstate@xstate@4.35.2/src/index.ts";`

loaded code has no types, probably since xstate doesn't use the _.ts_ file extensions when importing files. 
`import { createMachine, Machine } from './Machine'; `
=>
`import { createMachine, Machine } from './Machine.ts';`

### Expected result

typescript types should be loaded

### Actual result

everything is typed as any

### Reproduction

import * as xstate from "https://deno.land/x/xstate@xstate@4.35.2/src/index.ts";

**Comment by Andarist** [comment]
This will be fixed in the next major version of XState.

**Comment by Andarist** [comment]
We landed the appropriate change on the `next` branch: https://github.com/statelyai/xstate/pull/3765

**Comment by Andarist** [comment]
Actually, while that PR switches the repo to `moduleResolution: node16` and thus to using explicit extensions - it doesn't fix the issue at hand here. The repo is now using `.js` extensions in import sources - but Deno won't understand it as it's actually using `.ts`.

We gonna fix this and provide a way to import XState correctly in Deno but I need to rethink our options.

**Comment by davidkpiano** [comment]
Can you check `xstate@beta` and see if it now has types?

**Comment by guy-borderless** [comment]
importing [xstate](https://deno.land/x/xstate) 5 latest- alpha 6 I see types!
`import * as xstate from "https://deno.land/x/xstate@xstate@5.0.0-alpha.6/src/index.ts"`

**Comment by Andarist** [comment]
How does `deno.land` work today with the recently added support for `node_modules` in deno? It feels to me that, ideally, you shouldn't reach into `/src` sirectory when importing `xstate`.

**Comment by guy-borderless** [comment]
Personally I like that the import is not abstracted, like it is with local imports. Easier to debug and understand imported code IMO. For the main module in deno there is a [mod.ts convention](https://deno.land/manual@v1.32.4/references/contributing/style_guide#do-not-use-the-filename-indextsindexjs). Also, [This is an interesting read](https://deno.com/blog/package-json-support). if I understand correctly the next version of deno will formalize the mod.ts pattern to encourage npm style import with the "deno:" URL scheme. I think the more ESM the better, great ergonomics and less power to npm.

**Comment by davidkpiano** [comment]
Closing as it seems that `xstate@beta` in Deno how provides types 🎉 

Feel free to reopen if some details are still missing about this.

**Comment by Andarist** [comment]
I’d definitely like to figure out a better way for Deno users to consume our package. Relying in the `src` directory isn’t stable and could break for subtle reasons at any time

**Comment by guy-borderless** [comment]
> I’d definitely like to figure out a better way for Deno users to consume our package. Relying in the `src` directory isn’t stable and could break for subtle reasons at any time

[mod.ts](https://deno.land/manual@v1.32.4/references/contributing/style_guide#do-not-use-the-filename-indextsindexjs)

**Comment by guy-borderless** [comment]
npm imports works now 
`import { createMachine } from 'npm:xstate'`

**Comment by davidkpiano** [comment]
> npm import works now `import { createMachine } from 'npm:xstate'`

Great, thanks for the update!
