### ISSUE TITLE
Bug: Docs link on XState homepage isn't working on firefox

### ISSUE THREAD

**Issue by grahamclarkd** [statelyai/xstate#3784]
### Description

The Docs link on https://xstate.js.org/ links to:

"https://xstate.js.org/docs" instead of "https://xstate.js.org/docs/"

The missing slash at the end causes the page not to load for me on a firefox browers.

### Expected result

Expected to navigate to https://xstate.js.org/docs/

### Actual result

No page navigation occurs.

### Reproduction

Seen in live site: https://xstate.js.org/

**Comment by judicaelandria** [comment]
what's your firefox version? 
I'm using the latest(109.O) can't reproduce this

**Comment by grahamclarkd** [comment]
I'm using 109.O as well.

I believe the issue is that i followed a link in some documentation to the http version of the homepage http://xstate.js.org which times out with no response.

Looking at network logging when i now visit the correct https://xstate.js.org homepage and click the docs link i am being linked to https://xstate.js.org/docs, this responds with status code 301 from disk cache. From there I'm redirected to http://xstate.js.org/docs/ which times out with no response.

**Comment by judicaelandria** [comment]
that's weird tho I can't reproduce this even tho I open this link  [https://xstate.js.org/docs](https://xstate.js.org/docs)

**Comment by grahamclarkd** [comment]
Trying it again today i can no longer recreate the issue either. Yesterday i was finding that the http homepage was timing out and not redirecting to the https homepage but that doesnt seem to be the case today.

https://xstate.js.org/docs is still redirecting to http://xstate.js.org/docs/ but this now redirects to https://xstate.js.org/docs/ and the page loads correctly.

Closing as no longer recreatable. Apologies for any time wasted!
