### ISSUE TITLE
Bug: state.nextEvents stays undefined in @xstate/solid

### ISSUE THREAD

**Issue by waspeer** [statelyai/xstate#3809]
### Description

When using the `@xstate/solid` package, `state.nextEvents` is undefined and does not get updated.

### Expected result

I expected it to update with an array of possible next events.

### Actual result

Is stays undefined.

### Reproduction

https://codesandbox.io/s/romantic-dream-49b7li?file=/src/index.tsx

**Comment by waspeer** [comment]
For reference, this was the workaround that worked for me:

```ts
const [state, send, service] = useMachine(machine);
const [nextEvents, setNextEvents] = createSignal([]);

onMount(() => {
  const subscription = service.subscribe((state) => {
    setNextEvents(state.nextEvents);
  });

  onCleanup(() => {
    subscription.unsubscribe()
  });
});
```

**Comment by Andarist** [comment]
cc @GoldingAustin

**Comment by GoldingAustin** [comment]
I'll take a look at this today and add a test case, I'm guessing something wonky is happening with State defining a special get method for 'nextEvents' and pulling that in to the Solid store.
