### ISSUE TITLE
Bug: useActorContext type issues

### ISSUE THREAD

**Issue by mwarger** [statelyai/xstate#3811]
### Description

I have a basic machine that will do a search and report results.  The machine has a service, where at runtime I'm going to supply a TRPC client.

Normally, at runtime I would provide a service:

```
function ClassRevenueBreakdownContainer() {
    const facilityId = useFacilityIdParam();
    const client = useTrpcClient();

    return (
        <RevenueContext.Provider
            machine={() =>
                machine
                    .withContext({
                        start_date: new Date(),
                        end_date: new Date(),
                        facilityId,
                    })
                    .withConfig({
                        services: {
                            searchRevenue: async (context) => {
                                const { start_date, end_date, facilityId } = context;
                                const results =
                                    await client.classes.getClassTypesRevenueBreakdown.query({
                                        facility_id: facilityId,
                                    });
                                return results;
                            },
                        },
                    })
            }
        >
            <div>stuff</div>
        </RevenueContext.Provider>
    );
}
```

However, I end up with two issues.  First is that my default machine config is still requiring this service.

![image](https://user-images.githubusercontent.com/686823/216796892-48e90ca7-25b2-45be-839f-395cf265508e.png)

I won't have this service until I'm within the component, so I don't want to supply it to the initial createActorContext call.

Second, during runtime, I am still seeing a type error for the machine.

![image](https://user-images.githubusercontent.com/686823/216796903-1fe5dd46-b291-4803-9cef-dd4f1e4daf55.png)

I'm working on a repro of this, but I thought I'd ask here in case I'm missing something obvious.  Thanks in advance for anyone that can help me think about this.

### Expected result

I expect to not have to pass the service implementation to the useActorContext creation.  

I also wouldn't expect a type error during the use of `withConfig`.

### Actual result

See reproduction.

### Reproduction

https://github.com/mwarger/trpc-prisma-starter-useActorcontext

### Additional context

xstate - 4.35.4
@xstate/react - 3.1.2

**Comment by Andarist** [comment]
1. The `Provider` should conditionally accept `options` prop - that would allow it to resolve the "final" machine
2. The `createActorContext` shouldn't require all options upfront
