### ISSUE TITLE
Bug: 4.36.0 changes not applied to @xstate/immer assign

### ISSUE THREAD

**Issue by gkiely** [statelyai/xstate#3831]
### Description

The newest release causes typescript errors using assign from @xstate/immer and tsTypes

Is the @xstate/immer library still supported?
If yes,  please apply the new changes to @xstate/immer

### Expected result

No typescript errors

### Actual result

Using @xstate/immer assign
<img width="367" alt="image" src="https://user-images.githubusercontent.com/1948935/218608776-504d0586-c037-4557-9058-381d7e7db4ec.png">
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1948935/218608907-a19820e6-da91-4f3a-bdd7-08c29999b93f.png">

Using xstate assign
<img width="285" alt="image" src="https://user-images.githubusercontent.com/1948935/218608800-cd3e255f-18a4-43ae-b875-096bd5b997f2.png">

### Reproduction

See Additional context

### Additional context

If you need a reproduction I can set one up, but it requires typegen so I couldn't do it through codesandbox.

**Comment by davidkpiano** [comment]
A CodeSandbox reproduction would be appreciated; you can copy-paste the TS types output from typegen directly in the sandbox.

**Comment by gkiely** [comment]
Working version :
https://codesandbox.io/s/wizardly-brook-q5ixzw?file=/src/index.ts

Broken version:
https://codesandbox.io/s/objective-sanne-ftvjhy?file=/src/index.ts

See line 55

**Comment by gkiely** [comment]
Thanks for the quick turnaround @Andarist!
