### ISSUE TITLE
Bug: `Attempted to read state from uninitialized service` warnings logged after machine has stopped on React <18

### ISSUE THREAD

**Issue by giancarlo88** [statelyai/xstate#3847]
### Description

In our use case we have a component, a modal to confirm/cancel, that spins up a state machine with `useMachine`. The modal is rendered conditionally using a local state value in a parent component. The state machine in this case handles deletion of certain values via an API request.

When the state machine is finished with the deletion, it transitions to a final state and also sends an action that uses a callback function (as a prop) to clear the parent's local state and stop the modal from being rendered.

When run, we get multiple warnings logged to the console after the modal is unmounted: 
```
Warning: Attempted to read state from uninitialized service 'delete-modal-machine'. Make sure the service is started first.
```

We've noticed that this warning only seems to be logged on `@xstate/react` versions 3 or above while running React version 17 (the errors don't log on React version 18).

### Expected result

To not see any warnings in the console.

### Actual result

Multiple warnings in the console. This gets logged 5 times per use as well which causes a lot of noise when running unit tests.

### Reproduction

https://codesandbox.io/s/happy-ully-5nctvc?file=/src/state-machine.js

### Additional context

The CodeSandbox replication is as close as I could replicate to our implementation, thankfully I was able to recreate the warnings being logged there. 

```
"@xstate/react": "3.2.1", 
"xstate": "4.36.0", 
"react": "17.0.2", 
"react-dom": "17.0.2"
```

**Comment by davidkpiano** [comment]
With `input` in `xstate@beta`, you can avoid the problem completely. Here is the example (mostly?) rewritten in `xstate@beta`:

https://codesandbox.io/s/wizardly-bohr-wpmqgx?file=/src/state-machine.js:218-299
