### ISSUE TITLE
Bug: spawned actor in lazy context is orphaned with `.withConfig` 

### ISSUE THREAD

**Issue by tmikeschu** [statelyai/xstate#3849]
### Description

If I call `machine.withConfig({ ... })` and `machine` has a lazy context for a spawned child `context: () => ({ child: spawn(childMachine) })`, `child` is orphaned. Maybe orphan is the wrong term, but the parent does not send/forward events correctly. The `child.getSnapshot().event.type` is always `xstate.init` even after the parent sends an event to the child (e.g., `actions: forwardto(ctx => ctx.child)`.

### Expected result

The child's last event should match the one the parent sent.

### Actual result

The child's last event is always `xstate.init`.

### Reproduction

https://codesandbox.io/s/with-context-bug-4pw44k?file=/src/machine.spec.js

^ see the tests tab and tests file to see the two versions of `withConfig`.

### Additional context

I saw that `@xstate/react` was patched recently with a fix for stale spawned actors using `useActor`. I couldn't tell if it's a similar issue.

## Workaround

I wrote a custom `withConfig` wrapper that retains the lazy context and that works (there is a test showing both cases in the codesandbox).

```ts
import { StateMachine } from 'xstate';

/* This honors a lazy context so spawned actors are not orphaned */
export const withConfig = <M extends StateMachine<any, any, any, any, any, any, any>>(
  machine: M,
  config: Parameters<M['withConfig']>[0],
) => {
  return machine.withConfig(config, () => machine.context) as M;
};
```

Apologies if this is expected! I would expect `withConfig` to work fine. I came across this when overriding `sendParent` actions in tests e.g., `machine.withConfig({ actions: { sendParentSuccess: jest.fn() } })`

**Comment by davidkpiano** [comment]
In `xstate@beta`, this is no longer valid since 1) `spawn` can no longer be imported, and 2) `.withContext(...)` is removed.

```ts
export const parentMachine = createMachine({
  id: "parent",
  context: ({ spawn }) => ({
    child: spawn(childMachine, { id: "child" })
  }),
  on: {
    CLOSE: { actions: forwardTo((ctx) => ctx.child) },
    OPEN: { actions: forwardTo((ctx) => ctx.child) },
    LOCKED: {
      actions: () => {
        console.log("locked!");
      }
    }
  }
});
```

I converted most of this example to XState beta: https://codesandbox.io/s/with-context-bug-forked-978odu?file=/src/machines.js
