### ISSUE TITLE
Bug: @xstate/solid not updating arrays properly (createImmutable.ts)

### ISSUE THREAD

**Issue by russiann** [statelyai/xstate#3853]
### Description

I writed this reproducible example:
https://codesandbox.io/p/github/russiann/vite-solid/main?file=%2Fsrc%2Fmain.tsx

Scenario:

When you delete Item 1.
This happens:

![CleanShot 2023-02-23 at 16 23 56@2x](https://user-images.githubusercontent.com/4403429/221009787-2bcddcb5-b128-4403-972a-a2c5508a9f63.png)

Note that Item 3 is duplicated.
If you delete from top to down this duplication happens with other item.

The only way to delete all without bug is from down to top starting from last hehe

I tried to figure out whats happening and I my guess is that `updateStore` function at `createImmutable.ts` is not updating arrays correctly. During debugging I noticed that the loop at line 76 is not applying diff in all indexes it should do. I even tried to fix it somehow but I did not understand the `updateStore` properly (I started to try solidjs these days so I'm newbie) so I create this issue =)

When I return `setStore` instead `setImmutable` at line 109 everything works.

### Expected result

Arrays should be updated correctly

### Actual result

Some indexes are being ignored when updateStore update arrays

### Reproduction

https://codesandbox.io/p/github/russiann/vite-solid/main?file=%2Fsrc%2Fmain.tsx

**Comment by Andarist** [comment]
cc @GoldingAustin

**Comment by GoldingAustin** [comment]
Thanks for the codesandbox! I thought we had fixed this issue, I'll try to tackle this later today
