### ISSUE TITLE
Bug: Inappropriate error message

### ISSUE THREAD

**Issue by 7777chaitanya** [statelyai/xstate#3865]
### Description

Usually, we pass the machine definition to the `useMachine` hook. But, by mistake, I passed the machine definition as a string. It is obvious that it should throw an error message. But I think that this error message is not clear and it is not conveying the reason behind the actual error to the developer.

### Expected result

I am expecting the error message to be more clear like, `useMachine hook accepts only machine definition and it doesn't accept string as a value`

What I mean by machine defintion here is as follows,
1. Either the direct output of `createMachine(machineConfig)`
2. Or the value of `createMachine(machineConfig).withConfig({actions, services, guards})`

### Actual result

The actual error message doesn't clearly imply that the message occured in `useMachine` when the user tried to pass a string to it. 

![image](https://user-images.githubusercontent.com/56331036/221758183-dc4aa3a7-4d63-4ac9-9cc7-d3d560b4f6ca.png)

### Reproduction

https://codesandbox.io/s/xstate-react-template-3t2tg?file=/src/index.js

### Additional context

    "xstate": "^4.35.4"

cc: @davidkpiano @Andarist

**Comment by 7777chaitanya** [comment]
If this is a valid issue, I would like to work on it. Could you please assign this to me?

**Comment by davidkpiano** [comment]
It is not feasible to detect all incorrect usages of all functions in XState, and this also shouldn't be done in runtime, but instead, before then. It is highly recommended to either:

- Use TypeScript, or...
- If using JavaScript, add `// @ts-check` to the top of the file.

Adding `// @ts-check` or using TypeScript will result in a clearer TypeScript error message:

<img width="803" alt="CleanShot 2023-04-13 at 17 55 05@2x" src="https://user-images.githubusercontent.com/1093738/231891826-8a72f74f-db54-4c43-b675-059a96cd0ede.png">
