### ISSUE TITLE
Bug:  some "in" guard state references do not work

### ISSUE THREAD

**Issue by fwienber** [statelyai/xstate#3869]
### Description

`in` guards, similar to `target`, reference another state via a state expression. While this works when using the referenced state's own `id` and for states without an `id` via their "global path" (`#rootNodeId.topLevelStateId.nestedStateId`), it does not work for states with `id` via their global path, nor does it work to reference a state via a non-root parent with an `id`.

Maybe this is intended behavior in `parallel` states? I cannot really imagine, because the direct reference works across parallel nodes, so why should a non-root parent not be addressable?

### Expected result

For nested states `a`, `b` and `c` with `id` `idA`, `idB` and `idC`, respectively, all these state reference expressions should work as the value of an `in` guard:

1. `#idA.b.c`
2. `#idB.c`
3. `#idC`

### Actual result

1. only works when `c` has no `id` (then, of course, 3. is not possible)
2. never works
3. always works

### Reproduction

https://stately.ai/viz/fafd7a49-e09e-4ed0-b420-3f8c5c0fc2db

### Additional context

The linked XState Visualizer example shows four cases:
1. `EVENT_GLOBAL` - a working global path reference (no `id` on sub-state)
2. `EVENT_DIRECT` - a working direct reference
3. `EVENT_GLOBAL_BUG` - a buggy global path reference (`id` on sub-state)
4. `EVENT_NESTED_BUG` - a buggy path reference starting from a "middle" nested state with an `id`

In the simulation, you can see that only when hovering over 1. and 2., the follow-up state `stateA2` is highlighted. When hovering over 3. or 4., nothing happens. When you click on 3. or 4., an error message is shown that the respective state reference could not be resolved.

**Comment by fwienber** [comment]
If someone could give me code pointers and maybe answer some onboarding questions, I'd be willing to help fix this.

**Comment by fwienber** [comment]
If you want this to be based on the SCMXL standard, here is what they say about `in`:

> The set of operators in conditional expressions varies depending on the data model, but all data models must support the 'In()' predicate, which takes a state ID as its argument and returns true if the state machine is in that state. This predicate allows coordination among parallel regions.

https://www.w3.org/TR/scxml/#ConditionalExpressions

So in the spec, `In` is an operator to be used in any guard, not a dedicated property like in xstate JSON. Anyway, since it refers to a state (by ID), xstate JSON should use the same reference syntax as anywhere else.

Are you concerned that this would be a breaking change?

**Comment by davidkpiano** [comment]
`xstate@beta` has been released, and the `stateIn(...)` guard is to be used instead of `in`:

```diff
on: {
  EVENT: {
-   in: '#someState'
+   guard: stateIn('#someState')
  }
}
```
