### ISSUE TITLE
Bug: `@xstate/react` `useInterpret` With Passed State Renders Initially With Initial State

### ISSUE THREAD

**Issue by Alex-Yakubovsky** [statelyai/xstate#3870]
### Description

Hi XState team 👋 ,

When using `useInterpret` with a passed state (e.g., `useInterpret(myMachine, { state: seedState})`) the initial render contains the machine's initial state with initial context. This results in `useSelector` calls missing expected state. I'm using a SSR framework (Remix) and this results in a flash of stale content being displayed to the user.

I've included a small example here: https://codesandbox.io/s/laughing-williamson-wnx1o9

I poked around the source code a bit, I believe this occurs because the service is started within a `useEffect` (and therefore executed after initial render, never server side) here: https://github.com/statelyai/xstate/blob/main/packages/xstate-react/src/useInterpret.ts#L136-L146

I'm likely missing context, is there any reason to not start the service here  https://github.com/statelyai/xstate/blob/main/packages/xstate-react/src/useInterpret.ts#L71? (would need to pass the rehydrated state as well, but that's already available in the scope of this function)

### Expected result

In https://codesandbox.io/s/laughing-williamson-wnx1o9  would expect an out like

```
s2
```

### Actual result

The console output looks like

```
s1
s2
```

### Reproduction

https://codesandbox.io/s/laughing-williamson-wnx1o9

### Additional context

Happy to open a PR around this if someone can fill me in with the missing context

**Comment by davidkpiano** [comment]
Unfortunately this is something that will have to be fixed in v5, which will properly start the interpreter at the specified `state` instead of starting it at the original `initialState`. 

This work is being done in this PR: https://github.com/statelyai/xstate/pull/3743

**Comment by davidkpiano** [comment]
Works as expected with `xstate@beta` (with no code changes!) https://codesandbox.io/s/gracious-christian-83rfrk
