### ISSUE TITLE
Docs: some anchor links not working

### ISSUE THREAD

**Issue by johtso** [statelyai/xstate#3901]
### Description

https://xstate.js.org/docs/packages/xstate-immer/#api

The `#createupdatereventtype-recipe` anchor link on the immer docs page doesn't match the anchor link that gets dynamically produced from the heading of "createUpdater(eventType, recipe)", which actually becomes `#createupdater-eventtype-recipe` with an extra hyphen.

### Expected result

N/A

### Actual result

N/A

### Reproduction

N/A

**Comment by davidkpiano** [comment]
Thanks for the report. Seems like something's off with the way Vuepress (or the relevant plugin) is handling links.

We're moving all the documentation to https://stately.ai/docs though, so this should be "solved" there.
