### ISSUE TITLE
Bug: Spawned machine doesn't start when imported from a module

### ISSUE THREAD

**Issue by vladmaraev** [statelyai/xstate#3929]
### Description

I am trying to prepare my state chart as a module that one can import. But when trying to import it and interpret (through either `interpret` or `useInterpret` everything works fine except the spawned machines). When logging the state I can see that id is assigned to the reference, but there are no children created. I spawn the machine this way:

```
              assign({
                ttsRef: (c: DomainContext) => {
                  return spawn(
                    ttsMachine.withContext({
                      ttsVoice: c.parameters.ttsVoice,
                      audioCtx: c.audioCtx,
                      ttsLexicon: c.parameters.ttsLexicon,
                    })
                  );
                },
              }),
```

On the other hand, everything works as expected from within the module (children machines are created and running).

### Expected result

I expected the machine to start when imported from a module.

### Actual result

Only `id` for a spawned machine is assigned, but no machine is spawned under `children`. 

### Reproduction

https://codesandbox.io/p/sandbox/upbeat-golick-698q7n?file=%2FREADME.md

**Comment by vladmaraev** [comment]
It would be really nice if you can look at this issue.

**Comment by Andarist** [comment]
This reproduction case is **not** runnable. I keep getting into missing deps, misconfigured scripts, etc. Please make sure that there is a single command that I can run there to just get it going.

**Comment by vladmaraev** [comment]
I see, the problem was that I was linking local modules (using `npm link`) and installing dependencies through the codesandbox.io terminal and they were not persistent. I fixed, so now the local module (`packages/core`) is built and linked during the preinstall stage. Please check it now, it seems to be working just if you click "start" in codesandbox. 

This would run the failing case, when program that uses xstate is loaded as a module. You will see that there is only one actor in Stately inspector. 

To run the case where the actors are spawned successfully (without using a module), change start script in the `package.json` in the root folder to `"cd packages/core; yarn start"`. You will then see 3 actors in the inspector.

**Comment by vladmaraev** [comment]
@Andarist is it now possible to run?
