### ISSUE TITLE
Bug: useMachine from @xstate/svelte/lib/fsm not working

### ISSUE THREAD

**Issue by Shyrro** [statelyai/xstate#3938]
### Description

I have a machine that i converted from `xstate` to `@xstate/fsm` and tested it with React, Vue and Svelte. 
Both React and Vue useMachine fsm hooks work, the Svelte one throws an error.

To be sure the issue wasn't coming from my machine, i created a test using the fsm used in the xstate svelte docs.
Same result, it throws this : 

![Issue on stack blitz](https://i.ibb.co/JjYGNJ7/Capture-d-e-cran-2023-03-31-a-16-11-34.png)

EDIT: image seems broken, here is the link : https://i.ibb.co/JjYGNJ7/Capture-d-e-cran-2023-03-31-a-16-11-34.png

We can see the following error in the console : 

```
Function called outside component initialization
    at get_current_component (@xstate_svelte_lib_fsm.js?v=890f19af:1004:15)
    at onDestroy (@xstate_svelte_lib_fsm.js?v=890f19af:1017:7)
    at useMachine (@xstate_svelte_lib_fsm.js?v=890f19af:2532:30)
    at instance (Toggle.svelte:32:27)
    at init (chunk-UJLIVLOQ.js?v=890f19af:1861:23)
    at new Toggle (Toggle.svelte:44:39)
    at createProxiedComponent (svelte-hooks.js?v=890f19af:341:9)
    at new ProxyComponent (proxy.js?v=890f19af:242:7)
    at new Proxy<Toggle> (proxy.js?v=890f19af:349:11)
    at create_fragment (App.svelte:4:42)
```

### Expected result

To instantiate the interpreted machine correctly. 
Maybe onDestroy isn't necessary and the stop can bo done on unmount ?

### Actual result

error thrown in the console as pasted in description

### Reproduction

https://stackblitz.com/edit/vitejs-vite-cskkhs?file=src/lib/Toggle.svelte

### Additional context

EDIT: The hook from `@xstate/svelte/es/fsm` works.

**Comment by fnimick** [comment]
I'm having the same error with a machine created with `xstate`. I am not sure it's fsm related.

A simple fix (for me) was to disable SSR in sveltekit. It seems to run fine on the client.

**Comment by C-4PO** [comment]
This issue is a big blocker for me as well.

**Comment by C-4PO** [comment]
Would this make sense to remove the call to `onDelete`?
```
 const state = readable(service.state, (set) => {
    const subscription = service.subscribe((state) => {
      if (state.changed) {
        set(state);
      }
    })
    
    return () => {
      subscription.unsubscribe();
      service.stop()
    }
  });
```

**Comment by davidkpiano** [comment]
> EDIT: The hook from @xstate/svelte/es/fsm works.

Closing as this is the workaround 👍
