### ISSUE TITLE
Bug: Transition Priority

### ISSUE THREAD

**Issue by ChrisShank** [statelyai/xstate#3973]
### Description

It’s unexpected that wildcard transitions have priority over delayed transitions (`after`).

https://stately.ai/viz/d14c3481-3fb9-446a-8c16-b4ececfc70dd

### Expected result

A delayed transition should be chosen over a wildcard transition.

### Actual result

A wildcard transition is chosen over a delayed transition.

### Reproduction

https://stately.ai/viz/d14c3481-3fb9-446a-8c16-b4ececfc70dd

**Comment by Andarist** [comment]
This is definitely unintentional in the current design of the API.

Tangent question: SCXML actually allows situations like this (since its transitions are an array and not keyed values) - what do you think about that? Should we support this anyhow? Or should more specific descriptors always be treated with a higher priority?

**Comment by ChrisShank** [comment]
maybe “transition priority” is the wrong framing? Delayed transitions (after) have a different trigger than external/raised events (on) and I think it’s confusing different triggers could be enabled by the same event. I wouldn't expect a wildcard transition to be enabled on a “eventless event” (always) either. The fact that delayed transitions or eventless transitions are processed as an event is more of a implementation detail imo. 

I wonder if it’s fair to interpret a wildcard transition to only be enabled by external/raised events and not by any internally generated events?

**Comment by davidkpiano** [comment]
> I wonder if it’s fair to interpret a wildcard transition to only be enabled by external/raised events and not by any internally generated events?

It should be enabled by unhandled events, regardless of if it is internally/externally generated IMO.

I think the bug is transition priority, as demonstrated by adding a `cond: () => false` here: https://stately.ai/viz/b7af11f3-7458-4a87-92a4-184da041c915

There's probably a quick fix for this 🔍

**Comment by davidkpiano** [comment]
This should now work as expected in XState v5.
