### ISSUE TITLE
Bug: Parallel transitions always exit on transition in v5.0.0-beta.7

### ISSUE THREAD

**Issue by lewisl9029** [statelyai/xstate#3974]
### Description

Hi there! I was trying out the latest v5 beta with [Reflame](https://reflame.app/)'s [VSCode extension](https://marketplace.visualstudio.com/items?itemName=reflame.agent) and came cross an issue where parallel states seem to always exit no matter how I specify the transition to try to prevent it. Here's a sandbox reproducing the issue: https://codesandbox.io/s/cranky-dhawan-b16zyc?file=/src/index.js

In my extension, it causes infinite loops due to invoked actors existing prematurely and re-entering and executing side effects.

### Expected result

Parallel states should not exit when transitioning within the same state unless `reenter` is true.

### Actual result

Both parallel states end up exiting.

### Reproduction

https://codesandbox.io/s/cranky-dhawan-b16zyc?file=/src/index.js

**Comment by Andarist** [comment]
Does this behavior differ from v4? We are still hashing out how `reenter`+`parallel` should work together

**Comment by davidkpiano** [comment]
Thanks for the reproduction!

This may be confusing but it's actually expected behavior. The `reenter: false` flag is only for the state where the transition is specified. Since no transitions are found in the child states for that event, the algorithm _exits_ those states since it now needs to check the parent.

Here is an illustration:

<img width="916" alt="CleanShot 2023-04-23 at 12 58 03@2x" src="https://user-images.githubusercontent.com/1093738/233853671-2f4853a2-e452-4fab-a6fa-b3dbc0e6e3d9.png">

The workaround is to specify the transition on each state, which will give the expected behavior:

```ts
const machine = createMachine({
  id: "machine",
  type: "parallel",
  // on: {
  //   transition: {
  //     reenter: false,
  //     // all of these cause both states to exit
  //     // target: ".right.transitioned"
  //     // target: "#machine.right.transitioned"
  //     // target: ["#machine.right.transitioned", "#machine.left"]
  //     target: [".right.transitioned", ".left"]
  //   }
  // },
  states: {
    left: {
      exit: ({ event }) => console.log("exited left due to event", event),
      on: {
        transition: {}
      }
    },
    right: {
      initial: "initial",
      exit: ({ event }) => console.log("exited right due to event", event),
      states: {
        initial: {},
        transitioned: {}
      },
      on: {
        transition: ".transitioned",
        reenter: false
      }
    }
  }
});
```

https://codesandbox.io/s/mystifying-hugle-jozqgt

**Comment by lewisl9029** [comment]
@davidkpiano @Andarist appreciate the follow up! The reason I thought this was a bug was because it's a breaking change from how internal transitioned worked in v4. 

Take a look at this sandbox: https://codesandbox.io/s/elated-stallman-4liby6?file=/src/index.js

Note that neither of the states exit when specifying a target within the state for a transition specified at a parent.

I'm glad this can be worked around by specifying tighter scoped transitions, but I would much prefer the previous behavior to be preserved if possible. 

Part of it is that it'd force me to refactor a _ton_ of transitions to upgrade, but the other part is (as you alluded to) it just doesn't feel intuitive that a transition to the same state should cause it to exit, regardless of where it's specified. 

One of things that prompted me to attempt the upgrade was the move to make all transitions internal by default (whereas previously it defaulted to external), which sounded like an awesome improvement to ergonomics since I had to manually specify `internal: true` in so many transitions before, but this new behavior feels like a step backwards since it's no longer even possible to transition a parallel child state from the parent without causing it to exit.

**Comment by lewisl9029** [comment]
@davidkpiano @Andarist I gave the beta another shot earlier today and this particular breaking change has caused me the most pain _by far_.

It's forcing me to rewrite every state node that looks like this in v4:

```js
    status: {
      initial: "initial",
      on: {
        "config.none": {
          actions: assign({
            config: undefined
          }),
          target: "#config.status.none",
          internal: true
        },
        "config.invalid": {
          actions: assign({
            config: undefined
          }),
          target: "#config.status.invalid",
          internal: true
        },
        "config.valid": {
          actions: assign({
            config: (context, event) => event.config
          }),
          target: "#config.status.valid",
          internal: true
        }
      },
      states: {
        initial: {},
        none: {},
        invalid: {},
        valid: {
          initial: "inner",
          states: {
            inner: {
              exit: (context, event) => console.log("exited inner", event)
            }
          }
        }
      }
    }
```
([sandbox here](https://codesandbox.io/s/green-sun-3t83ny?file=/src/index.js), note that there's no exited log)

... into monstrosities like this in v5 in order to preserve the previous behavior:

```js
    status: {
      initial: "initial",
      states: {
        initial: {
          on: {
            "config.none": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.none"
            },
            "config.invalid": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.invalid"
            },
            "config.valid": {
              actions: assign({
                config: ({ context, event }) => event.config
              }),
              target: "#config.status.valid"
            }
          }
        },
        none: {
          on: {
            "config.none": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.none"
            },
            "config.invalid": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.invalid"
            },
            "config.valid": {
              actions: assign({
                config: ({ context, event }) => event.config
              }),
              target: "#config.status.valid"
            }
          }
        },
        invalid: {
          on: {
            "config.none": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.none"
            },
            "config.invalid": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.invalid"
            },
            "config.valid": {
              actions: assign({
                config: ({ context, event }) => event.config
              }),
              target: "#config.status.valid"
            }
          }
        },
        valid: {
          on: {
            "config.none": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.none"
            },
            "config.invalid": {
              actions: assign({
                config: undefined
              }),
              target: "#config.status.invalid"
            }
          },
          initial: "inner",
          states: {
            inner: {
              exit: ({ event }) => console.log("exited inner", event)
            }
          }
        }
      }
    }
```
([sandbox here](https://codesandbox.io/s/crazy-shamir-jybwxp?file=/src/index.js). If we use the same structure as v4, inner ends up exiting as can be seen in [this sandbox](https://codesandbox.io/s/long-wind-tyhiel?file=/src/index.js).)

I haven't seen any way around having to duplicate transitions in each child node like this to prevent the `inner` node from exiting (there are a bunch of long-running processes that are rather expensive to restart nested in there). Maybe I'm missing something?

Putting this migration on pause for now since refactoring every node like this isn't really workable. Keeping my fingers crossed that either there's a workaround or this behavior ends up getting changed before v5 reaches stable. 🙏
