### ISSUE TITLE
Bug: Subscribe callback gets re-called infinitely in tight loop when exception is thrown in 5.0.0-beta

### ISSUE THREAD

**Issue by lewisl9029** [statelyai/xstate#4004]
### Description

See repro here: https://codesandbox.io/s/magical-burnell-roiyht?file=/src/index.js
Uncomment the `throw` inside the subscribe callback to see the browser pane become completely unresponsive.

Make sure to open the _browser_ console beforehand if you want to see the infinitely repeating logs. Opening it after the infinite loop starts seems to be too late to capture any logs (likely because the page itself is busy being stuck in a tight loop), the Codesandbox logs also show nothing (likely for the same reason).

### Expected result

Exception will be logged, callback doesn't get re-called infinitely in a tight loop.

### Actual result

Callback gets re-called infinitely in a tight loop.

### Reproduction

https://codesandbox.io/s/magical-burnell-roiyht?file=/src/index.js

**Comment by Andarist** [comment]
We are aware of this issue. I believe that @davidkpiano has already run into this once 😅 We'll take care of it soon

**Comment by Andarist** [comment]
This was fixed by https://github.com/statelyai/xstate/pull/4145
