### ISSUE TITLE
Bug: Interpret execute false doesn't listen for spawned actor transitions

### ISSUE THREAD

**Issue by vipero07** [statelyai/xstate#4037]
### Description

If using a spawned actor in xstate and passing the `{execute: false}` flag to the interpreter spawned children never trigger a parent transition and are thus never executed.

https://codesandbox.io/s/crimson-tree-sey9h6?file=/src/index.ts

### Expected result

Uncomment lines 64-68 on https://codesandbox.io/s/crimson-tree-sey9h6?file=/src/index.ts

The typescript is incorrect here because actor refs are actually just the same as an interpreted machine.

### Actual result

Spawned children don't transition if execute false. This is either a failing of the typescript or a failing of spawned actor transitions not propagating to the parent.

### Reproduction

https://codesandbox.io/s/crimson-tree-sey9h6?file=/src/index.ts

### Additional context

```
"xstate": "^4.37.2"
```

**Comment by Andarist** [comment]
What's your use case for the `execute: false`? IIRC, we are removing it in the next major version

**Comment by vipero07** [comment]
Ironically, the example on the old docs. I'm actually using it to execute actions on animation frames. I have somewhat large machines that are composed of many smaller machines and without the request animation frame fix it actually halts the main thread of the application on resource weak systems. I tried using very short sendto delays and transition delays but those seem to be more of a hack than a proper solution.

**Comment by Andarist** [comment]
Could you share a code snippet that would closer resemble your use case?

**Comment by vipero07** [comment]
This is kinda close... but really my actors are a lot more complicated.

https://codesandbox.io/s/friendly-wildflower-f8pj5x?file=/src/index.ts

Almost all the actors I've got have parallel states and the "grand_child_machine" is actually spawning the "child_machine" in my case. What I have is roughly an actor and the item and section actors for https://schema.org/Menu where each child can get their own relevant information (note the recursion).

**Comment by vipero07** [comment]
I'm not sure I follow the question. Yes, I can detect if I'm running on the hardware, but doing so doesn't address this particular issue.

Ultimately the problem comes down to spawning a number of complex actors in an array in a single assign action can halt the main thread.

There are a few other problems I've come across with the execute false, request animation frame pattern too. Like `internal:false` transitions not functioning correctly.

Honestly a better solution than doing all this execute false request animation stuff would probably be a different interpreter that handles spawns asynchronously.

**Comment by Andarist** [comment]
This option was removed in v5 (see [here](https://github.com/statelyai/xstate/pull/1203)) so we don't plan to address any issues with it.

> Ultimately the problem comes down to spawning a number of complex actors in an array in a single assign action can halt the main thread.

We plan to investigate the performance of actor creation etc but there will always be some upper limit of what runtime can handle. Any custom async behavior can be built on top of XState, so I believe a workaround is possible here.

**Comment by seanlennaerts** [comment]
> This option was removed in v5

This detail is missing in the migrating to v5 doc and couldn't find it in any of the other docs (v4 or v5). Looks like this issue and the linked pr are the only places this is documented. Might be worth adding - am happy to open a pr if this is a desired change.
