### ISSUE TITLE
Bug: Warning: Attempted to read state from uninitialized service `MACHINE_NAME`. Make sure the service is started first.

### ISSUE THREAD

**Issue by anonymouscatcher** [statelyai/xstate#4070]
### Description

Hi,

Still I get this warning, I'm using xstate with react, I know the reason, probably in `useInterpret` the service starts in `useEffect` or somewhere after first render. because when I use `interpret(machine).start()` directly in constructor or in a function not after first mount, it works without any warning.
but don't you want to fix this? 

### Expected result

.

### Actual result

.

### Reproduction

.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox.

**Comment by anonymouscatcher** [comment]
I'll try to reproduce it in a sandbox and share it here.

**Comment by anonymouscatcher** [comment]
But this is what I'm talking about.
https://github.com/statelyai/xstate/blob/679a84eee468a9c4b359b68eff3e82d60aab6fe0/packages/xstate-react/src/useInterpret.ts#L138

**Comment by Andarist** [comment]
No actual repro case has been provided here so it's hard for me to investigate this specific problem. If you manage to create a repro case, let me know - I can always reopen this issue.
