### ISSUE TITLE
Bug: onDone not getting called when all child states are final

### ISSUE THREAD

**Issue by newyork-anthonyng** [statelyai/xstate#4072]
### Description

1. Fill out "Name" field
1. Click "Submit" button. There is an error that the Category is missing
1. Select an option for the "Category" and "Network" dropdowns
1. Click "Submit" button

### Expected result

The states are all in a "final" state. The "onDone" transition should be called and put us into the "Creating" state.

### Actual result

We are still in the "Ready" state. All of the child nodes are in the "Submitting" state.

### Reproduction

https://codesandbox.io/s/ondone-demo-26sy9n

### Additional context

If I ignore step 2 from above, then we transition to the "Creating" state.

1. Fill out "Name" field
1. Select an option for the "Category" and "Network" dropdowns
1. Click "Submit" button

I'm not sure why the addition of the "Submit" button click would cause any issues.

Also, if I add a self-transition in the "Submitting" state ([see here](https://codesandbox.io/s/ondone-demo-26sy9n?file=/src/machine.js:588-804)), then it transitions to the "Creating" state.
```diff
Name: {
  initial: "Ready",
  states: {
    Ready: {
      // ...
        Submitting: {
          type: "final"
+            on: {
+              SUBMIT: {
+                 target: "Submitting"
+              }
+            }
              Error: {}
            },
            // ...
          },
```

**Comment by Andarist** [comment]
See the discussion [here](https://github.com/statelyai/xstate/discussions/3639). @davidkpiano I think this should become recursive in v5 (and thus it should deviate from SCXML), what do you think?

**Comment by Andarist** [comment]
This was addressed by https://github.com/statelyai/xstate/pull/4358
