### ISSUE TITLE
Bug: [v5] `state` object passed to `subscribe` method does not expose event that triggered the transition 

### ISSUE THREAD

**Issue by bhvngt** [statelyai/xstate#4074]
### Description

in v4, [state](https://xstate.js.org/docs/guides/states.html#state-definition) object passed to `onTransition` method was exposing `event` object that triggered the transition.

in v5, `event` object is not available within `state` object passed to `subscribe` method. 

Its quiet useful to access event that triggered the transition. Is there any other way to access this information?

### Expected result

Expecting `event` object triggering the transition to be available within `subscribe` method.

### Actual result

`event` is not exposed in v5 `subscribe` method which as per [docs](https://stately.ai/docs/xstate-v5/migration#use-subscribe-for-changes-not-ontransition) replaces v4 `onTransition` method

### Reproduction

https://codesandbox.io/s/nostalgic-lichterman-7252dt?file=/src/index.ts

**Comment by bhvngt** [comment]
I am basically using this to create a trace of all the transitions (including transitions happening within child actors if any) to help me debug state transitions across root and invoked or spawned actors. This becomes quiet important when multiple machines are at play. I include triggering event as part of transition information.

Here's a the trace function that used to work quiet well for me in v4 with the help of `rxjs` [expand](https://rxjs.dev/api/operators/expand) operator

```typescript
```export function createTrace$<T extends ActorRef<any>>(service: T) {
  const subscriptions: string[] = [];
  let seqId = 0;
  return from(service).pipe(
    map((state) => {
      seqId += 1;
      return {
        seqId, machineId: state.machine?.id, parentState: undefined,
        state, event: state.event, context: state.context,
        depth: 0, path: state.machine?.id + ":" + state.value, timestamp: new Date(),
        ...toStr, toJSON() {
          return toJSON<typeof state>(this);
        }
      } as TransitionInfo<typeof state>;
    }),

    expand(({ state, path, parentState }) => {
      const child$ = Object.entries(state.children)
        .filter(([childKey, childService]) =>
          !subscriptions.includes(`${state.machine?.id}.${childKey}`) && (childService instanceof Interpreter)
        )
        .map(([childKey, childService]) => {
          seqId += 1;
          subscriptions.push(`${state.machine?.id}.${childKey}`);
          const childStateMapper = (childState: any) => {
            const childPath = `${path} -> ${childState.machine?.id}:${childState.value}`;
            return ({
              seqId, machineId: childState.machine?.id, parentState: { ...state, parentState },
              state: childState, event: childState.event, context: childState.context,
              depth: path.split("->").length, path: childPath,
              timestamp: new Date(),
              ...toStr, toJSON() {
                return toJSON<typeof state>(this);
              }
            }) as TransitionInfo<typeof state>;
          };
          return from(childService as ActorRef<any>).pipe(map(childStateMapper));
        });
      return merge(...child$);
    }));
}⏎

**Comment by Andarist** [comment]
> I am basically using this to create a trace of all the transitions (including transitions happening within child actors if any) to help me debug state transitions across root and invoked or spawned actors.

That's something that we plan to solve with the inspection API. For the time being, I'd suggest u to patch the `send` method like this:
```ts
export function createTrace$<T extends ActorRef<any>>(service: T) {
  // ...
  const original = service.send
  let lastEvent = event;
  service.send = function (event) {
    lastEvent = event
    return original.call(this, event)
  }
  // ...
}
```

This way you should be able to track almost the same information as you did in v4. Remember that you might have to patch this similarly on child actors since you are tracking those as well.

**Comment by bhvngt** [comment]
> That's something that we plan to solve with the inspection API.

That will be super. 

> For the time being, I'd suggest u to patch the `send` method like this:

Thanks a ton for the example. This should work fine for me till inspection API is published.

**Comment by davidkpiano** [comment]
This is now solved by the inspection API:

```ts
const actorRef = createActor(machine, {
  inspect: (inspEvent) => {
    if (inspEvent.type === "@xstate.event") {
      console.log("EVENT:", inspEvent.event);
    }
  },
});
```

Documentation coming soon. For now, here is the updated code: https://codesandbox.io/p/sandbox/happy-http-n5j83w?file=%2Fsrc%2Findex.ts%3A41%2C1-47%2C4
