### ISSUE TITLE
Bug: [v5] callback actor isn't getting cleaned up when another actor is spawned

### ISSUE THREAD

**Issue by rostero1** [statelyai/xstate#4077]
### Description

In the following example you'll see that the existence of `otherRef` prevents the socketRef's cleanup from being executed.  This is made more evident by assigning socketRef a systemId.

### Expected result

No errors and the cleanup function of socketRef to be executed.

### Actual result

- An error:  Actor with system ID 'next' already exists.
- Cleanup function isn't called, which is evident by the logs.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-u8lam3

**Comment by Andarist** [comment]
Thanks for testing out v5 and reporting the problem! I see what's going wrong, gonna fix this in a moment.
