### ISSUE TITLE
Shebang in workflow examples breaks Quokka execution

### ISSUE THREAD

**Issue by RainerAtSpirit** [statelyai/xstate#4087]
This is more like a just for information issue as it has an easy workaround.

https://github.com/statelyai/xstate/blame/59e372d152168cfdbd33b6de0cb5f3297f8475b7/examples/workflow-accumulate-room-readings/main.ts#L1

```
Failed to instrument ./main.ts 
> 1 | #!/usr/bin/env vite-node --script 
```

Workaround: Delete or comment out the line before you run with quokka.

**Comment by Andarist** [comment]
removed them in https://github.com/statelyai/xstate/pull/4089
