### ISSUE TITLE
Bug: Sending an event to an actor ref in context does not work as described in the docs

### ISSUE THREAD

**Issue by charislam** [statelyai/xstate#4115]
### Description

As described in the [v4 docs on the `sendTo` action](https://stately.ai/docs/xstate/actions/built-in-actions#sending-events-to-actors), `sendTo` can take an actor ref from context, which was created using `spawn`.

But the example doesn't work: I copied and pasted the example, added just enough code to make it run (see repro), and the spawned machine doesn't receive the `PING` event.

There is a workaround which does work, directly calling the _spawned_ machine's bound `send` by accessing it via the `ref`. Doing this, I do see the response to the `FIZZ` event.

### Expected result

Console log:

```
received some event
PONG
received some other event
BUZZ
```

### Actual result

Console log:

```
received some event
received some other event
BUZZ
```

### Reproduction

https://codesandbox.io/s/hardcore-austin-gssq95?file=/src/index.js

**Comment by davidkpiano** [comment]
The `sendTo` action is not imperative; it is an action creator that returns an action object.

Function actions are fire-and-forget actions; their result is discarded.

The example should be rewritten like this:

```ts
// instead of:
// (context) => sendTo(context.someRef, { type: "PING" })
sendTo(context => context.someRef, { type: 'PING' })
```

See here for a working example: https://codesandbox.io/s/epic-panka-dfsq64

**Comment by charislam** [comment]
Thanks! That makes a lot of sense.

But as a follow-up question, wouldn't that make the [example in the docs](https://stately.ai/docs/xstate/actions/built-in-actions#sending-events-to-actors) wrong?

```
SOME_EVENT: {
          actions: (context) =>
            sendTo(context.someRef, { type: 'PING' }),
        },
```
