### ISSUE TITLE
Bug: waitFor can not found in 5.0.0-beta.18

### ISSUE THREAD

**Issue by zhanglongqi** [statelyai/xstate#4144]
### Description

I can not find `waitFor` in `5.0.0-beta.18` like the example described, https://stately.ai/blog/2022-05-03-whats-new-may-2022#waitfor

![image](https://github.com/statelyai/xstate/assets/956693/db6b14c9-8ee9-4ef5-80de-8323a8adbbe5)

### Expected result

the file should be there, or can list in the migration doc

### Actual result

the file is missing.

### Reproduction

no need

**Comment by davidkpiano** [comment]
The `waitFor(...)` function is exported at the top-level:

```ts
// import { waitFor } from 'xstate/lib/waitFor' // v4
import { waitFor } from 'xstate' // v5
```

We will add this to the migration docs. Thanks for making us aware!
