### ISSUE TITLE
Bug: running machines from serialized definition results in unexpected behavior regarding service invocation

### ISSUE THREAD

**Issue by 94tx** [statelyai/xstate#4152]
### Description

When running machines from a serialized definition, states invoking actors have their actors invoked twice.

### Expected result

![image](https://github.com/statelyai/xstate/assets/113658863/f62cb4d2-62d6-4d0d-8fb5-004bd0a57d1a)

In the example machine (also in the reproduction code), one would expect `service-1` and `service-2` to be fired exactly once.

### Actual result

In the example machine (also in the reproduction code), `service-1` and `service-2` get fired twice, with XState outputting the following warning:

```
Warning: Event "done.invoke.invoke-4qkv9" was sent to stopped service "Test". This service has already reached its final state, and will not transition.
Event: {"type":"done.invoke.invoke-4qkv9"}
```

### Reproduction

https://codesandbox.io/s/inspiring-microservice-s7h4ny

### Additional context

**XState version:** 4.38.1

**Comment by pixtron** [comment]
The call to `JSON.stringify(machine)` duplicates the `invoke` properties to `activities`:
Eg: 
```json
"invoke-first": {
  "id": "Test.invoke-first",
  "key": "invoke-first",
  "activities": [
    {
      "src": {
        "type": "service-1"
      },
      "id": "invoke-43uy5",
      "type": "xstate.invoke"
    }
  ],
  "invoke": [
    {
      "src": {
        "type": "service-1"
      },
      "id": "invoke-43uy5",
      "type": "xstate.invoke"
    }
  ]
},
```

If activities are removed the machine works as expected.

```ts
const newMachine = createMachine(
  JSON.parse(JSON.stringify(machine, (key, val) => key === "activities" ? [] : val)),
  machineOpts
)
```

**Comment by mellson** [comment]
I think the problem here is that when the machine is rehydrated, the entire machine is passed to `createMachine`. It should only be the machine config that is passed along with the options:
```js
// Don't pass the full machine to createMachine
createMachine(JSON.parse(JSON.stringify(machine)), machineOpts);

// Only pass the config
createMachine(JSON.parse(JSON.stringify(machine.config)), machineOpts);
```

I think this should make it work as expected? Test an [updated code sandbox here](https://codesandbox.io/s/stupefied-wu-5dn6y9?file=/src/index.js:1593-1641).
