### ISSUE TITLE
Bug: Svelte subscription to machine initially returning undefined in v5

### ISSUE THREAD

**Issue by mjamesderocher** [statelyai/xstate#4160]
### Description

When using XState v5 beta with the latest stable version of Svelte, the subscription to the interpreted machine returns `undefined`. If there is any activity in the machine, then the subscription works. I have tested with the latest stable version of XState and the subscription works on the initial state.

### Expected result

The subscription should start with an initial state of the machine.

### Actual result

The subscription returns `undefined`

### Reproduction

https://github.com/mjamesderocher/xstate-v5-svelte-bug

**Comment by Andarist** [comment]
This was a deliberate change done in https://github.com/statelyai/xstate/pull/3877 . It's a big assumption on Svelte's side in their types that the subscription gets called synchronously. The API itself doesn't prescribe that after all. It also doesn't work "well" with RxJS as mentioned in the Svelte docs [here](https://svelte.dev/docs/svelte-components#script-4-prefix-stores-with-$-to-access-their-values): 
> For interoperability with RxJS Observables, the .subscribe method is also allowed to return an object with an .unsubscribe method, rather than return the unsubscription function directly. Note however that unless .subscribe synchronously calls the subscription (which is not required by the Observable spec), Svelte will see the value of the store as undefined until it does.

To contrast this with other libraries... SolidJS doesn't make such an unsafe assumption in their types: https://github.com/solidjs/solid/blob/039cf60d602f8ed396832d1c06fc6c975f423bbc/packages/solid/src/reactive/observable.ts#L91

I feel like an explicit util from `@xstate/svelte` should be used together with our actors to make them compatible with Svelte's stores. This is an integration layer that can bridge the gap between both worlds.

**Comment by mjamesderocher** [comment]
Ok. That makes sense. I see that there is already a note about this in the migration guide, which I missed: https://stately.ai/docs/xstate-v5/migration#use-actorgetsnapshot-to-get-actors-state

So I will close this issue.

Thanks for explaining this to me!
