### ISSUE TITLE
Bug: State Not Executed in State Machine

### ISSUE THREAD

**Issue by infra403** [statelyai/xstate#4174]
### Description

I have a state machine with the following states: task1, task2, task3, task4, success, and failure. I have services associated with each of these states that perform certain tasks.

Everything works as expected until the state machine transitions to the task4 state. At this point, I noticed that the task4 service executes correctly, but the state machine appears to transition to the success state before the task4 service is finished.

### Expected result

I expected the task4 service to fully complete before the state machine transitions to the success state.

### Actual result

The state machine transitions to the success state before the task4 service is completed.

### Reproduction

https://codesandbox.io/s/relaxed-cherry-lymjxf

**Comment by Andarist** [comment]
> I expected the task4 service to fully complete before the state machine transitions to the success state.

As far as I can tell this is exactly what happens. Take a look at the `cond` that I added [here](https://codesandbox.io/s/strange-hoover-vcf695?file=/src/index.ts:894-1033) and the overall console.log sequence. Perhaps the fact that you are logging `savedState` in `executePlugin` created some confusion here because that value might be not updated yet when the `executePlugin` creates a new task.

**Comment by infra403** [comment]
I've been using cond for orchestration, but in real-world scenarios, possibly due to extended execution times, there are still tasks that don't complete correctly after a long time. I've been troubled by this issue for a long time now. Do you have any other solutions or recommendations?

**Comment by infra403** [comment]
From logging, I discovered that the onEvent function has printed logs, but the service was not invoked using invoke.

**Comment by infra403** [comment]
> > I expected the task4 service to fully complete before the state machine transitions to the success state.
> 
> As far as I can tell this is exactly what happens. Take a look at the `cond` that I added [here](https://codesandbox.io/s/strange-hoover-vcf695?file=/src/index.ts:894-1033) and the overall console.log sequence. Perhaps the fact that you are logging `savedState` in `executePlugin` created some confusion here because that value might be not updated yet when the `executePlugin` creates a new task.

I created a state machine through JSON configuration and services. The problem might be that the state machine is not correctly parsed or executed. Is there any way I can debug the execution flow of xstate?

**Comment by Andarist** [comment]
It's hard to tell how to debug this without having a solid repro case. I can also offer scheduling a call with you to get to the bottom of this - if that's something that you'd be interested in.

**Comment by Andarist** [comment]
I'm going to close this as part of cleaning up issues for housekeeping purposes. However, please don't hesitate to respond here or in another issue - I will reopen this if you feel like the issue has not been addressed in full.
