### ISSUE TITLE
Bug: onDone not being called when childMachine is done

### ISSUE THREAD

**Issue by nhibrex** [statelyai/xstate#4212]
### Description
`onDone` is not invoked when child machine is in final state

#### Parent machine
```
....
CHILD_STATE : {
    invoke: {
        src: childMachine
        onDone: "DONE"
    }
...
```
#### Child machine
```
const childMachine = createMachine(
...
id: "machineId",
    initial: "STEP1", // Only call parent onDone if in active state
    context: defaultContext,
    states: {
      active: {
        after: {
          3000: { target: 'DONE' } // This correctly calls parent onDone after 3 seconds
        }
      },
      STEP1: {
        on: {
          CONTINUE: {
            target: "STEP2",
          },
          BACK: {
            target: "DONE", // This does not call parent onDone when invoking send("BACK") to this target
          },
        },
      },
      STEP2: {
        on: {
          BACK: "STEP1",
          CONTINUE: {
            target: "DONE",
          },
        },
      },
      DONE: {
        type: "final",
      },
...)
```

### Expected result

Expecting onDone on parent machine to be invoked when child is in final state

### Actual result

onDone on parent machine is not called when state transition into final state from a `send()` event.

### Reproduction

https://codesandbox.io/s/optimistic-chandrasekhar-p5r7y9?file=/src/index.js:0-1808

### Additional context

"xstate": "^4.31.0",

**Comment by with-heart** [comment]
Hi @nhibrex 👋 

The problem here is that `useMachine(childMachine)` isn't referring to the _invoked child_ of the parent, it's starting an actor for an entirely new instance of `childMachine`. 

That's why the child machine in `ChildComponent` starts in `STEP1` without having been invoked and why the `BACK` event doesn't affect the parent.

Here's a diagram that shows what's happening:

```mermaid
flowchart TB
  parent{{"useMachine(parentMachine)"}} -.- parentMachine(parentMachine) --- pending -- next --> child_state
  child_state -. invokes .- childMachine(childMachine)

  child{{"useMachine(childMachine)"}} -.- childMachine1(childMachine) --- STEP1 -- BACK --> DONE
```

There are a couple of options you could use to solve this problem:

1. Manually forward events to the child using [`forwardTo`](https://stately.ai/docs/xstate/actors/parent-child-communication#forwardto)
    
    Add an `id` to the `invoke` config and configure each event for the state to be forwarded to the invoked child. 

    https://codesandbox.io/s/focused-fog-h5qxgy?file=/src/index.js:1115-1279

1. Automatically forward events using [`autoForward`](https://stately.ai/docs/xstate/actors/parent-child-communication#autoforward)

    Using `autoForward` in the `invoke` config will cause _all_ events sent to `parentMachine` to also be sent to the invoked machine, meaning you can send `BACK` (or `CONTINUE`) to `parentMachine` and it will be sent to the invoked `childMachine`.

    https://codesandbox.io/s/focused-fog-h5qxgy?file=/src/index.js:1137-1162

1. Spawn the child using [`spawn`](https://stately.ai/docs/xstate/actors/spawn)

	Spawning the child allows us to store a reference to its actor in `context` and then use that reference with `useActor` to access the child's `state` and `send`.

    This is the closest to your original solution and allows treating the spawned child as a first-class actor, just like the parent.

    https://codesandbox.io/s/focused-fog-h5qxgy?file=/src/index.js:1896-1897

**Comment by nhibrex** [comment]
Thank you @with-heart ! This is super helpful info. I think all 3 codesandbox links have the same code. Do you mind updating?

**Comment by nhibrex** [comment]
Thank you @with-heart ! 
I also notice passing in `data` with invoke does not assign the context to the child machine. Anythought?
```
// parent machine
...
invoke: {
        src: childMachine,
        data: {
            someData: (ctx, evt) => ctx.someData // child machine context does not get this.
        },
        onDone: "DONE",
    }
...
```

**Comment by davidkpiano** [comment]
Thanks for answering as always, @with-heart!

Closing this as invalid; feel free to reopen if there is a bug.
