### ISSUE TITLE
Bug: getSnapshot().value does type does not represent the machine schema.

### ISSUE THREAD

**Issue by dmitriid** [statelyai/xstate#4229]
### Description

The question is for v5 (`5.0.0-beta.26`)

`actor.getSnapshot().value` is typed as `string | StateValue` which does not reflect the actual state schema, and defaults to `string` in TypeScript.

You can cast it to `StateValue`, but then the next nested state defaults to `string` etc.

Example: (let's take a toy nested state machine): https://codesandbox.io/s/fervent-blackburn-kd3667?file=/src/index.ts 

- `actor.getSnapshot().value` is an object, however, Typescript defaults it to string.
- you can cast it to StateValueMap, but then actor.getSnapshot().value.state1 defaults to string
- you can cast it to StateValueMap, but then actor.getSnapshot().value.state1.child_1_1 defaults to string
   even if it's an object etc.

### Expected result

If it is possible within the Typescript type system, the type for `actor.getSnapshot().value` should reflect the actual state machine.

If this is impossible, this should be reflected in the docs.

### Actual result

As described in `Description`

### Reproduction

https://codesandbox.io/s/fervent-blackburn-kd3667?file=/src/index.ts

**Comment by davidkpiano** [comment]
Thanks for the report. Getting the `StateValue` is not yet possible, but it may be soon, and/or with typegen (cc. @Andarist for clarification)

**Comment by Andarist** [comment]
We just landed this as a new feature: https://github.com/statelyai/xstate/pull/4498 . Note that it requires you to use the `setup` API (that was also recently introduced to v5)

**Comment by dmitriid** [comment]
This is brilliant, thank you!
