### ISSUE TITLE
Bug: Typo in Method Name (StateNode.ts)

### ISSUE THREAD

**Issue by PaulJPhilp** [statelyai/xstate#4254]
### Description

The function 'toSerializableAction' is spell incorrectly (see below):

const **toSerializableActon** = (action: UnknownAction) => {

toSerializableActon is use 5 times in the file StateNode.ts

### Expected result

const **toSerializableAction** = (action: UnknownAction) => {

### Actual result

const **toSerializableActon** = (action: UnknownAction) => {

### Reproduction

Read the code in core/src/StateNode.ts

### Additional context

I found this error while reviewing the code (not while running or testing).

**Comment by 7777chaitanya** [comment]
I just checked the entire code base and I don't find any function with the name `toSerializableActon`. Could you please reconfirm if  this exists or not @PaulJPhilp ?
