### ISSUE TITLE
Update Vue3 examples - e.g. todo-mvc-vue

### ISSUE THREAD

**Issue by Simonl9l** [statelyai/xstate#4259]
I'm very impressed so far with what xstate has going on here! Thanks for maintaining this repo!

per `package.json`:
https://github.com/statelyai/xstate/blob/a171ea15100f027eb883c20735767181443e3887/examples/todo-mvc-vue/package.json#L8-L23
vs:
```json
{
"dependencies": {
    "@xstate/inspect": "^0.8.0", // <-- "^0.4.1"
    "@xstate/vue": "^2.0.0", // <-- "^0.6.0"
     "nanoid": "^3.3.4",
    "todomvc-app-css": "^2.4.2", 
    "todomvc-common": "^1.0.5", 
     "vue": "^3.3.4", // <-- "^3.2.37",
     "xstate": "^4.38.2" <-- "^4.32.1"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.3.1" // <-- "^1.10.2"
    "@vue/compiler-sfc": "^3.3.4", // <-- "^3.2.37",
    "typescript": "^5.2.2", // <-- "^4.7.4"
    "vite": "^4.4.9", // <-- "^2.9.13"
    "vue-tsc": "^1.8.8" // <-- "^0.2.3"
  }
}
```
The  code comes up with a lot of errors. For newbies that are typing to understand it would be great of these samples can be bolted into our new implementation so we can boot out dev processes, given we may have started with an `npm create vite@latest my-vue-app -- --template vue`.

Updates to these examples would be most helpful and apprecaited!

Thanks

**Comment by davidkpiano** [comment]
> I note that you have dropped bunch of examples in the [next](https://github.com/statelyai/xstate/tree/next/examples) branch (V5). Is the intention to not have Vue based samples vs react? Would be good to have vue (and other supported frameworks) versions equivalent of the react samples so one can compare approaches and best practices for each framework.

Yes, the intention is to have the React examples done in Vue as well.

**Comment by davidkpiano** [comment]
Closing for housekeeping 🧹 we will be updating the examples for other frameworks soon.
