### ISSUE TITLE
Bug: Warnings on unmount while in action handler

### ISSUE THREAD

**Issue by jashworth** [statelyai/xstate#4296]
### Description

xstate: 4.38.2
@xstate/react: 3.2.2

xstate may issue unwarranted warnings if, when executing an action handler, the machine to which it belongs is reinitialized, typically as a result of the component that created it being unmounted.

### Expected result

no warnings

### Actual result

"Warning: Attempted to read state from uninitialized service '(machine)'. Make sure the service is started first."

### Reproduction

https://codesandbox.io/s/nameless-dust-9vsd63?file=/src/App.tsx

### Additional context

codesandbox includes workarounds

**Comment by jashworth** [comment]
"bug" may be a bit strong but current behaviour doesn't seem quite right

**Comment by davidkpiano** [comment]
XState v5 beta seems to do the right thing; can you confirm? https://codesandbox.io/s/4296-with-xstate-v5-beta-x4gzl6?file=/src/CustomDialog.tsx

**Comment by jashworth** [comment]
Yep looks good there.

**Comment by davidkpiano** [comment]
Great; we've feature-frozen XState v4 so we probably won't be devoting effort to making any changes there (except for high-priority bug fixes) as we're focusing on releasing XState v5. Thanks for the report/confirmation!
