### ISSUE TITLE
Bug: v5 does not error on missing actions

### ISSUE THREAD

**Issue by inverted-capital** [statelyai/xstate#4297]
### Description

When I load up a machine, I expect the supplied actions and guards to be checked to ensure the machine was supplied with everything it needs.

### Expected result

The machine should be checked at startup, or at the very least when it gets to call an action that is missing, an error should be thrown rather than a silent skip.

### Actual result

Machine just casually moves on to the next state like nothing happened

### Reproduction

https://stackblitz.com/edit/w71t4z?file=machine.js

### Additional context

This reproduction shows a machine loading but missing its action, and there is no error when that state is passed.

**Comment by davidkpiano** [comment]
Would a warning suffice? E.g. something like:

> Missing action implementations: 'doSomething', 'doSomethingElse'

**Comment by inverted-capital** [comment]
Absolutely. Anything but silence 🤐

**Comment by Substancia** [comment]
Is this up for grabs? If so, I would like to take this up.

**Comment by davidkpiano** [comment]
> Is this up for grabs? If so, I would like to take this up.

Feel free! Always happy to have more contributors.

**Comment by Substancia** [comment]
Hi @davidkpiano , raised a PR for this, can you please take a look? TIA!

**Comment by Andarist** [comment]
@inverted-capital we recommend using the `setup` API. With it, you are "forced" to prepare all implementations so not providing some of them is not even an option.

**Comment by davidkpiano** [comment]
Relevant docs, for now: https://stately.ai/docs/machines#typescript
