### ISSUE TITLE
Bug: @xstate/test transitions give resulting state, not starting state

### ISSUE THREAD

**Issue by inverted-capital** [statelyai/xstate#4310]
### Description

When supplying functions in the system under test, which are supposed to get called on the transitions during the test path, a state parameter is provided.  I thought this was supposed to be the state before the transition is made, but it is the state after the transition.  This seems illogical since my system under test should not have been transitioned yet, and so I want to read my model to know what the state of the system is.  Once the transition has been taken in the model I cannot figure this out.

### Expected result

The state prior to the transition being taken should be supplied.

### Actual result

The result of having taken the transition.

### Reproduction
https://stackblitz.com/edit/stackblitz-starters-fgxewa?file=index.js

### Additional context

This might be related to the same kind of issue in https://github.com/statelyai/xstate/issues/4302

**Comment by davidkpiano** [comment]
Which version of `@xstate/test` is this? Can you provide a code repro?

**Comment by inverted-capital** [comment]
Sorry - `@xstate/test": "1.0.0-beta.4` - I'll set up a repro.
I was mostly wanting to confirm that this behaviour is in error, and not intended, and it sounds unintentional

**Comment by inverted-capital** [comment]
repro: https://stackblitz.com/edit/stackblitz-starters-fgxewa?file=index.js

**Comment by davidkpiano** [comment]
This is actually by design.

We've changed the way that paths are output so that instead of (`currentState` + `event`), it is (`event` + `nextState`). 


![CleanShot 2023-09-06 at 00 42 32](https://github.com/statelyai/xstate/assets/1093738/dbe8ecac-d296-4de6-bf8e-bec99eb70320)

See here: https://github.com/statelyai/xstate/pull/4238

**Comment by inverted-capital** [comment]
But sir !  If I am moving my SUT along with the paths, then I need to know what state my SUT is in currently before I act on it.  I can't get that if you don't give me the current state, so how can I manipulate the SUT effectively given that this is the only time in the testing framework that I am told what event I am to transition the SUT thru ?

**Comment by davidkpiano** [comment]
> But sir ! If I am moving my SUT along with the paths, then I need to know what state my SUT is in currently before I act on it. I can't get that if you don't give me the current state, so how can I manipulate the SUT effectively given that this is the only time in the testing framework that I am told what event I am to transition the SUT thru ?

It shouldn't be much different. The first event is an "init" event, which you can ignore or use to do some setup, and then assert that the SUT is in the initial state.

And then for each path step, the testing library is executing an event (we already asserted the previous state) and then asserting that we result in the next state that results from that event.

We're just shifting by one; this shouldn't affect the test strategy. If you can share some code that demonstrates where this may be a problem, I'd be happy to look at it.

**Comment by inverted-capital** [comment]
It would be my pleasure to share the pain this causes us 🤣 
So on [this line](https://github.com/dreamcatcher-tech/ether-dream/blob/89930948de1a04bce03daa0b018ec18ce3f070b7/test/sut.js#L140) we had to workaround this change by storing the current state whenever it is asserted using a `*` state assertion, and [this line](https://github.com/dreamcatcher-tech/ether-dream/blob/89930948de1a04bce03daa0b018ec18ce3f070b7/test/sut.js#L210C12-L210C12) is where we need to use the state we are currently in to determine how to apply the event we just received.

In our machine we have the concept of a cursor that tells us which item is currently focused.  Events can cause this to change, and so we need to read it from the state machine each time to make sure it is the correct value.

Given that you guys saw some value in the past to give us the current state as well as the event, would it be so bad as to give us both current and next ?  I do not understand the benefits of giving us the resulting state - are there some code examples I can see that show this utility ?

Or, perhaps if there was a way to get the previous state out of the next state that we were given, then I could stop bleating ?  It just feels wrong to have to store the current state each time in this manner.  If I have the current state and an event, I can easily transition the state to the next state if I need it, but it doesn't seem I can go backwards nearly as easily ?

**Comment by inverted-capital** [comment]
As far as the importance of using the `init` event, that could be represented in your diagram by having the initial state of the machine and the `init` event occuring first, then the starting state of the post init machine being state 0:

![image](https://github.com/statelyai/xstate/assets/69952973/42691e86-2471-4621-8dee-7e804c7ab30d)

**Comment by davidkpiano** [comment]
> I did read the explanation given in #4238 but it sounded like it helped you guys internally more than it helped me as a consumer

It was mostly to simplify the API for consumers actually, since ideally a path would just be an array of (event, nextState) and the idea for testing is that you would:

1. Execute the event
2. Assert the state
3. Goto 1

I don't want to revert to the old way since I think having this structure makes things easier (both for us and consumers), but I understand that each step in the path may be missing some important information for your testing. So which would be better?

**Option A: include `previousState`**
```ts
interface Step {
  previousState?: State; // undefined if first step
  event: EventObject;
  state: State;
}
```

**Option B: include `nextEvent`**
```ts
interface Step {
  event: EventObject;
  state: State;
  nextEvent?: EventObject; // undefined if last step
}
```

**Comment by davidkpiano** [comment]
> As far as the importance of using the `init` event, that could be represented in your diagram by having the initial state of the machine and the `init` event occuring first, then the starting state of the post init machine being state 0:
> 
> ![image](https://user-images.githubusercontent.com/69952973/276741702-42691e86-2471-4621-8dee-7e804c7ab30d.png)

This wouldn't work because there is no state before the "initial event" (sort of a pseudo-event).

**Comment by inverted-capital** [comment]
Option A pretty please 🎁 

Apologies about the initial event misunderstanding - I thought the initial state was the state machine before any init action had gone in, since I can declare a state machine, and this (in my mind at least) is the initial state before any init actions have transitioned it, which I may or may not have reacted to.
