### ISSUE TITLE
Bug: During the ongoing execution of the exit action, the state machine has already transitioned to the next state.

### ISSUE THREAD

**Issue by howard-57blocks** [statelyai/xstate#4311]
### Description

```javascript
import {createMachine, interpret} from "@xstate/fsm";
let service;
// Edit your machine(s) here
const machine = createMachine({
    id: "machine",
    initial: "inactive",
    states: {
        inactive: {
            exit: 'inactiveExitAction',
            on: { TOGGLE: "active" }
        },
        active: {
            on: { TOGGLE: "inactive" }
        }
    }
}, {
    actions: {
        inactiveExitAction: (context,) => {
            console.log('inactiveExitAction', service.state.value)
        }
    }
});

service = interpret(machine).start()
service.send({type: 'TOGGLE'})
``` 

the output is `inactiveExitAction active`
why is not `inactiveExitAction inactive` ?

the doc says

An entry/exit action means “execute this action on any transition that enters/exits this state”. Use entry/exit actions when the action is only dependent on the state node that it’s in, and not on previous/next state nodes or events.

I am not sure if this is a bug

I am using the @xstate/fsm@2.1.0

### Expected result

the output should be `inactiveExitAction inactive`

### Actual result

 inactiveExitAction active

### Reproduction

https://codesandbox.io/s/cool-oskar-jscsc7?file=/src/index.js

**Comment by davidkpiano** [comment]
This behavior is fixed in XState v5 beta (`xstate@beta`): https://codesandbox.io/s/damp-wave-4frjj9?file=/src/index.js
