### ISSUE TITLE
Bug: Interpreter.onEvent() type without Generics

### ISSUE THREAD

**Issue by tuotuo-cloud** [statelyai/xstate#4342]
### Description

In version 4.38.2, when I use Interpreter.onEvent((event) =>  {  // do something  }), I want to use the payload data carried by event(in fact, I actually could access to payload data), but the typescript throw an error cause the event type without the Generics TEvent.

### Expected result

`
export declare class Interpreter<TContext, TStateSchema extends StateSchema = any, TEvent extends EventObject = EventObject, TTypestate extends Typestate<TContext> = {
    value: any;
    context: TContext;
}, TResolvedTypesMeta = TypegenDisabled> implements ActorRef<TEvent, State<TContext, TEvent, TStateSchema, TTypestate, TResolvedTypesMeta>> {
...
 onEvent(listener: EventListener<TEvent>): this;
...
}
`

### Actual result

`
export declare class Interpreter<TContext, TStateSchema extends StateSchema = any, TEvent extends EventObject = EventObject, TTypestate extends Typestate<TContext> = {
    value: any;
    context: TContext;
}, TResolvedTypesMeta = TypegenDisabled> implements ActorRef<TEvent, State<TContext, TEvent, TStateSchema, TTypestate, TResolvedTypesMeta>> {
...
 onEvent(listener: EventListener): this;
...
}
`

### Reproduction

https://codesandbox.io/s/vigilant-mccarthy-s8s3x8

**Comment by davidkpiano** [comment]
As we are working on releasing XState v5, this is unlikely to be addressed in v4 soon, but this is a simple workaround:

```ts
const service = interpret(machine).onTransition((state) => {
  console.log(state.value);
//                 vvvvvvvvvvv
}).onEvent((event: ToggleEvent) => {
  console.log(event.data);
});
```

Curious: what is your use-case for `.onEvent()`? This is removed in XState v5 beta (there's a more general inspection API for that); I want to make sure your use-case is covered though.

**Comment by tuotuo-cloud** [comment]
My machine need to be used in several components.
Each component may make different UI interaction for same event.
So I use onEvent to perceive my machine's events.

now, I replace onEvent with onTransition, it also meets my needs(I can get event's payload through onTransition((state) => state.event.data)), and it carry the Generics TEvent😄

**Comment by tuotuo-cloud** [comment]
> As we are working on releasing XState v5, this is unlikely to be addressed in v4 soon, but this is a simple workaround:
> 
> ```ts
> const service = interpret(machine).onTransition((state) => {
>   console.log(state.value);
> //                 vvvvvvvvvvv
> }).onEvent((event: ToggleEvent) => {
>   console.log(event.data);
> });
> ```
> 
> Curious: what is your use-case for `.onEvent()`? This is removed in XState v5 beta (there's a more general inspection API for that); I want to make sure your use-case is covered though.

**Comment by tuotuo-cloud** [comment]
> My machine need to be used in several components. Each component may make different UI interaction for same event. So I use onEvent to perceive my machine's events.
> 
> now, I replace onEvent with onTransition, it also meets my needs(I can get event's payload through onTransition((state) => state.event.data)), and it carry the Generics TEvent😄

My machine need to be used in several components.
Each component may make different UI interaction for same event.
So I use onEvent to perceive my machine's events.

now, I replace onEvent with onTransition, it also meets my needs(I can get event's payload through onTransition((state) => state.event.data)), and it carry the Generics TEvent😄

**Comment by tuotuo-cloud** [comment]
> As we are working on releasing XState v5, this is unlikely to be addressed in v4 soon, but this is a simple workaround:
> 
> ```ts
> const service = interpret(machine).onTransition((state) => {
>   console.log(state.value);
> //                 vvvvvvvvvvv
> }).onEvent((event: ToggleEvent) => {
>   console.log(event.data);
> });
> ```
> 
> Curious: what is your use-case for `.onEvent()`? This is removed in XState v5 beta (there's a more general inspection API for that); I want to make sure your use-case is covered though.

My machine need to be used in several components.
Each component may make different UI interaction for same event.
So I use onEvent to perceive my machine's events.

now, I replace onEvent with onTransition, it also meets my needs(I can get event's payload through onTransition((state) => state.event.data)), and it carry the Generics TEvent😄
