### ISSUE TITLE
Bug: Covid-Tracker sample in documentation shows error: idle.failure, empty select list

### ISSUE THREAD

**Issue by jafin** [statelyai/xstate#4359]
### Description

Repro:
Navigate to https://xstate.js.org/docs/examples/covid-tracker.html
Attempt to use the tracker but note the Country selector is empty.

![image](https://github.com/statelyai/xstate/assets/127927/782d757b-9826-44a7-801c-19156d5a2e9d)

### Expected result

Expect the demo to operate.

### Actual result

As noted above, the select list, is empty.
The State machine says: `idle.failure`

### Reproduction

See above repro steps

### Additional context

Browser tested was Chrome 118.

**Comment by davidkpiano** [comment]
Thanks for the report. This is an example submitted externally that may be using some outdated APIs. At least it properly modeled the error state as `idle.failure` 😅 

We will be making updated examples for XState v5, which you can find in this directory: https://github.com/statelyai/xstate/tree/next/examples
