### ISSUE TITLE
Bug: @xstate/solid not updating arrays properly (createImmutable.ts)

### ISSUE THREAD

**Issue by leonwilly** [statelyai/xstate#4369]
### Description

First off thank you for an amazing open sourced library. I know the title is a duplicate of bug #3853 . That was done intentionally as it seems the fix for the issue did work however it only works if the arrays are different sizes or the length is divisible by two. 

### Expected result

Given these two arrays as an example
```javascript
const next = [4,3,2,1,0]
const prev = [1,2,3,4,5]
```
The output should be `[4,3,2,1,0]`

### Actual result

However the current output is 
```javascript
[4,3,3,1,0]
```

 The issue lies in the for loop here 

https://github.com/statelyai/xstate/blob/98f9f9165df328bba68622b69ec46dada0e3a4f7/packages/xstate-solid/src/createImmutable.ts#L56-L59C8

```typescript
      // Diff array
      for (let start = 0, end = largestSize - 1; start < end; start++, end--) {
        diff(next[start], prev[start], [...path, start] as Path);
        diff(next[end], prev[end], [...path, end] as Path);
      }
```

In this loop both `start` and `end` are incremented / decremented on each iteration.  Because of the use of th `<` operator the start and end will miss the center value in an odd length array.  

## Example
```typescript
const next = [4,3,2,1,0]
const prev = [1,2,3,4,5]
for (let start = 0, end = next.length - 1; start < end; start++, end--) {
  console.log(`start: ${start}, next[start]: ${next[start]}, prev[start]: ${prev[start]}`)
  console.log(`end: ${end}, next[end]: ${next[end]}, prev[end]: ${prev[end]}\n`)
  if (next[start] !== prev[start]) prev[start] = next[start]
  if (next[end] !== prev[end]) prev[end] = next[end]
}
console.log(`updated: [${prev}]`)
```

The above code will output the following

```bash
start: 0, next[start]: 4, prev[start]: 1
end: 4, next[end]: 0, prev[end]: 5

start: 1, next[start]: 3, prev[start]: 2
end: 3, next[end]: 1, prev[end]: 4

updated: [4,3,3,1,0]
```

As you can see because `start` and `end` don't converge the 3rd element in the `next` array doesn't get assigned to the updated state. 

One solution would be to change `start < end` to `start < end + 1` then add a conditional equality check between the two diff operations for `start === end` and break the loop.

The other is obviously using a traditional unidirectional for loop. So I thought I would compare the approaches and see which one preformed better.  

```javascript
import { Bench } from 'tinybench';
const bench = new Bench();

function diff1(prev, next) {
  const state = [...prev];
  for (let start = 0, end = next.length - 1; start < end; start++, end--) {
    if (next[start] !== prev[start]) state[start] = next[start]
    if (next[end] !== prev[end]) state[end] = next[end]
  }
  return state;
}

function diff2(prev, next) {
  const state = [...prev];
  for (let start = 0, end = next.length; start < end; start++) {
    if (next[start] !== prev[start]) state[start] = next[start]
  }
  return state;
}

function diff3(prev, next) {
  const state = [...prev];
  for (let start = 0, end = next.length - 1; start < end + 1; start++, end--) {
    if (next[start] !== prev[start]) state[start] = next[start]
    if (start == end) break;
    if (next[end] !== prev[end]) state[end] = next[end]
  }
  return state;
}

function randomPrevAndNext() {
  return [Array.from({length: 5}, () => Math.floor(Math.random() * 100)), Array.from({length: 5}, () => Math.floor(Math.random() * 100))]
}


bench.add("diff fixed multidirection", diff3.bind(null, ...randomPrevAndNext()))
bench.add("diff multidirection broken", diff1.bind(null, ...randomPrevAndNext()))
bench.add("diff unidirection", diff2.bind(null, ...randomPrevAndNext()))
await bench.run();
console.table(bench.table());
```

I used a randomly generated array of length 5 to eliminate any caching or JIT optimizations that would have skewed the results. 

```bash
┌─────────┬──────────────────────────────┬──────────────┬───────────────────┬──────────┬─────────┐
│ (index) │          Task Name           │   ops/sec    │ Average Time (ns) │  Margin  │ Samples │
├─────────┼──────────────────────────────┼──────────────┼───────────────────┼──────────┼─────────┤
│    0    │ 'diff fixed multidirection'  │ '13,478,123' │ 74.19430570991092 │ '±1.52%' │ 6739062 │
│    1    │ 'diff multidirection broken' │ '13,588,260' │ 73.59293492150188 │ '±0.84%' │ 6794131 │
│    2    │     'diff unidirection'      │ '13,700,434' │ 72.99038840504755 │ '±0.94%' │ 6850218 │
└─────────┴──────────────────────────────┴──────────────┴───────────────────┴──────────┴─────────┘
```

I think 0 & 2 are basically the same in performance as running this multiple times will flip flop the winner randomly. Personally I would go with the unidirectional comparison as it's less code. 

### Reproduction

Not necessary

**Comment by Andarist** [comment]
I'm OK with the unidirectional approach. I'm not quite sure why this is written like this in the first place today (cc @GoldingAustin ). Would you like to open a PR to fix this?

**Comment by leonwilly** [comment]
Unfortunately it's a bit more complicated than that. While the unidirectional approach does work it breaks reactivity and it's not straight forward to fix it. I did isolate the problem causing the broken reactivity but ultimately I elected to write my own useMachine and useActor that do not use a sync store and work similar to `@xstate/react` where you use a signal to choose what you want to be reactive vs forcing a full state diff and adding a pretty decent amount of overhead.  In many cases i'm only looking for state changes or a specific property in the context on a single component.

**Comment by davidkpiano** [comment]
> Unfortunately it's a bit more complicated than that. While the unidirectional approach does work it breaks reactivity and it's not straight forward to fix it. I did isolate the problem causing the broken reactivity but ultimately I elected to write my own useMachine and useActor that do not use a sync store and work similar to `@xstate/react` where you use a signal to choose what you want to be reactive vs forcing a full state diff and adding a pretty decent amount of overhead. In many cases i'm only looking for state changes or a specific property in the context on a single component.

I'd like to see this approach; seems like avoiding a full state diff would be more beneficial.

**Comment by GoldingAustin** [comment]
> > Unfortunately it's a bit more complicated than that. While the unidirectional approach does work it breaks reactivity and it's not straight forward to fix it. I did isolate the problem causing the broken reactivity but ultimately I elected to write my own useMachine and useActor that do not use a sync store and work similar to `@xstate/react` where you use a signal to choose what you want to be reactive vs forcing a full state diff and adding a pretty decent amount of overhead. In many cases i'm only looking for state changes or a specific property in the context on a single component.
> 
> I'd like to see this approach; seems like avoiding a full state diff would be more beneficial.

Here is a relevant thread from the original PR for why we took this approach: https://github.com/statelyai/xstate/pull/2932#discussion_r889494285. Ultimately, to get deep fine-grained reactivity, we need to do a diff every time. There is a performance hit compared to directly updating the exact path, but it's still very fast.

Solid has a [from](https://www.solidjs.com/docs/latest/api#from) utility that can be used on any machine/actor/service to provide similar updates that you'd see in `@xstate/react` by wrapping it in a signal.

**Comment by GoldingAustin** [comment]
Thanks for the detailed look into this @leonwilly!

If we update these lines: https://github.com/statelyai/xstate/blob/06e4de0b99238446014df46312a409637d914e57/packages/xstate-solid/src/createImmutable.ts#L56-L59

To this, similar to one of your suggested fixes:
```typescript
      for (let start = 0, end = largestSize - 1; start <= end; start++, end--) {
        diff(next[start], prev[start], [...path, start] as Path);
        if (start === end) break;
        diff(next[end], prev[end], [...path, end] as Path);
      }
```

It passes all tests including a few new ones based on your examples

**Comment by Andarist** [comment]
@GoldingAustin would you be interested in turning this into a PR?
