### ISSUE TITLE
Bug: Issue with statemachine in v5

### ISSUE THREAD

**Issue by ShravanSunder** [statelyai/xstate#4397]
### Description

It doesn't seem like waitFor is working and waiting for a transition.  
I expect the second snap output to be `light`.  It stays `green` and the `waitFor` timesout
```ts

const lightMachine = createMachine(
  {
    /** @xstate-layout N4IgpgJg5mDOIC5gF8A0IB2B7CdGgBsBLKACwBd8QAHLWI8orDKgD0QFoA2dAT067I0IYmXIA6KACcwYFkhp0GTeaHYIALACY+iABwBGcQGYtWgJwGArOYDs5rQdsa9Q9KIriPlBbXqNmNkRtXQQDPS5xLg0DB1s9ewAGY0SNISEgA */
    id: 'light',
    initial: 'green',
    states: {
      green: {
        // action referenced via string
        entry: 'alertGreen',
        on: {
          // action referenced via object
          CLICK: 'light',
        },
      },
      light: {
        entry: ['alertGreen'],
        invoke: {
          src: myMachine,
        },
      },
    },
  },
  {
    actions: {},
  }
);


const actor = createActor(lightMachine);
const snap1 = actor.getSnapshot()
console.log('------------')
console.log('lets do this');
console.log('can', snap1.can({ type: 'CLICK' }));
console.log('can2', snap1.can({ type: 'CLICdK' }));
console.log('output', snap1.output);

actor.send({ 'type': 'CLICK' })
// console.log(answer);
await waitFor(actor, (snapshot)=> snapshot.matches('green'));
const snap2 = actor.getSnapshot();
console.log('snap2', snap2);
```

i'm using v5 beta 27

### Expected result

I expect the second snap output to be `light`.  

### Actual result

it stays green or timesout because of waitFor

## Reproduction

https://codesandbox.io/s/lively-silence-kc5f2t?file=/src/index.ts

### Additional context

![2023-10-25 1038 Brave Browser Notifications](https://github.com/statelyai/xstate/assets/5294949/f783cd04-2045-4e94-a166-e3259087721e)

**Comment by ShravanSunder** [comment]
@davidkpiano any idea why this woudln't work?

**Comment by davidkpiano** [comment]
> @davidkpiano any idea why this woudln't work?

Yes, you didn't start the actor yet. Make sure to call `actor.start()`

**Comment by ShravanSunder** [comment]
doh 🤣  !  @davidkpiano  thank s so much!
