### ISSUE TITLE
Bug: v5 onDone is not called by fromPromise when completed

### ISSUE THREAD

**Issue by ShravanSunder** [statelyai/xstate#4409]
### Description

- When a invoked promise finishes and type is not final, 
   - the onDone callback is not called.  only onShapshot is.
- Also when the state is final, 
   - the fromPromise return value is not part of the state machine's output.  It does not call onShapshot either.

### Expected result

The onDone should be called according to the docs https://stately.ai/docs/invoke#ondone

### Actual result

onDone is not called

### Reproduction

https://codesandbox.io/s/currying-brook-3hym5g?file=/src/index.ts

### Additional context

![2023-10-27 1045 Brave Browser 0 0 0 08787xstate-test](https://github.com/statelyai/xstate/assets/5294949/d8e3313a-6ce7-47dd-a5db-995dda5aa4a5)

**Comment by davidkpiano** [comment]
I see that you're calling `actor.stop()`, which will recursively stop all actors in the system. That is why `onDone` is not getting called.

If it is a different problem, then let's reopen the issue and discuss.
