### ISSUE TITLE
Bug[v5] An inline child actor cannot be persisted.

### ISSUE THREAD

**Issue by zavx0z** [statelyai/xstate#4410]
### Description
```
<script>
	import { createMachine, assign, createActor } from "xstate"

const rootMachine = createMachine({
  context: {
    atoms: {},
  },
  on: {
    "actor.put": {
      actions: assign(({ context, event, spawn }) => {
        const { atoms } = context
        atoms["atom"] = spawn(event.params.atom, event.params.options)
        return { ...context, atoms: { ...atoms } }
      }),
    },
  },
  initial: "idle",
  states: {
    idle: {},
  },
})

const actor = createActor(rootMachine, { systemId: "root-actor" })
actor.subscribe((state) => {
  console.log(actor.getPersistedState())
})
actor.start()

const childMachine = createMachine({
  initial: "idle",
  states: {
    idle: {},
  },
})

actor.send({ type: "actor.put", params: { atom: childMachine, options: { systemId: "child-id", id: "child" } } })

</script>
<h1>xstate</h1>

```
### Expected result

```
  VITE v4.5.0  ready in 3801 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
{
  value: 'idle',
  status: 'active',
  error: undefined,
  historyValue: {},
  matches: [Function: bound matches],
  toStrings: [Function: bound toStrings],
  output: undefined,
  context: { atoms: {} },
  children: {}
}
Error: An inline child actor cannot be persisted.
    at Object.getPersistedState (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/raise-b69a3d16.development.cjs.js:1441:13)
    at StateMachine.getPersistedState (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/xstate.development.cjs.js:586:37)
    at Actor.getPersistedState (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:756:23)
    at eval (/home/projects/sveltejs-kit-template-default-je7z77/src/routes/+page.svelte:29:21)
    at Actor.update (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:486:24)
    at Actor._process (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:606:10)
    at Mailbox.flush (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:54:12)
    at Mailbox.enqueue (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:46:12)
    at Actor._send (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:703:18)
    at Object._relay (/home/projects/sveltejs-kit-template-default-je7z77/node_modules/xstate/dist/interpreter-ed3f81f7.development.cjs.js:180:14)
```

### Actual result

`{"value":"idle","status":"active","historyValue":{},"context":{"atoms":{"atom":{"xstate$$type":1,"id":"child"}}},"children":{"child":{"state":{"value":"idle","status":"active","historyValue":{},"context":{},"children":{}},"systemId":"child-id"}}}`

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-xstate?file=src%2Froutes%2F%2Bpage.svelte

### Additional context

ts without sveltekit worked
https://stackblitz.com/edit/xstate-ts?file=index.ts

**Comment by davidkpiano** [comment]
This is working as expected; we currently cannot serialize arbitrary actor logic, nor do we plan to do this since it would require essentially serializing fully executable code. The machine needs to have the actor already defined (named `src`) to properly rehydrate it.

**Comment by Andarist** [comment]
We might be able to improve the situation for the new `spawn` action (as in `entry: spawn(inlineLogic)`) but that's it. This one we can always try to "recover" from the same config position (if it stays there)

**Comment by zavx0z** [comment]
Why does the same code work in vanilla, but give an error in Sveltekit?
[sveltekit](https://stackblitz.com/edit/sveltejs-kit-xstate?file=src%2Froutes%2F%2Bpage.svelte)
[vanila ts](https://stackblitz.com/edit/xstate-ts?file=index.ts)

**Comment by zavx0z** [comment]
> This is working as expected; we currently cannot serialize arbitrary actor logic, nor do we plan to do this since it would require essentially serializing fully executable code. The machine needs to have the actor already defined (named `src`) to properly rehydrate it.

If I have a generated actor, then I cannot get PersistedState?
Sorry for Google translator.
Не могли бы вы детальнее взглянуть на примеры кода и результат?
Мне кажется, что тут имеется все же ошибка.
Все очень не очевидно.

**Comment by davidkpiano** [comment]
> > This is working as expected; we currently cannot serialize arbitrary actor logic, nor do we plan to do this since it would require essentially serializing fully executable code. The machine needs to have the actor already defined (named `src`) to properly rehydrate it.
> 
> If I have a generated actor, then I cannot get PersistedState? Could you take a closer look at the code examples and the output? It seems to me that there is still a mistake here. Everything is very unclear.
> 
> Sorry for Google translator.

No worries; in your code, you are passing an entire machine definition in the event. I would recommend another way of modeling it so that the machine knows about the other kinds of machines it can spawn already, instead of having that passed through an event.

**Comment by zavx0z** [comment]
> Не беспокойся; в вашем коде вы передаете в событии все определение машины. Я бы порекомендовал другой способ моделирования, чтобы машина знала о других типах машин, которые она уже может создать, вместо того, чтобы передавать их через событие.

Thanks for your reaction.
The modeling method you suggested does not suit me.
I am developing 3D, where an individual actor is created for each object. The parent state machine is mainly needed as a message passing system. How can I restore the states of dynamic objects? How to save a previously unknown number of actors?

**Comment by zavx0z** [comment]
is it possible to use actors without a parent actor in a single system?
How to share addresses between users if they are not on the same system?
If the actors can communicate directly, then I could write the logic of the system myself so that the actors can restore their state. It will also be possible to create a dynamic number of actors who can communicate with each other.
Please give me direction on where to go to fulfill my needs.

**Comment by burakakca** [comment]
Are there any changes in this regard?

**Comment by Andarist** [comment]
What kind of an inline child actor you'd like to persist? Could you show how your machine looks like?

**Comment by hckhanh** [comment]
@Andarist I can share with you a machine:

```ts
import {
  mainTabGroupMachine,
  type TabData,
} from '@/components/main-tabs/group/main-tab-group-machine'
import { inspect } from '@/lib/inspect'
import { type ActorRefFrom, assign, createActor, setup } from 'xstate'

export type MainTabLayoutPosition = 'bottom' | 'left' | 'right' | 'top'

export const mainTabLayoutMachine = setup({
  types: {
    context: {} as {
      direction: 'column' | 'none' | 'row'
      groups: ActorRefFrom<typeof mainTabGroupMachine>[]
      isTabDragging: boolean
    },
    events: {} as
      | {
          position: MainTabLayoutPosition
          tabs: TabData[]
          type: 'tabs.assigned'
        }
      | { tabs: TabData[]; type: 'tabs.added' }
      | { type: 'tab.dragging' }
      | { type: 'tab.dropped' },
  },
  actions: {
    addNewGroup: assign({
      groups: ({ spawn }, { tabs }: { tabs: TabData[] }) => [
        spawn(mainTabGroupMachine, { input: { tabs } }),
      ],
    }),
  },
}).createMachine({
  id: 'mainTabLayoutMachine',
  context: {
    direction: 'none',
    groups: [],
    isTabDragging: false,
  },
  initial: 'empty',
  states: {
    empty: {
      on: {
        'tabs.added': {
          target: 'filled',
          actions: {
            type: 'addNewGroup',
            params: ({ event }) => ({ tabs: event.tabs }),
          },
        },
        'tabs.assigned': {
          target: 'filled',
          actions: {
            type: 'addNewGroup',
            params: ({ event }) => ({ tabs: event.tabs }),
          },
        },
      },
    },
    filled: {
      on: {
        'tabs.assigned': {
          target: 'filled',
          actions: assign({
            direction: ({ event }) =>
              ['top', 'bottom'].includes(event.position) ? 'column' : 'row',
            groups: ({ context, event, spawn }) =>
              ['left', 'top'].includes(event.position)
                ? [
                    spawn(mainTabGroupMachine, {
                      input: { tabs: event.tabs },
                    }),
                    ...context.groups,
                  ]
                : [
                    ...context.groups,
                    spawn(mainTabGroupMachine, {
                      input: { tabs: event.tabs },
                    }),
                  ],
          }),
        },
      },
    },
  },
  on: {
    'tab.dragging': {
      actions: assign({ isTabDragging: true }),
    },
    'tab.dropped': {
      actions: assign({ isTabDragging: false }),
    },
  },
})

export const mainTabLayoutActor = createActor(mainTabLayoutMachine, {
  inspect,
}).start()
```
