### ISSUE TITLE
[v5] actions run but not applied

### ISSUE THREAD

**Issue by smakinson** [statelyai/xstate#4439]
## Bug or feature request?
A potential bug: https://discord.com/channels/795785288994652170/1171822378003742791/1171825429099855872

## Description:
I have an example here with some instructions in it. I see console logs from actions running, but they don't take affect. It seems like a guard may be affecting in a case where maybe it should not be? (but only when 2 events happen one after the other) 

## (Bug) Expected result:
I expect that when the button pressed that sends the 2 events in succession, that the reset would change the state & the context would be reset before the 2nd event is handled/run.

## (Bug) Actual result:
I see the console logs from the actions being run, but the state does not change and the context is not changed.

## Link to reproduction:

https://codesandbox.io/s/objective-cache-46f786?file=/src/App.vue

Thanks for looking in to this!

**Comment by with-heart** [comment]
I'm confused. Isn't this working as expected?

You click

**Comment by with-heart** [comment]
I'm confused. Isn't this working as expected?

If you send `reset` and then `increase`, `count` is reset to 0 and transitions to `foo.idle` and then `count` is incremented and transitions to `foo.blocked`. So if you click "Send increase" and then "Send reset, then increase", state and context change but you've ended up exactly where you were before you clicked "Send reset, then increase" so it looks like nothing changed.

**Comment by smakinson** [comment]
My apologies, I just spent the whole day trying to determine whats going on in my local project and if I needed to/could make something simple to represent it better than the above. The above code sandbox does turn out to be ok and I no longer believe there is any issue related to xstate for this, so I am closing this issue. Again, sorry for the confusion.
