### ISSUE TITLE
Bug: [v5] fromPromise and actor causes machine to get stuck in state

### ISSUE THREAD

**Issue by gkiely** [statelyai/xstate#4459]
### Description

In V4, using a service with an async function, when double clicking, eventually the state returns to idle.
https://codesandbox.io/s/musing-framework-mqfnxr?file=/src/App.js

In V5, using an actor with fromPromise, the state gets stuck in loading.
https://codesandbox.io/s/awesome-currying-7yc6nz?file=/src/App.js

### Expected result

State returns to idle

### Actual result

State gets stuck in loading

### Reproduction

See description

**Comment by Andarist** [comment]
In v5 transitions are not reentering by default and you were relying on reentering in v4. You can still make that transition a reentering one by configuring `reenter: true` on it, like here: https://codesandbox.io/s/great-joliot-7w9vzd?file=/src/throttleFetchMachine.js:650-664

**Comment by gkiely** [comment]
Thanks!

**Comment by gkiely** [comment]
@Andarist Is there a possibility to allow setting this default at the machine level?

It would be nice to be able to set the default and then override at the transition level if needed.

The machines that I have that use reentering would have this on for all transitions. It has caught me out a couple times as I need to enable it for each transition.
