### ISSUE TITLE
Bug: Enqueued Actions throw type error inside setup()

### ISSUE THREAD

**Issue by KrisCoulson** [statelyai/xstate#4545]
### Description

When using the new setup api to provide actions when you use the enqueueActions action typescript throws

### Expected result

This should not throw an error. It does not throw an error when it is used as an object passed to createMachine

![image](https://github.com/statelyai/xstate/assets/6943688/a2ea57b2-cd13-4964-b4c8-c63477fb2c9d)

### Actual result

![image](https://github.com/statelyai/xstate/assets/6943688/b045779f-39cd-4d10-8db0-1060121defd3)

### Reproduction

https://codesandbox.io/p/sandbox/silly-danny-vf63fc

### Additional context

Also just incase demo doesn't show it when you goto the repro it was being weird when I would refresh and it would show the right type but when I commented it out it would break again  🤔

https://github.com/statelyai/xstate/assets/6943688/aee6c437-21e0-4076-bf50-d6286c903d90

**Comment by Andarist** [comment]
Unfortunately, we are hitting a limitation in TypeScript right now. I'd be happy to review any PR that fixes this but I already tried **extensively** to fix this issue with no luck. I will be working towards fixing this within the TS compiler but that will take some time to do, get reviewed, and released. 

For the time being, we need to classify this as a limitation that we are aware of and add a note about this in the docs or something. `enqueueActions` can't be used within `setup` - but it can be used within `createMachine` chained off `setup`

**Comment by Jgordon-pencilwrench** [comment]
To expand on the (temporary?) workaround, use `enqueueActions` as an inline action within your event's action config, like:

```
 CANCEL_EDITING: {
            target: "editingComplete",
            actions: [
              enqueueActions(({ context, event, enqueue, check }) => {
                if (
                  check({
                    type: "formIsEmpty",
                    params: {
                      formData: context.formData,
                      additionalInformation: context.additionalInformation,
                    },
                  })
                ) {
                  enqueue({
                    type: "sendDeleteThisComplaintEventToParent",
                    params: { machineUuid: context.machineUuid },
                  });
                } else {
                  enqueue({
                    type: "editingCompleted",
                    params: {
                      machineUuid: context.machineUuid,
                      summary: event.payload.summary,
                      selectedChoiceUuid: context.selectedChoiceUuid ?? "",
                    },
                  });
                }
              }),
            ],
          }, ```

**Comment by Andarist** [comment]
https://github.com/statelyai/xstate/pull/4750 fixes the reported issue. It's still not perfect but the OP's code works alright with this PR

**Comment by andrecrimb** [comment]
The issue still persists in `v5.13.0`.

**Comment by davidkpiano** [comment]
> The issue still persists in `v5.13.0`. TS still complains when I try to declare an enqueued action within `setup.actions`.

The original example does work with the latest versions. Can you please open a new issue with code that shows that it is not working?

**Comment by andrecrimb** [comment]
Done https://github.com/statelyai/xstate/issues/4923 👍🏽
