### ISSUE TITLE
Bug: Git book examples produce errors

### ISSUE THREAD

**Issue by ohaddahan** [statelyai/xstate#4548]
### Description

Trying to follow https://xstate.js.org/docs/guides/start.html#our-first-machine , getting 2 issues:
1. `interpret` is marked as `deprecated`.
2. `Property 'onTransition' does not exist on type 'Actor<StateMachine<MachineContext, AnyEventObject, Record<string, AnyActorRef>, ProvidedActor, ParameterizedObject, ... 6 more ..., ResolveTypegenMeta<...>>>'.` error trying to run the code.

### Expected result

No errors.

### Actual result

Has errors.

### Reproduction

https://stately.ai/viz/bbd1f59e-c2b8-49af-9aba-3d82fdffe8cd

**Comment by davidkpiano** [comment]
We have updated the v4 readme pages to let developers know that they are for the old XState v4.
