### ISSUE TITLE
Bug: [v5] - `fromPromise` actors cannot infer their type

### ISSUE THREAD

**Issue by christophe-g** [statelyai/xstate#4550]
### Description

I get the following TS error when I try to use `fromPromise` typed actors :
```
Type 'EventObject' is not assignable to type '{ [k: string]: unknown; type: string; }'.
```

For instance in trying out examples like
```ts
const fetcher = fromPromise(
  async ({ input }: { input: { userId: string } }) => {
    const user = await fetchUser(input.userId);
    return user;
  },
);

const machine = setup({
  types: {} as {
    children:  {
      fetch1: 'fetchData';
      fetch2: 'fetchData';
    }
  },
  actors: { 
     // This is where the error occurs
     fetchData: fetcher //as unknown as UnknownActorLogic
  }
}).createMachine({
  invoke: {
    src: 'fetchData', // strongly typed
    id: 'fetch2', // strongly typed
    onDone: {
      actions: ({ event }) => {
        event.output; // should be strongly typed as { result: string } - it is not
      },
    },
    input: { userId: '42'  }, // strongly typed
  },
});
```

I suspect it is because of [this](https://github.com/statelyai/xstate/blob/5ec855e54da0b09007602d3ecbbe4af74ee8b203/packages/core/src/actors/promise.ts#L33)

### Expected result

`fetchedData` is typed properly

### Actual result

`fetchedData` throw a TS error

### Reproduction

https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAbwM4FMYFcwBo4DMoQgAKBIwqAvnqXAOQAeSMAhjCrQFAcDGEAdkzxpuACwCqqKHAC8cZkgCefbnAAU6SQEkAJgC44TKMD4BzAJQyAfIg5w4UNOih9EcdMG1x9GlFB0UOAJ5+QVxhEV8ZakISQnIUVVs5RWU1BDhjMHR4Cn10zOy8ty09AxgjUzgqCgtpawQku14BeB8pWWYAd2ZgeDCYUQlfVQKYADo2nTMAbi47OwcMZ2LfWbsKLA4ZrmbBEGZRYxQo1AwwVQa7GAUwFCQ8qnkbebhDgBttBz59Z5ehAZEAEZ9LR+qIACKsZi0NZ-MEiABMIPhkJYMMaVSSGySBxg0Hurgx-whUP08MiAHoKU90HwANZ8CCdFxPMT0xnMgCC3DxUAAMhATMBuFjAmYxtwHKwUABZA4iI4XJLGABuEDpKDyGKQUG4yPCqOhOCpZQIpjeCjg11u2gxHn1AIRtGNFNN-BMFqtNxQtpe-HB-E1vxeuOAIX0FzgKBVKD4OVq9SJ82jsfGEGyWRg0zgJsM7s91p9yVcDiQ6DeMH0hmMJkxfyqmxe2JeoyKk1KtAALE71i63ebLYXfQ2xdMgA

**Comment by Andarist** [comment]
I was working on this since this morning. Gonna put up a PR for this soon
