### ISSUE TITLE
Bug: What happend to useInterpret on xstate v5? on react

### ISSUE THREAD

**Issue by allestaire** [statelyai/xstate#4557]
### Description

There are major changes on this,
But sadly the team did not document on how to replace `useInterpret` when using react context,
I see that there is a context example but thats not the main goal I wanted to acheive

### Expected result

useInterpret on version 5

### Actual result

useInterpret on version 5

### Reproduction

awdawd

**Comment by davidkpiano** [comment]
This is documented in the migration guide: https://stately.ai/docs/migration#useinterpret-is-now-useactorref

```ts
import { useActorRef } from '@xstate/react';

// instead of:
// const actorRef = useInterpret(machine);
const actorRef = useActorRef(machine); // or any other logic
```

**Comment by davidkpiano** [comment]
Ah, just read the context part. You can use the the [`createActorContext` helper](https://stately.ai/docs/xstate-react#createactorcontextlogic) (also documented), or just create the actor in module scope and use normal React context to pass it down to components.

**Comment by allestaire** [comment]
I guess this is a full documentation, I just lazy to read it all
https://xstate.js.org/docs/recipes/react.html#global-state-react-context

**Comment by allestaire** [comment]
Xstate v5 is not usefull, it take too much time, 
There are less examples on how it should be used
If there are examples, it is not in one place,
Its time consuming, though they suggest better performance

BUT it is not a good documentation, tsk tsk
Will stick to older version

Instead of using useSelection, there is useMemo instead

What a disapointment

**Comment by davidkpiano** [comment]
Thank you for sharing your opinion @allestaire. Feel free to use any other library if this one doesn't suit your needs. Happy holidays!

**Comment by allestaire** [comment]
Thanks for understanding @davidkpiano 😄 
Probabbly if I have extra time, will try to study more on the newer version
