### ISSUE TITLE
Bug: 'const' in type declaration other than type param declaration

### ISSUE THREAD

**Issue by sunshinezxf** [statelyai/xstate#4558]
### Description

createMachine() fails when integrating with midwayjs

### Expected result

run the build script without any error

### Actual result

Type parameter declaration expected. (node_modules/xstate/dist/declarations/src/setup.d.ts:51:20)
    at Object.error (/workspace/node_modules/@midwayjs/cli/src/index.ts:62:13)
    at BuildPlugin.compile (/workspace/node_modules/@midwayjs/cli-plugin-build/src/index.ts:168:23)
    at CommandCore.execLifecycle (/workspace/node_modules/@midwayjs/command-core/src/core.ts:227:11)
    at CommandCore.invoke (/workspace/node_modules/@midwayjs/command-core/src/core.ts:187:5)
    at CLI.start (/workspace/node_modules/@midwayjs/command-core/src/cli.ts:191:5)
error Command failed with exit code 1.

### Reproduction

https://codesandbox.io/p/sandbox/epic-bash-grjnq9

### Additional context

When I check the "xstate/dist/declarations/src/setup.d.ts 51:20",(corresponding source file: https://github.com/statelyai/xstate/blob/main/packages/core/src/setup.ts Line 157) I found:
```
createMachine: <const TConfig extends 
    MachineConfig<...>>(config: TConfig)  => StateMachine<...>
```
**const** looks inappropriate here since it is used to declare a type instead of a type parameter. And that's why I ran into the build failure with error message "Type parameter declaration expected". After I manually remove the keyword 'const' in the file, it works okay.
![image](https://github.com/statelyai/xstate/assets/5189253/33392f07-03a8-4c4c-8cdf-65c4dbd0a16e)

the build result after I manually delete the const keyword:
![image](https://github.com/statelyai/xstate/assets/5189253/d2c70758-e562-4019-9e2b-2ec381edb877)

Could you please check whether the 'const' keyword is appropriate here?

**Comment by Andarist** [comment]
> const looks inappropriate here since it is used to declare a type instead of a type parameter

this is used on a type parameter. What version of TS are you using? XState v5 requires at least TS 5.0

**Comment by sunshinezxf** [comment]
> > const looks inappropriate here since it is used to declare a type instead of a type parameter
> 
> this is used on a type parameter. What version of TS are you using? XState v5 requires at least TS 5.0

Thanks for your quick response, the TS version I used is 4.8.0. After changing it to 5.0, the problem is gone. Thank you!
