### ISSUE TITLE
Bug: `@xstate/vue`'s `useActor` incorrectly types the `send()` function with `EventFrom` rather than `EventFromLogic`

### ISSUE THREAD

**Issue by tkofh** [statelyai/xstate#4603]
### XState version

XState version 5

### Description

`@xstate/vue`'s `useActor` function creates a top level alias for `actorRef.send` so that you can destructure `send` out like so:

```typescript
const { send } = useActor(myLogic, { /* ... */ })
```

However, this `send` function is typed as `(event: EventFrom<TLogic>) => void` which consistently resolves to `never` when fed an `ActorLogic`, because the underlying `ResolveEventType` only checks for `ActorRef`s not `ActorLogic`s.

### Expected result

`useActor(/* ... */).send({ type: 'my-event' })` should not produce a type error

### Actual result

`useActor(/* ... */).send({ type: 'my-event' })` produces a type error, because "`{ type: 'my-event }` is not assignable to `never`"

### Reproduction

[codesandbox link](https://codesandbox.io/p/devbox/determined-forest-7qvtmw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq9y8gxz00073b6j5ax6kyfd%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq9y8gxz00023b6jpqp00cun%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq9y8gxz00043b6jdxs0selu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq9y8gxz00063b6jmrc37pqg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B74.03619909502262%252C25.963800904977376%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq9y8gxz00023b6jpqp00cun%2522%253A%257B%2522id%2522%253A%2522clq9y8gxz00023b6jpqp00cun%2522%252C%2522activeTabId%2522%253A%2522clq9y9gmc00el3b6jqqj06rii%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq9y92x1005u3b6jqqmldcbm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clq9y9gmc00el3b6jqqj06rii%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clq9y8gxz00063b6jmrc37pqg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq9y8gxz00053b6jdp851gxc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq9y8gxz00063b6jmrc37pqg%2522%252C%2522activeTabId%2522%253A%2522clq9y8gxz00053b6jdp851gxc%2522%257D%252C%2522clq9y8gxz00043b6jdxs0selu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq9y8gxz00033b6jdiygiojh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clq9y8gxz00043b6jdxs0selu%2522%252C%2522activeTabId%2522%253A%2522clq9y8gxz00033b6jdiygiojh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Additional context

My investigation only involved `fromTransition`, although it looks like all `from*` logic definers result in an `ActorLogic` type. In any event, if I've made a mistake here I apologize.

Also happy to open a PR for this if I'm on the right track

**Comment by davidkpiano** [comment]
> Also happy to open a PR for this if I'm on the right track

A PR would be welcome; your solution seems like it would fix the problem.

**Comment by tkofh** [comment]
I ended up copying the React package with `ActorRefFrom<TLogic>['send']>`
