### ISSUE TITLE
Bug: Uncaught Error: Unable to send event to actor 'grandchild' from machine 'child'.

### ISSUE THREAD

**Issue by j-5-s** [statelyai/xstate#4617]
### XState version

XState version 5

### Description

I have 3 machines:
 - Root
 - Child
 - Grandchild

The root machine has an event that creates the Child machine as a service.  The Child machine creates a Grandchild.  After 5 seconds the child machine attempts to send a message to both the parent in the onDone actions.

![Untitled-2023-12-10-0813](https://github.com/statelyai/xstate/assets/666455/08d64b31-b63d-47de-8ecc-fe0a5914fca1)

### Expected result

The grandchild and the root machine should receive events from parent

### Actual result

If the onDone has a target set ("complete") in the example, the error is thrown `Unable to send event to actor 'grandchild' from machine 'child'.`. However if there is no target set in the onDone, it works as expecte

### Reproduction

https://codesandbox.io/p/devbox/mutable-glade-2yh5p6?file=%2Fsrc%2FfeedbackMachine.ts%3A36%2C25

### Additional context

In the codesandbox linked, run `feedbackActor.send({ type: 'CREATE_CHILD' })` in console to kick off the process and 5 seconds later will see the error.  You can see it working as expected if you comment out the "complete" target in onDone on line 42.

**Comment by Andarist** [comment]
What are you trying to achieve here? The grandchild is going to be stopped within this transition either way (since you exit the invoking state) - so the question is: why is it important for you to deliver an event to this grandchild in this scenario?

**Comment by j-5-s** [comment]
yeah, i think thats my misunderstanding. I just was able to achieve what i wanted moving the states around and creating the grandchild like this: 
https://codesandbox.io/p/devbox/quirky-perlman-kwqmqj?file=%2Fsrc%2FfeedbackMachine.ts%3A53%2C13

It makes sense now. thanks!
