### ISSUE TITLE
Bug: Exit actions aren't triggered when machine is stopped

### ISSUE THREAD

**Issue by xylophonehero** [statelyai/xstate#4630]
### XState version

XState version 5

### Description

Breaking change from v4 exit actions aren't called when a state machine actor is stopped.

### Expected result

Exit actions are executed when machine is stopped (like in v4)

### Actual result

Exit actions aren't executed when machine is stopped

### Reproduction

https://codesandbox.io/p/sandbox/exit-actions-v5-c3c4rr

### Additional context

Not sure if this is intended but it is not part of the migration guide
https://stately.ai/docs/migration

Sandbox using v4 where exit actions are called when machine is stopped
https://codesandbox.io/p/sandbox/exit-actions-v4-8xc332

**Comment by Andarist** [comment]
This was changed on purpose, see https://github.com/statelyai/xstate/pull/4377 . Is there any particular reason why you want exit actions to be called when machine is stopped?

**Comment by xylophonehero** [comment]
Ah interesting we don't use server rendering so hydration doesn't bother us in our app.

We mainly use it for cleanup on services we run. For example we have a machine that contains the logic for joining a websocket and channels (through phoenix). So in our exit actions, we call the socket disconnect method when the actor is stopped. This could happen when a fatal error occurs within another part of our app and we don't render the provider containing our machine anymore (which causes it to stop and an exit action that disconnects from the socket).

What would be a work around for this?

I can move the cleanup actions into a return function of a `fromCallback` but that seems quite strange (see the updated sandbox https://codesandbox.io/p/sandbox/exit-actions-v5-c3c4rr)

Maybe a configuration option to run exit actions on stop?

**Comment by davidkpiano** [comment]
All state machine actions (entry, exit, transition actions) are _fire-and-forget_, emphasis on the **forget** key word. There is no clean-up for these effects, because they are already forgotten.

It sounds like you don't want to forget these effects, so yes, invoking a callback would be more appropriate:

```ts
const machine = createMachine({
  // You don't really want this, since you don't want the effect
  // to be "forgotten":
  // entry: () => console.log('entered'),
  // exit: () => console.log('exited'),
  invoke: {
    src: fromCallback(() => {
      console.log('entered')

      return () => {
        console.log('exited');
        console.log('cleaned up')
      }
    }),
  },
});
```

**Comment by lmcgartland** [comment]
Just ran into this as well, definitely wondering if for a machine (non callback), there should be a clean up function on stopping. For now just sending a cleanup event to run the action previously in `exit`

**Comment by Andarist** [comment]
Please post a motivating example for what you are asking for.

**Comment by axis-d0op** [comment]
Also running into this issue.
We got services that we want to dispose when machine is teared down(exited), else risk memory leaks.

**Comment by Andarist** [comment]
You can model those as actors, those are teared down when u stop a machine
