### ISSUE TITLE
Bug: Logger not propagated to child machines from root

### ISSUE THREAD

**Issue by xylophonehero** [statelyai/xstate#4634]
### XState version

XState version 5

### Description

In v4, when passing a custom logger to the machine options, the child machines also used to use the same logger.

In v5, they just use the default logger `console.log`

### Expected result

Expected the log function in a child machine to use the custom logger defined in the root machine from the interpreter options

### Actual result

The child machines log using the default log function

### Reproduction

https://codesandbox.io/p/sandbox/logging-not-propagated-tn93jf

**Comment by Andarist** [comment]
We should "inherit" it:
- [here](https://github.com/statelyai/xstate/blob/94c884103eb928938dbc16284822bc707f0df584/packages/core/src/spawn.ts#L83)
- and [here](https://github.com/statelyai/xstate/blob/94c884103eb928938dbc16284822bc707f0df584/packages/core/src/actions/spawnChild.ts#L61)

Alternatively, we could try to "inherit" it through the `system`.

**Comment by xylophonehero** [comment]
Inheriting through the system would be super nice. Right now we have extended the logger to pass the systemId as the category. We intercept this directly on the root and forward it to our third party log service
```ts
import { AnyActorRef, enqueueActions, log as xstateLog } from 'xstate5'

export const log: typeof xstateLog = (logExp) =>
  enqueueActions(({ enqueue, self }) => {
    const systemId = (self as AnyActorRef & { _systemId: string })._systemId
    return enqueue(
      xstateLog((args) => {
        // We can't pass params to the log function as they don't work with enqueue actions
        if (typeof logExp === 'function') return logExp(args, {} as any)
        return logExp
      }, systemId),
    )
  })
```

This function sadly doesn't accept parameters but we always use logging inline in the machine anyway so not a problem

**Comment by boneskull** [comment]
`spawn()` and `spawnChild()` seem like they should allow a `logger` option, yes?  Maybe other options available on  `createActor()`?

I'm just trying to use [debug](https://npm.im/debug) in place of the default logger.  It works for the machine I created with `createActor()`, but not for any spawned machine.

**Comment by davidkpiano** [comment]
A workaround for now: behind the scenes, `spawn(…)` and `spawnChild(…)` just call `createActor(…)` with specific actor options:

```ts
assign({
  actorRef: ({ self }) => {
    const actor = createActor(someMachine, {
      parent: self, // IMPORTANT!
      logger: customLogger
    });

    return actor;
  }
})
```
