### ISSUE TITLE
Bug: Output should be strongly typed and automatically set once a final state is reached

### ISSUE THREAD

**Issue by spoptchev** [statelyai/xstate#4652]
### XState version

XState version 5

### Description

Please follow the example:

```
const someMachine = setup({
  types: {} as {
    output: { id: string }
  }
}).createMachine({
  initial: "idle",
  states: {
    idle: { 
       always: {
         target: "done"
       }
    },
    done: {
      type: "final",
      output: { wrongField: "hello-world" }
    }
  }
});

const actor = createActor(someMachine);
actor.start();

const output = await toPromise(actor);
```

### Expected result

From the example I would expect that the `wrongField` is detected as invalid, as it does not comply with the type of `output`. Additionally, the output of the final state is not automatically assigned to the state machine output. You have to manually set up the following code:

```
output: ({event}) => event.output as { id: string }
```

As you can see this also requires a type cast, because the `DoneStateEvent` output type is declared as `unknown`.

### Actual result

Automatic extraction of the final state output and type inference of the `output` object fails.

### Reproduction

https://codesandbox.io/p/devbox/gallant-noether-pz46md

**Comment by Andarist** [comment]
In v5 you specify `output` of the machine at the root, see this [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwKYwK5jgXzgMyghDgCIAPZGAQxlVIG44B6ZuGATzFWQC44ArADoALEICMAKElpMYABQJJcdlx78EeaskTKVcCBhhgjGuMAAm-KlGAA7AOa4GenABpJOAJRCAxlFRaVABZal8AC3tURT17YBhgagAbflJLJPoPFSogvl19cwsMjT0C5IB3ag48pQKCmigHdFSLCDtM0v13Tu6C1vaSutVuVPx7ZNIsrqnegyMTGDNyokcAMWBUJKsycM2kiABacugt0lwPbxcZdCwYlU5uGq0dWv1DY1NEQusYW0dnVwXHz+QJ0UIRKJ3cx2eKJFJkdIdbI0Og1TqIwZ1CpVNFDe7URrNMj9JF1WYqclwEmY+pqUbjJKTHozKbvBZmSz8cQABm5508Xiuslurwe6kQz3yb3mnyQnJQv3sThwLgpQL8ASC4Mi7ShcQSyVSiKZyNyNMKxSlZSSlWq5vqBKai2JbVJBUplOpVv0YvpdgmUzVgL0bNl3zgAHJ8BAIBH+ZdJEA):
```ts
import { setup } from "xstate"; // types: 5.4.1

setup({
  types: {} as {
    output: { id: string };
  },
}).createMachine({
  initial: "idle",
  states: {
    idle: {
      always: {
        target: "done",
      },
    },
    done: {
      type: "final",
    },
  },
  output: { id: 'foo' },
});
```

The `.output` on the final state becomes part of the auto-generated `done.state.*` event and, IIRC, you receive that here in the `output` of the root (if you make that a function).

> As you can see this also requires a type cast, because the DoneStateEvent output type is declared as unknown.

Yeah, this is unfortunate but currently, we don't have a way to infer types here. We constantly look for improvements in this area and we might also release typegen for v5. This might allow those types to be inferred with the caveat that this will require an extra tool (like our VS Code extension or the `@xstate/cli`)

**Comment by spoptchev** [comment]
Ok, thank you.

```
  },
  output: { id: 'foo' },
});
```
This is not very good option, because the output can be different based on the final states. 

This is especially useful if you consider `discriminating union types`: `type Output = {type: "x"; attributeY: string} | {type: "y"; attributeX: string}`.

**Comment by Andarist** [comment]
`output` can still be dynamic so you can still return a discriminated union from it. It might require some extra steps to do so though.

The problem with per-final state output acting as the output of the whole machine is that it becomes tricky to deal with `output` for `createMachine({ type: 'parallel' })`. The current solution gives the user more control over that because they can adapt the context/event into the machine's output regardless of what is the type of the root state etc.

**Comment by spoptchev** [comment]
I understand that it is hard to make everyone happy. 😄  It is an open source project. 

But in the current development state it feels like neither the context nor the output are a good way to store data based on the state of the state machine.  Most of the time the context is polluted with unnecessary data that is not used in all of the states and has to be null checked when extracting it for further processing.

But still a great project. Thank you for the explanation.
