### ISSUE TITLE
Bug: Typescript 'something is never used in the machine definition' when it is used

### ISSUE THREAD

**Issue by josephfh** [statelyai/xstate#4655]
### XState version

XState version 5

### Description

Typescript error on actions and guards that are used: 'createNotification is never used in the machine definition'

### Expected result

No typescript error when these are used in the machine

### Actual result

Code repoduction in Stackblitz: no typescript error
When downloaded, installed packages with pnpm and opened in VSCode: 2 typescript errors

See screenshot below

### Reproduction

https://stackblitz.com/edit/github-wmbzqs?file=package.json,src%2FfeedbackMachine.ts

To reproduce: download, install packages with pnpm, open in VSCode

<img width="660" alt="Screenshot 2024-01-07 at 11 55 27" src="https://github.com/statelyai/xstate/assets/889121/aa8e65f3-a6e2-42f3-b853-d427a73ec345">

**Comment by davidkpiano** [comment]
The VS Code extension does not yet work for XState v5, but we are working on upgrading it this month.

**Comment by josephfh** [comment]
Tou're right! It's coming from the extension and not typescript. And there was me explaining to another user in the Discord that the extension wasn't upgraded, just 30 minutes before reporting this bug 😄 

Closing this now
