### ISSUE TITLE
Bug: After 5.5, type of state.context from @xstate/react useMachine being inferred incorrectly with @xstate/react < 4.0.2

### ISSUE THREAD

**Issue by pckilgore** [statelyai/xstate#4664]
### XState version

XState version 5

### Description

Updated from 5.4 -> 5.5

### Expected result

Everything works, everything compiles (patch change).

### Actual result

New type errors (state.context values being inferred to any instead of the correct type).

### Reproduction

[link here](https://codesandbox.io/p/devbox/cranky-stallman-slyqpl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr882dn300073b6i8haat2bh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr882dn200023b6iswegif61%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr882dn200043b6i691jkwax%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr882dn300063b6iivhmudzu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr882dn200023b6iswegif61%2522%253A%257B%2522id%2522%253A%2522clr882dn200023b6iswegif61%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr882dn200013b6i92h5zsz3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr882dn200013b6i92h5zsz3%2522%257D%252C%2522clr882dn300063b6iivhmudzu%2522%253A%257B%2522id%2522%253A%2522clr882dn300063b6iivhmudzu%2522%252C%2522activeTabId%2522%253A%2522clr89hp7h02653b6i2lww36ot%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr89hp7h02653b6i2lww36ot%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr882dn200043b6i691jkwax%2522%253A%257B%2522id%2522%253A%2522clr882dn200043b6i691jkwax%2522%252C%2522activeTabId%2522%253A%2522clr89962x00xp3b6ighpk4yqi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr882dn200033b6i42rtgy1p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr898ab400ny3b6imdrstyga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr898aei000medjz2n7a31cm%2522%257D%252C%257B%2522id%2522%253A%2522clr89962x00xp3b6ighpk4yqi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr89966b000nedjzeyrc91dc%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
### Additional context

"@xstate/react@^4.0.0":
  version "4.0.1"
  resolved "https://registry.yarnpkg.com/@xstate/react/-/react-4.0.1.tgz#a5cec511e23e44ac5dd64852a1497efb6434c3f0"
  integrity sha512-UB9qUC11wcaYd05wGea0mvEA3uTHikNaB4InMZfxD7MVFxzBFU+3JFkemjiN8bDdPJfDrObyP9ZPDVojq2LytA==
  dependencies:
    use-isomorphic-layout-effect "^1.1.2"
    use-sync-external-store "^1.0.0"

typescript@^5.0.0:
  version "5.3.2"

**Comment by davidkpiano** [comment]
Can you please share a code reproduction?

**Comment by pckilgore** [comment]
I can fix by upgrading @xstate/react to 4.0.2.  Repro by reverting to 4.0.1

<details>
<summary>repro based on xstate/react version</summary>


```console
(✓) 14:40:27 [~/gravity/monorepo/src/www::renovate/xstate-monorepo]
$ yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
✨  Done in 2.69s.

$ git diff
diff --git a/src/www/yarn.lock b/src/www/yarn.lock
index e9ba93a5b..080f19816 100644
--- a/src/www/yarn.lock
+++ b/src/www/yarn.lock
@@ -3085,9 +3085,9 @@
     react-refresh "^0.14.0"

 "@xstate/react@^4.0.0":
-  version "4.0.1"
-  resolved "https://registry.yarnpkg.com/@xstate/react/-/react-4.0.1.tgz#a5cec511e23e44ac5dd64852a1497efb6434c3f0"
-  integrity sha512-UB9qUC11wcaYd05wGea0mvEA3uTHikNaB4InMZfxD7MVFxzBFU+3JFkemjiN8bDdPJfDrObyP9ZPDVojq2LytA==
+  version "4.0.2"
+  resolved "https://registry.yarnpkg.com/@xstate/react/-/react-4.0.2.tgz#97193ba96129e0cebf0ac7245dd355b723c1e37c"
+  integrity sha512-t5Xau/H8nS9nlowV+72RneqaQ/wqkQ8C/8ij4gEvHcoCQptc2REgZkjOpV74xyTabUZnUeYwdDTsMmz5ot3S+Q==
   dependencies:
     use-isomorphic-layout-effect "^1.1.2"
     use-sync-external-store "^1.0.0"

(✓) 14:40:34 [~/gravity/monorepo/src/www::renovate/xstate-monorepo]
$ yarn tsc
yarn run v1.22.19
$ /Users/kilgore/gravity/monorepo/src/www/node_modules/.bin/tsc
✨  Done in 3.18s.

(✓) 14:40:42 [~/gravity/monorepo/src/www::renovate/xstate-monorepo]
$ yarn add xstate/react@4.0.1
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/xstate%2freact: Request \"https://registry.yarnpkg.com/xstate%2freact\" returned a 405".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kilgore/gravity/monorepo/src/www/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

(✖ - 1) 14:41:06 [~/gravity/monorepo/src/www::renovate/xstate-monorepo]
$ yarn add @xstate/react@4.0.1
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @xstate/react@4.0.1
info All dependencies
└─ @xstate/react@4.0.1
✨  Done in 2.35s.

(✓) 14:41:15 [~/gravity/monorepo/src/www::renovate/xstate-monorepo]
$ yarn tsc
yarn run v1.22.19
$ /Users/kilgore/gravity/monorepo/src/www/node_modules/.bin/tsc
[SNIP].tsx:203:28 - error TS7006: Parameter 'error' implicitly has an 'any' type.

203               {errors.map((error, i) => (
                               ~~~~~

[SNIP].tsx:203:35 - error TS7006: Parameter 'i' implicitly has an 'any' type.

203               {errors.map((error, i) => (
                                      ~


Found 2 errors in the same file, starting at: src/components/discovery/AddSiteFlow.tsx:203

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</detail>

**Comment by pckilgore** [comment]
> Can you please share a code reproduction?

Here, you might want to add a note in the template that with new packages, you have to manually install the right version of the package using the codesandbox internal terminal and yarn, not the UI, which won't do it (I assume because of newness, at least).

[link here
](https://codesandbox.io/p/devbox/cranky-stallman-slyqpl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr882dn300073b6i8haat2bh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr882dn200023b6iswegif61%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr882dn200043b6i691jkwax%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr882dn300063b6iivhmudzu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr882dn200023b6iswegif61%2522%253A%257B%2522id%2522%253A%2522clr882dn200023b6iswegif61%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr882dn200013b6i92h5zsz3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr882dn200013b6i92h5zsz3%2522%257D%252C%2522clr882dn300063b6iivhmudzu%2522%253A%257B%2522id%2522%253A%2522clr882dn300063b6iivhmudzu%2522%252C%2522activeTabId%2522%253A%2522clr89hp7h02653b6i2lww36ot%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr89hp7h02653b6i2lww36ot%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr882dn200043b6i691jkwax%2522%253A%257B%2522id%2522%253A%2522clr882dn200043b6i691jkwax%2522%252C%2522activeTabId%2522%253A%2522clr89962x00xp3b6ighpk4yqi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr882dn200033b6i42rtgy1p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr898ab400ny3b6imdrstyga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr898aei000medjz2n7a31cm%2522%257D%252C%257B%2522id%2522%253A%2522clr89962x00xp3b6ighpk4yqi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr89966b000nedjzeyrc91dc%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

<img width="842" alt="image" src="https://github.com/statelyai/xstate/assets/2559043/7ab10f55-acbb-43d9-8689-022e326864d5">

**Comment by Andarist** [comment]
Repro: [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs04BfOAMyghDgCIAPAZxizQYG44B6XuDACeYNCwBccAKwA6WQAYAUKEixEcAK4tc+IqQrVa9BgAFW7bL3T4Y3PgOGiJcACwz5MgIyLFyCMTY4EF04AF4Ua2w8QhI0AAoERTg4YAATSQZ0MFoGABokwRExSQRKDBZEAuS0ADc0YhhnJEc0DIBxAHkGCi4qlH9sJhgSvuqoWihnNigSAHMAbQBdXuTk8hWKfOS-BrQhkdW4NHHoZyWtzYKSYBhgDAAbDIw8grYOJr6MA8O4f2+fuCdEqCDBQWZoYaMABG3XIF0OcL6iMOUP+qxaGSoJAeLwRF0R5AAlL1FHtVPAqBpiMhbv44ABBMBgOKEyrbfyBeZvbC5OAAfW0xFSizCmm00T08WChGJrwsaBkO0GMBkxwmLBkVGgAFFdHE4mhWaEAHz9AIQe4K+4QWaygroGAaKDEODEDT3e69ciKIA).

It's not great that the compatibility between `xstate@5.5.0` and `@xstate/react@4.0.1` has been broken but isn't the simplest thing to do here to update to `@xstate/react@4.0.2`? That works OK: [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs04BfOAMyghDgCIAPAZxizQYG44B6XuDACeYNCwBccAKwA6WQAYAUKEixEcAK4tc+IqQrVa9BgAFW7bL3T4Y3PgOGiJcACwz5MgEyLFyCMTY4EF04AF4Ua2w8QhI0AAoERTg4YAATSQZ0MFoGABokwRExSQRKDBZEAuS0ADc0YhhnJEc0DIBxAHkGCi4qlH9sJhgSvuqoWihnNigSAHMAbQBdXuTk8hWKfOS-BrQhkdW4NHHoZyWtzYKSYBhgDAAbDIw8grYOJr6MA8O4f2+fuCdEqCDBQWZoYaMABG3XIF0OcL6iMOUP+qxaGSoJAeLwRF0R5AAlL1FHtVPAqBpiMhbv44ABBMBgOKEyrbfyBeZvbC5OAAfW0xFSizCmm00T08WChGJrwsaBkO0GMBkxwmLBkVGgAFFdHE4mhWaEAHz9AIQe4K+4QWaygroGAaKDEODEDT3e69ciKIA)

**Comment by pckilgore** [comment]
Sure, that resolved it for us and avoids https://xkcd.com/979/

Leaving open for your tracking only.
