### ISSUE TITLE
Bug: Using `raise` in entry action with `always.target` to final node doesn't execute

### ISSUE THREAD

**Issue by offirgolan** [statelyai/xstate#4665]
### XState version

XState version 5

### Description

When using `raise` in an entry action that will immediately transition to a `final` node via `always.target`, the `raise` action is never executed.

This does not work:

```ts
exit: {
  entry: [() => console.log("exit: entry"), raise({ type: "LOG" })],
  always: {
    target: "done",
  },
},
done: {
  type: "final",
  entry: [() => console.log("done: entry")],
},
```

This works:

```ts
exit: {
  entry: [() => console.log("exit: entry"), raise({ type: "LOG" })],
  after: {
    0: {
      target: "done",
    },
  },
},
done: {
  type: "final",
  entry: [() => console.log("done: entry")],
},
```

### Expected result

All actions should be executed in the node's entry actions before transitioning via `always.target`.

### Actual result

`raise` action is not executed in the node's entry actions before transitioning via `always.target`.

### Reproduction

https://codesandbox.io/p/sandbox/jolly-khorana-ss2tvf

### Additional context

This was working in v4 and when migrating over, noticed that it was not behaving the same in v5.

**Comment by davidkpiano** [comment]
This is by design and conforms to the SCXML algorithm: eventless transitions are prioritized first over internal (raised) events:

```
procedure mainEventLoop():
    while running:
        enabledTransitions = null
        macrostepDone = false
        # Here we handle eventless transitions and transitions 
        # triggered by internal events until macrostep is complete
        while running and not macrostepDone:
            enabledTransitions = selectEventlessTransitions()
            if enabledTransitions.isEmpty():
                if internalQueue.isEmpty(): 
                    macrostepDone = true
                else:
                    internalEvent = internalQueue.dequeue()
                    datamodel["_event"] = internalEvent
                    enabledTransitions = selectTransitions(internalEvent)
            if not enabledTransitions.isEmpty():
                microstep(enabledTransitions.toList())
...
```

For more information: https://www.w3.org/TR/scxml/#mainEventLoop

**Comment by offirgolan** [comment]
@davidkpiano gotcha. Is using `after` a proper replacement or do you have an alternate suggestion?

**Comment by Andarist** [comment]
If you reach a top-level `final` state then the machine gets put in its done state~ and it won't process any new events. So if you want to make sure that all synchronous~ (including the raised ones) events are processed then ye, `after: { 0: 'done' }` does seem like a suitable workaround.
