### ISSUE TITLE
Bug: `const` in createMachine type definition breaks the method's typing 

### ISSUE THREAD

**Issue by furf** [statelyai/xstate#4672]
### XState version

XState version 5

### Description

When using `setup({ … }).createMachine({ … })`, the machine definition passed to the latter method reports the error "Expected 0 arguments, but got 1" in the TypeScript linter (see screenshot).

<img width="507" alt="image" src="https://github.com/statelyai/xstate/assets/35775/791ead9f-430a-4dc6-990d-c2b4593cc809">

This screenshot demonstrates the example from [machines](https://stately.ai/docs/machines) documentation. (Note: you also have an error in your types property. Lines should end with commas not semi-colons.)

<img width="255" alt="image" src="https://github.com/statelyai/xstate/assets/35775/f4c326e2-6b73-4d0d-b2e5-21808721f962">

### Expected result

I expected the example from the documentation to be typed correctly. I did not expect to see an error when `createMachine` is provided a configuration object.

### Actual result

The TypeScript linter displays an error. It expects zero arguments despite the actual requirement of a configuration object.

### Reproduction

https://codesandbox.io/p/devbox/github/statelyai/xstate/tree/main/templates/vanilla-ts?file=%2Fsrc%2FfeedbackMachine.ts%3A30%2C13

### Additional context

The error appears originate in the generated setup.d.ts.

<img width="526" alt="image" src="https://github.com/statelyai/xstate/assets/35775/acf18020-0cb4-40b3-942e-664930a4ef5a">

When the `const` is removed, the code is correctly typed and the original error disappears.

<img width="549" alt="image" src="https://github.com/statelyai/xstate/assets/35775/ca41b824-9180-48ab-9335-1d0a444576c6">

The `const` was introduced in [this commit](https://github.com/statelyai/xstate/commit/87521afc99cae8e07ec41ed77ae5ab7a3ba821a0) of [this PR](https://github.com/statelyai/xstate/pull/4483).

Unsure what regressions are introduced by removing the offending code. I'll comment back if I find any while I continue to develop off of a patch branch.

---

The lint error does not appear to occur in isolation: https://codesandbox.io/p/devbox/admiring-star-7hjlsm?file=%2Fsrc%2FfeedbackMachine.ts%3A22%2C5

I'm using the same versions of TS and xstate:

<img width="339" alt="image" src="https://github.com/statelyai/xstate/assets/35775/67c840eb-8fc6-4122-afea-3ce9feca6cc5">

[Per documentation](https://stately.ai/docs/typescript#set-up-your-tsconfigjson-file), the relevant tsconfig appears to match:

<img width="410" alt="image" src="https://github.com/statelyai/xstate/assets/35775/819d25d2-f31a-49d4-80a0-d63ca2c31717">

**Comment by furf** [comment]
I may have solved my problem.

I had to add updated eslint dependencies ot the project.

<img width="313" alt="image" src="https://github.com/statelyai/xstate/assets/35775/3e5b3406-307a-4235-9b3f-6c19b0f464ec">

The project lives in a monorepo and the root's eslint dependencies were out of sync with the project's typescript dependency.

<img width="376" alt="image" src="https://github.com/statelyai/xstate/assets/35775/0730012b-594d-4824-bfd2-a2ddb5ffb3ac">

**Comment by Andarist** [comment]
From what I've seen so far the error exactly like this is usually an indication of using an older TS version (4.x).

**Comment by davidkpiano** [comment]
The resolution here is to ensure you're using the latest version of TypeScript.

More info here: 📖 https://stately.ai/docs/typescript

**Comment by furf** [comment]
I'd upgraded to the latest version of Typescript (5.3.3), but the error was still appearing. It wasn't until I upgraded our TS eslint plugins that the error disappeared. Might not be necessary to document, but good to remember if this comes up again.

Now for today's update: at the end of yesterday, I installed [Pretty TypeScript Errors](https://marketplace.visualstudio.com/items?itemName=yoavbls.pretty-ts-errors) and the issue has resurfaced. Even after uninstalling, the problem remains. It must have modified a TS version setting somewhere, but I haven't found it yet.

<img width="469" alt="image" src="https://github.com/statelyai/xstate/assets/35775/d6157fe5-8d33-4499-a732-a550317dba03">

Latest versions:
<img width="370" alt="image" src="https://github.com/statelyai/xstate/assets/35775/58cd924a-1a9c-455f-a120-e4673ebccdd6">
<img width="238" alt="image" src="https://github.com/statelyai/xstate/assets/35775/6249efb2-0979-4f71-bd29-04b457a90aab">

**Comment by furf** [comment]
interesting… Restart TS Server is missing as well

<img width="465" alt="image" src="https://github.com/statelyai/xstate/assets/35775/eabf0cef-c418-44ea-9ddd-2b574ee1443d">

**Comment by Andarist** [comment]
Note that VS Code might use its own TS version until you manually "Select TypeScript Version..." in the command palette and choose to use the workspace version.

**Comment by furf** [comment]
It looks like that was the issue. It was relying on the monorepo's TS version instead of the package. It HAD been using the package's version, but the plugin install must have modified it. 🤷 

<img width="447" alt="image" src="https://github.com/statelyai/xstate/assets/35775/f306f2e3-050a-44be-8357-05306f35154f">

<img width="259" alt="image" src="https://github.com/statelyai/xstate/assets/35775/bce9716c-29f8-4da2-9b9c-781d333a6f90">

I was able to get things sorted. 

<img width="976" alt="image" src="https://github.com/statelyai/xstate/assets/35775/b770d2e1-acee-44de-ae31-66257f70119a">

<img width="290" alt="image" src="https://github.com/statelyai/xstate/assets/35775/d693a550-428f-4d5d-b16c-ef6c67e201b0">

Thanks for your advice!
