### ISSUE TITLE
Bug: npm version of `@xstate/solid` lists a peer dependency to `xstate@4.37.0` causing a peer dependency warning when using xsate v5

### ISSUE THREAD

**Issue by escritorio-gustavo** [statelyai/xstate#4682]
### XState version

XState version 5

### Description

The `package.json` of the `xstate/solid` package in this repo lists a peer dependency to `xstate@5.5.1`, but the version publish to npm depends on `xstate@4.37.0` causing a peer dependency warning.

### Expected result

No warnings when installing both packages

### Actual result

```
+ @xstate/solid ^0.1.3

 WARN  Issues with peer dependencies found
.
└─┬ @xstate/solid 0.1.3
  └── ✕ unmet peer xstate@^4.37.0: found 5.5.1
```

### Reproduction

npm i xstate @xstate/solid

**Comment by Andarist** [comment]
We are still working on releasing the `@xstate/solid` version that would be compatible with v5. To do this we need to fix https://github.com/statelyai/xstate/issues/3925

**Comment by escritorio-gustavo** [comment]
I see... so other than the `after` bug, is it safe to use `@xstate/solid` with v5 as of right now?

**Comment by Andarist** [comment]
I wouldn't say so - at the very least you could run into TS-related issues but there might be others as well. It's hard to say with certainty what kind of problems you could run into but on principle the currently published version of `@xstate/solid` integrates with XState v4 and it's not meant to be used with v5.

You could copy-paste things that you need directly from our repo ([here](https://github.com/statelyai/xstate/tree/2ba2d7fa78585f35a6377143e1b8df2b3541b4d9/packages/xstate-solid/src)). This code is adjusted to use the v5 APIs and all.

**Comment by escritorio-gustavo** [comment]
Okay, I'll stick to v4 for now then, thank you for the quick response
