### ISSUE TITLE
Bug: Actor Unions have typing issues related when calling methods

### ISSUE THREAD

**Issue by devanfarrell** [statelyai/xstate#4734]
### XState version

XState version 5

### Description

Unions of actor types have issues when it comes to calling methods like `can` or `matches`.

### Expected result

A union type of actors that has the same states and events shouldn't complain if you try to use `can` or `matches`.

### Actual result

Typescript can't figure out that they are essentially the same outside of the context object and requires a `ts-expect-error` to use the methods due to the `this` property not being the same.

### Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwKYwK5gDRwIIDGM0ASqgGYBiUEIcAvnOTXQOQAeyMAhjKqwG4AUKEixEcDGgDKqADaoi0BkxZxWAAU48+AeiipuRQSPDR4SSgGEVzWuoNGYJoanZj4BCADsucb6gA7sgACtxgqFAAskYAFsABcAC8KOhYABQIQnBwMACeEcgAXIiM3MiI2TlwXt587DAlWdXVMMAwCsUoMFAJAOYA2gC6wi30o9WoAG6odcVVLQA+lS2ruQWoJawAIgCiADK7ACq7JmstwAAmJVy93n0Ta-QL1cvN5zn5EVt429tnH1y7QUNx6-Ueq3GVXo2CE9AAlAA6AiOPgxAjxAKZKq1eqNCRtDqoLrDBiwnIJdrAbhyLZXBSscndXjEpovembUpMmFw+HCVzucw1Hx+ABGEAgAGt0ZjUMlUpgwNjPhsuggyhV3jlcW58VrWsDWd07oMRi8oS1prMYPM1m8XmsvpydgdjqcIWsrqCTR7qs87StAU6fn8AR9CSDjeCHX6Y291t91FYABK7KwAaQA+gB5ACqR0EcC9UfuDAmPIRyNRqBlCVQyuFdV1TSBRJJQzJVUpbRpdMuDKZXBZavZ-c56u5sIR-KdcAAckFQuFIrWAmRyPLCMQoOvqLQADxOiAbgLBMIRaJxOsAPmEs4AQhLpVe1xRN0odxQ9yBDxtj3BxSlVdUFvIQBQ8Rs-F2dhuHASNrH3JAnFICgSgXM9l0vDE63XOBlkfICX1QdcBCLa4Sz6Bhr3lTI4GQz9yFwK4GHhZJqPeWo-BAIj5SkVBZAUD90no9dcHSZBWKSaiJImTj4DQbxLnlESKERBTLn5HIDEwKBvDgdIXn3UUMBgYg9MuYBkG4UUFEuJIEAAQm47CAmRbhvFo4N1D2Q4TkZMiWMYHwrDkYACElez0kk6TZkuTyNi2Hy3X85iEXoa8Y22eR0FQQzdGM0yfAynI+ThYQgA

**Comment by Andarist** [comment]
The fix for this would be to remove `this` parameter from all snapshot methods.
