### ISSUE TITLE
Bug: Child machine provides do not get latest implementation

### ISSUE THREAD

**Issue by clarinetpaul** [statelyai/xstate#4736]
### XState version

XState version 5

### Description

I have a child machine actor spawned from a parent actor. I want to be able to provide this child actor with the latest implementation from React. In the Codesandbox below, I expect both the `childPrint` and the `parentPrint` to print the latest counter. However, it seems like only the `parentPrint` will get the latest implementation. `childPrint` will continue to print with counter 0.

```
  const [counter, setCounter] = useState(0)
  const [state, send] = useMachine(feedbackMachine.provide({
    actions: {
      parentPrint: () => console.log('parent print: ', counter)
    },
    actors: {
      childMachine: childMachine.provide({
        actions: {
          childPrint: () => console.log('child print: ', counter)
        }
      })
    }
  });
```

What is the best way for child actors to get the latest implementation?

### Expected result

Expect child machine actors to get the latest provided implementation.

### Actual result

Only the parent machine gets the latest provided information.

### Reproduction

https://codesandbox.io/p/devbox/child-provide-nqmmnz?file=%2Fsrc%2FApp.tsx%3A27%2C12

**Comment by Andarist** [comment]
`spawn`/`spawnChild`/`invoke` "freeze" the spawned/invoked child in this sense. It never has been our intention to make those `.provide` calls within React components recursive. I'm inclined to say that this works as expected. WDYT @davidkpiano ?

**Comment by davidkpiano** [comment]
I recommend you use a [ref with `useRef`](https://react.dev/learn/referencing-values-with-refs) to access the latest value within a closure, regardless of whether this is being done in XState or not.
