### ISSUE TITLE
Bug: error TS2344: Type 'NonNullable<TStateValue[K]>' does not satisfy the constraint 'StateValue'

### ISSUE THREAD

**Issue by autoscatto** [statelyai/xstate#4737]
### XState version

XState version 5

### Description

When I transpile my project, I get an error regarding the xstate types:

`
node_modules/xstate/dist/declarations/src/State.d.ts:5:49 - error TS2344: Type 'NonNullable<TStateValue[K]>' does not satisfy the constraint 'StateValue'.
  Type 'NonNullable<TStateValue[K]>' is not assignable to type 'StateValueMap'.
    Index signature for type 'string' is missing in type '{}'.

      [K in keyof TStateValue]?: ToTestStateValue<NonNullable<TStateValue[K]>>;
`

### Expected result

no type errors in transpilation

### Actual result

type errors in transpilation

### Reproduction

https://stackblitz.com/edit/github-9ms4pa?file=tsconfig.json

**Comment by Andarist** [comment]
TypeScript's `strict` mode is required for XState v5 to typecheck correctly.

**Comment by davidkpiano** [comment]
See here for all the TypeScript requirements: https://stately.ai/docs/typescript

**Comment by asheeshmathur** [comment]
I still get following messages when I import
"node_modules/xstate/dist/declarations/src/State.d.ts:5:49 - error TS2344: Type 'NonNullable<TStateValue[K]>' does not satisfy the constraint 'StateValue'.
  Type 'NonNullable<TStateValue[K]>' is not assignable to type 'StateValueMap'.
    Index signature for type 'string' is missing in type '{}'.

5     [K in keyof TStateValue]?: ToTestStateValue<NonNullable<TStateValue[K]>>;
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/xstate/dist/declarations/src/State.d.ts:5

Can I run it as node app as backend console
