### ISSUE TITLE
Type error since xstate@5.8

### ISSUE THREAD

**Issue by nightire** [statelyai/xstate#4814]
## Bug or feature request?

Bug report

## Description:

There's a type error when using `spawn` since xstate@5.8, I've made a minimal reproduction to show and compare:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnAggYxtAJXQDMAxKCEAGjgGd0YBXMOAXzmIpDgCIAPWjACGMdDwBQAeklxQkWImRpMufFCJkuNekxbtOlXgOGiecaUoy0AXHACsAOgDsDgIzipAKk90A7sBgcAAtkCHtnNzgQIRQ4KHQAR0ZgeNpQuJJUkJgg4DSwIQBzTE9JDxwIADtBOGDgABsAEwBZITrKzABeOgZmAAoEVgBKBxx4kXRW9vQB8ThZRtseOqaeKnFh8qqagvjKmCncjrhunX6EOct0G0RL+Yr99D4YW0G4ITSkFcbVaFtf9QkciUAA8qAwEGItVyTUOwA6AD42Ot5qx1sNRuNRHCOrN5sBFrxduh9mtLg9RM9bAM6AVfJU2EMTkiLvN5vEmFAGay2fcYT88H9aUJ6X1vjj0EMUWzWJc0RshuIgA

## (Bug) Expected result:

The same code works well with versions lower than v5.8.0

## (Bug) Actual result:

The same code shows a bug with versions higher than or equal to v5.8.0

**Comment by davidkpiano** [comment]
cc. @Andarist

**Comment by nightire** [comment]
For your information, this is an alternative version that does not have the type problem; if the previous example is an anti-pattern after xstate@5.8, should we emphasize it in the document?

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnAggYxtAJXQDMAxKCEAGjgGd0YBXMOAXzmIpDgCIAPWjACGMdDwBQAeklxQkWImRpMufFCJkuNekxbtOlXgOGiecaUoy0AXHACsAOgDsDgIzipAKk90A7sBgcAAtkCHtnNzgQIRQ4KHQAR0ZgeNpQuJJUkJgg4DSwIQBzTE9JDxwIADtBOGDgABsAEwBZITrKzABeOgZmAAoEVgBKBxx4kXRW9vQB2UbbHjqms2GPdD55eArq+AL4ypgp3I64bp1+hHE4ODa1G0Qr69rcpqPgDsfWKkfUK1tLp61KqiPgwf7sIRpJBLRqqaC2OHqEjkSgAHl+6AgxGeDRabWO6AAfGxvtcvuJhqNxqI3h0Bo9gPNeHt0AceKSgQd1mC4LNaAVfJU2ENTsSAU94kwoELxYCYYjbPyhIK+osXnjpjwhhyyZ9vqsgA

**Comment by davidkpiano** [comment]
The error seems to no longer exist for the latest version of XState 🎉
