### ISSUE TITLE
Bug: Promise actor error handling doesn't work as documented

### ISSUE THREAD

**Issue by fusionstrings** [statelyai/xstate#4852]
### XState version

XState version 5

### Description

Promise actor error handling [doesn't work as documented](https://stately.ai/docs/promise-actors#promise-actor-error-handling).

It's notable that if actor is invoked with `onDone` and `onError` then it works as expected but in that case there must be an output property in machine as [documented here](https://stately.ai/docs/output#output-and-typescript). 

Here is [repository](https://github.com/fusionstrings/xstate-promise-actor-error) which reproduces the error.

### Expected result

Directly using promise actor doesn't [need to have these boilerplates](https://stately.ai/docs/output#output-in-promise-actors), as the output is the return value of the promise. 

### Actual result

This works in case of success but not in case of thrown error.

Machine never reaches to `snapshot.status === 'error'` because thrown error terminates the process.

### Reproduction
[Code Sandbox](https://codesandbox.io/p/github/fusionstrings/xstate-promise-actor-error/creation)

**Comment by Andarist** [comment]
The docs are wrong here - errored snapshots are never given to the `next` listeners. You can handle errors in this situation like this:

```ts
const { fromPromise, createActor } = require("xstate");

const promiseLogic = fromPromise(async () => {
  // ...
  throw new Error("Something went wrong");
});

const promiseActor = createActor(promiseLogic);
promiseActor.subscribe({
  error: (error) => {
    console.log(error);
  },
});

promiseActor.start();

```

**Comment by davidkpiano** [comment]
Fixed the documentation: https://stately.ai/docs/promise-actors#promise-actor-error-handling

**Comment by fusionstrings** [comment]
Thanks 🙏
