### ISSUE TITLE
Bug: [@xstate/store] typings broken

### ISSUE THREAD

**Issue by wcastand** [statelyai/xstate#4859]
### XState version

XState version 5

### Description

the transition event is broken when i pass a type to create.

because i try to access `event: { newContext }` but types expect `update` to possibly also be `{type: update}` which breaks the types.

Couldn't find an example in your repo on typing stores so maybe i'm doing it wrong.

### Expected result

type to not show an error

### Actual result

showing a type error when passing the `update` fn

### Reproduction

https://replit.com/join/ifbbvxzfvf-wcastand

**Comment by davidkpiano** [comment]
Can you try with the latest version?

**Comment by wcastand** [comment]
looks fixed, thanks :)
