### ISSUE TITLE
Bug: History state in parallel machines is changing states unexpectedly

### ISSUE THREAD

**Issue by ccapndave** [statelyai/xstate#4900]
### XState version

XState version 5

### Description

<img width="768" alt="image" src="https://github.com/statelyai/xstate/assets/297992/b96b65d2-5de4-4228-b0fd-cb1ef77d01a2">

Given the above [machine](https://stately.ai/registry/editor/bd32f722-9969-49f2-b2c4-18a0f14275c5?machineId=77da3e21-71fa-4f1c-b4d8-acdd6895be75&mode=Design), send the following sequence of events in the simulator:

1. `child1.next`
2. `child2.next`
3. `child1.history`
4. `child1.history`
5. `child1.history`
...

### Expected result

Whenever history is called, both machines stay in their previous state as (I think?) is expected.  I use this pattern in my application to intercept events that need to do actions without changing any states.

### Actual result

Although we get this result in the simulator, in real XState code it behaves differently.  If both machines are in their `Next` states and `child1.history` is sent, one of the machines changes back to its initial state.

This can be reproduced by clicking on the buttons in the codesandbox.  In this case when both machines are in `Next` and `child1.history` is sent, `Child1` goes back to its initial state.

### Reproduction

https://codesandbox.io/p/sandbox/jolly-meadow-5sxz66

### Additional context

Note that in my actual app in fact it is `Child2` (i.e. the machine without the history state) which goes back to its initial state and `Child1` stays where it is.

**Comment by davidkpiano** [comment]
It says "Sandbox not found" - can you please make it available?

**Comment by ccapndave** [comment]
Sorry!  Have a go now.

**Comment by davidkpiano** [comment]
Workaround (as discussed on Discord):

- Don't use a history state
- Remove the `target` from the transition (make a targetless transition)
- Only use `actions: ...`
