### ISSUE TITLE
Bug: _xstate_react__WEBPACK_IMPORTED_MODULE_1__.useInterpret is not a function

### ISSUE THREAD

**Issue by gls-manifold** [statelyai/xstate#4927]
### XState version

XState version 5

### Description

I try to use this hook [link](https://xstate.js.org/docs/packages/xstate-react/#useinterpret-machine-options-observer) as in the example, but I get an error:
_xstate_react__WEBPACK_IMPORTED_MODULE_1__.useInterpret is not a function

"xstate": "^5.8.0",
"@xstate/react": "^4.1.1",

### Expected result

Working hook

### Actual result

_xstate_react__WEBPACK_IMPORTED_MODULE_1__.useInterpret is not a function

### Reproduction

xstate/react

**Comment by davidkpiano** [comment]
This is as expected; it has been deprecated. Please see here: https://stately.ai/docs/migration#useinterpret-is-now-useactorref

-----


### `useInterpret()` is now `useActorRef()`

Breaking change

The `useInterpret()` hook, which is used to return an `actorRef` ("service" in XState v4), is renamed to `useActorRef()`.

```ts
// ✅
import { useActorRef } from '@xstate/react';

const actorRef = useActorRef(machine); // or any other logic
```

```ts
// ❌ DEPRECATED
import { useInterpret } from '@xstate/react';

const service = useInterpret(machine);
```
