### ISSUE TITLE
Bug: https://stately.ai/docs/xstate - Docs site is not working

### ISSUE THREAD

**Issue by RollingTL** [statelyai/xstate#5004]
### XState version

XState version 5

### Description

https://stately.ai/docs/xstate - is not accessible

https://stately.ai/docs - can't be opened in Safari,  but works in Chrome

### Expected result

Site is working

### Actual result

Safari can't Open the page
Chrome can't Open the page

### Reproduction

goto https://xstate.js.org

**Comment by with-heart** [comment]
Tested it on Chrome and Safari on my iPhone, iPad, and MBP. Everything seems to be working fine

**Comment by RollingTL** [comment]
Started working.
