### ISSUE TITLE
Bug: [Typescript] EventFrom helper type returning `never` since 5.17.0

### ISSUE THREAD

**Issue by taraldr** [statelyai/xstate#5031]
### XState version

XState version 5

### Description

`EventFrom` and `ContextFrom` utilities appear to have stopped working since 5.17.0, always returning `never` when being passed the typeof a machine.

### Expected result

Expected non-`never`.

### Actual result

Got `never`.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qubngj?file=src%2Fmain.ts&view=editor

**Comment by davidkpiano** [comment]
Quick workaround for events: use `EventFromLogic` instead of `EventFrom`

Investigating this 🔍
