### ISSUE TITLE
Bug: `input` is not inferred using `fromPromise` in `setup`

### ISSUE THREAD

**Issue by FedericoBiccheddu** [statelyai/xstate#5102]
### XState version

XState version 5

### Description

Using `fromPromise` for defining `actors` in  `setup`, the parameter `input` is not inferred.

### Expected result

I expect the `input` to be inferred as the `useActor` works correctly and requires `input` to be provided.

### Actual result

`Property 'myInput' does not exist on type '{}'. ts(2339)`

### Reproduction

https://codesandbox.io/p/devbox/xstate-ts-actor-input-frompromise-infer-zwfvs5?file=%2Fsrc%2FfeedbackMachine.ts%3A26%2C63-26%2C76

### Additional context

xstate: 5.18.2
@xstate/svelte: 3.0.5

**Comment by Andarist** [comment]
It works OK as intended, the input that you configure for your promise actor is its input - not the input given to the outer machine. Please take a look at this TS playground that, I hope, will help to clarify the confusion: [TS playground](https://www.typescriptlang.org/play/?ts=5.6.3#code/JYWwDg9gTgLgBAbzgZwKYwK5gDRwGZQQgAKhIwauAxlKgIYyoCCVM0cAvvmXAEQAeyGA1S8A3HAD0kuDACeYVMgBccAKwA6AIwAODQCYAUIaoQAdkLgg6VABbAzqOAF4U6LAAoEhuLIVLVBC46ZEQfXzgHMAwYQPCIuAgY1ChVISgHAHMxeM4c3w5scJs2KBUwhIATCABlTDw8VQIiUiIKVA9c3xC5Myo4L0izaPgOQKGR8YdHVLgzDBAAIxTOTgBKFwA+LoiAWQZbDSg6M2qQDw2AagmYjWmUooS1x84ijjWNGnpGfbsHDu8vgcADcIABrVBxBLIKBUVS8ap1DANXgvIHDGJQhJSGQAARgyAAtKh+IpWMSoIQoDt7rNeHgIBBUblCuFWe8coZpHB8USSWSYBSqSZaCIWKUPNY-o41pyvmLWNBJTZ7I5cICbrEKhFubziaTUOSUsKEklGLMACz6F7s2Ui77MRVQZXS1Dq8JRTHa3xmlLwuR0OQAQmZBTedqAA)

**Comment by FedericoBiccheddu** [comment]
I found it a bit counterintuitive, but I understand it now; thank you for the example.

So the suggested approach is to provide the second generic to `fromPromise` in order to keep the parameter (`promiseCreator`) correctly typed, right?

**Comment by Andarist** [comment]
Providing explicit generic to `fromPromise` is probably the easiest.
