### ISSUE TITLE
Bug: @xstate/react not compatible with React 19

### ISSUE THREAD

**Issue by rothsandro** [statelyai/xstate#5138]
### XState version

XState version 5

### Description

React 19 was just released. `@xstate/react` already added support for this version in #5109 but there is still an error when running `npm i` again because the package depends on `use-isomorphic-layout-effect` which doesn't support React 19.

### Expected result

No error when running `npm i`

### Actual result

![image](https://github.com/user-attachments/assets/89cc8bb8-5eb5-4cf5-a6db-9f2547acd12a)

### Reproduction

https://stackblitz.com/edit/github-sr4un6?file=package.json

### Additional context

`use-isomorphic-layout-effect` has an open PR https://github.com/Andarist/use-isomorphic-layout-effect/pull/6

**Comment by Andarist** [comment]
`use-isomorphic-layout-effect@1.2.0` has been published, you can update it to resolve the issue on your end
