### ISSUE TITLE
Bug: @xstate/graph ignores always transitions

### ISSUE THREAD

**Issue by hyrfilm** [statelyai/xstate#5160]
### XState version

XState version 5

### Description

When using @xstate/graph `always` transitions are either ignored completely (eg `getSimplePaths`) or their targets are not represented as edges (`toDirectedGraph`).

### Expected result

I expected always-transitions to in some way be represented by at least one of the functions in @xstate/graph

### Actual result

`getSimplePaths` and `getShortestPaths` seems to ignore them completely. `toDirectedGraph` represents them as nodes but without any edges.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-udamrvkw?file=src%2Fmain.ts

**Comment by davidkpiano** [comment]
This is expected - XState Graph calculates the graph by determining the next state given the current state and triggered event, and _internally_ an always-transition immediately transitions to another state. XState Graph only sees the final resulting state.

What is your use-case for wanting to see the intermediate transitions?

**Comment by hyrfilm** [comment]
@davidkpiano Ah ok, I see. TL;DR My use-case was for writing unit-tests. I'm testing the machine when its running as well but wanted additionally to have tests that just focused on the transitions/paths, so I was a bit confused when there didn't seem to be any function in @xstate/graph for covering the always-transitions...

Long explanation: I'm working on a persistent task queue running in the browser. One of the things I'm using xstate for is for the executor (which there can be several of). A snippet of that code looks like this:
```ts
machineSetup.createMachine({
  context: {},
  id: "TaskExecutor",
  initial: "idle",
  states: {
    idle: { always: { target: "ready" } },
    ready: {
      tags: ["ready"],
      on: {
        poll: { target: "reservingTask" },
      },
    },
    reservingTask: {
      tags: ["busy"],
      invoke: {
        src: "reserveHook",
        onDone: { target: "taskExecuting" },
        onError: { target: "noReservation" },
      },
    },
    taskExecuting: {
      invoke: {
        src: "executeHook",
        onDone: { target: "taskSuccessful" },
        onError: { target: "taskFailed" },
      },
    },
    noReservation: {
      always: { target: "continue" },
    },
    taskFailed: {
      invoke: {
        src: "failureHook",
        onDone: { target: "backingOff" },
        onError: { target: "halted" },
      },
    },
    taskSuccessful: {
      entry: () => {
        backoff.resetBackoff();
      },
      invoke: {
        src: "successHook",
        onDone: { target: "continue" },
        onError: { target: "halted" },
      },
    },
    continue: {
      always: { target: "ready" },
    },
    backingOff: {
      after: {
        DELAY: { target: "continue" },
      },
      exit: () => {
        backoff.increaseBackoff();
      },
    },
    halted: {
      type: "final",
    },
  },
});
```

So for example, if the executor fails to reserve a task it goes to the `noReservation` state, and it eventually ends up back in the `ready` state. I'm aware of the fact that I could remove the always-transitions in this machine, and just let the preceding states transition to where they eventually will end up of course. But I found it easier to model and reason about the machine by having these intermediate states, and I'm also planning to add some actions for the `noReservation`-state as well.

Amazing library btw, especially v5 is mindbendingly awesome. Thanks a lot. ❤️
