### ISSUE TITLE
State meta and context are not available when interpreting a machine

### ISSUE THREAD

**Issue by nick-keller** [statelyai/xstate#564]
# Bug

## Description:
When interpreting a machine and starting from a state, the state's meta and context are not available:

```js
const machine = Machine({
  id: 'flow',
  initial: 'step1',
  states: {
    step1: {
      on: {
        NEXT: 'step2',
      },
    },
    step2: {
      meta: {
        name: 'step2',
      },
    },
  },
})

const service = interpret(machine.withContext({ key: 'value', }))

service.start('step2')

console.log(service.state.context, service.state.meta)
// => undefined {}
```
## Expected result:
I'd expect the same result than doing this:
```js
service.start()
service.send('NEXT')

console.log(service.state.context, service.state.meta)
// => { key: 'value' } { 'flow.step2': { name: 'step2' } }
```

Maybe I am doing something wrong here?

**Comment by davidkpiano** [comment]
⚠️ `service.state` is a volatile property and you should avoid accessing it directly. Instead, you should always read the state as it comes in via a transition listener:

```js
service.onTransition(state => {
  console.log(state); // will have state.meta and state.context
});
```

Or a subscription:

```js
const subscription = service.subscribe(state => {
  console.log(state); // same as above
});
```

**Comment by nick-keller** [comment]
When doing this:
```js
const service = interpret(machine.withContext({ key: 'value', }))

service.onTransition(state => {
  console.log(state.context, state.meta)
  // => undefined {}
})

service.start('step2')
```

I still do not get the context and the meta. Same thing for `.subscribe()`.

I am wondering if this is because I start the interpreter from a step using a string. Maybe this is not the right way of serializing a state, I should serialize everything, including meta and context?

**Comment by davidkpiano** [comment]
> Maybe this is not the right way of serializing a state, I should serialize everything, including meta and context?

Generally yes, this is a good practice. See here: https://xstate.js.org/docs/guides/states.html#persisting-state

**Comment by thomasaull** [comment]
@davidkpiano I'm having the same problem as in the code example in @nick-keller's comment (https://github.com/davidkpiano/xstate/issues/564#issuecomment-514081349) and I think this issue is not resolved. Could you reopen maybe?

**Comment by davidkpiano** [comment]
@thomasaull ✏️ Please create a [CodeSandbox (XState template)](https://codesandbox.io/s/xstate-example-template-qcwed) reproduction of this. Thanks!

**Comment by thomasaull** [comment]
I was able to work around this by using the following:

```javascript
let initialState = stateMachine.getInitialState('my.initial.state.path')
stateService.start(initialState)
```

In this case all the meta information, actions etc. are there.

Code Sandbox for both the initial issue and the workaround: https://codesandbox.io/s/xstate-start-service-with-state-b16le
