### ISSUE TITLE
"Root" machine shouldn't produce done event 

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#590]
Leaving this mainly as a reminder for myself to look into this - I believe this case is not handled properly right now, according to the spec:

> In cases where the SCXML Processor generates a 'done' event upon entry into the final state, it must evaluate the <donedata> elements <param> or <content> children and place the resulting data in the _event.data field. The exact format of that data will be determined by the data model (see B Data Models for details). In other cases (namely when the <final> element is a child of <scxml> and the state machine has not been triggered by <invoke>), the SCXML Processor should return the data to the environment in an implementation-dependent manner.

The done data of a final state of the root machine should be given to the user in onDone callback or something.

**Comment by davidkpiano** [comment]
Related to #464?

**Comment by Andarist** [comment]
Not quite, rather to my findings described [here](https://github.com/davidkpiano/xstate/pull/536#issue-296926165) and that [TODO comment](https://github.com/davidkpiano/xstate/blob/9191d331531db563c48736fb46e7b5f46925510c/src/StateNode.ts#L983) (so basically just regarding correct `done.state.id` events generation algorithm)

**Comment by davidkpiano** [comment]
Producing a `done` event can be considered the implementation-dependent manner for this. We'll close this out as it's stale regardless, and bring it up again if it contradicts any SCXML tests.

**Comment by Andarist** [comment]
There won't be any SCXML test for this as it's hard to write one - can't listen for events sent from "root" SCXML service there.

However, it can be easily confirmed by the `exitInterpreter` algorithm: https://www.w3.org/TR/scxml/#exitInterpreter .:
```
        if isFinalState(s) and isScxmlElement(s.parent):   
            returnDoneEvent(s.donedata)
```
Currently our implementation doesn't adhere to this 1to1. We just generate `doneInvoke` for a finished machine, the parent gets notified about it through `onDone` callback and it sends the received event to itself.

The distinction is not that much observable, but it's there in terms of how this communication is taken care of.

**Comment by davidkpiano** [comment]
This has been added to the v5 `next` branch and will be available in an upcoming alpha release.

Specifically here, where a done invoke event is explicitly being sent to the parent from any actor: https://github.com/statelyai/xstate/blob/next/packages/core/src/interpreter.ts#L186-L192
