### ISSUE TITLE
Invoked services communicating their errors with wrong type

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#623]
I don't want to touch this as part of v4, but maybe this would be something to consider before next major.

At the moment we use `error.platform.#id` for those, but when reading and analyzing SCXML spec I've noticed that this might be wrong. In general description of `error.platform` is vague as f* 😢 and there are no good examples of how this can be utilized. There are also no w3c tests covering this as its platform-specific.

According to https://www.w3.org/TR/scxml/#ErrorEvents any errors should be **raised** (so that would include `error.platform`): 
> Once the SCXML processor has begun executing a well-formed SCXML document, it must signal any errors that occur by raising SCXML events whose names begin with 'error.'. the processor must place these events in the internal event queue and must process them like any other event.

Communication between invoked service and the invoking one is always external though, so an invoked service can't put anything (even errors) into its parent internalQueue. One could argue that such errors are not even errors per se but rather events which signalize some kind of a failure. Technically i.e. Promise service can be expressed as SCXML with 3 states (pending, resolved, rejected) where resolved & rejected are of type final and thus entering them should send an external `done.invoke` to the invoking service.

The confusing part of the spec ( https://www.w3.org/TR/scxml/#InternalStructureofEvents ) is that errors are considered to be events of type platform:
> type. This field describes the event type. The SCXML Processor must set it to: "platform" (for events raised by the platform itself, such as error events), "internal" (for events raised by <raise> and <send> with target '_internal') or "external" (for all other events).

But it's not necessarily contradicting any previous points.

**Comment by coodoo** [comment]
I, for one, also found the naming scheme `error.platform.#id` a bit weird (and it's not mentioned anywhere in the doc at all, btw), just wondering is there any valid solution to this now? Thanks.

**Comment by Andarist** [comment]
My concerns are purely from the SCXML perspective - you shouldn't quite rely on that event's type (whatever we settle for) in your code anyway.

**Comment by coodoo** [comment]
So how to receive events (both `resolve` and `reject`) from a spawned actor (Promise in this case), currently using `error.platform.#id` seemed to be the only way to go?

**Comment by Andarist** [comment]
Hm, that's a good question! I forgot about spawned actors, for invoked ones you can totally implement logic without relying on those types. 

I'm not completely sure what's the recommended way of handling this, but seems like indeed you have to inspect the event's type. For now, I would recommend creating helper functions for testing those events - so you could swap the implementation easily in the future if we decide to change the type in next major version.

**Comment by davidkpiano** [comment]
Addressed in #1240

**Comment by Andarist** [comment]
@davidkpiano I'm not sure if this has been addressed in #1240. This issue here is about "async" errors events - and that PR has mostly tweaked cases when a service cant send an event to another actor.

I've created this issue because, as far as I understand, SCXML treats error events as **local** to a statechart. It never receives those `error.*` events from other actors, but yet it is what we are doing. So in this regard, we introduce some semantic discrepancy between XState and SCXML. Assuming I'm interpreting this correctly... 🤷‍♂️

**Comment by davidkpiano** [comment]
Ah, yeah you're right. Regarding the original issue:

> One could argue that such errors are not even errors per se but rather events which signalize some kind of a failure. 

This is what we have to embrace. Any non-local "error" is an event like any other. Just like an HTTP request can respond successfully, but might have `status: 500`, which we would need to _interpret_ as an error (or not, depending on biz logic requirements).

**Comment by davidkpiano** [comment]
@Andarist What should be done here?

**Comment by Andarist** [comment]
We diverged from SCXML here in https://github.com/statelyai/xstate/pull/4270 and we plan to maintain our own "rules" around this (perhaps inspired by SCXML but with no goal of being the same).
