### ISSUE TITLE
Sync actor emits crashing on sync responses

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#671]
Each `.spawnX` method subscribes to the spawned actor first and only after that the created actor gets put into `this.children`, so if that actor emits an event synchronously which causes a "response" event to that actor synchronously then the machine will crash on invalid target here:
https://github.com/davidkpiano/xstate/blob/912d204a01b2d3fb90755a6d3c5d3e1fd64095ce/src/interpreter.ts#L582

**Comment by davidkpiano** [comment]
Can you make a simple test case? This probably has a straightforward fix (reordering so that the actor is defined on `this.children` before any subscription happens).

**Comment by Andarist** [comment]
I plan to handle this later, reported it here as a reminder for myself.

The fix is not 100% straightforward because of actor definition often referencing stuff from actor creation (like subscription), so this is kinda a circular dependency problem. I'd like to spend slightly more time on this one to figure out a clean implementation - because such things become quickly condition hells.

**Comment by davidkpiano** [comment]
@Andarist is this still valid?

**Comment by davidkpiano** [comment]
Closing as stale; feel free to reopen.
