### ISSUE TITLE
Always resolve state value to leaf nodes

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#674]
At the moment e.g. compound states without initial state defined can get "stuck" in the middle of the state node tree. 

According to SCXML semantics, this results in an invalid configuration. We should either:
- throw if no initial state is provided
- use SCXML logic for picking default initial state (first in document order) 

Seems like both solutions are pretty much breaking, so probably this would have to wait for v5

**Comment by davidkpiano** [comment]
Yeah, I think the major focus for 5.0 should be dev-time static analysis, so that invalid configurations are surfaced earlier.

**Comment by Andarist** [comment]
The dev-time static analysis would be a great feature, not sure if it has to be tied to 5.0 though. It can be implemented (most likely as ESLint plugin) at any time as it's a completely new feature.

We can also surface invalid configurations in dev mode at runtime (and we probably should do that independently of possible static analysis) - but that is often a breaking change and thus has to wait for a new major version.

**Comment by SimonGAndrews** [comment]
Hi, have you decided if or not, future version will use the 'first in doc order' as the default when initial not specified on a compound state ?   I suppose if used it means there could never be a transition to a compound state, is that correct??

**Comment by SimonGAndrews** [comment]
pS ... I mean the a transition would never resolve to a compound state.  :)

**Comment by davidkpiano** [comment]
> Hi, have you decided if or not, future version will use the 'first in doc order' as the default when initial not specified on a compound state ? I suppose if used it means a transition could never Resolve to a compound state, is that correct??

I don't believe we will use "first in doc order" since that ordering isn't guaranteed with object keys: https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by davidkpiano** [comment]
This is currently in the v5 `next` branch, and it correctly throws an error like:

> No initial state specified for compound state node "#(machine).one". Try adding { initial: "two" } to the state config.
