### ISSUE TITLE
[4.7.0] proper type for second generic parameter to assign?

### ISSUE THREAD

**Issue by wKovacs64** [statelyai/xstate#836]
**Description**

May not be a bug, might just be a misunderstanding. Prior to v4.7.0, I had omitted the second generic parameter of the `assign` action creator and TypeScirpt was OK with it, but now it complains that `event` does not have a `data` property (which makes sense, because it now defaults to `EventObject` which does not have said property).

Example:
```ts
interface Context {
  count: number;
}

interface Schema {
  states: {
    inactive: {};
    active: {};
  };
}

interface ToggleEvent {
  type: 'TOGGLE';
}

const machine = Machine<Context, Schema, ToggleEvent>(
  {
    id: 'machine',
    initial: 'inactive',
    context: {
      count: 0,
    },
    states: {
      inactive: {
        on: { TOGGLE: 'active' },
      },
      active: {
        invoke: {
          id: 'setCountService',
          src: () => Promise.resolve(42),
          onDone: {
            actions: 'setCount',
          },
        },
        on: { TOGGLE: 'inactive' },
      },
    },
  },
  {
    actions: {
      // what should the second generic parameter to `assign` be?
      setCount: assign<Context /* , ___here___ */>({
        count: (_, event) => event.data,
      }),
    },
  },
);
```

**Expected Result**

No errors.

**Actual Result**

```
Property 'data' does not exist on type 'EventObject'.
```

**Reproduction**

https://codesandbox.io/s/xstate-issue-836-w3bjm

**Additional context**

I found `AnyEventObject` works, but I am uncertain if that's correct. Is there something narrower that makes more sense to use here?

**Comment by davidkpiano** [comment]
The second parameter should be which events would trigger this action, or (in your case) just `ToggleEvent`.

**Comment by wKovacs64** [comment]
In this example, it's not a `ToggleEvent` because the action is called from an `onDone` handler of an invoked service. So `event.data` is the result of the resolved Promise in the service `src` property. It's in the CodeSandbox, but I updated the issue to include the entire machine.

Maybe I'm just way more off base than I thought? 😅

**Comment by davidkpiano** [comment]
Ah, then provide it the event that you expect.

In 4.7, event typings were fixed because it was a mistake to assume that an event can contain any payload where it might not exist.

**Comment by wKovacs64** [comment]
> Ah, then provide it the event that you expect.

That doesn't seem to work, as TS complains if the event passed here does not match the event that was passed into the machine config:

```
interface SetCountServiceResolvedEvent {
  type: 'done.invoke.setCountService';
  data: number;
}

// or maybe just `DoneInvokeEvent<number>` ?
```

```
Argument of type '{ actions: { setCount: AssignAction<Context, SetCountServiceResolvedEvent>; }; }' is not assignable to parameter of type 'Partial<MachineOptions<Context, ToggleEvent>>'.
  Types of property 'actions' are incompatible.
    Type '{ setCount: AssignAction<Context, SetCountServiceResolvedEvent>; }' is not assignable to type 'Record<string, ActionFunction<Context, ToggleEvent> | ActionObject<Context, ToggleEvent>>'.
      Property 'setCount' is incompatible with index signature.
        Type 'AssignAction<Context, SetCountServiceResolvedEvent>' is not assignable to type 'ActionFunction<Context, ToggleEvent> | ActionObject<Context, ToggleEvent>'.
          Type 'AssignAction<Context, SetCountServiceResolvedEvent>' is not assignable to type 'ActionObject<Context, ToggleEvent>'.
            Types of property 'exec' are incompatible.
              Type 'ActionFunction<Context, SetCountServiceResolvedEvent> | undefined' is not assignable to type 'ActionFunction<Context, ToggleEvent> | undefined'.
                Type 'ActionFunction<Context, SetCountServiceResolvedEvent>' is not assignable to type 'ActionFunction<Context, ToggleEvent>'.
                  Types of parameters 'event' and 'event' are incompatible.
                    Type 'ToggleEvent' is not assignable to type 'SetCountServiceResolvedEvent'.
```

So I guess it needs to match what was passed into the machine initially, which should be a union of all possible event types that could take place within the machine (both incoming and "internal")? Which would mean I need a type guard (etc.) to ensure the event is the right type inside the action.

That's fine if that's how it's supposed to be - just wanting to make sure I'm not working around a problem.

**Comment by davidkpiano** [comment]
Can you update the CodeSandbox with what you have now?

**Comment by wKovacs64** [comment]
Uhh, well... it seems `assign<Context, SetCountServiceResolvedEvent>({ ... })` is working as expected in CodeSandbox, but not in my real project. That's unfortunate...

**Comment by wKovacs64** [comment]
Wow... so, I decided to import my real project to CodeSandbox so I could show you. In my main browser window, CSB is showing the same TypeScript errors **I get locally running `tsc`**. In a fresh private browser window, and in another browser all together, the same code (same CSB URL) is working fine and reports no TypeScript errors. I don't know how that's even possible. 😨 

Here is the real code:
https://codesandbox.io/s/pwl-1r8zz?module=/src/utils/use-update-poller.ts

Does that show TS errors for you? The block beginning at line 91 is the issue for me.

**Comment by wKovacs64** [comment]
That first CodeSandbox link was being weird, maybe this fork will be more stable:

https://codesandbox.io/s/pwl-hr1zj?module=/src/utils/use-update-poller.ts

The same problem manifests itself in two different machines:

- [`src/utils/use-update-poller.ts`](https://codesandbox.io/s/pwl-hr1zj?module=/src/utils/use-update-poller.ts) (line 91)
- [`src/components/pwned-info.tsx`](https://codesandbox.io/s/pwl-hr1zj?module=/src/components/pwned-info.tsx) (line 95)

I must be typing something incorrectly? Changing the third generic parameter on `Machine` to `any` works, but that's obviously not ideal nor should it be necessary.

**Comment by davidkpiano** [comment]
Workaround:

```ts
      setErrorMessage: assign<
        UpdatePollerContext,
        UpdatePollerEvent
      >({
        ...initialContext,
        error: (_, event) => (event as UpdatePollerCheckFailureEvent).data.message,
      }),
```

**Comment by davidkpiano** [comment]
In general, since an action like this is specific to `onError`, it's best to not define serialize it/define it in `{ actions: ... }` and instead define it inline (in `{ onError: { actions: ... } }`).

**Comment by wKovacs64** [comment]
I actually had that [exact workaround in place](https://github.com/wKovacs64/pwl/pull/101/commits/b539efafd47d92f9c9091f4d9d794d7b9de1ff03#diff-5dacc628022df20786ed656be8b76b21R103) but figured it was cheating. Is the workaround necessary due to limitations in the XState types, or because I'm doing something incorrectly?

> In general, since an action like this is specific to onError, it's best to not define serialize it/define it in { actions: ... } and instead define it inline (in { onError: { actions: ... } }).

I put it there due to the tip in the Actions guide in the docs:

> It is _not recommended_ to keep the machine config like this in production code, as this makes it difficult to debug, serialize, test, and accurately visualize actions. Always prefer refactoring inline action implementations in the `actions` property of the machine options, like the previous example.

🤷‍♂ 

However, moving them inline does eliminate the problem (and does not require the workaround). So... fine with me! 🙂

**Comment by wKovacs64** [comment]
On a related note, should the third generic parameter to `Machine` (`TEvent`) include the internal events that are specific to internal actions? Or only event types that can be sent into the machine?

(removing the internal events _appears_ to have no adverse affect after inlining the actions)

**Comment by davidkpiano** [comment]
> should the third generic parameter to Machine (TEvent) include the internal events that are specific to internal actions? Or only event types that can be sent into the machine?

Only event types that can be sent to the machine. The other internal actions will be added (union) internally.

**Comment by wKovacs64** [comment]
> Only event types that can be sent to the machine. The other internal actions will be added (union) internally.

OK, cool.

So overall, is it your opinion that everything is fine and we can close this issue? I can PR some documentation to reflect the findings here, if you'd like.

**Comment by davidkpiano** [comment]
I think typing can be improved, because `assign<...>` should be able to take in a specific subset of `TEvent` instead of forcing all `TEvent` events inside.

**Comment by CMCDragonkai** [comment]
I was facing this problem as well: https://github.com/davidkpiano/xstate/issues/863#issuecomment-718561133

The type errors aren't very clear for fixing this. Hopefully this can be spelled out in the documentation.

Now I have to do this:

```
actions: assign<BackupRestoreContext, {type: 'DELETE_RESTORE'}>({ backedUp: false }),
```

Seems quite verbose.

**Comment by Andarist** [comment]
@CMCDragonkai Please take a look at those 2 answers:
https://github.com/davidkpiano/xstate/discussions/1591#discussioncomment-111875
https://github.com/davidkpiano/xstate/discussions/1591#discussioncomment-111875

**Comment by TheDutchCoder** [comment]
Any ETA on this?

There seems to be no way around this except using inline assigns which is not an option.

**Comment by davidkpiano** [comment]
Also, see this PR which will simplify things: https://github.com/davidkpiano/xstate/pull/1439#issue-480529519

**Comment by Andarist** [comment]
It's currently impossible for us to infer the per-action event types at the type level. We can't process the state machine transitions at the type level to learn about the possible event types for given actions.

You can use our typegen to get better types in those kinds of situations: https://xstate.js.org/docs/guides/typescript.html#typegen

Without typegen the proper way of typing this is to do this:
```ts
  {
    actions: {
      // what should the second generic parameter to `assign` be?
      setCount: assign<Context, ToggleEvent>({
        count: (_, event) => event.data,
      }),
    },
  },
```

In this example, the `ToggleEvent` represents **all** of the events that this particular machine accepts. It should also be possible to just omi the generic type arguments here and let them be inferred from the `createMachine` call.
