### ISSUE TITLE
Empty events in transient states guards

### ISSUE THREAD

**Issue by fparga** [statelyai/xstate#890]
**Description**
Guards on transient states transitions are not receiving the original events. This prevents using guards based on the events data.

**Expected Result**
The events received in transient state transitions should be the ones that originated the transition. 

**Actual Result**
The events received are empty.

**Reproduction**
https://codesandbox.io/s/xstate-null-transition-guard-ogu34

**Comment by Andarist** [comment]
Yes - from SCXML perspective this is a bug. Fixing this right now has too high possibility of breaking our users though. We are starting to work on a new major version and fixing this will have to wait for it.

**Comment by AjaxSolutions** [comment]
Is there any write up listing the planned features/changes of the next major version?

**Comment by Andarist** [comment]
Some things are listed here https://github.com/davidkpiano/xstate/issues/742 - its not yet an exhaustive list though. One thing that will land for sure is 100% SCXML compatibility.

**Comment by davidkpiano** [comment]
@AjaxSolutions I will start marking roadmap items as 5.0 here: https://github.com/davidkpiano/xstate/issues/742

**Comment by rlaffers** [comment]
I have discovered a workaround: the 3rd argument passed to the guard is the meta object. It contains the current [state](https://xstate.js.org/api/classes/state.html). You can get your event from it.
```
// your guard in the transient transition
cond: (ctx, event, meta) => {
  console.log(event) // always {type: ''}
  console.log(meta.state.event) // e.g. {type: 'xstate.init'} this is what you want
}
```
This workaround works the same whether you define your transient transition with `'': {}` syntax or the [newer](https://xstate.js.org/docs/guides/transitions.html#eventless-transitions) `always: {}` syntax.

**Comment by thantos** [comment]
This work around only works when there is a single level transient transition. I am writing a machine that relies on an unknown number of transient transitions. 

This has worked so far...

```ts
const lastEvent = (state: State): Event=> {
  if (state.event.type) {
    return state.event;
  }
  return state.history ? lastEvent(state.history) : undefined;
};
```

used like...

```ts
// when there isn't a concrete last event
cond: (_context, _event, meta) => !lastEvent(meta.state),
```
