### ISSUE TITLE
@xstate/test warns on final states and onDone handlers

### ISSUE THREAD

**Issue by tivac** [statelyai/xstate#981]
**Description**

If your test machine uses the pattern where you have a `type : "final"` state and its parent uses an `onDone` the implicit event fired by the `final` state will be logged as a warning unless you create a definition for it in `.withEvents()`.

**Expected Result**

No warning, it's not a normal event and doesn't need a user implementation.

**Actual Result**

Warning in the console about an even that clearly wasn't something the user intended to require an implementation of.

**Reproduction**
https://codesandbox.io/s/xstatetest-ondone-warning-g26k1

**Additional context**

- `@xstate/test@0.3.0`
- `xstate@4.7.8`

<details>
  <summary>Repro Code</summary>

```js
const { Machine: createMachine } = require("xstate");
const { createModel } = require("@xstate/test");

const machine = createMachine({
  id: "menu",
  initial: "initial",
  states: {
    initial: {
      initial: "inner1",

      states: {
        inner1: {
          on: {
            INNER2: "inner2"
          }
        },

        inner2: {
          on: {
            DONE: "done"
          }
        },

        done: {
          type: "final"
        }
      },

      onDone: "later"
    },

    later: {}
  }
});

const model = createModel(machine).withEvents({
  INNER2: {},
  DONE: {}

  // Uncommenting this will silence the warning
  // "done.state.menu.initial" : {}
});

const execute = async plans => {
  plans.forEach(plan => {
    plan.paths.forEach(async path => {
      console.log(`${plan.description}\n\t${path.description}`);
      await path.test({ ctx: "foo" });
    });
  });
};

(async function() {
  await execute(model.getSimplePathPlans());
})();
```
</details>

<details>
<summary>Warning generated by the repro</summary>

```
Missing config for event "done.state.menu.initial". 
```
</details>

**Comment by tivac** [comment]
I added some logging of the plans and paths and noticed something that seems strange.

```
reaches state: "#menu.initial.inner1"  
    via  
reaches state: "#menu.later"  
    via done.state.menu.initial 
    via INNER2 → DONE 
    via INNER2 → done.state.menu.initial 
reaches state: "#menu.initial.inner2"  
    via INNER2 
```

Unless I'm misunderstanding the output here it thinks that `#menu.initial → #menu.later` and `#menu.initial.inner2 → #menu.later` are both possible via `done.state.menu.initial`. That seems wrong?

**Comment by jamestharpe** [comment]
I'm seeing the same thing - I can't get generated test cases to pass because there is no way to trigger the "done.state.*" transitions directly; instead, it should be completing the child statechart.

**Comment by patel-jeel92** [comment]
I am running into the same issue. For my test paths generated with xstate/test, my tests that have paths with done.state.* fail and there is no way to trigger transitions for that state. Has there been any update on this?

**Comment by davidkpiano** [comment]
This warning no longer occurs on `@xstate/test@alpha`: https://codesandbox.io/s/xstate-test-ondone-warning-forked-5krdu3?file=/src/index.js
